#!/usr/bin/env python3
"""Phase 2: Add languages bg through mt."""

import json

with open("/home/babelfree.com/public_html/generator/translations.json", "r", encoding="utf-8") as f:
    data = json.load(f)

# =============================================================================
# BULGARIAN
# =============================================================================
data["bg"] = {
    "lang_attr": "bg",
    "lang_name_english": "Bulgarian",
    "lang_name_native": "Български",
    "meta_title": "La Aventura de Yaguará — Научи испански през живи светове",
    "meta_description": "Научи испански с Yaguará, дух-ягуар, през живите светове на Colombia. Три свята за откриване. Безплатен курс A1-C2 със 144+ срещи.",
    "og_description": "Научи испански с Yaguará през живите светове на Colombia. Безплатен курс A1-C2.",
    "twitter_description": "Научи испански през живите светове на Colombia с Yaguará. Безплатен курс.",
    "brand_subtitle": "Жив испански",
    "nav_languages": "Езици",
    "nav_journey": "Пътешествието",
    "nav_contact": "Контакт",
    "nav_login": "Вход",
    "nav_start": "Започни",
    "hero_subtitle": "Yaguará чака. Пътешествие на езика и паметта през живите светове на Colombia.",
    "feature1_title": "Назови света",
    "feature1_desc": "Учи като назоваваш това, което съществува: реки, дървета, животни. Думата дава живот.",
    "feature2_title": "Пълно потапяне",
    "feature2_desc": "Испански от първия момент. Без преводи. Само присъствие.",
    "feature3_title": "Yaguará те води",
    "feature3_desc": "Дух-ягуар между световете. Върви с теб, задава въпроси и понякога просто наблюдава.",
    "cta_begin": "Започни пътешествието",
    "free_title": "Всички пътеки са безплатни",
    "free_subtitle": "Без плащания, без абонаменти — просто започни да вървиш",
    "free_desc": "Вярваме, че ученето на език е право, не привилегия. Три свята за откриване, 144+ срещи с живия език и пълната история на Yaguará из Colombia. Всичко безплатно.",
    "free_feature1": "Три свята за откриване, от корените до звездите",
    "free_feature2": "144+ срещи с живия език на Colombia",
    "free_feature3": "Yaguará като твой спътник на всяка крачка от пътя",
    "free_feature4": "Истинска география, култура и традиции на Colombia",
    "about_title": "Какво прави това пътешествие уникално?",
    "about_desc": "Това не е просто поредният курс по испански. Това е пътешествие между световете, където Yaguará — дух-ягуар и пазител — те води през живите екосистеми на Colombia. Всяка среща е история. Всяка дума, акт на баланс.",
    "about_feature1_title": "Живи светове",
    "about_feature1_desc": "От Amazon до Sierra Nevada: истинска география, култура и традиции на Colombia",
    "about_feature2_title": "Семена и пътеки",
    "about_feature2_desc": "Напредъкът ти се показва като семена, които растат, и съзвездия, които се появяват",
    "about_feature3_title": "Гласовете на земята",
    "about_feature3_desc": "Шамани, занаятчии, реки, които говорят — всеки глас те учи на автентичен испански",
    "contact_title": "Готов ли си да слушаш?",
    "contact_subtitle": "Пътешествието започва, когато решиш да тръгнеш",
    "contact_cta": "Направи първата крачка",
    "contact_write": "Пиши ни",
    "footer_desc": "Научи испански с Yaguará, дух-ягуар, през живите светове на Colombia.",
    "footer_available": "Достъпно на над 100 езика на babelfree.com",
    "footer_worlds": "Трите Свята",
    "footer_contact": "Контакт",
    "footer_languages": "Езици",
    "footer_login": "Вход",
    "welcome_title": "🐆 Добре дошъл!",
    "welcome_message": "Yaguará чака. Пътешествието започва."
}

# =============================================================================
# CROATIAN
# =============================================================================
data["hr"] = {
    "lang_attr": "hr",
    "lang_name_english": "Croatian",
    "lang_name_native": "Hrvatski",
    "meta_title": "La Aventura de Yaguará — Nauči španjolski kroz žive svjetove",
    "meta_description": "Nauči španjolski s Yaguará, duhom jaguara, kroz žive svjetove Colombia. Tri svijeta za otkriti. Besplatan tečaj A1-C2 sa 144+ susreta.",
    "og_description": "Nauči španjolski s Yaguará kroz žive svjetove Colombia. Besplatan tečaj A1-C2.",
    "twitter_description": "Nauči španjolski kroz žive svjetove Colombia s Yaguará. Besplatan tečaj.",
    "brand_subtitle": "Živi španjolski",
    "nav_languages": "Jezici",
    "nav_journey": "Putovanje",
    "nav_contact": "Kontakt",
    "nav_login": "Prijava",
    "nav_start": "Započni",
    "hero_subtitle": "Yaguará čeka. Putovanje jezika i sjećanja kroz žive svjetove Colombia.",
    "feature1_title": "Imenuj svijet",
    "feature1_desc": "Uči imenujući ono što postoji: rijeke, stabla, životinje. Riječ daje život.",
    "feature2_title": "Potpuno uranjanje",
    "feature2_desc": "Španjolski od prvog trenutka. Bez prijevoda. Samo prisutnost.",
    "feature3_title": "Yaguará te vodi",
    "feature3_desc": "Duh jaguara između svjetova. Hoda s tobom, postavlja pitanja i ponekad samo promatra.",
    "cta_begin": "Započni putovanje",
    "free_title": "Svi putevi su besplatni",
    "free_subtitle": "Bez plaćanja, bez pretplata — samo počni hodati",
    "free_desc": "Vjerujemo da je učenje jezika pravo, a ne privilegija. Tri svijeta za otkriti, 144+ susreta s živim jezikom i potpuna priča o Yaguará kroz Colombia. Sve besplatno.",
    "free_feature1": "Tri svijeta za otkriti, od korijena do zvijezda",
    "free_feature2": "144+ susreta s živim jezikom Colombia",
    "free_feature3": "Yaguará kao tvoj suputnik na svakom koraku puta",
    "free_feature4": "Stvarna geografija, kultura i tradicije Colombia",
    "about_title": "Što ovo putovanje čini jedinstvenim?",
    "about_desc": "Ovo nije samo još jedan tečaj španjolskog. To je putovanje između svjetova gdje Yaguará — duh jaguara i čuvar — vodi te kroz žive ekosustave Colombia. Svaki susret je priča. Svaka riječ, čin ravnoteže.",
    "about_feature1_title": "Živi svjetovi",
    "about_feature1_desc": "Od Amazon do Sierra Nevada: stvarna geografija, kultura i tradicije Colombia",
    "about_feature2_title": "Sjemenke i staze",
    "about_feature2_desc": "Tvoj napredak se pokazuje kao sjemenke koje rastu i sazviježđa koja se pojavljuju",
    "about_feature3_title": "Glasovi zemlje",
    "about_feature3_desc": "Šamani, obrtnici, rijeke koje govore — svaki glas te uči autentični španjolski",
    "contact_title": "Jesi li spreman slušati?",
    "contact_subtitle": "Putovanje započinje kada odlučiš hodati",
    "contact_cta": "Napravi prvi korak",
    "contact_write": "Piši nam",
    "footer_desc": "Nauči španjolski s Yaguará, duhom jaguara, kroz žive svjetove Colombia.",
    "footer_available": "Dostupno na više od 100 jezika na babelfree.com",
    "footer_worlds": "Tri Svijeta",
    "footer_contact": "Kontakt",
    "footer_languages": "Jezici",
    "footer_login": "Prijava",
    "welcome_title": "🐆 Dobrodošli!",
    "welcome_message": "Yaguará čeka. Putovanje započinje."
}

# =============================================================================
# SERBIAN
# =============================================================================
data["sr"] = {
    "lang_attr": "sr",
    "lang_name_english": "Serbian",
    "lang_name_native": "Српски",
    "meta_title": "La Aventura de Yaguará — Научи шпански кроз живе светове",
    "meta_description": "Научи шпански са Yaguará, духом јагуара, кроз живе светове Colombia. Три света за откривање. Бесплатан курс A1-C2 са 144+ сусрета.",
    "og_description": "Научи шпански са Yaguará кроз живе светове Colombia. Бесплатан курс A1-C2.",
    "twitter_description": "Научи шпански кроз живе светове Colombia са Yaguará. Бесплатан курс.",
    "brand_subtitle": "Живи шпански",
    "nav_languages": "Језици",
    "nav_journey": "Путовање",
    "nav_contact": "Контакт",
    "nav_login": "Пријава",
    "nav_start": "Започни",
    "hero_subtitle": "Yaguará чека. Путовање језика и сећања кроз живе светове Colombia.",
    "feature1_title": "Именуј свет",
    "feature1_desc": "Учи именујући оно што постоји: реке, дрвеће, животиње. Реч даје живот.",
    "feature2_title": "Потпуно урањање",
    "feature2_desc": "Шпански од првог тренутка. Без превода. Само присутност.",
    "feature3_title": "Yaguará те води",
    "feature3_desc": "Дух јагуара између светова. Хода са тобом, поставља питања и понекад само посматра.",
    "cta_begin": "Започни путовање",
    "free_title": "Сви путеви су бесплатни",
    "free_subtitle": "Без плаћања, без претплата — само почни да ходаш",
    "free_desc": "Верујемо да је учење језика право, а не привилегија. Три света за откривање, 144+ сусрета са живим језиком и комплетна прича о Yaguará кроз Colombia. Све бесплатно.",
    "free_feature1": "Три света за откривање, од корена до звезда",
    "free_feature2": "144+ сусрета са живим језиком Colombia",
    "free_feature3": "Yaguará као твој сапутник на сваком кораку пута",
    "free_feature4": "Стварна географија, култура и традиције Colombia",
    "about_title": "Шта ово путовање чини јединственим?",
    "about_desc": "Ово није само још један курс шпанског. То је путовање између светова где Yaguará — дух јагуара и чувар — те води кроз живе екосистеме Colombia. Сваки сусрет је прича. Свака реч, чин равнотеже.",
    "about_feature1_title": "Живи светови",
    "about_feature1_desc": "Од Amazon до Sierra Nevada: стварна географија, култура и традиције Colombia",
    "about_feature2_title": "Семенке и стазе",
    "about_feature2_desc": "Твој напредак се показује као семенке које расту и сазвежђа која се појављују",
    "about_feature3_title": "Гласови земље",
    "about_feature3_desc": "Шамани, занатлије, реке које говоре — сваки глас те учи аутентичном шпанском",
    "contact_title": "Јеси ли спреман да слушаш?",
    "contact_subtitle": "Путовање почиње када одлучиш да ходаш",
    "contact_cta": "Направи први корак",
    "contact_write": "Пиши нам",
    "footer_desc": "Научи шпански са Yaguará, духом јагуара, кроз живе светове Colombia.",
    "footer_available": "Доступно на више од 100 језика на babelfree.com",
    "footer_worlds": "Три Света",
    "footer_contact": "Контакт",
    "footer_languages": "Језици",
    "footer_login": "Пријава",
    "welcome_title": "🐆 Добродошли!",
    "welcome_message": "Yaguará чека. Путовање почиње."
}

# =============================================================================
# SLOVAK
# =============================================================================
data["sk"] = {
    "lang_attr": "sk",
    "lang_name_english": "Slovak",
    "lang_name_native": "Slovenčina",
    "meta_title": "La Aventura de Yaguará — Naučte sa španielčinu cez živé svety",
    "meta_description": "Naučte sa španielčinu s Yaguará, duchom jaguára, cez živé svety Colombia. Tri svety na objavenie. Bezplatný kurz A1-C2 so 144+ stretnutiami.",
    "og_description": "Naučte sa španielčinu s Yaguará cez živé svety Colombia. Bezplatný kurz A1-C2.",
    "twitter_description": "Naučte sa španielčinu cez živé svety Colombia s Yaguará. Bezplatný kurz.",
    "brand_subtitle": "Živá španielčina",
    "nav_languages": "Jazyky",
    "nav_journey": "Cesta",
    "nav_contact": "Kontakt",
    "nav_login": "Prihlásiť sa",
    "nav_start": "Začať",
    "hero_subtitle": "Yaguará čaká. Cesta jazyka a pamäte cez živé svety Colombia.",
    "feature1_title": "Pomenuj svet",
    "feature1_desc": "Učte sa pomenovaním toho, čo existuje: rieky, stromy, zvieratá. Slovo dáva život.",
    "feature2_title": "Úplné ponorenie",
    "feature2_desc": "Španielčina od prvého okamihu. Bez prekladov. Iba prítomnosť.",
    "feature3_title": "Yaguará vás vedie",
    "feature3_desc": "Duch jaguára medzi svetmi. Kráča s vami, kladie otázky a niekedy len pozoruje.",
    "cta_begin": "Začať cestu",
    "free_title": "Všetky cesty sú zadarmo",
    "free_subtitle": "Žiadne platby, žiadne predplatné — jednoducho začnite kráčať",
    "free_desc": "Veríme, že učiť sa jazyk je právo, nie privilégium. Tri svety na objavenie, 144+ stretnutí so živým jazykom a kompletný príbeh Yaguará naprieč Colombia. Všetko zadarmo.",
    "free_feature1": "Tri svety na objavenie, od koreňov po hviezdy",
    "free_feature2": "144+ stretnutí so živým jazykom Colombia",
    "free_feature3": "Yaguará ako váš spoločník na každom kroku cesty",
    "free_feature4": "Skutočná geografia, kultúra a tradície Colombia",
    "about_title": "Čo robí túto cestu výnimočnou?",
    "about_desc": "Toto nie je len ďalší kurz španielčiny. Je to cesta medzi svetmi, kde Yaguará — duch jaguára a strážca — vás vedie cez živé ekosystémy Colombia. Každé stretnutie je príbeh. Každé slovo akt rovnováhy.",
    "about_feature1_title": "Živé svety",
    "about_feature1_desc": "Od Amazon po Sierra Nevada: skutočná geografia, kultúra a tradície Colombia",
    "about_feature2_title": "Semienka a cestičky",
    "about_feature2_desc": "Váš pokrok sa ukazuje ako semienka, ktoré rastú, a súhvezdia, ktoré sa objavujú",
    "about_feature3_title": "Hlasy zeme",
    "about_feature3_desc": "Šamani, remeselníci, rieky čo hovoria — každý hlas vás učí autentickú španielčinu",
    "contact_title": "Ste pripravení počúvať?",
    "contact_subtitle": "Cesta začína, keď sa rozhodnete kráčať",
    "contact_cta": "Urobte prvý krok",
    "contact_write": "Napíšte nám",
    "footer_desc": "Naučte sa španielčinu s Yaguará, duchom jaguára, cez živé svety Colombia.",
    "footer_available": "Dostupné vo viac ako 100 jazykoch na babelfree.com",
    "footer_worlds": "Tri Svety",
    "footer_contact": "Kontakt",
    "footer_languages": "Jazyky",
    "footer_login": "Prihlásiť sa",
    "welcome_title": "🐆 Vitajte!",
    "welcome_message": "Yaguará čaká. Cesta začína."
}

# =============================================================================
# SLOVENIAN
# =============================================================================
data["sl"] = {
    "lang_attr": "sl",
    "lang_name_english": "Slovenian",
    "lang_name_native": "Slovenščina",
    "meta_title": "La Aventura de Yaguará — Uči se španščino skozi žive svetove",
    "meta_description": "Uči se španščino z Yaguará, duhom jaguarja, skozi žive svetove Colombia. Trije svetovi za odkrivanje. Brezplačen tečaj A1-C2 s 144+ srečanji.",
    "og_description": "Uči se španščino z Yaguará skozi žive svetove Colombia. Brezplačen tečaj A1-C2.",
    "twitter_description": "Uči se španščino skozi žive svetove Colombia z Yaguará. Brezplačen tečaj.",
    "brand_subtitle": "Živa španščina",
    "nav_languages": "Jeziki",
    "nav_journey": "Potovanje",
    "nav_contact": "Kontakt",
    "nav_login": "Prijava",
    "nav_start": "Začni",
    "hero_subtitle": "Yaguará čaka. Potovanje jezika in spomina skozi žive svetove Colombia.",
    "feature1_title": "Poimenuj svet",
    "feature1_desc": "Uči se s poimenovanjem obstoječega: reke, drevesa, živali. Beseda daje življenje.",
    "feature2_title": "Popolna potopitev",
    "feature2_desc": "Španščina od prvega trenutka. Brez prevodov. Le prisotnost.",
    "feature3_title": "Yaguará te vodi",
    "feature3_desc": "Duh jaguarja med svetovi. Hodi s tabo, postavlja vprašanja in včasih le opazuje.",
    "cta_begin": "Začni potovanje",
    "free_title": "Vse poti so brezplačne",
    "free_subtitle": "Brez plačil, brez naročnin — preprosto začni hoditi",
    "free_desc": "Verjamemo, da je učenje jezika pravica, ne privilegij. Trije svetovi za odkrivanje, 144+ srečanj z živim jezikom in popolna zgodba Yaguará po Colombia. Vse brezplačno.",
    "free_feature1": "Trije svetovi za odkrivanje, od korenin do zvezd",
    "free_feature2": "144+ srečanj z živim jezikom Colombia",
    "free_feature3": "Yaguará kot tvoj spremljevalec na vsakem koraku poti",
    "free_feature4": "Resnična geografija, kultura in tradicije Colombia",
    "about_title": "Kaj dela to potovanje edinstveno?",
    "about_desc": "To ni le še en tečaj španščine. To je potovanje med svetovi, kjer Yaguará — duh jaguarja in varuh — te vodi skozi žive ekosisteme Colombia. Vsako srečanje je zgodba. Vsaka beseda dejanje ravnotežja.",
    "about_feature1_title": "Živi svetovi",
    "about_feature1_desc": "Od Amazon do Sierra Nevada: resnična geografija, kultura in tradicije Colombia",
    "about_feature2_title": "Semena in poti",
    "about_feature2_desc": "Tvoj napredek se kaže kot semena, ki rastejo, in ozvezdja, ki se pojavljajo",
    "about_feature3_title": "Glasovi zemlje",
    "about_feature3_desc": "Šamani, obrtniki, reke ki govorijo — vsak glas te uči avtentično španščino",
    "contact_title": "Si pripravljen poslušati?",
    "contact_subtitle": "Potovanje se začne, ko se odločiš hoditi",
    "contact_cta": "Naredi prvi korak",
    "contact_write": "Piši nam",
    "footer_desc": "Uči se španščino z Yaguará, duhom jaguarja, skozi žive svetove Colombia.",
    "footer_available": "Na voljo v več kot 100 jezikih na babelfree.com",
    "footer_worlds": "Trije Svetovi",
    "footer_contact": "Kontakt",
    "footer_languages": "Jeziki",
    "footer_login": "Prijava",
    "welcome_title": "🐆 Dobrodošli!",
    "welcome_message": "Yaguará čaka. Potovanje se začne."
}

# =============================================================================
# LITHUANIAN
# =============================================================================
data["lt"] = {
    "lang_attr": "lt",
    "lang_name_english": "Lithuanian",
    "lang_name_native": "Lietuvių",
    "meta_title": "La Aventura de Yaguará — Mokykis ispaniškai per gyvus pasaulius",
    "meta_description": "Mokykis ispaniškai su Yaguará, jaguaro dvasia, per gyvus Colombia pasaulius. Trys pasauliai atrasti. Nemokamas A1-C2 kursas su 144+ susitikimais.",
    "og_description": "Mokykis ispaniškai su Yaguará per gyvus Colombia pasaulius. Nemokamas A1-C2 kursas.",
    "twitter_description": "Mokykis ispaniškai per gyvus Colombia pasaulius su Yaguará. Nemokamas kursas.",
    "brand_subtitle": "Gyva ispanų kalba",
    "nav_languages": "Kalbos",
    "nav_journey": "Kelionė",
    "nav_contact": "Kontaktai",
    "nav_login": "Prisijungti",
    "nav_start": "Pradėti",
    "hero_subtitle": "Yaguará laukia. Kalbos ir atminties kelionė per gyvus Colombia pasaulius.",
    "feature1_title": "Pavadink pasaulį",
    "feature1_desc": "Mokykis pavadindamas tai, kas egzistuoja: upes, medžius, gyvūnus. Žodis suteikia gyvybę.",
    "feature2_title": "Visiškas panardinimas",
    "feature2_desc": "Ispaniškai nuo pirmojo momento. Jokių vertimų. Tik buvimas.",
    "feature3_title": "Yaguará tave veda",
    "feature3_desc": "Jaguaro dvasia tarp pasaulių. Eina su tavimi, klausia ir kartais tiesiog stebi.",
    "cta_begin": "Pradėk kelionę",
    "free_title": "Visi keliai yra nemokami",
    "free_subtitle": "Jokių mokėjimų, jokių prenumeratų — tiesiog pradėk eiti",
    "free_desc": "Tikime, kad kalbos mokymasis yra teisė, ne privilegija. Trys pasauliai atrasti, 144+ susitikimų su gyva kalba ir pilna Yaguará istorija per Colombia. Viskas nemokamai.",
    "free_feature1": "Trys pasauliai atrasti, nuo šaknų iki žvaigždžių",
    "free_feature2": "144+ susitikimų su gyva Colombia kalba",
    "free_feature3": "Yaguará kaip tavo palydovas kiekviename kelio žingsnyje",
    "free_feature4": "Tikra geografija, kultūra ir Colombia tradicijos",
    "about_title": "Kas daro šią kelionę unikalią?",
    "about_desc": "Tai ne šiaip dar vienas ispanų kalbos kursas. Tai kelionė tarp pasaulių, kur Yaguará — jaguaro dvasia ir sargas — veda tave per gyvąsias Colombia ekosistemas. Kiekvienas susitikimas yra istorija. Kiekvienas žodis — pusiausvyros aktas.",
    "about_feature1_title": "Gyvi pasauliai",
    "about_feature1_desc": "Nuo Amazon iki Sierra Nevada: tikra geografija, kultūra ir Colombia tradicijos",
    "about_feature2_title": "Sėklos ir takai",
    "about_feature2_desc": "Tavo pažanga rodosi kaip sėklos, kurios auga, ir žvaigždynai, kurie pasirodo",
    "about_feature3_title": "Žemės balsai",
    "about_feature3_desc": "Šamanai, amatininkai, kalbančios upės — kiekvienas balsas moko tave autentiškos ispanų kalbos",
    "contact_title": "Ar esi pasiruošęs klausytis?",
    "contact_subtitle": "Kelionė prasideda, kai nuspręsti eiti",
    "contact_cta": "Ženk pirmąjį žingsnį",
    "contact_write": "Parašyk mums",
    "footer_desc": "Mokykis ispaniškai su Yaguará, jaguaro dvasia, per gyvus Colombia pasaulius.",
    "footer_available": "Prieinama daugiau nei 100 kalbų adresu babelfree.com",
    "footer_worlds": "Trys Pasauliai",
    "footer_contact": "Kontaktai",
    "footer_languages": "Kalbos",
    "footer_login": "Prisijungti",
    "welcome_title": "🐆 Sveiki!",
    "welcome_message": "Yaguará laukia. Kelionė prasideda."
}

# =============================================================================
# LATVIAN
# =============================================================================
data["lv"] = {
    "lang_attr": "lv",
    "lang_name_english": "Latvian",
    "lang_name_native": "Latviešu",
    "meta_title": "La Aventura de Yaguará — Mācies spāņu valodu caur dzīvām pasaulēm",
    "meta_description": "Mācies spāņu valodu ar Yaguará, jaguāra garu, caur Colombia dzīvajām pasaulēm. Trīs pasaules atklāšanai. Bezmaksas A1-C2 kurss ar 144+ tikšanās reizēm.",
    "og_description": "Mācies spāņu valodu ar Yaguará caur Colombia dzīvajām pasaulēm. Bezmaksas A1-C2 kurss.",
    "twitter_description": "Mācies spāņu valodu caur Colombia dzīvajām pasaulēm ar Yaguará. Bezmaksas kurss.",
    "brand_subtitle": "Dzīvā spāņu valoda",
    "nav_languages": "Valodas",
    "nav_journey": "Ceļojums",
    "nav_contact": "Kontakti",
    "nav_login": "Ieiet",
    "nav_start": "Sākt",
    "hero_subtitle": "Yaguará gaida. Valodas un atmiņu ceļojums caur Colombia dzīvajām pasaulēm.",
    "feature1_title": "Nosauc pasauli",
    "feature1_desc": "Mācies nosaucot to, kas pastāv: upes, kokus, dzīvniekus. Vārds dod dzīvību.",
    "feature2_title": "Pilnīga iegremdēšanās",
    "feature2_desc": "Spāņu valoda no pirmā mirkļa. Bez tulkojumiem. Tikai klātbūtne.",
    "feature3_title": "Yaguará tevi vada",
    "feature3_desc": "Jaguāra gars starp pasaulēm. Tas iet ar tevi, uzdod jautājumus un dažreiz vienkārši vēro.",
    "cta_begin": "Sāc ceļojumu",
    "free_title": "Visas takas ir bezmaksas",
    "free_subtitle": "Nav maksājumu, nav abonementu — vienkārši sāc iet",
    "free_desc": "Mēs ticam, ka valodas apgūšana ir tiesības, ne privilēģija. Trīs pasaules atklāšanai, 144+ tikšanās reizes ar dzīvo valodu un pilns Yaguará stāsts pa Colombia. Viss bezmaksas.",
    "free_feature1": "Trīs pasaules atklāšanai, no saknēm līdz zvaigznēm",
    "free_feature2": "144+ tikšanās reizes ar Colombia dzīvo valodu",
    "free_feature3": "Yaguará kā tavs ceļabiedrs katrā ceļa solī",
    "free_feature4": "Īsta ģeogrāfija, kultūra un Colombia tradīcijas",
    "about_title": "Kas padara šo ceļojumu unikālu?",
    "about_desc": "Šis nav vienkārši vēl viens spāņu valodas kurss. Tas ir ceļojums starp pasaulēm, kur Yaguará — jaguāra gars un sargs — vada tevi caur Colombia dzīvajām ekosistēmām. Katra tikšanās ir stāsts. Katrs vārds — līdzsvara akts.",
    "about_feature1_title": "Dzīvās pasaules",
    "about_feature1_desc": "No Amazon līdz Sierra Nevada: īsta ģeogrāfija, kultūra un Colombia tradīcijas",
    "about_feature2_title": "Sēklas un takas",
    "about_feature2_desc": "Tavs progress parādās kā sēklas, kas aug, un zvaigznāji, kas atklājas",
    "about_feature3_title": "Zemes balsis",
    "about_feature3_desc": "Šamaņi, amatnieki, upes, kas runā — katra balss māca tev autentisku spāņu valodu",
    "contact_title": "Vai esi gatavs klausīties?",
    "contact_subtitle": "Ceļojums sākas, kad tu nolemj iet",
    "contact_cta": "Sper pirmo soli",
    "contact_write": "Raksti mums",
    "footer_desc": "Mācies spāņu valodu ar Yaguará, jaguāra garu, caur Colombia dzīvajām pasaulēm.",
    "footer_available": "Pieejams vairāk nekā 100 valodās vietnē babelfree.com",
    "footer_worlds": "Trīs Pasaules",
    "footer_contact": "Kontakti",
    "footer_languages": "Valodas",
    "footer_login": "Ieiet",
    "welcome_title": "🐆 Laipni lūdzam!",
    "welcome_message": "Yaguará gaida. Ceļojums sākas."
}

# =============================================================================
# ESTONIAN
# =============================================================================
data["et"] = {
    "lang_attr": "et",
    "lang_name_english": "Estonian",
    "lang_name_native": "Eesti",
    "meta_title": "La Aventura de Yaguará — Õpi hispaania keelt elavate maailmade kaudu",
    "meta_description": "Õpi hispaania keelt Yaguará, jaguarivaimu, juhtimisel Colombia elavate maailmade kaudu. Kolm maailma avastamiseks. Tasuta A1-C2 kursus 144+ kohtumisega.",
    "og_description": "Õpi hispaania keelt Yaguará juhtimisel Colombia elavate maailmade kaudu. Tasuta A1-C2 kursus.",
    "twitter_description": "Õpi hispaania keelt Colombia elavate maailmade kaudu koos Yaguarága. Tasuta kursus.",
    "brand_subtitle": "Elav hispaania keel",
    "nav_languages": "Keeled",
    "nav_journey": "Teekond",
    "nav_contact": "Kontakt",
    "nav_login": "Logi sisse",
    "nav_start": "Alusta",
    "hero_subtitle": "Yaguará ootab. Keele ja mälu teekond Colombia elavate maailmade kaudu.",
    "feature1_title": "Nimeta maailm",
    "feature1_desc": "Õpi nimetades seda, mis on olemas: jõed, puud, loomad. Sõna annab elu.",
    "feature2_title": "Täielik keelekümblus",
    "feature2_desc": "Hispaania keel esimesest hetkest. Ilma tõlgeteta. Ainult kohalolek.",
    "feature3_title": "Yaguará juhib sind",
    "feature3_desc": "Jaguarivaim maailmade vahel. Ta kõnnib sinuga, esitab küsimusi ja mõnikord lihtsalt vaatab.",
    "cta_begin": "Alusta teekonda",
    "free_title": "Kõik rajad on tasuta",
    "free_subtitle": "Ilma makseteta, ilma tellimusteta — lihtsalt hakka kõndima",
    "free_desc": "Usume, et keeleõpe on õigus, mitte privileeg. Kolm maailma avastamiseks, 144+ kohtumist elava keelega ja Yaguará täielik lugu üle Colombia. Kõik tasuta.",
    "free_feature1": "Kolm maailma avastamiseks, juurtest tähtedeni",
    "free_feature2": "144+ kohtumist Colombia elava keelega",
    "free_feature3": "Yaguará sinu kaaslasena igal sammul teel",
    "free_feature4": "Tõeline geograafia, kultuur ja Colombia traditsioonid",
    "about_title": "Mis teeb selle teekonna ainulaadseks?",
    "about_desc": "See pole lihtsalt veel üks hispaania keele kursus. See on teekond maailmade vahel, kus Yaguará — jaguarivaim ja kaitsja — juhib sind läbi Colombia elavate ökosüsteemide. Iga kohtumine on lugu. Iga sõna on tasakaalu tegu.",
    "about_feature1_title": "Elavad maailmad",
    "about_feature1_desc": "Amazonist Sierra Nevadani: tõeline geograafia, kultuur ja Colombia traditsioonid",
    "about_feature2_title": "Seemned ja rajad",
    "about_feature2_desc": "Sinu edenemine ilmneb kasvavate seemnete ja ilmuvate tähtkujudena",
    "about_feature3_title": "Maa hääled",
    "about_feature3_desc": "Šamaanid, käsitöölised, rääkivad jõed — iga hääl õpetab sulle ehtssat hispaania keelt",
    "contact_title": "Kas oled valmis kuulama?",
    "contact_subtitle": "Teekond algab, kui otsustad kõndima hakata",
    "contact_cta": "Astu esimene samm",
    "contact_write": "Kirjuta meile",
    "footer_desc": "Õpi hispaania keelt Yaguará, jaguarivaimu, juhtimisel Colombia elavate maailmade kaudu.",
    "footer_available": "Saadaval enam kui 100 keeles aadressil babelfree.com",
    "footer_worlds": "Kolm Maailma",
    "footer_contact": "Kontakt",
    "footer_languages": "Keeled",
    "footer_login": "Logi sisse",
    "welcome_title": "🐆 Tere tulemast!",
    "welcome_message": "Yaguará ootab. Teekond algab."
}

# =============================================================================
# ALBANIAN
# =============================================================================
data["sq"] = {
    "lang_attr": "sq",
    "lang_name_english": "Albanian",
    "lang_name_native": "Shqip",
    "meta_title": "La Aventura de Yaguará — Mëso spanjisht përmes botëve të gjalla",
    "meta_description": "Mëso spanjisht me udhëheqjen e Yaguará, shpirtit-jaguar, përmes botëve të gjalla të Colombia. Tre botë për të zbuluar. Kurs falas A1-C2 me 144+ takime.",
    "og_description": "Mëso spanjisht me udhëheqjen e Yaguará përmes botëve të gjalla të Colombia. Kurs falas A1-C2.",
    "twitter_description": "Mëso spanjisht përmes botëve të gjalla të Colombia me Yaguará. Kurs falas.",
    "brand_subtitle": "Spanjisht e gjallë",
    "nav_languages": "Gjuhët",
    "nav_journey": "Udhëtimi",
    "nav_contact": "Kontakti",
    "nav_login": "Hyr",
    "nav_start": "Fillo",
    "hero_subtitle": "Yaguará pret. Një udhëtim gjuhe dhe kujtese përmes botëve të gjalla të Colombia.",
    "feature1_title": "Emërto botën",
    "feature1_desc": "Mëso duke emërtuar atë që ekziston: lumenj, pemë, kafshë. Fjala jep jetë.",
    "feature2_title": "Zhytje totale",
    "feature2_desc": "Spanjisht që nga momenti i parë. Pa përkthime. Vetëm prani.",
    "feature3_title": "Yaguará të udhëheq",
    "feature3_desc": "Një shpirt-jaguar mes botëve. Ecën me ty, bën pyetje dhe ndonjëherë thjesht vëzhgon.",
    "cta_begin": "Fillo udhëtimin",
    "free_title": "Të gjitha shtigjet janë falas",
    "free_subtitle": "Pa pagesa, pa abonime — thjesht fillo të ecësh",
    "free_desc": "Besojmë se mësimi i një gjuhe është e drejtë, jo privilegj. Tre botë për të zbuluar, 144+ takime me gjuhën e gjallë dhe historia e plotë e Yaguará nëpër Colombia. Gjithçka falas.",
    "free_feature1": "Tre botë për të zbuluar, nga rrënjët tek yjet",
    "free_feature2": "144+ takime me gjuhën e gjallë të Colombia",
    "free_feature3": "Yaguará si shoqëruesi yt në çdo hap të rrugës",
    "free_feature4": "Gjeografi reale, kulturë dhe tradita të Colombia",
    "about_title": "Çfarë e bën këtë udhëtim unik?",
    "about_desc": "Ky nuk është thjesht një kurs tjetër spanjishteje. Është një udhëtim mes botëve ku Yaguará — shpirt-jaguar dhe kujdestar — të udhëheq përmes ekosistemeve të gjalla të Colombia. Çdo takim është një histori. Çdo fjalë, një akt ekuilibri.",
    "about_feature1_title": "Botë të gjalla",
    "about_feature1_desc": "Nga Amazon tek Sierra Nevada: gjeografi reale, kulturë dhe tradita të Colombia",
    "about_feature2_title": "Fara dhe shtigje",
    "about_feature2_desc": "Progresi yt shfaqet si fara që rriten dhe yjësi që dalin",
    "about_feature3_title": "Zërat e tokës",
    "about_feature3_desc": "Shamanë, artizanë, lumenj që flasin — çdo zë të mëson spanjishte autentike",
    "contact_title": "A je gati të dëgjosh?",
    "contact_subtitle": "Udhëtimi fillon kur vendos të ecësh",
    "contact_cta": "Bëj hapin e parë",
    "contact_write": "Na shkruaj",
    "footer_desc": "Mëso spanjisht me udhëheqjen e Yaguará, shpirtit-jaguar, përmes botëve të gjalla të Colombia.",
    "footer_available": "E disponueshme në mbi 100 gjuhë në babelfree.com",
    "footer_worlds": "Tre Botët",
    "footer_contact": "Kontakti",
    "footer_languages": "Gjuhët",
    "footer_login": "Hyr",
    "welcome_title": "🐆 Mirë se vini!",
    "welcome_message": "Yaguará pret. Udhëtimi fillon."
}

# =============================================================================
# MACEDONIAN
# =============================================================================
data["mk"] = {
    "lang_attr": "mk",
    "lang_name_english": "Macedonian",
    "lang_name_native": "Македонски",
    "meta_title": "La Aventura de Yaguará — Научи шпански низ живи светови",
    "meta_description": "Научи шпански со Yaguará, јагуар-дух, низ живите светови на Colombia. Три светови за откривање. Бесплатен курс A1-C2 со 144+ средби.",
    "og_description": "Научи шпански со Yaguará низ живите светови на Colombia. Бесплатен курс A1-C2.",
    "twitter_description": "Научи шпански низ живите светови на Colombia со Yaguará. Бесплатен курс.",
    "brand_subtitle": "Жив шпански",
    "nav_languages": "Јазици",
    "nav_journey": "Патувањето",
    "nav_contact": "Контакт",
    "nav_login": "Најава",
    "nav_start": "Започни",
    "hero_subtitle": "Yaguará чека. Патување на јазикот и сеќавањето низ живите светови на Colombia.",
    "feature1_title": "Именувај го светот",
    "feature1_desc": "Учи именувајќи го она што постои: реки, дрвја, животни. Зборот дава живот.",
    "feature2_title": "Целосно потопување",
    "feature2_desc": "Шпански од првиот миг. Без преводи. Само присуство.",
    "feature3_title": "Yaguará те води",
    "feature3_desc": "Јагуар-дух меѓу световите. Оди со тебе, поставува прашања и понекогаш само набљудува.",
    "cta_begin": "Започни го патувањето",
    "free_title": "Сите патеки се бесплатни",
    "free_subtitle": "Без плаќања, без претплати — едноставно започни да одиш",
    "free_desc": "Веруваме дека учењето јазик е право, не привилегија. Три светови за откривање, 144+ средби со живиот јазик и комплетната приказна за Yaguará низ Colombia. Сè бесплатно.",
    "free_feature1": "Три светови за откривање, од корените до ѕвездите",
    "free_feature2": "144+ средби со живиот јазик на Colombia",
    "free_feature3": "Yaguará како твој придружник на секој чекор од патот",
    "free_feature4": "Вистинска географија, култура и традиции на Colombia",
    "about_title": "Што го прави ова патување уникатно?",
    "about_desc": "Ова не е само уште еден курс по шпански. Тоа е патување меѓу светови каде Yaguará — јагуар-дух и чувар — те води низ живите екосистеми на Colombia. Секоја средба е приказна. Секој збор, чин на рамнотежа.",
    "about_feature1_title": "Живи светови",
    "about_feature1_desc": "Од Amazon до Sierra Nevada: вистинска географија, култура и традиции на Colombia",
    "about_feature2_title": "Семиња и патеки",
    "about_feature2_desc": "Твојот напредок се покажува како семиња што растат и соѕвездија што се појавуваат",
    "about_feature3_title": "Гласови на земјата",
    "about_feature3_desc": "Шамани, занаетчии, реки што зборуваат — секој глас те учи автентичен шпански",
    "contact_title": "Си спремен да слушаш?",
    "contact_subtitle": "Патувањето започнува кога ќе одлучиш да одиш",
    "contact_cta": "Направи го првиот чекор",
    "contact_write": "Пишете ни",
    "footer_desc": "Научи шпански со Yaguará, јагуар-дух, низ живите светови на Colombia.",
    "footer_available": "Достапно на повеќе од 100 јазици на babelfree.com",
    "footer_worlds": "Трите Светови",
    "footer_contact": "Контакт",
    "footer_languages": "Јазици",
    "footer_login": "Најава",
    "welcome_title": "🐆 Добредојдовте!",
    "welcome_message": "Yaguará чека. Патувањето започнува."
}

# =============================================================================
# BOSNIAN
# =============================================================================
data["bs"] = {
    "lang_attr": "bs",
    "lang_name_english": "Bosnian",
    "lang_name_native": "Bosanski",
    "meta_title": "La Aventura de Yaguará — Nauči španski kroz žive svjetove",
    "meta_description": "Nauči španski s Yaguará, duhom jaguara, kroz žive svjetove Colombia. Tri svijeta za otkriti. Besplatan kurs A1-C2 sa 144+ susreta.",
    "og_description": "Nauči španski s Yaguará kroz žive svjetove Colombia. Besplatan kurs A1-C2.",
    "twitter_description": "Nauči španski kroz žive svjetove Colombia s Yaguará. Besplatan kurs.",
    "brand_subtitle": "Živi španski",
    "nav_languages": "Jezici",
    "nav_journey": "Putovanje",
    "nav_contact": "Kontakt",
    "nav_login": "Prijava",
    "nav_start": "Započni",
    "hero_subtitle": "Yaguará čeka. Putovanje jezika i sjećanja kroz žive svjetove Colombia.",
    "feature1_title": "Imenuj svijet",
    "feature1_desc": "Uči imenujući ono što postoji: rijeke, stabla, životinje. Riječ daje život.",
    "feature2_title": "Potpuno uranjanje",
    "feature2_desc": "Španski od prvog trenutka. Bez prevoda. Samo prisutnost.",
    "feature3_title": "Yaguará te vodi",
    "feature3_desc": "Duh jaguara između svjetova. Hoda s tobom, postavlja pitanja i ponekad samo posmatra.",
    "cta_begin": "Započni putovanje",
    "free_title": "Svi putevi su besplatni",
    "free_subtitle": "Bez plaćanja, bez pretplata — samo počni hodati",
    "free_desc": "Vjerujemo da je učenje jezika pravo, a ne privilegija. Tri svijeta za otkriti, 144+ susreta sa živim jezikom i kompletna priča o Yaguará kroz Colombia. Sve besplatno.",
    "free_feature1": "Tri svijeta za otkriti, od korijena do zvijezda",
    "free_feature2": "144+ susreta sa živim jezikom Colombia",
    "free_feature3": "Yaguará kao tvoj saputnik na svakom koraku puta",
    "free_feature4": "Stvarna geografija, kultura i tradicije Colombia",
    "about_title": "Šta ovo putovanje čini jedinstvenim?",
    "about_desc": "Ovo nije samo još jedan kurs španskog. To je putovanje između svjetova gdje Yaguará — duh jaguara i čuvar — te vodi kroz žive ekosisteme Colombia. Svaki susret je priča. Svaka riječ, čin ravnoteže.",
    "about_feature1_title": "Živi svjetovi",
    "about_feature1_desc": "Od Amazon do Sierra Nevada: stvarna geografija, kultura i tradicije Colombia",
    "about_feature2_title": "Sjemenke i staze",
    "about_feature2_desc": "Tvoj napredak se pokazuje kao sjemenke koje rastu i sazviježđa koja se pojavljuju",
    "about_feature3_title": "Glasovi zemlje",
    "about_feature3_desc": "Šamani, zanatlije, rijeke koje govore — svaki glas te uči autentični španski",
    "contact_title": "Jesi li spreman slušati?",
    "contact_subtitle": "Putovanje započinje kada odlučiš hodati",
    "contact_cta": "Napravi prvi korak",
    "contact_write": "Piši nam",
    "footer_desc": "Nauči španski s Yaguará, duhom jaguara, kroz žive svjetove Colombia.",
    "footer_available": "Dostupno na više od 100 jezika na babelfree.com",
    "footer_worlds": "Tri Svijeta",
    "footer_contact": "Kontakt",
    "footer_languages": "Jezici",
    "footer_login": "Prijava",
    "welcome_title": "🐆 Dobrodošli!",
    "welcome_message": "Yaguará čeka. Putovanje započinje."
}

# =============================================================================
# ICELANDIC
# =============================================================================
data["is"] = {
    "lang_attr": "is",
    "lang_name_english": "Icelandic",
    "lang_name_native": "Íslenska",
    "meta_title": "La Aventura de Yaguará — Lærðu spænsku í gegnum lifandi heima",
    "meta_description": "Lærðu spænsku með Yaguará, jagúar-andanum, í gegnum lifandi heima Colombia. Þrír heimar til að uppgötva. Ókeypis A1-C2 námskeið með 144+ fundum.",
    "og_description": "Lærðu spænsku með Yaguará í gegnum lifandi heima Colombia. Ókeypis A1-C2 námskeið.",
    "twitter_description": "Lærðu spænsku í gegnum lifandi heima Colombia með Yaguará. Ókeypis námskeið.",
    "brand_subtitle": "Lifandi spænska",
    "nav_languages": "Tungumál",
    "nav_journey": "Ferðalagið",
    "nav_contact": "Hafa samband",
    "nav_login": "Skrá inn",
    "nav_start": "Byrja",
    "hero_subtitle": "Yaguará bíður. Ferðalag tungumáls og minnis í gegnum lifandi heima Colombia.",
    "feature1_title": "Nefndu heiminn",
    "feature1_desc": "Lærðu með því að nefna það sem er til: ár, tré, dýr. Orðið gefur líf.",
    "feature2_title": "Full nám",
    "feature2_desc": "Spænska frá fyrstu stundu. Engar þýðingar. Aðeins nærvera.",
    "feature3_title": "Yaguará leiðir þig",
    "feature3_desc": "Jagúar-andi á milli heima. Hann gengur með þér, spyr spurninga og stundum bara fylgist með.",
    "cta_begin": "Byrjaðu ferðalagið",
    "free_title": "Allar leiðir eru ókeypis",
    "free_subtitle": "Engar greiðslur, engar áskriftir — byrjaðu bara að ganga",
    "free_desc": "Við trúum að tungumálanám sé réttur, ekki forréttindi. Þrír heimar til að uppgötva, 144+ fund með lifandi tungumálinu og heildarsagan af Yaguará um Colombia. Allt ókeypis.",
    "free_feature1": "Þrír heimar til að uppgötva, frá rótum til stjarna",
    "free_feature2": "144+ fund með lifandi tungumáli Colombia",
    "free_feature3": "Yaguará sem félagi þinn á hverju skrefi leiðarinnar",
    "free_feature4": "Raunveruleg landafræði, menning og hefðir Colombia",
    "about_title": "Hvað gerir þetta ferðalag einstakt?",
    "about_desc": "Þetta er ekki bara enn eitt spænskunámskeiðið. Þetta er ferðalag milli heima þar sem Yaguará — jagúar-andi og verndarari — leiðir þig í gegnum lifandi vistkerfi Colombia. Hver fundur er saga. Hvert orð, athöfn jafnvægis.",
    "about_feature1_title": "Lifandi heimar",
    "about_feature1_desc": "Frá Amazon til Sierra Nevada: raunveruleg landafræði, menning og hefðir Colombia",
    "about_feature2_title": "Fræ og slóðir",
    "about_feature2_desc": "Framfarir þínar birtast sem fræ sem vaxa og stjörnumerki sem koma í ljós",
    "about_feature3_title": "Raddir landsins",
    "about_feature3_desc": "Sjámanar, handverksmenn, ár sem tala — hver rödd kennir þér ekta spænsku",
    "contact_title": "Ertu tilbúin/n að hlusta?",
    "contact_subtitle": "Ferðalagið byrjar þegar þú ákveður að ganga",
    "contact_cta": "Taktu fyrsta skrefið",
    "contact_write": "Skrifaðu okkur",
    "footer_desc": "Lærðu spænsku með Yaguará, jagúar-andanum, í gegnum lifandi heima Colombia.",
    "footer_available": "Tiltækt á yfir 100 tungumálum á babelfree.com",
    "footer_worlds": "Þrír Heimarnir",
    "footer_contact": "Hafa samband",
    "footer_languages": "Tungumál",
    "footer_login": "Skrá inn",
    "welcome_title": "🐆 Velkomin!",
    "welcome_message": "Yaguará bíður. Ferðalagið hefst."
}

# =============================================================================
# MALTESE
# =============================================================================
data["mt"] = {
    "lang_attr": "mt",
    "lang_name_english": "Maltese",
    "lang_name_native": "Malti",
    "meta_title": "La Aventura de Yaguará — Tgħallem l-Ispanjol permezz ta' dinjiet ħajjin",
    "meta_description": "Tgħallem l-Ispanjol iggwidat minn Yaguará, spirtu-ġagwar, permezz tad-dinjiet ħajjin ta' Colombia. Tliet dinjiet biex tiskopri. Kors b'xejn A1-C2 b'144+ laqgħat.",
    "og_description": "Tgħallem l-Ispanjol iggwidat minn Yaguará permezz tad-dinjiet ħajjin ta' Colombia. Kors b'xejn A1-C2.",
    "twitter_description": "Tgħallem l-Ispanjol permezz tad-dinjiet ħajjin ta' Colombia ma' Yaguará. Kors b'xejn.",
    "brand_subtitle": "Spanjol ħaj",
    "nav_languages": "Lingwi",
    "nav_journey": "Il-Vjaġġ",
    "nav_contact": "Kuntatt",
    "nav_login": "Idħol",
    "nav_start": "Ibda",
    "hero_subtitle": "Yaguará qed jistenna. Vjaġġ ta' lingwa u memorja permezz tad-dinjiet ħajjin ta' Colombia.",
    "feature1_title": "Semmi d-dinja",
    "feature1_desc": "Tgħallem billi ssemmi dak li jeżisti: xmajjar, siġar, annimali. Il-kelma tagħti l-ħajja.",
    "feature2_title": "Immersjoni totali",
    "feature2_desc": "Spanjol mill-ewwel mument. L-ebda traduzzjonijiet. Biss preżenza.",
    "feature3_title": "Yaguará jiggwidak",
    "feature3_desc": "Spirtu-ġagwar bejn id-dinjiet. Jimxi miegħek, jagħmel mistoqsijiet u xi drabi sempliċement josserva.",
    "cta_begin": "Ibda l-vjaġġ",
    "free_title": "Il-mogħdijiet kollha huma b'xejn",
    "free_subtitle": "L-ebda ħlasijiet, l-ebda abbonamenti — sempliċement ibda miexi",
    "free_desc": "Nemmnu li titgħallem lingwa hija dritt, mhux privileġġ. Tliet dinjiet biex tiskopri, 144+ laqgħat mal-lingwa ħajja, u l-istorja sħiħa ta' Yaguará madwar Colombia. Kollox b'xejn.",
    "free_feature1": "Tliet dinjiet biex tiskopri, mill-għeruq sal-kwiekeb",
    "free_feature2": "144+ laqgħat mal-lingwa ħajja ta' Colombia",
    "free_feature3": "Yaguará bħala sieħeb tiegħek f'kull pass tal-mixja",
    "free_feature4": "Ġeografija reali, kultura u tradizzjonijiet ta' Colombia",
    "about_title": "X'jagħmel dan il-vjaġġ uniku?",
    "about_desc": "Dan mhux sempliċiment kors ieħor tal-Ispanjol. Huwa vjaġġ bejn id-dinjiet fejn Yaguará — spirtu-ġagwar u gwardjan — jiggwidak permezz tal-ekosistemi ħajjin ta' Colombia. Kull laqgħa hija storja. Kull kelma, att ta' bilanċ.",
    "about_feature1_title": "Dinjiet ħajjin",
    "about_feature1_desc": "Mill-Amazon għal Sierra Nevada: ġeografija reali, kultura u tradizzjonijiet ta' Colombia",
    "about_feature2_title": "Żrieragħ u mogħdijiet",
    "about_feature2_desc": "Il-progress tiegħek jidher bħala żrieragħ li jikbru u kostellazzjonijiet li jidhru",
    "about_feature3_title": "Vuċijiet tal-art",
    "about_feature3_desc": "Xjamani, artiġġjani, xmajjar li jitkellmu — kull vuċi tgħallmek Spanjol awtentiku",
    "contact_title": "Inti lest biex tisma'?",
    "contact_subtitle": "Il-vjaġġ jibda meta tiddeċiedi timxi",
    "contact_cta": "Agħmel l-ewwel pass",
    "contact_write": "Iktbilna",
    "footer_desc": "Tgħallem l-Ispanjol iggwidat minn Yaguará, spirtu-ġagwar, permezz tad-dinjiet ħajjin ta' Colombia.",
    "footer_available": "Disponibbli f'aktar minn 100 lingwa fuq babelfree.com",
    "footer_worlds": "It-Tliet Dinjiet",
    "footer_contact": "Kuntatt",
    "footer_languages": "Lingwi",
    "footer_login": "Idħol",
    "welcome_title": "🐆 Merħba!",
    "welcome_message": "Yaguará qed jistenna. Il-vjaġġ jibda."
}

with open("/home/babelfree.com/public_html/generator/translations.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Phase 2 complete: {len(data)} languages written")
