#!/usr/bin/env python3
"""Phase 3: cy, ga, gd, eu, ca, gl, lb, uk, be, ru, tr, af, zh, zh-tw, ja, ko"""

import json

with open("/home/babelfree.com/public_html/generator/translations.json", "r", encoding="utf-8") as f:
    data = json.load(f)

# =============================================================================
# WELSH
# =============================================================================
data["cy"] = {
    "lang_attr": "cy",
    "lang_name_english": "Welsh",
    "lang_name_native": "Cymraeg",
    "meta_title": "La Aventura de Yaguará — Dysgwch Sbaeneg trwy fydoedd byw",
    "meta_description": "Dysgwch Sbaeneg dan arweiniad Yaguará, ysbryd-jagwar, trwy fydoedd byw Colombia. Tri byd i'w darganfod. Cwrs am ddim A1-C2 gyda 144+ o gyfarfodydd.",
    "og_description": "Dysgwch Sbaeneg dan arweiniad Yaguará trwy fydoedd byw Colombia. Cwrs am ddim A1-C2.",
    "twitter_description": "Dysgwch Sbaeneg trwy fydoedd byw Colombia gyda Yaguará. Cwrs am ddim.",
    "brand_subtitle": "Sbaeneg byw",
    "nav_languages": "Ieithoedd",
    "nav_journey": "Y Daith",
    "nav_contact": "Cysylltwch",
    "nav_login": "Mewngofnodi",
    "nav_start": "Dechrau",
    "hero_subtitle": "Mae Yaguará yn aros. Taith iaith a chof trwy fydoedd byw Colombia.",
    "feature1_title": "Enwch y byd",
    "feature1_desc": "Dysgwch trwy enwi'r hyn sy'n bodoli: afonydd, coed, anifeiliaid. Mae'r gair yn rhoi bywyd.",
    "feature2_title": "Trochi llwyr",
    "feature2_desc": "Sbaeneg o'r eiliad gyntaf. Dim cyfieithiadau. Dim ond presenoldeb.",
    "feature3_title": "Yaguará yn eich arwain",
    "feature3_desc": "Ysbryd-jagwar rhwng bydoedd. Mae'n cerdded gyda chi, yn gofyn cwestiynau, ac weithiau'n gwylio'n unig.",
    "cta_begin": "Dechreuwch y daith",
    "free_title": "Mae pob llwybr am ddim",
    "free_subtitle": "Dim taliadau, dim tanysgrifiadau — dechreuwch gerdded",
    "free_desc": "Rydym yn credu bod dysgu iaith yn hawl, nid braint. Tri byd i'w darganfod, 144+ o gyfarfodydd â'r iaith fyw, a hanes cyflawn Yaguará ledled Colombia. I gyd am ddim.",
    "free_feature1": "Tri byd i'w darganfod, o'r gwreiddiau i'r sêr",
    "free_feature2": "144+ o gyfarfodydd ag iaith fyw Colombia",
    "free_feature3": "Yaguará fel eich cydymaith bob cam o'r ffordd",
    "free_feature4": "Daearyddiaeth go iawn, diwylliant a thraddodiadau Colombia",
    "about_title": "Beth sy'n gwneud y daith hon yn unigryw?",
    "about_desc": "Nid cwrs Sbaeneg arall yn unig yw hwn. Mae'n daith rhwng bydoedd lle mae Yaguará — ysbryd-jagwar a gwarcheidwad — yn eich arwain trwy ecosystemau byw Colombia. Mae pob cyfarfod yn stori. Pob gair, yn weithred o gydbwysedd.",
    "about_feature1_title": "Bydoedd byw",
    "about_feature1_desc": "O'r Amazon i Sierra Nevada: daearyddiaeth go iawn, diwylliant a thraddodiadau Colombia",
    "about_feature2_title": "Hadau a llwybrau",
    "about_feature2_desc": "Mae eich cynnydd yn ymddangos fel hadau sy'n tyfu a chytserau sy'n ymddangos",
    "about_feature3_title": "Lleisiau'r tir",
    "about_feature3_desc": "Siamaniaid, crefftwyr, afonydd sy'n siarad — mae pob llais yn eich dysgu Sbaeneg dilys",
    "contact_title": "Ydych chi'n barod i wrando?",
    "contact_subtitle": "Mae'r daith yn dechrau pan fyddwch yn penderfynu cerdded",
    "contact_cta": "Cymerwch y cam cyntaf",
    "contact_write": "Ysgrifennwch atom",
    "footer_desc": "Dysgwch Sbaeneg dan arweiniad Yaguará, ysbryd-jagwar, trwy fydoedd byw Colombia.",
    "footer_available": "Ar gael mewn dros 100 o ieithoedd ar babelfree.com",
    "footer_worlds": "Y Tri Byd",
    "footer_contact": "Cysylltwch",
    "footer_languages": "Ieithoedd",
    "footer_login": "Mewngofnodi",
    "welcome_title": "🐆 Croeso!",
    "welcome_message": "Mae Yaguará yn aros. Mae'r daith yn dechrau."
}

# =============================================================================
# IRISH
# =============================================================================
data["ga"] = {
    "lang_attr": "ga",
    "lang_name_english": "Irish",
    "lang_name_native": "Gaeilge",
    "meta_title": "La Aventura de Yaguará — Foghlaim Spáinnis trí dhomhain bheo",
    "meta_description": "Foghlaim Spáinnis le treoir Yaguará, spiorad-jaguar, trí dhomhain bheo Colombia. Trí dhomhan le fáil amach. Cúrsa saor in aisce A1-C2 le 144+ teagmháil.",
    "og_description": "Foghlaim Spáinnis le treoir Yaguará trí dhomhain bheo Colombia. Cúrsa saor in aisce A1-C2.",
    "twitter_description": "Foghlaim Spáinnis trí dhomhain bheo Colombia le Yaguará. Cúrsa saor in aisce.",
    "brand_subtitle": "Spáinnis bheo",
    "nav_languages": "Teangacha",
    "nav_journey": "An Turas",
    "nav_contact": "Teagmháil",
    "nav_login": "Logáil isteach",
    "nav_start": "Tosaigh",
    "hero_subtitle": "Tá Yaguará ag fanacht. Turas teanga agus cuimhne trí dhomhain bheo Colombia.",
    "feature1_title": "Ainmnigh an domhan",
    "feature1_desc": "Foghlaim trí ainmniú a bhfuil ann: aibhneacha, crainn, ainmhithe. Tugann an focal beatha.",
    "feature2_title": "Tumadh iomlán",
    "feature2_desc": "Spáinnis ón gcéad nóiméad. Gan aistriúcháin. Láithreacht amháin.",
    "feature3_title": "Treoraíonn Yaguará tú",
    "feature3_desc": "Spiorad-jaguar idir dhomhain. Siúlann sé leat, cuireann ceisteanna agus uaireanta ní dhéanann ach breathnú.",
    "cta_begin": "Tosaigh an turas",
    "free_title": "Tá gach cosán saor in aisce",
    "free_subtitle": "Gan íocaíochtaí, gan síntiúis — ní gá ach tosú ag siúl",
    "free_desc": "Creidimid gur ceart é teanga a fhoghlaim, ní pribhléid. Trí dhomhan le fáil amach, 144+ teagmháil leis an teanga bheo, agus scéal iomlán Yaguará ar fud Colombia. Saor in aisce ar fad.",
    "free_feature1": "Trí dhomhan le fáil amach, ó na fréamhacha go na réaltaí",
    "free_feature2": "144+ teagmháil le teanga bheo Colombia",
    "free_feature3": "Yaguará mar do chompánach gach céim den bhealach",
    "free_feature4": "Tíreolaíocht fhíor, cultúr agus traidisiúin Colombia",
    "about_title": "Cad a dhéanann an turas seo uathúil?",
    "about_desc": "Ní cúrsa Spáinnise eile amháin é seo. Is turas é idir dhomhain ina dtreoraíonn Yaguará — spiorad-jaguar agus caomhnóir — tú trí éiceachórais bheo Colombia. Is scéal é gach teagmháil. Gach focal, gníomh cothromaíochta.",
    "about_feature1_title": "Domhain bheo",
    "about_feature1_desc": "Ón Amazon go Sierra Nevada: tíreolaíocht fhíor, cultúr agus traidisiúin Colombia",
    "about_feature2_title": "Síolta agus cosáin",
    "about_feature2_desc": "Taispeántar do dhul chun cinn mar shíolta a fhásann agus réaltbhuíonta a thagann chun solais",
    "about_feature3_title": "Guthanna na talún",
    "about_feature3_desc": "Seamain, ceardaithe, aibhneacha a labhraíonn — múineann gach guth Spáinnis fhírinneach duit",
    "contact_title": "An bhfuil tú réidh le héisteacht?",
    "contact_subtitle": "Tosaíonn an turas nuair a chinneann tú siúl",
    "contact_cta": "Glac an chéad chéim",
    "contact_write": "Scríobh chugainn",
    "footer_desc": "Foghlaim Spáinnis le treoir Yaguará, spiorad-jaguar, trí dhomhain bheo Colombia.",
    "footer_available": "Ar fáil i mbreis is 100 teanga ar babelfree.com",
    "footer_worlds": "Na Trí Dhomhan",
    "footer_contact": "Teagmháil",
    "footer_languages": "Teangacha",
    "footer_login": "Logáil isteach",
    "welcome_title": "🐆 Fáilte!",
    "welcome_message": "Tá Yaguará ag fanacht. Tosaíonn an turas."
}

# =============================================================================
# SCOTTISH GAELIC
# =============================================================================
data["gd"] = {
    "lang_attr": "gd",
    "lang_name_english": "Scottish Gaelic",
    "lang_name_native": "Gàidhlig",
    "meta_title": "La Aventura de Yaguará — Ionnsaich Spàinntis tro shaoghan beò",
    "meta_description": "Ionnsaich Spàinntis le stiùireadh Yaguará, spiorad-jaguar, tro shaoghan beò Colombia. Trì saoghan ri lorg. Cùrsa an-asgaidh A1-C2 le 144+ coinneamhan.",
    "og_description": "Ionnsaich Spàinntis le stiùireadh Yaguará tro shaoghan beò Colombia. Cùrsa an-asgaidh A1-C2.",
    "twitter_description": "Ionnsaich Spàinntis tro shaoghan beò Colombia le Yaguará. Cùrsa an-asgaidh.",
    "brand_subtitle": "Spàinntis bheò",
    "nav_languages": "Cànanan",
    "nav_journey": "An Turas",
    "nav_contact": "Fios thugainn",
    "nav_login": "Clàraich a-steach",
    "nav_start": "Tòisich",
    "hero_subtitle": "Tha Yaguará a' feitheamh. Turas cànain is cuimhne tro shaoghan beò Colombia.",
    "feature1_title": "Ainmich an saoghal",
    "feature1_desc": "Ionnsaich le bhith ag ainmeachadh na th' ann: aibhnichean, craobhan, beathaichean. Bheir am facal beatha.",
    "feature2_title": "Bogadh slàn",
    "feature2_desc": "Spàinntis bhon chiad mhionaid. Gun eadar-theangachadh. Dìreach làthaireachd.",
    "feature3_title": "Stiùiridh Yaguará thu",
    "feature3_desc": "Spiorad-jaguar eadar saoghan. Coiseachdaidh e leat, cuiridh e ceistean agus uaireannan cha dèan e ach coimhead.",
    "cta_begin": "Tòisich an turas",
    "free_title": "Tha gach slighe an-asgaidh",
    "free_subtitle": "Gun phàighidhean, gun fo-sgrìobhaidhean — dìreach tòisich a' coiseachd",
    "free_desc": "Tha sinn a' creidsinn gur e còir a th' ann an cànan ionnsachadh, chan e sochair. Trì saoghan ri lorg, 144+ coinneamhan leis a' chànan bheò, agus sgeulachd shlàn Yaguará air feadh Colombia. An-asgaidh uile.",
    "free_feature1": "Trì saoghan ri lorg, bho na freumhan gu na reultan",
    "free_feature2": "144+ coinneamhan le cànan beò Colombia",
    "free_feature3": "Yaguará mar do chompanach gach ceum den t-slighe",
    "free_feature4": "Cruinn-eòlas fìor, dualchas agus traidiseanan Colombia",
    "about_title": "Dè a nì an turas seo sònraichte?",
    "about_desc": "Chan e dìreach cùrsa Spàinntis eile a tha seo. Is e turas a th' ann eadar saoghan far an stiùir Yaguará — spiorad-jaguar agus neach-gleidhidh — thu tro eag-shiostaman beò Colombia. Is sgeulachd a th' ann an gach coinneamh. Gach facal, gnìomh co-chothromachd.",
    "about_feature1_title": "Saoghan beò",
    "about_feature1_desc": "Bhon Amazon gu Sierra Nevada: cruinn-eòlas fìor, dualchas agus traidiseanan Colombia",
    "about_feature2_title": "Sìl agus slighean",
    "about_feature2_desc": "Nochdaidh d' adhartas mar shìl a' fàs agus reul-bhadan a' nochdadh",
    "about_feature3_title": "Guthan na talmhainn",
    "about_feature3_desc": "Sìomainn, luchd-ciùird, aibhnichean a bhruidhneas — teagaisgidh gach guth Spàinntis fhìor dhuit",
    "contact_title": "A bheil thu deiseil airson èisteachd?",
    "contact_subtitle": "Tòisichidh an turas nuair a cho-dhùineas tu coiseachd",
    "contact_cta": "Gabh a' chiad cheum",
    "contact_write": "Sgrìobh thugainn",
    "footer_desc": "Ionnsaich Spàinntis le stiùireadh Yaguará, spiorad-jaguar, tro shaoghan beò Colombia.",
    "footer_available": "Ri fhaighinn ann an còrr is 100 cànan aig babelfree.com",
    "footer_worlds": "Na Trì Saoghan",
    "footer_contact": "Fios thugainn",
    "footer_languages": "Cànanan",
    "footer_login": "Clàraich a-steach",
    "welcome_title": "🐆 Fàilte!",
    "welcome_message": "Tha Yaguará a' feitheamh. Tha an turas a' tòiseachadh."
}

# =============================================================================
# BASQUE
# =============================================================================
data["eu"] = {
    "lang_attr": "eu",
    "lang_name_english": "Basque",
    "lang_name_native": "Euskara",
    "meta_title": "La Aventura de Yaguará — Ikasi gaztelania mundu bizietan zehar",
    "meta_description": "Ikasi gaztelania Yaguará jaguar-espirituak gidatuta, Colombia-ko mundu bizietan zehar. Hiru mundu deskubritzeko. A1-C2 ikastaroa doan, 144+ topaketekin.",
    "og_description": "Ikasi gaztelania Yaguará-k gidatuta Colombia-ko mundu bizietan zehar. A1-C2 ikastaroa doan.",
    "twitter_description": "Ikasi gaztelania Colombia-ko mundu bizietan zehar Yaguará-rekin. Doako ikastaroa.",
    "brand_subtitle": "Gaztelania bizia",
    "nav_languages": "Hizkuntzak",
    "nav_journey": "Bidaia",
    "nav_contact": "Kontaktua",
    "nav_login": "Sartu",
    "nav_start": "Hasi",
    "hero_subtitle": "Yaguará zain dago. Hizkuntza eta oroimenaren bidaia Colombia-ko mundu bizietan zehar.",
    "feature1_title": "Izendatu mundua",
    "feature1_desc": "Ikasi existitzen dena izendatuz: ibaiak, zuhaitzak, animaliak. Hitzak bizitza ematen du.",
    "feature2_title": "Murgilketa osoa",
    "feature2_desc": "Gaztelania lehen unetik. Itzulpenik gabe. Presentzia soilik.",
    "feature3_title": "Yaguará-k gidatzen zaitu",
    "feature3_desc": "Jaguar-espiritu bat munduen artean. Zurekin ibiltzen da, galderak egiten ditu eta batzuetan begiratzen besterik ez du egiten.",
    "cta_begin": "Hasi bidaia",
    "free_title": "Bide guztiak doakoak dira",
    "free_subtitle": "Ordainketarik ez, harpidetzarik ez — hasi ibiltzen besterik ez",
    "free_desc": "Sinesten dugu hizkuntza ikastea eskubide bat dela, ez pribilegio bat. Hiru mundu deskubritzeko, 144+ topaketa hizkuntza biziarekin, eta Yaguará-ren istorio osoa Colombia osoan zehar. Dena doan.",
    "free_feature1": "Hiru mundu deskubritzeko, sustraietatik izarretara",
    "free_feature2": "144+ topaketa Colombia-ko hizkuntza biziarekin",
    "free_feature3": "Yaguará zure lagun bidearen urrats guztietan",
    "free_feature4": "Benetako geografia, kultura eta Colombia-ko tradizioak",
    "about_title": "Zerk egiten du bidaia hau berezia?",
    "about_desc": "Hau ez da gaztelaniako beste ikastaro bat besterik. Munduen arteko bidaia bat da, non Yaguará-k — jaguar-espiritu eta zaindari — Colombia-ko ekosistema bizietan zehar gidatzen zaituen. Topaketa bakoitza istorio bat da. Hitz bakoitza, oreka-ekintza bat.",
    "about_feature1_title": "Mundu biziak",
    "about_feature1_desc": "Amazon-etik Sierra Nevada-ra: benetako geografia, kultura eta Colombia-ko tradizioak",
    "about_feature2_title": "Haziak eta bideak",
    "about_feature2_desc": "Zure aurrerakuntza hazten diren hazi eta agertzen diren konstelazio gisa erakusten da",
    "about_feature3_title": "Lurraren ahotsak",
    "about_feature3_desc": "Xamanak, artisauak, hitz egiten duten ibaiak — ahots bakoitzak benetako gaztelania irakasten dizu",
    "contact_title": "Prest zaude entzuteko?",
    "contact_subtitle": "Bidaia ibiltzen erabakitzen duzunean hasten da",
    "contact_cta": "Eman lehen urratsa",
    "contact_write": "Idatzi guri",
    "footer_desc": "Ikasi gaztelania Yaguará jaguar-espirituak gidatuta Colombia-ko mundu bizietan zehar.",
    "footer_available": "100 hizkuntza baino gehiagotan eskuragarri babelfree.com-en",
    "footer_worlds": "Hiru Munduak",
    "footer_contact": "Kontaktua",
    "footer_languages": "Hizkuntzak",
    "footer_login": "Sartu",
    "welcome_title": "🐆 Ongi etorri!",
    "welcome_message": "Yaguará zain dago. Bidaia hasten da."
}

# =============================================================================
# CATALAN
# =============================================================================
data["ca"] = {
    "lang_attr": "ca",
    "lang_name_english": "Catalan",
    "lang_name_native": "Català",
    "meta_title": "La Aventura de Yaguará — Aprèn espanyol a través de mons vius",
    "meta_description": "Aprèn espanyol guiat per Yaguará, esperit-jaguar, a través dels mons vius de Colombia. Tres mons per descobrir. Curs gratuït A1-C2 amb 144+ trobades.",
    "og_description": "Aprèn espanyol guiat per Yaguará a través dels mons vius de Colombia. Curs gratuït A1-C2.",
    "twitter_description": "Aprèn espanyol a través dels mons vius de Colombia amb Yaguará. Curs gratuït.",
    "brand_subtitle": "Espanyol viu",
    "nav_languages": "Idiomes",
    "nav_journey": "El Viatge",
    "nav_contact": "Contacte",
    "nav_login": "Inicia sessió",
    "nav_start": "Comença",
    "hero_subtitle": "Yaguará t'espera. Un viatge de llengua i memòria a través dels mons vius de Colombia.",
    "feature1_title": "Anomena el món",
    "feature1_desc": "Aprèn anomenant allò que existeix: rius, arbres, animals. La paraula dona vida.",
    "feature2_title": "Immersió total",
    "feature2_desc": "Espanyol des del primer instant. Sense traduccions. Només presència.",
    "feature3_title": "Yaguará et guia",
    "feature3_desc": "Un esperit-jaguar entre mons. Camina amb tu, fa preguntes i de vegades simplement observa.",
    "cta_begin": "Comença el viatge",
    "free_title": "Tots els camins són gratuïts",
    "free_subtitle": "Sense pagaments, sense subscripcions — simplement comença a caminar",
    "free_desc": "Creiem que aprendre un idioma és un dret, no un privilegi. Tres mons per descobrir, 144+ trobades amb la llengua viva i la història completa de Yaguará per Colombia. Tot gratuït.",
    "free_feature1": "Tres mons per descobrir, des de les arrels fins als estels",
    "free_feature2": "144+ trobades amb la llengua viva de Colombia",
    "free_feature3": "Yaguará com a company a cada pas del camí",
    "free_feature4": "Geografia real, cultura i tradicions de Colombia",
    "about_title": "Què fa aquest viatge únic?",
    "about_desc": "Això no és un simple curs d'espanyol. És un viatge entre mons on Yaguará — esperit-jaguar i guardià — et guia a través dels ecosistemes vius de Colombia. Cada trobada és una història. Cada paraula, un acte d'equilibri.",
    "about_feature1_title": "Mons vius",
    "about_feature1_desc": "De l'Amazon a la Sierra Nevada: geografia real, cultura i tradicions de Colombia",
    "about_feature2_title": "Llavors i camins",
    "about_feature2_desc": "El teu progrés es mostra com llavors que creixen i constel·lacions que apareixen",
    "about_feature3_title": "Veus de la terra",
    "about_feature3_desc": "Xaman, artesans, rius que parlen — cada veu t'ensenya espanyol autèntic",
    "contact_title": "Estàs preparat per escoltar?",
    "contact_subtitle": "El viatge comença quan decideixes caminar",
    "contact_cta": "Fes el primer pas",
    "contact_write": "Escriu-nos",
    "footer_desc": "Aprèn espanyol guiat per Yaguará, esperit-jaguar, a través dels mons vius de Colombia.",
    "footer_available": "Disponible en més de 100 idiomes a babelfree.com",
    "footer_worlds": "Els Tres Mons",
    "footer_contact": "Contacte",
    "footer_languages": "Idiomes",
    "footer_login": "Inicia sessió",
    "welcome_title": "🐆 Benvingut!",
    "welcome_message": "Yaguará t'espera. El viatge comença."
}

# =============================================================================
# GALICIAN
# =============================================================================
data["gl"] = {
    "lang_attr": "gl",
    "lang_name_english": "Galician",
    "lang_name_native": "Galego",
    "meta_title": "La Aventura de Yaguará — Aprende español a través de mundos vivos",
    "meta_description": "Aprende español guiado por Yaguará, espírito-xaguar, a través dos mundos vivos de Colombia. Tres mundos por descubrir. Curso gratuíto A1-C2 con 144+ encontros.",
    "og_description": "Aprende español guiado por Yaguará a través dos mundos vivos de Colombia. Curso gratuíto A1-C2.",
    "twitter_description": "Aprende español a través dos mundos vivos de Colombia con Yaguará. Curso gratuíto.",
    "brand_subtitle": "Español vivo",
    "nav_languages": "Linguas",
    "nav_journey": "A Viaxe",
    "nav_contact": "Contacto",
    "nav_login": "Iniciar sesión",
    "nav_start": "Comezar",
    "hero_subtitle": "Yaguará agarda. Unha viaxe de lingua e memoria a través dos mundos vivos de Colombia.",
    "feature1_title": "Nomea o mundo",
    "feature1_desc": "Aprende nomeando o que existe: ríos, árbores, animais. A palabra dá vida.",
    "feature2_title": "Inmersión total",
    "feature2_desc": "Español dende o primeiro instante. Sen traducións. Só presenza.",
    "feature3_title": "Yaguará guíate",
    "feature3_desc": "Un espírito-xaguar entre mundos. Camiña contigo, fai preguntas e ás veces simplemente observa.",
    "cta_begin": "Comeza a viaxe",
    "free_title": "Todos os camiños son gratuítos",
    "free_subtitle": "Sen pagamentos, sen subscricións — simplemente comeza a camiñar",
    "free_desc": "Cremos que aprender unha lingua é un dereito, non un privilexio. Tres mundos por descubrir, 144+ encontros coa lingua viva e a historia completa de Yaguará por Colombia. Todo gratuíto.",
    "free_feature1": "Tres mundos por descubrir, das raíces ás estrelas",
    "free_feature2": "144+ encontros coa lingua viva de Colombia",
    "free_feature3": "Yaguará como compañeiro en cada paso do camiño",
    "free_feature4": "Xeografía real, cultura e tradicións de Colombia",
    "about_title": "Que fai esta viaxe única?",
    "about_desc": "Isto non é simplemente outro curso de español. É unha viaxe entre mundos onde Yaguará — espírito-xaguar e gardián — guíate a través dos ecosistemas vivos de Colombia. Cada encontro é unha historia. Cada palabra, un acto de equilibrio.",
    "about_feature1_title": "Mundos vivos",
    "about_feature1_desc": "Do Amazon á Sierra Nevada: xeografía real, cultura e tradicións de Colombia",
    "about_feature2_title": "Sementes e camiños",
    "about_feature2_desc": "O teu progreso móstrase como sementes que medran e constelacións que aparecen",
    "about_feature3_title": "Voces da terra",
    "about_feature3_desc": "Xamáns, artesáns, ríos que falan — cada voz ensinache español auténtico",
    "contact_title": "Estás preparado para escoitar?",
    "contact_subtitle": "A viaxe comeza cando decides camiñar",
    "contact_cta": "Dá o primeiro paso",
    "contact_write": "Escríbenos",
    "footer_desc": "Aprende español guiado por Yaguará, espírito-xaguar, a través dos mundos vivos de Colombia.",
    "footer_available": "Dispoñible en máis de 100 linguas en babelfree.com",
    "footer_worlds": "Os Tres Mundos",
    "footer_contact": "Contacto",
    "footer_languages": "Linguas",
    "footer_login": "Iniciar sesión",
    "welcome_title": "🐆 Benvido!",
    "welcome_message": "Yaguará agarda. A viaxe comeza."
}

# =============================================================================
# LUXEMBOURGISH
# =============================================================================
data["lb"] = {
    "lang_attr": "lb",
    "lang_name_english": "Luxembourgish",
    "lang_name_native": "Lëtzebuergesch",
    "meta_title": "La Aventura de Yaguará — Léiert Spuenesch duerch lieweg Welten",
    "meta_description": "Léiert Spuenesch mat Yaguará, dem Jaguar-Geescht, duerch déi lieweg Welten vu Colombia. Dräi Welten ze entdecken. Gratis A1-C2 Cours mat 144+ Begéinungen.",
    "og_description": "Léiert Spuenesch mat Yaguará duerch déi lieweg Welten vu Colombia. Gratis A1-C2 Cours.",
    "twitter_description": "Léiert Spuenesch duerch déi lieweg Welten vu Colombia mat Yaguará. Gratis Cours.",
    "brand_subtitle": "Liewegt Spuenesch",
    "nav_languages": "Sproochen",
    "nav_journey": "D'Rees",
    "nav_contact": "Kontakt",
    "nav_login": "Aloggen",
    "nav_start": "Ufänken",
    "hero_subtitle": "Yaguará waart. Eng Rees vun der Sprooch an der Erënnerung duerch déi lieweg Welten vu Colombia.",
    "feature1_title": "Benenn d'Welt",
    "feature1_desc": "Léiert andeems Dir dat benannt wat existéiert: Flëss, Beem, Déieren. D'Wuert gëtt Liewen.",
    "feature2_title": "Total Andauchen",
    "feature2_desc": "Spuenesch vum éischte Moment un. Keng Iwwersetzungen. Nëmmen Ureesendheet.",
    "feature3_title": "Yaguará féiert Iech",
    "feature3_desc": "E Jaguar-Geescht tëschent Welten. Hie geet mat Iech, stellt Froen a kuckt heiansdo einfach nëmmen zou.",
    "cta_begin": "Fänkt d'Rees un",
    "free_title": "All Weeër si gratis",
    "free_subtitle": "Keng Bezuelung, keng Abonnementer — fänkt einfach un ze goen",
    "free_desc": "Mir gleewen datt eng Sprooch léieren e Recht ass, kee Privileg. Dräi Welten ze entdecken, 144+ Begéinunge mat der lieweger Sprooch an d'komplett Geschicht vu Yaguará duerch Colombia. Alles gratis.",
    "free_feature1": "Dräi Welten ze entdecken, vun de Wuerzelen bis zu de Stären",
    "free_feature2": "144+ Begéinunge mat der lieweger Sprooch vu Colombia",
    "free_feature3": "Yaguará als Äre Begleeder op all Schrëtt vum Wee",
    "free_feature4": "Richteg Geografie, Kultur an Traditioune vu Colombia",
    "about_title": "Wat mécht dës Rees eenzegaarteg?",
    "about_desc": "Dëst ass net nëmmen e weideren Spuenesch-Cours. Et ass eng Rees tëschent Welten wou Yaguará — Jaguar-Geescht a Wiechter — Iech duerch déi lieweg Ökosystemer vu Colombia féiert. All Begéinung ass eng Geschicht. All Wuert, en Akt vum Gläichgewiicht.",
    "about_feature1_title": "Lieweg Welten",
    "about_feature1_desc": "Vum Amazon bis zur Sierra Nevada: richteg Geografie, Kultur an Traditioune vu Colombia",
    "about_feature2_title": "Somen a Weeër",
    "about_feature2_desc": "Äre Fortschrëtt weist sech als Somen déi wuessen a Stärebiller déi erschéngen",
    "about_feature3_title": "Stëmme vum Land",
    "about_feature3_desc": "Schamanen, Handwierker, Flëss déi schwätzen — all Stëmm léiert Iech authentescht Spuenesch",
    "contact_title": "Sidd Dir prett fir ze lauschteren?",
    "contact_subtitle": "D'Rees fänkt un wann Dir entscheet ze goen",
    "contact_cta": "Maacht den éischte Schrëtt",
    "contact_write": "Schreift eis",
    "footer_desc": "Léiert Spuenesch mat Yaguará, dem Jaguar-Geescht, duerch déi lieweg Welten vu Colombia.",
    "footer_available": "Disponibel a méi wéi 100 Sprooche op babelfree.com",
    "footer_worlds": "Déi Dräi Welten",
    "footer_contact": "Kontakt",
    "footer_languages": "Sproochen",
    "footer_login": "Aloggen",
    "welcome_title": "🐆 Wëllkomm!",
    "welcome_message": "Yaguará waart. D'Rees fänkt un."
}

# =============================================================================
# UKRAINIAN
# =============================================================================
data["uk"] = {
    "lang_attr": "uk",
    "lang_name_english": "Ukrainian",
    "lang_name_native": "Українська",
    "meta_title": "La Aventura de Yaguará — Вивчайте іспанську через живі світи",
    "meta_description": "Вивчайте іспанську з Yaguará, духом ягуара, через живі світи Colombia. Три світи для відкриття. Безкоштовний курс A1-C2 зі 144+ зустрічами.",
    "og_description": "Вивчайте іспанську з Yaguará через живі світи Colombia. Безкоштовний курс A1-C2.",
    "twitter_description": "Вивчайте іспанську через живі світи Colombia з Yaguará. Безкоштовний курс.",
    "brand_subtitle": "Жива іспанська",
    "nav_languages": "Мови",
    "nav_journey": "Подорож",
    "nav_contact": "Контакт",
    "nav_login": "Увійти",
    "nav_start": "Почати",
    "hero_subtitle": "Yaguará чекає. Подорож мовою та пам'яттю через живі світи Colombia.",
    "feature1_title": "Назви світ",
    "feature1_desc": "Вчися називаючи те, що існує: річки, дерева, тварини. Слово дає життя.",
    "feature2_title": "Повне занурення",
    "feature2_desc": "Іспанська з першої миті. Без перекладів. Лише присутність.",
    "feature3_title": "Yaguará веде тебе",
    "feature3_desc": "Дух ягуара між світами. Іде з тобою, ставить питання і іноді просто спостерігає.",
    "cta_begin": "Почни подорож",
    "free_title": "Усі шляхи безкоштовні",
    "free_subtitle": "Без платежів, без підписок — просто почни йти",
    "free_desc": "Ми віримо, що вивчення мови — це право, а не привілей. Три світи для відкриття, 144+ зустрічей з живою мовою та повна історія Yaguará по Colombia. Усе безкоштовно.",
    "free_feature1": "Три світи для відкриття, від коріння до зірок",
    "free_feature2": "144+ зустрічей з живою мовою Colombia",
    "free_feature3": "Yaguará як твій супутник на кожному кроці шляху",
    "free_feature4": "Справжня географія, культура та традиції Colombia",
    "about_title": "Що робить цю подорож унікальною?",
    "about_desc": "Це не просто ще один курс іспанської. Це подорож між світами, де Yaguará — дух ягуара та охоронець — веде тебе через живі екосистеми Colombia. Кожна зустріч — це історія. Кожне слово — акт рівноваги.",
    "about_feature1_title": "Живі світи",
    "about_feature1_desc": "Від Amazon до Sierra Nevada: справжня географія, культура та традиції Colombia",
    "about_feature2_title": "Насіння та шляхи",
    "about_feature2_desc": "Твій прогрес з'являється як насіння, що росте, та сузір'я, що виникають",
    "about_feature3_title": "Голоси землі",
    "about_feature3_desc": "Шамани, ремісники, річки що говорять — кожен голос вчить тебе автентичній іспанській",
    "contact_title": "Готовий слухати?",
    "contact_subtitle": "Подорож починається, коли ти вирішуєш йти",
    "contact_cta": "Зроби перший крок",
    "contact_write": "Напиши нам",
    "footer_desc": "Вивчайте іспанську з Yaguará, духом ягуара, через живі світи Colombia.",
    "footer_available": "Доступно більш ніж 100 мовами на babelfree.com",
    "footer_worlds": "Три Світи",
    "footer_contact": "Контакт",
    "footer_languages": "Мови",
    "footer_login": "Увійти",
    "welcome_title": "🐆 Ласкаво просимо!",
    "welcome_message": "Yaguará чекає. Подорож починається."
}

# =============================================================================
# BELARUSIAN
# =============================================================================
data["be"] = {
    "lang_attr": "be",
    "lang_name_english": "Belarusian",
    "lang_name_native": "Беларуская",
    "meta_title": "La Aventura de Yaguará — Вывучайце іспанскую праз жывыя светы",
    "meta_description": "Вывучайце іспанскую з Yaguará, духам ягуара, праз жывыя светы Colombia. Тры светы для адкрыцця. Бясплатны курс A1-C2 са 144+ сустрэчамі.",
    "og_description": "Вывучайце іспанскую з Yaguará праз жывыя светы Colombia. Бясплатны курс A1-C2.",
    "twitter_description": "Вывучайце іспанскую праз жывыя светы Colombia з Yaguará. Бясплатны курс.",
    "brand_subtitle": "Жывая іспанская",
    "nav_languages": "Мовы",
    "nav_journey": "Падарожжа",
    "nav_contact": "Кантакт",
    "nav_login": "Увайсці",
    "nav_start": "Пачаць",
    "hero_subtitle": "Yaguará чакае. Падарожжа мовы і памяці праз жывыя светы Colombia.",
    "feature1_title": "Назаві свет",
    "feature1_desc": "Вучыся называючы тое, што існуе: рэкі, дрэвы, жывёлы. Слова дае жыццё.",
    "feature2_title": "Поўнае пагружэнне",
    "feature2_desc": "Іспанская з першага моманту. Без перакладаў. Толькі прысутнасць.",
    "feature3_title": "Yaguará вядзе цябе",
    "feature3_desc": "Дух ягуара паміж светамі. Ідзе з табой, задае пытанні і часам проста назірае.",
    "cta_begin": "Пачні падарожжа",
    "free_title": "Усе шляхі бясплатныя",
    "free_subtitle": "Без плацяжоў, без падпісак — проста пачні ісці",
    "free_desc": "Мы верым, што вывучэнне мовы — гэта права, а не прывілей. Тры светы для адкрыцця, 144+ сустрэч з жывой мовай і поўная гісторыя Yaguará па Colombia. Усё бясплатна.",
    "free_feature1": "Тры светы для адкрыцця, ад каранёў да зорак",
    "free_feature2": "144+ сустрэч з жывой мовай Colombia",
    "free_feature3": "Yaguará як твой спадарожнік на кожным кроку шляху",
    "free_feature4": "Сапраўдная геаграфія, культура і традыцыі Colombia",
    "about_title": "Што робіць гэтае падарожжа ўнікальным?",
    "about_desc": "Гэта не проста яшчэ адзін курс іспанскай. Гэта падарожжа паміж светамі, дзе Yaguará — дух ягуара і ахоўнік — вядзе цябе праз жывыя экасістэмы Colombia. Кожная сустрэча — гэта гісторыя. Кожнае слова — акт раўнавагі.",
    "about_feature1_title": "Жывыя светы",
    "about_feature1_desc": "Ад Amazon да Sierra Nevada: сапраўдная геаграфія, культура і традыцыі Colombia",
    "about_feature2_title": "Насенне і сцежкі",
    "about_feature2_desc": "Твой прагрэс з'яўляецца як насенне, якое расце, і сузор'і, якія з'яўляюцца",
    "about_feature3_title": "Галасы зямлі",
    "about_feature3_desc": "Шаманы, рамеснікі, рэкі якія гавораць — кожны голас вучыць цябе сапраўднай іспанскай",
    "contact_title": "Гатовы слухаць?",
    "contact_subtitle": "Падарожжа пачынаецца, калі ты вырашаеш ісці",
    "contact_cta": "Зрабі першы крок",
    "contact_write": "Напішы нам",
    "footer_desc": "Вывучайце іспанскую з Yaguará, духам ягуара, праз жывыя светы Colombia.",
    "footer_available": "Даступна на больш чым 100 мовах на babelfree.com",
    "footer_worlds": "Тры Светы",
    "footer_contact": "Кантакт",
    "footer_languages": "Мовы",
    "footer_login": "Увайсці",
    "welcome_title": "🐆 Сардэчна запрашаем!",
    "welcome_message": "Yaguará чакае. Падарожжа пачынаецца."
}

# =============================================================================
# RUSSIAN
# =============================================================================
data["ru"] = {
    "lang_attr": "ru",
    "lang_name_english": "Russian",
    "lang_name_native": "Русский",
    "meta_title": "La Aventura de Yaguará — Учите испанский через живые миры",
    "meta_description": "Учите испанский с Yaguará, духом ягуара, через живые миры Colombia. Три мира для открытия. Бесплатный курс A1-C2 со 144+ встречами.",
    "og_description": "Учите испанский с Yaguará через живые миры Colombia. Бесплатный курс A1-C2.",
    "twitter_description": "Учите испанский через живые миры Colombia с Yaguará. Бесплатный курс.",
    "brand_subtitle": "Живой испанский",
    "nav_languages": "Языки",
    "nav_journey": "Путешествие",
    "nav_contact": "Контакт",
    "nav_login": "Войти",
    "nav_start": "Начать",
    "hero_subtitle": "Yaguará ждёт. Путешествие языка и памяти через живые миры Colombia.",
    "feature1_title": "Назови мир",
    "feature1_desc": "Учись называя то, что существует: реки, деревья, животные. Слово даёт жизнь.",
    "feature2_title": "Полное погружение",
    "feature2_desc": "Испанский с первого мгновения. Без переводов. Только присутствие.",
    "feature3_title": "Yaguará ведёт тебя",
    "feature3_desc": "Дух ягуара между мирами. Идёт с тобой, задаёт вопросы и иногда просто наблюдает.",
    "cta_begin": "Начни путешествие",
    "free_title": "Все пути бесплатны",
    "free_subtitle": "Без платежей, без подписок — просто начни идти",
    "free_desc": "Мы верим, что изучение языка — это право, а не привилегия. Три мира для открытия, 144+ встреч с живым языком и полная история Yaguará по Colombia. Всё бесплатно.",
    "free_feature1": "Три мира для открытия, от корней до звёзд",
    "free_feature2": "144+ встреч с живым языком Colombia",
    "free_feature3": "Yaguará как твой спутник на каждом шаге пути",
    "free_feature4": "Настоящая география, культура и традиции Colombia",
    "about_title": "Что делает это путешествие уникальным?",
    "about_desc": "Это не просто ещё один курс испанского. Это путешествие между мирами, где Yaguará — дух ягуара и хранитель — ведёт тебя через живые экосистемы Colombia. Каждая встреча — это история. Каждое слово — акт равновесия.",
    "about_feature1_title": "Живые миры",
    "about_feature1_desc": "От Amazon до Sierra Nevada: настоящая география, культура и традиции Colombia",
    "about_feature2_title": "Семена и тропы",
    "about_feature2_desc": "Твой прогресс проявляется как семена, которые растут, и созвездия, которые появляются",
    "about_feature3_title": "Голоса земли",
    "about_feature3_desc": "Шаманы, ремесленники, реки которые говорят — каждый голос учит тебя настоящему испанскому",
    "contact_title": "Готов слушать?",
    "contact_subtitle": "Путешествие начинается, когда ты решаешь идти",
    "contact_cta": "Сделай первый шаг",
    "contact_write": "Напиши нам",
    "footer_desc": "Учите испанский с Yaguará, духом ягуара, через живые миры Colombia.",
    "footer_available": "Доступно более чем на 100 языках на babelfree.com",
    "footer_worlds": "Три Мира",
    "footer_contact": "Контакт",
    "footer_languages": "Языки",
    "footer_login": "Войти",
    "welcome_title": "🐆 Добро пожаловать!",
    "welcome_message": "Yaguará ждёт. Путешествие начинается."
}

# =============================================================================
# TURKISH
# =============================================================================
data["tr"] = {
    "lang_attr": "tr",
    "lang_name_english": "Turkish",
    "lang_name_native": "Türkçe",
    "meta_title": "La Aventura de Yaguará — Yaşayan dünyalar aracılığıyla İspanyolca öğrenin",
    "meta_description": "Yaguará, jaguar-ruhu rehberliğinde Colombia'nın yaşayan dünyaları aracılığıyla İspanyolca öğrenin. Keşfedilecek üç dünya. 144+ karşılaşmalı ücretsiz A1-C2 kursu.",
    "og_description": "Yaguará rehberliğinde Colombia'nın yaşayan dünyaları aracılığıyla İspanyolca öğrenin. Ücretsiz A1-C2 kursu.",
    "twitter_description": "Yaguará ile Colombia'nın yaşayan dünyaları aracılığıyla İspanyolca öğrenin. Ücretsiz kurs.",
    "brand_subtitle": "Yaşayan İspanyolca",
    "nav_languages": "Diller",
    "nav_journey": "Yolculuk",
    "nav_contact": "İletişim",
    "nav_login": "Giriş",
    "nav_start": "Başla",
    "hero_subtitle": "Yaguará bekliyor. Colombia'nın yaşayan dünyaları boyunca bir dil ve bellek yolculuğu.",
    "feature1_title": "Dünyayı adlandır",
    "feature1_desc": "Var olanı adlandırarak öğren: nehirler, ağaçlar, hayvanlar. Söz hayat verir.",
    "feature2_title": "Tam daldırma",
    "feature2_desc": "İlk andan itibaren İspanyolca. Çeviri yok. Sadece bulunuş.",
    "feature3_title": "Yaguará sana rehberlik eder",
    "feature3_desc": "Dünyalar arasında bir jaguar-ruhu. Seninle yürür, sorular sorar ve bazen sadece izler.",
    "cta_begin": "Yolculuğa başla",
    "free_title": "Tüm yollar ücretsiz",
    "free_subtitle": "Ödeme yok, abonelik yok — sadece yürümeye başla",
    "free_desc": "Bir dil öğrenmenin ayrıcalık değil, hak olduğuna inanıyoruz. Keşfedilecek üç dünya, 144+ canlı dille karşılaşma ve Yaguará'nın Colombia boyunca tam hikâyesi. Hepsi ücretsiz.",
    "free_feature1": "Köklerden yıldızlara, keşfedilecek üç dünya",
    "free_feature2": "144+ Colombia'nın yaşayan diliyle karşılaşma",
    "free_feature3": "Yolun her adımında Yaguará yol arkadaşın",
    "free_feature4": "Colombia'nın gerçek coğrafyası, kültürü ve gelenekleri",
    "about_title": "Bu yolculuğu benzersiz kılan ne?",
    "about_desc": "Bu sıradan bir İspanyolca kursu değil. Yaguará'nın — jaguar-ruhu ve koruyucu — seni Colombia'nın yaşayan ekosistemleri boyunca yönlendirdiği dünyalar arası bir yolculuk. Her karşılaşma bir hikâye. Her söz, bir denge eylemi.",
    "about_feature1_title": "Yaşayan dünyalar",
    "about_feature1_desc": "Amazon'dan Sierra Nevada'ya: Colombia'nın gerçek coğrafyası, kültürü ve gelenekleri",
    "about_feature2_title": "Tohumlar ve yollar",
    "about_feature2_desc": "İlerlemeniz büyüyen tohumlar ve beliren takımyıldızları olarak görünür",
    "about_feature3_title": "Toprağın sesleri",
    "about_feature3_desc": "Şamanlar, zanaatkârlar, konuşan nehirler — her ses sana otantik İspanyolca öğretir",
    "contact_title": "Dinlemeye hazır mısın?",
    "contact_subtitle": "Yolculuk yürümeye karar verdiğinde başlar",
    "contact_cta": "İlk adımı at",
    "contact_write": "Bize yaz",
    "footer_desc": "Yaguará, jaguar-ruhu rehberliğinde Colombia'nın yaşayan dünyaları aracılığıyla İspanyolca öğrenin.",
    "footer_available": "babelfree.com adresinde 100'den fazla dilde mevcut",
    "footer_worlds": "Üç Dünya",
    "footer_contact": "İletişim",
    "footer_languages": "Diller",
    "footer_login": "Giriş",
    "welcome_title": "🐆 Hoş geldiniz!",
    "welcome_message": "Yaguará bekliyor. Yolculuk başlıyor."
}

# =============================================================================
# AFRIKAANS
# =============================================================================
data["af"] = {
    "lang_attr": "af",
    "lang_name_english": "Afrikaans",
    "lang_name_native": "Afrikaans",
    "meta_title": "La Aventura de Yaguará — Leer Spaans deur lewende wêrelde",
    "meta_description": "Leer Spaans onder leiding van Yaguará, jaguar-gees, deur die lewende wêrelde van Colombia. Drie wêrelde om te ontdek. Gratis A1-C2 kursus met 144+ ontmoetings.",
    "og_description": "Leer Spaans onder leiding van Yaguará deur die lewende wêrelde van Colombia. Gratis A1-C2 kursus.",
    "twitter_description": "Leer Spaans deur die lewende wêrelde van Colombia met Yaguará. Gratis kursus.",
    "brand_subtitle": "Lewende Spaans",
    "nav_languages": "Tale",
    "nav_journey": "Die Reis",
    "nav_contact": "Kontak",
    "nav_login": "Teken in",
    "nav_start": "Begin",
    "hero_subtitle": "Yaguará wag. 'n Reis van taal en herinnering deur die lewende wêrelde van Colombia.",
    "feature1_title": "Noem die wêreld",
    "feature1_desc": "Leer deur te noem wat bestaan: riviere, bome, diere. Die woord gee lewe.",
    "feature2_title": "Totale onderdompeling",
    "feature2_desc": "Spaans van die heel eerste oomblik af. Geen vertalings nie. Net teenwoordigheid.",
    "feature3_title": "Yaguará lei jou",
    "feature3_desc": "'n Jaguar-gees tussen wêrelde. Hy stap saam met jou, vra vrae en kyk soms net.",
    "cta_begin": "Begin die reis",
    "free_title": "Alle paaie is gratis",
    "free_subtitle": "Geen betalings, geen intekenings nie — begin net stap",
    "free_desc": "Ons glo dat 'n taal leer 'n reg is, nie 'n voorreg nie. Drie wêrelde om te ontdek, 144+ ontmoetings met die lewende taal en die volledige verhaal van Yaguará deur Colombia. Alles gratis.",
    "free_feature1": "Drie wêrelde om te ontdek, van die wortels tot die sterre",
    "free_feature2": "144+ ontmoetings met die lewende taal van Colombia",
    "free_feature3": "Yaguará as jou metgesel elke tree van die pad",
    "free_feature4": "Regte geografie, kultuur en tradisies van Colombia",
    "about_title": "Wat maak hierdie reis uniek?",
    "about_desc": "Dit is nie net nog 'n Spaanse kursus nie. Dit is 'n reis tussen wêrelde waar Yaguará — jaguar-gees en bewaker — jou deur die lewende ekostelsels van Colombia lei. Elke ontmoeting is 'n verhaal. Elke woord, 'n daad van balans.",
    "about_feature1_title": "Lewende wêrelde",
    "about_feature1_desc": "Van die Amazon tot die Sierra Nevada: regte geografie, kultuur en tradisies van Colombia",
    "about_feature2_title": "Sade en paaie",
    "about_feature2_desc": "Jou vordering verskyn as sade wat groei en sterrebeelde wat te voorskyn kom",
    "about_feature3_title": "Stemme van die land",
    "about_feature3_desc": "Sjamane, ambagsmanne, riviere wat praat — elke stem leer jou egte Spaans",
    "contact_title": "Is jy gereed om te luister?",
    "contact_subtitle": "Die reis begin wanneer jy besluit om te stap",
    "contact_cta": "Neem die eerste tree",
    "contact_write": "Skryf aan ons",
    "footer_desc": "Leer Spaans onder leiding van Yaguará, jaguar-gees, deur die lewende wêrelde van Colombia.",
    "footer_available": "Beskikbaar in meer as 100 tale by babelfree.com",
    "footer_worlds": "Die Drie Wêrelde",
    "footer_contact": "Kontak",
    "footer_languages": "Tale",
    "footer_login": "Teken in",
    "welcome_title": "🐆 Welkom!",
    "welcome_message": "Yaguará wag. Die reis begin."
}

# =============================================================================
# CHINESE SIMPLIFIED
# =============================================================================
data["zh"] = {
    "lang_attr": "zh-Hans",
    "lang_name_english": "Chinese (Simplified)",
    "lang_name_native": "简体中文",
    "meta_title": "La Aventura de Yaguará — 通过生动世界学习西班牙语",
    "meta_description": "在美洲豹之灵Yaguará的引导下，穿越Colombia的生动世界学习西班牙语。三个世界等待探索。免费A1-C2课程，144+场相遇。",
    "og_description": "在Yaguará的引导下穿越Colombia的生动世界学习西班牙语。免费A1-C2课程。",
    "twitter_description": "与Yaguará一起穿越Colombia的生动世界学习西班牙语。免费课程。",
    "brand_subtitle": "鲜活的西班牙语",
    "nav_languages": "语言",
    "nav_journey": "旅程",
    "nav_contact": "联系",
    "nav_login": "登录",
    "nav_start": "开始",
    "hero_subtitle": "Yaguará在等待。一段穿越Colombia生动世界的语言与记忆之旅。",
    "feature1_title": "命名世界",
    "feature1_desc": "通过命名存在之物来学习：河流、树木、动物。词语赋予生命。",
    "feature2_title": "全面沉浸",
    "feature2_desc": "从第一刻起就是西班牙语。没有翻译。只有存在感。",
    "feature3_title": "Yaguará引导你",
    "feature3_desc": "世界之间的美洲豹之灵。它与你同行，提出问题，有时只是静静观察。",
    "cta_begin": "开始旅程",
    "free_title": "所有道路均免费",
    "free_subtitle": "无需付费，无需订阅——只需开始行走",
    "free_desc": "我们相信学习语言是一种权利，而非特权。三个世界等待探索，144+场与鲜活语言的相遇，以及Yaguará穿越Colombia的完整故事。全部免费。",
    "free_feature1": "三个世界等待探索，从根源到星辰",
    "free_feature2": "144+场与Colombia鲜活语言的相遇",
    "free_feature3": "Yaguará在旅途的每一步陪伴你",
    "free_feature4": "Colombia真实的地理、文化和传统",
    "about_title": "是什么让这段旅程与众不同？",
    "about_desc": "这不仅仅是又一门西班牙语课程。这是一段穿越世界的旅程，Yaguará——美洲豹之灵与守护者——引导你穿越Colombia的生动生态系统。每次相遇都是一个故事。每个词语，都是平衡的行为。",
    "about_feature1_title": "生动世界",
    "about_feature1_desc": "从Amazon到Sierra Nevada：Colombia真实的地理、文化和传统",
    "about_feature2_title": "种子与道路",
    "about_feature2_desc": "你的进步以成长的种子和出现的星座展现",
    "about_feature3_title": "大地之声",
    "about_feature3_desc": "萨满、工匠、会说话的河流——每一个声音都教你地道的西班牙语",
    "contact_title": "你准备好聆听了吗？",
    "contact_subtitle": "当你决定行走时，旅程便开始了",
    "contact_cta": "迈出第一步",
    "contact_write": "写信给我们",
    "footer_desc": "在美洲豹之灵Yaguará的引导下穿越Colombia的生动世界学习西班牙语。",
    "footer_available": "在babelfree.com提供100+种语言版本",
    "footer_worlds": "三个世界",
    "footer_contact": "联系",
    "footer_languages": "语言",
    "footer_login": "登录",
    "welcome_title": "🐆 欢迎！",
    "welcome_message": "Yaguará在等待。旅程开始了。"
}

# =============================================================================
# CHINESE TRADITIONAL
# =============================================================================
data["zh-tw"] = {
    "lang_attr": "zh-Hant",
    "lang_name_english": "Chinese (Traditional)",
    "lang_name_native": "繁體中文",
    "meta_title": "La Aventura de Yaguará — 透過生動世界學習西班牙語",
    "meta_description": "在美洲豹之靈Yaguará的引導下，穿越Colombia的生動世界學習西班牙語。三個世界等待探索。免費A1-C2課程，144+場相遇。",
    "og_description": "在Yaguará的引導下穿越Colombia的生動世界學習西班牙語。免費A1-C2課程。",
    "twitter_description": "與Yaguará一起穿越Colombia的生動世界學習西班牙語。免費課程。",
    "brand_subtitle": "鮮活的西班牙語",
    "nav_languages": "語言",
    "nav_journey": "旅程",
    "nav_contact": "聯繫",
    "nav_login": "登入",
    "nav_start": "開始",
    "hero_subtitle": "Yaguará在等待。一段穿越Colombia生動世界的語言與記憶之旅。",
    "feature1_title": "命名世界",
    "feature1_desc": "透過命名存在之物來學習：河流、樹木、動物。詞語賦予生命。",
    "feature2_title": "全面沉浸",
    "feature2_desc": "從第一刻起就是西班牙語。沒有翻譯。只有存在感。",
    "feature3_title": "Yaguará引導你",
    "feature3_desc": "世界之間的美洲豹之靈。牠與你同行，提出問題，有時只是靜靜觀察。",
    "cta_begin": "開始旅程",
    "free_title": "所有道路均免費",
    "free_subtitle": "無需付費，無需訂閱——只需開始行走",
    "free_desc": "我們相信學習語言是一種權利，而非特權。三個世界等待探索，144+場與鮮活語言的相遇，以及Yaguará穿越Colombia的完整故事。全部免費。",
    "free_feature1": "三個世界等待探索，從根源到星辰",
    "free_feature2": "144+場與Colombia鮮活語言的相遇",
    "free_feature3": "Yaguará在旅途的每一步陪伴你",
    "free_feature4": "Colombia真實的地理、文化和傳統",
    "about_title": "是什麼讓這段旅程與眾不同？",
    "about_desc": "這不僅僅是又一門西班牙語課程。這是一段穿越世界的旅程，Yaguará——美洲豹之靈與守護者——引導你穿越Colombia的生動生態系統。每次相遇都是一個故事。每個詞語，都是平衡的行為。",
    "about_feature1_title": "生動世界",
    "about_feature1_desc": "從Amazon到Sierra Nevada：Colombia真實的地理、文化和傳統",
    "about_feature2_title": "種子與道路",
    "about_feature2_desc": "你的進步以成長的種子和出現的星座展現",
    "about_feature3_title": "大地之聲",
    "about_feature3_desc": "薩滿、工匠、會說話的河流——每一個聲音都教你道地的西班牙語",
    "contact_title": "你準備好聆聽了嗎？",
    "contact_subtitle": "當你決定行走時，旅程便開始了",
    "contact_cta": "邁出第一步",
    "contact_write": "寫信給我們",
    "footer_desc": "在美洲豹之靈Yaguará的引導下穿越Colombia的生動世界學習西班牙語。",
    "footer_available": "在babelfree.com提供100+種語言版本",
    "footer_worlds": "三個世界",
    "footer_contact": "聯繫",
    "footer_languages": "語言",
    "footer_login": "登入",
    "welcome_title": "🐆 歡迎！",
    "welcome_message": "Yaguará在等待。旅程開始了。"
}

# =============================================================================
# JAPANESE
# =============================================================================
data["ja"] = {
    "lang_attr": "ja",
    "lang_name_english": "Japanese",
    "lang_name_native": "日本語",
    "meta_title": "La Aventura de Yaguará — 生きた世界を通じてスペイン語を学ぶ",
    "meta_description": "ジャガーの精霊Yaguaráに導かれ、Colombiaの生きた世界を通じてスペイン語を学びましょう。発見すべき三つの世界。144+の出会いを含む無料A1-C2コース。",
    "og_description": "Yaguaráに導かれColombia の生きた世界を通じてスペイン語を学ぶ。無料A1-C2コース。",
    "twitter_description": "Yaguaráと共にColombiaの生きた世界を通じてスペイン語を学ぶ。無料コース。",
    "brand_subtitle": "生きたスペイン語",
    "nav_languages": "言語",
    "nav_journey": "旅",
    "nav_contact": "お問い合わせ",
    "nav_login": "ログイン",
    "nav_start": "始める",
    "hero_subtitle": "Yaguaráが待っています。Colombiaの生きた世界を巡る言葉と記憶の旅。",
    "feature1_title": "世界に名前をつける",
    "feature1_desc": "存在するものに名前をつけて学ぶ：川、木、動物。言葉が命を与える。",
    "feature2_title": "完全な没入",
    "feature2_desc": "最初の瞬間からスペイン語。翻訳なし。ただ存在するのみ。",
    "feature3_title": "Yaguaráがあなたを導く",
    "feature3_desc": "世界の間を行くジャガーの精霊。あなたと歩き、問いかけ、時にはただ見守る。",
    "cta_begin": "旅を始める",
    "free_title": "すべての道は無料",
    "free_subtitle": "支払いなし、サブスクリプションなし — ただ歩き始めるだけ",
    "free_desc": "言語を学ぶことは特権ではなく権利だと信じています。発見すべき三つの世界、144+の生きた言葉との出会い、そしてColombia全土にわたるYaguaráの完全な物語。すべて無料。",
    "free_feature1": "根源から星々まで、発見すべき三つの世界",
    "free_feature2": "144+のColombiaの生きた言葉との出会い",
    "free_feature3": "旅のすべての一歩にYaguaráが寄り添う",
    "free_feature4": "Colombiaの本物の地理、文化、伝統",
    "about_title": "この旅を特別にするものは？",
    "about_desc": "これは単なるスペイン語コースではありません。Yaguará — ジャガーの精霊にして守護者 — がColombiaの生きた生態系を通じてあなたを導く、世界を渡る旅です。すべての出会いが物語。すべての言葉が、均衡の行為。",
    "about_feature1_title": "生きた世界",
    "about_feature1_desc": "AmazonからSierra Nevadaまで：Colombiaの本物の地理、文化、伝統",
    "about_feature2_title": "種と道",
    "about_feature2_desc": "あなたの進歩は成長する種と現れる星座として映し出される",
    "about_feature3_title": "大地の声",
    "about_feature3_desc": "シャーマン、職人、語りかける川 — すべての声が本物のスペイン語を教える",
    "contact_title": "聴く準備はできていますか？",
    "contact_subtitle": "旅は歩くと決めた時に始まる",
    "contact_cta": "最初の一歩を踏み出す",
    "contact_write": "お問い合わせ",
    "footer_desc": "ジャガーの精霊Yaguaráに導かれ、Colombiaの生きた世界を通じてスペイン語を学ぶ。",
    "footer_available": "babelfree.comにて100以上の言語で利用可能",
    "footer_worlds": "三つの世界",
    "footer_contact": "お問い合わせ",
    "footer_languages": "言語",
    "footer_login": "ログイン",
    "welcome_title": "🐆 ようこそ！",
    "welcome_message": "Yaguaráが待っています。旅が始まります。"
}

# =============================================================================
# KOREAN
# =============================================================================
data["ko"] = {
    "lang_attr": "ko",
    "lang_name_english": "Korean",
    "lang_name_native": "한국어",
    "meta_title": "La Aventura de Yaguará — 살아 있는 세계를 통해 스페인어를 배우세요",
    "meta_description": "재규어의 영혼 Yaguará의 인도로 Colombia의 살아 있는 세계를 통해 스페인어를 배우세요. 발견할 세 개의 세계. 144+개의 만남이 포함된 무료 A1-C2 과정.",
    "og_description": "Yaguará의 인도로 Colombia의 살아 있는 세계를 통해 스페인어를 배우세요. 무료 A1-C2 과정.",
    "twitter_description": "Yaguará와 함께 Colombia의 살아 있는 세계를 통해 스페인어를 배우세요. 무료 과정.",
    "brand_subtitle": "살아 있는 스페인어",
    "nav_languages": "언어",
    "nav_journey": "여정",
    "nav_contact": "연락처",
    "nav_login": "로그인",
    "nav_start": "시작",
    "hero_subtitle": "Yaguará가 기다립니다. Colombia의 살아 있는 세계를 관통하는 언어와 기억의 여정.",
    "feature1_title": "세상에 이름을 붙이다",
    "feature1_desc": "존재하는 것에 이름을 붙여 배우세요: 강, 나무, 동물. 말이 생명을 줍니다.",
    "feature2_title": "완전한 몰입",
    "feature2_desc": "첫 순간부터 스페인어. 번역 없이. 오직 존재만으로.",
    "feature3_title": "Yaguará가 안내합니다",
    "feature3_desc": "세계 사이의 재규어 영혼. 당신과 함께 걷고, 질문하고, 때로는 그저 지켜봅니다.",
    "cta_begin": "여정을 시작하세요",
    "free_title": "모든 길은 무료입니다",
    "free_subtitle": "결제 없이, 구독 없이 — 그냥 걷기 시작하세요",
    "free_desc": "언어를 배우는 것은 특권이 아닌 권리라고 믿습니다. 발견할 세 개의 세계, 144+개의 살아 있는 언어와의 만남, 그리고 Colombia 전역에 걸친 Yaguará의 완전한 이야기. 모두 무료.",
    "free_feature1": "뿌리에서 별까지, 발견할 세 개의 세계",
    "free_feature2": "144+개의 Colombia 살아 있는 언어와의 만남",
    "free_feature3": "여정의 모든 발걸음에 Yaguará가 함께합니다",
    "free_feature4": "Colombia의 진짜 지리, 문화, 전통",
    "about_title": "이 여정을 특별하게 만드는 것은?",
    "about_desc": "이것은 단순한 스페인어 과정이 아닙니다. Yaguará — 재규어의 영혼이자 수호자 — 가 Colombia의 살아 있는 생태계를 통해 당신을 안내하는, 세계를 넘나드는 여정입니다. 모든 만남은 이야기. 모든 말은 균형의 행위.",
    "about_feature1_title": "살아 있는 세계",
    "about_feature1_desc": "Amazon에서 Sierra Nevada까지: Colombia의 진짜 지리, 문화, 전통",
    "about_feature2_title": "씨앗과 길",
    "about_feature2_desc": "당신의 진보는 자라나는 씨앗과 나타나는 별자리로 보입니다",
    "about_feature3_title": "대지의 목소리",
    "about_feature3_desc": "샤먼, 장인, 말하는 강 — 모든 목소리가 당신에게 진짜 스페인어를 가르칩니다",
    "contact_title": "들을 준비가 되셨나요?",
    "contact_subtitle": "여정은 걷기로 결정할 때 시작됩니다",
    "contact_cta": "첫걸음을 내딛으세요",
    "contact_write": "문의하기",
    "footer_desc": "재규어의 영혼 Yaguará의 인도로 Colombia의 살아 있는 세계를 통해 스페인어를 배우세요.",
    "footer_available": "babelfree.com에서 100개 이상의 언어로 이용 가능",
    "footer_worlds": "세 개의 세계",
    "footer_contact": "연락처",
    "footer_languages": "언어",
    "footer_login": "로그인",
    "welcome_title": "🐆 환영합니다!",
    "welcome_message": "Yaguará가 기다립니다. 여정이 시작됩니다."
}

with open("/home/babelfree.com/public_html/generator/translations.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Phase 3 complete: {len(data)} languages written")
