#!/usr/bin/env python3
"""
Generate login_lang_data.js from translation data files and language metadata.
Combines translations from login_trans_eu.py, login_trans_asia.py, login_trans_other.py
with language metadata from lang_data_1.py, lang_data_2.py, lang_data_3.py.
"""

import json
import sys
import os

# Import language metadata
from lang_data_1 import LANGS_1
from lang_data_2 import LANGS_2
from lang_data_3 import LANGS_3

# Import translation data
from login_trans_eu import TRANS_EU
from login_trans_asia import TRANS_ASIA
from login_trans_other import TRANS_OTHER

# Combine all languages metadata
ALL_LANGS = LANGS_1 + LANGS_2 + LANGS_3

# Combine all translations
ALL_TRANSLATIONS = {}
ALL_TRANSLATIONS.update(TRANS_EU)
ALL_TRANSLATIONS.update(TRANS_ASIA)
ALL_TRANSLATIONS.update(TRANS_OTHER)

# English fallback
EN = ALL_TRANSLATIONS.get("en", {})

# The 38 translation keys
KEYS = [
    "nav.back", "ui.auto-detect", "ui.select-language", "auth.welcome",
    "auth.subtitle", "ui.lang-detected", "ui.lang-suggestion", "version.title",
    "version.individual-title", "version.individual-desc", "version.classroom-title",
    "version.classroom-desc", "registration.pref-title", "demo.title",
    "form.email", "form.password", "demo.guest-option", "form.email-label",
    "form.password-label", "auth.forgot-password", "auth.login-button", "ui.or",
    "auth.guest-access", "auth.signup-prompt", "auth.signup-link",
    "notify.version-selected", "notify.version-configured", "notify.credentials-loaded",
    "notify.credentials-filled", "error.fill-all-fields", "error.invalid-credentials",
    "error.wrong-version", "login.redirecting-student", "login.redirecting-teacher",
    "guest.accessing", "session.active-redirecting", "placeholder.email",
    "placeholder.password",
]


def get_translation(code, key):
    """Get translated string with English fallback."""
    lang_data = ALL_TRANSLATIONS.get(code, EN)
    return lang_data.get(key, EN.get(key, key))


def generate_js():
    """Generate login_lang_data.js file."""
    lines = []
    lines.append("// Auto-generated by generate_login_translations.py")
    lines.append("// Do not edit manually — regenerate with: python3 generate_login_translations.py")
    lines.append("")

    # Build LOGIN_TRANSLATIONS object
    lines.append("window.LOGIN_TRANSLATIONS = {")

    # Add "auto" as alias for "es"
    lines.append('  "auto": null, // resolved at runtime to es')

    # Track which language codes we have metadata for
    lang_meta = {}
    for entry in ALL_LANGS:
        code = entry[0]
        lang_meta[code] = entry

    # Add "es" first (Spanish — the target language)
    es_trans = ALL_TRANSLATIONS.get("es", EN)
    lines.append('  "es": ' + json.dumps(es_trans, ensure_ascii=False) + ",")

    # Add all other languages that have both metadata and translations
    for entry in ALL_LANGS:
        code = entry[0]
        if code == "es":
            continue  # already added

        if code in ALL_TRANSLATIONS:
            trans = ALL_TRANSLATIONS[code]
        else:
            # Use English fallback for languages without translations
            trans = dict(EN)

        # Ensure all keys are present (fill missing with English)
        for key in KEYS:
            if key not in trans:
                trans[key] = EN.get(key, key)

        lines.append('  "' + code + '": ' + json.dumps(trans, ensure_ascii=False) + ",")

    lines.append("};")
    lines.append("")

    # Resolve "auto" to "es" reference
    lines.append('window.LOGIN_TRANSLATIONS["auto"] = window.LOGIN_TRANSLATIONS["es"];')
    lines.append("")

    # Build LOGIN_LANGUAGES array
    lines.append("window.LOGIN_LANGUAGES = [")

    # Add auto-detect entry first
    lines.append('  { code: "auto", name: "Auto-Detect", native: "Auto", flag: "🌐", dir: "ltr" },')

    for entry in ALL_LANGS:
        code, name, native, flag = entry[0], entry[1], entry[2], entry[3]
        direction = entry[7] if len(entry) > 7 else "ltr"
        lines.append(
            "  { "
            + f'code: "{code}", name: {json.dumps(name, ensure_ascii=False)}, '
            + f'native: {json.dumps(native, ensure_ascii=False)}, '
            + f'flag: {json.dumps(flag, ensure_ascii=False)}, '
            + f'dir: "{direction}"'
            + " },"
        )

    lines.append("];")
    lines.append("")

    return "\n".join(lines)


def main():
    js_content = generate_js()

    output_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "login_lang_data.js")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(js_content)

    # Stats
    lang_count = len([e for e in ALL_LANGS if e[0] in ALL_TRANSLATIONS])
    total_langs = len(ALL_LANGS)
    print(f"✅ Generated {output_path}")
    print(f"   Languages with translations: {lang_count}/{total_langs}")
    print(f"   Keys per language: {len(KEYS)}")
    print(f"   File size: {len(js_content):,} bytes ({len(js_content)/1024:.1f} KB)")

    # List languages without translations
    missing = [e[0] for e in ALL_LANGS if e[0] not in ALL_TRANSLATIONS]
    if missing:
        print(f"   ⚠ Languages using English fallback: {', '.join(missing)}")


if __name__ == "__main__":
    main()
