"""Login page translations — Europe + Americas languages."""
TRANS_EU = {
    "es": {
        "nav.back": "← Volver", "ui.auto-detect": "Automático", "ui.select-language": "Seleccionar Idioma",
        "auth.welcome": "¡Bienvenido!", "auth.subtitle": "Continúa tu aventura con Yaguará por los ecosistemas colombianos",
        "ui.lang-detected": "🌍 Idioma detectado automáticamente", "ui.lang-suggestion": "💡 ¿Prefieres continuar en tu idioma nativo?",
        "version.title": "🎯 Elige tu camino de aprendizaje con Yaguará",
        "version.individual-title": "Viaje individual", "version.individual-desc": "Aventura personal con Yaguará por Colombia",
        "version.classroom-title": "Edición aula", "version.classroom-desc": "Aprendizaje estructurado para educadores",
        "registration.pref-title": "📚 Selecciona tu idioma de aprendizaje preferido",
        "demo.title": "🎯 Acceso de demostración", "form.email": "Email", "form.password": "Contraseña",
        "demo.guest-option": "O explora como invitado sin registrarte",
        "form.email-label": "📧 Dirección de Email", "form.password-label": "🔒 Contraseña",
        "auth.forgot-password": "¿Olvidaste tu contraseña?", "auth.login-button": "Comenzar Aventura",
        "ui.or": "o", "auth.guest-access": "Acceso como Invitado",
        "auth.signup-prompt": "¿No tienes cuenta?", "auth.signup-link": "Regístrate aquí",
        "notify.version-selected": "Versión Seleccionada", "notify.version-configured": "configurada",
        "notify.credentials-loaded": "Credenciales Cargadas", "notify.credentials-filled": "Datos de demo rellenados",
        "error.fill-all-fields": "Por favor completa todos los campos.",
        "error.invalid-credentials": "Credenciales inválidas para la versión seleccionada.",
        "error.wrong-version": "Este email es para la versión {version}. Por favor selecciona la versión correcta.",
        "login.redirecting-student": "🐆 ¡Bienvenido! Redirigiendo al panel de estudiante...",
        "login.redirecting-teacher": "👨‍🏫 ¡Bienvenido! Redirigiendo al panel de profesor...",
        "guest.accessing": "🌟 Accediendo como invitado...",
        "session.active-redirecting": "🐆 Sesión activa detectada. Redirigiendo...",
        "placeholder.email": "tu@correo.com", "placeholder.password": "Tu contraseña",
    },
    "en": {
        "nav.back": "← Back", "ui.auto-detect": "Auto", "ui.select-language": "Select Language",
        "auth.welcome": "Welcome!", "auth.subtitle": "Continue your adventure with Yaguará through Colombian ecosystems",
        "ui.lang-detected": "🌍 Language detected automatically", "ui.lang-suggestion": "💡 Would you prefer to continue in your native language?",
        "version.title": "🎯 Choose your learning path with Yaguará",
        "version.individual-title": "Individual Journey", "version.individual-desc": "Personal adventure with Yaguará through Colombia",
        "version.classroom-title": "Classroom Edition", "version.classroom-desc": "Structured learning for educators",
        "registration.pref-title": "📚 Select your preferred learning language",
        "demo.title": "🎯 Demo Access", "form.email": "Email", "form.password": "Password",
        "demo.guest-option": "Or explore as a guest without registration",
        "form.email-label": "📧 Email Address", "form.password-label": "🔒 Password",
        "auth.forgot-password": "Forgot your password?", "auth.login-button": "Start Adventure",
        "ui.or": "or", "auth.guest-access": "Guest Access",
        "auth.signup-prompt": "Don't have an account?", "auth.signup-link": "Sign up here",
        "notify.version-selected": "Version Selected", "notify.version-configured": "configured",
        "notify.credentials-loaded": "Credentials Loaded", "notify.credentials-filled": "Demo data filled",
        "error.fill-all-fields": "Please fill in all fields.",
        "error.invalid-credentials": "Invalid credentials for the selected version.",
        "error.wrong-version": "This email is for the {version} version. Please select the correct version.",
        "login.redirecting-student": "🐆 Welcome! Redirecting to student panel...",
        "login.redirecting-teacher": "👨‍🏫 Welcome! Redirecting to teacher panel...",
        "guest.accessing": "🌟 Accessing as guest...",
        "session.active-redirecting": "🐆 Active session detected. Redirecting...",
        "placeholder.email": "your@email.com", "placeholder.password": "Your password",
    },
    "fr": {
        "nav.back": "← Retour", "ui.auto-detect": "Automatique", "ui.select-language": "Sélectionner la Langue",
        "auth.welcome": "Bienvenue!", "auth.subtitle": "Continuez votre aventure avec Yaguará à travers les écosystèmes colombiens",
        "ui.lang-detected": "🌍 Langue détectée automatiquement", "ui.lang-suggestion": "💡 Préférez-vous continuer dans votre langue maternelle?",
        "version.title": "🎯 Choisissez votre parcours d'apprentissage avec Yaguará",
        "version.individual-title": "Voyage Individuel", "version.individual-desc": "Aventure personnelle avec Yaguará en Colombie",
        "version.classroom-title": "Édition Classe", "version.classroom-desc": "Apprentissage structuré pour éducateurs",
        "registration.pref-title": "📚 Sélectionnez votre langue d'apprentissage préférée",
        "demo.title": "🎯 Accès Démo", "form.email": "Email", "form.password": "Mot de passe",
        "demo.guest-option": "Ou explorez comme invité sans inscription",
        "form.email-label": "📧 Adresse Email", "form.password-label": "🔒 Mot de passe",
        "auth.forgot-password": "Mot de passe oublié?", "auth.login-button": "Commencer l'Aventure",
        "ui.or": "ou", "auth.guest-access": "Accès Invité",
        "auth.signup-prompt": "Pas de compte?", "auth.signup-link": "Inscrivez-vous ici",
        "notify.version-selected": "Version Sélectionnée", "notify.version-configured": "configurée",
        "notify.credentials-loaded": "Identifiants Chargés", "notify.credentials-filled": "Données démo remplies",
        "error.fill-all-fields": "Veuillez remplir tous les champs.",
        "error.invalid-credentials": "Identifiants invalides pour la version sélectionnée.",
        "error.wrong-version": "Cet email est pour la version {version}. Veuillez sélectionner la version correcte.",
        "login.redirecting-student": "🐆 Bienvenue! Redirection vers le panneau étudiant...",
        "login.redirecting-teacher": "👨‍🏫 Bienvenue! Redirection vers le panneau enseignant...",
        "guest.accessing": "🌟 Accès en tant qu'invité...",
        "session.active-redirecting": "🐆 Session active détectée. Redirection...",
        "placeholder.email": "votre@email.com", "placeholder.password": "Votre mot de passe",
    },
    "de": {
        "nav.back": "← Zurück", "ui.auto-detect": "Automatisch", "ui.select-language": "Sprache auswählen",
        "auth.welcome": "Willkommen!", "auth.subtitle": "Setze dein Abenteuer mit Yaguará durch die kolumbianischen Ökosysteme fort",
        "ui.lang-detected": "🌍 Sprache automatisch erkannt", "ui.lang-suggestion": "💡 Möchtest du in deiner Muttersprache fortfahren?",
        "version.title": "🎯 Wähle deinen Lernpfad mit Yaguará",
        "version.individual-title": "Individuelle Reise", "version.individual-desc": "Persönliches Abenteuer mit Yaguará durch Kolumbien",
        "version.classroom-title": "Klassenraum-Edition", "version.classroom-desc": "Strukturiertes Lernen für Pädagogen",
        "registration.pref-title": "📚 Wähle deine bevorzugte Lernsprache",
        "demo.title": "🎯 Demo-Zugang", "form.email": "E-Mail", "form.password": "Passwort",
        "demo.guest-option": "Oder erkunde als Gast ohne Registrierung",
        "form.email-label": "📧 E-Mail-Adresse", "form.password-label": "🔒 Passwort",
        "auth.forgot-password": "Passwort vergessen?", "auth.login-button": "Abenteuer starten",
        "ui.or": "oder", "auth.guest-access": "Gastzugang",
        "auth.signup-prompt": "Noch kein Konto?", "auth.signup-link": "Hier registrieren",
        "notify.version-selected": "Version ausgewählt", "notify.version-configured": "konfiguriert",
        "notify.credentials-loaded": "Zugangsdaten geladen", "notify.credentials-filled": "Demodaten ausgefüllt",
        "error.fill-all-fields": "Bitte fülle alle Felder aus.",
        "error.invalid-credentials": "Ungültige Zugangsdaten für die ausgewählte Version.",
        "error.wrong-version": "Diese E-Mail ist für die Version {version}. Bitte wähle die richtige Version.",
        "login.redirecting-student": "🐆 Willkommen! Weiterleitung zum Schülerpanel...",
        "login.redirecting-teacher": "👨‍🏫 Willkommen! Weiterleitung zum Lehrerpanel...",
        "guest.accessing": "🌟 Zugang als Gast...",
        "session.active-redirecting": "🐆 Aktive Sitzung erkannt. Weiterleitung...",
        "placeholder.email": "deine@email.com", "placeholder.password": "Dein Passwort",
    },
    "it": {
        "nav.back": "← Indietro", "ui.auto-detect": "Automatico", "ui.select-language": "Seleziona Lingua",
        "auth.welcome": "Benvenuto!", "auth.subtitle": "Continua la tua avventura con Yaguará attraverso gli ecosistemi colombiani",
        "ui.lang-detected": "🌍 Lingua rilevata automaticamente", "ui.lang-suggestion": "💡 Preferisci continuare nella tua lingua madre?",
        "version.title": "🎯 Scegli il tuo percorso di apprendimento con Yaguará",
        "version.individual-title": "Viaggio Individuale", "version.individual-desc": "Avventura personale con Yaguará in Colombia",
        "version.classroom-title": "Edizione Classe", "version.classroom-desc": "Apprendimento strutturato per educatori",
        "registration.pref-title": "📚 Seleziona la tua lingua di apprendimento preferita",
        "demo.title": "🎯 Accesso Demo", "form.email": "Email", "form.password": "Password",
        "demo.guest-option": "Oppure esplora come ospite senza registrazione",
        "form.email-label": "📧 Indirizzo Email", "form.password-label": "🔒 Password",
        "auth.forgot-password": "Password dimenticata?", "auth.login-button": "Inizia l'Avventura",
        "ui.or": "o", "auth.guest-access": "Accesso Ospite",
        "auth.signup-prompt": "Non hai un account?", "auth.signup-link": "Registrati qui",
        "notify.version-selected": "Versione Selezionata", "notify.version-configured": "configurata",
        "notify.credentials-loaded": "Credenziali Caricate", "notify.credentials-filled": "Dati demo inseriti",
        "error.fill-all-fields": "Compila tutti i campi.",
        "error.invalid-credentials": "Credenziali non valide per la versione selezionata.",
        "error.wrong-version": "Questa email è per la versione {version}. Seleziona la versione corretta.",
        "login.redirecting-student": "🐆 Benvenuto! Reindirizzamento al pannello studente...",
        "login.redirecting-teacher": "👨‍🏫 Benvenuto! Reindirizzamento al pannello insegnante...",
        "guest.accessing": "🌟 Accesso come ospite...",
        "session.active-redirecting": "🐆 Sessione attiva rilevata. Reindirizzamento...",
        "placeholder.email": "tua@email.com", "placeholder.password": "La tua password",
    },
    "pt": {
        "nav.back": "← Voltar", "ui.auto-detect": "Automático", "ui.select-language": "Selecionar Idioma",
        "auth.welcome": "Bem-vindo!", "auth.subtitle": "Continue sua aventura com Yaguará pelos ecossistemas colombianos",
        "ui.lang-detected": "🌍 Idioma detectado automaticamente", "ui.lang-suggestion": "💡 Prefere continuar no seu idioma nativo?",
        "version.title": "🎯 Escolha seu caminho de aprendizado com Yaguará",
        "version.individual-title": "Jornada Individual", "version.individual-desc": "Aventura pessoal com Yaguará pela Colômbia",
        "version.classroom-title": "Edição Sala de Aula", "version.classroom-desc": "Aprendizado estruturado para educadores",
        "registration.pref-title": "📚 Selecione seu idioma de aprendizado preferido",
        "demo.title": "🎯 Acesso Demo", "form.email": "Email", "form.password": "Senha",
        "demo.guest-option": "Ou explore como convidado sem registro",
        "form.email-label": "📧 Endereço de Email", "form.password-label": "🔒 Senha",
        "auth.forgot-password": "Esqueceu sua senha?", "auth.login-button": "Começar Aventura",
        "ui.or": "ou", "auth.guest-access": "Acesso Convidado",
        "auth.signup-prompt": "Não tem conta?", "auth.signup-link": "Cadastre-se aqui",
        "notify.version-selected": "Versão Selecionada", "notify.version-configured": "configurada",
        "notify.credentials-loaded": "Credenciais Carregadas", "notify.credentials-filled": "Dados demo preenchidos",
        "error.fill-all-fields": "Preencha todos os campos.",
        "error.invalid-credentials": "Credenciais inválidas para a versão selecionada.",
        "error.wrong-version": "Este email é para a versão {version}. Selecione a versão correta.",
        "login.redirecting-student": "🐆 Bem-vindo! Redirecionando para o painel do estudante...",
        "login.redirecting-teacher": "👨‍🏫 Bem-vindo! Redirecionando para o painel do professor...",
        "guest.accessing": "🌟 Acessando como convidado...",
        "session.active-redirecting": "🐆 Sessão ativa detectada. Redirecionando...",
        "placeholder.email": "seu@email.com", "placeholder.password": "Sua senha",
    },
    "nl": {
        "nav.back": "← Terug", "ui.auto-detect": "Automatisch", "ui.select-language": "Taal selecteren",
        "auth.welcome": "Welkom!", "auth.subtitle": "Ga verder met je avontuur met Yaguará door de Colombiaanse ecosystemen",
        "ui.lang-detected": "🌍 Taal automatisch gedetecteerd", "ui.lang-suggestion": "💡 Wil je doorgaan in je moedertaal?",
        "version.title": "🎯 Kies je leerpad met Yaguará",
        "version.individual-title": "Individuele Reis", "version.individual-desc": "Persoonlijk avontuur met Yaguará door Colombia",
        "version.classroom-title": "Klaslokaal Editie", "version.classroom-desc": "Gestructureerd leren voor docenten",
        "registration.pref-title": "📚 Selecteer je voorkeurstaal",
        "demo.title": "🎯 Demo Toegang", "form.email": "E-mail", "form.password": "Wachtwoord",
        "demo.guest-option": "Of verken als gast zonder registratie",
        "form.email-label": "📧 E-mailadres", "form.password-label": "🔒 Wachtwoord",
        "auth.forgot-password": "Wachtwoord vergeten?", "auth.login-button": "Start Avontuur",
        "ui.or": "of", "auth.guest-access": "Gasttoegang",
        "auth.signup-prompt": "Geen account?", "auth.signup-link": "Registreer hier",
        "notify.version-selected": "Versie Geselecteerd", "notify.version-configured": "geconfigureerd",
        "notify.credentials-loaded": "Inloggegevens Geladen", "notify.credentials-filled": "Demogegevens ingevuld",
        "error.fill-all-fields": "Vul alle velden in.", "error.invalid-credentials": "Ongeldige inloggegevens voor de geselecteerde versie.",
        "error.wrong-version": "Dit e-mailadres is voor versie {version}. Selecteer de juiste versie.",
        "login.redirecting-student": "🐆 Welkom! Doorverwijzing naar studentenpaneel...",
        "login.redirecting-teacher": "👨‍🏫 Welkom! Doorverwijzing naar docentenpaneel...",
        "guest.accessing": "🌟 Toegang als gast...", "session.active-redirecting": "🐆 Actieve sessie gedetecteerd. Doorverwijzing...",
        "placeholder.email": "jouw@email.com", "placeholder.password": "Je wachtwoord",
    },
    "pl": {
        "nav.back": "← Wróć", "ui.auto-detect": "Automatycznie", "ui.select-language": "Wybierz język",
        "auth.welcome": "Witaj!", "auth.subtitle": "Kontynuuj przygodę z Yaguará przez kolumbijskie ekosystemy",
        "ui.lang-detected": "🌍 Język wykryty automatycznie", "ui.lang-suggestion": "💡 Wolisz kontynuować w swoim języku?",
        "version.title": "🎯 Wybierz ścieżkę nauki z Yaguará",
        "version.individual-title": "Podróż Indywidualna", "version.individual-desc": "Osobista przygoda z Yaguará przez Kolumbię",
        "version.classroom-title": "Edycja Klasowa", "version.classroom-desc": "Strukturalna nauka dla nauczycieli",
        "registration.pref-title": "📚 Wybierz preferowany język nauki",
        "demo.title": "🎯 Dostęp Demo", "form.email": "Email", "form.password": "Hasło",
        "demo.guest-option": "Lub eksploruj jako gość bez rejestracji",
        "form.email-label": "📧 Adres Email", "form.password-label": "🔒 Hasło",
        "auth.forgot-password": "Zapomniałeś hasła?", "auth.login-button": "Rozpocznij Przygodę",
        "ui.or": "lub", "auth.guest-access": "Dostęp Gościnny",
        "auth.signup-prompt": "Nie masz konta?", "auth.signup-link": "Zarejestruj się",
        "notify.version-selected": "Wersja Wybrana", "notify.version-configured": "skonfigurowana",
        "notify.credentials-loaded": "Dane załadowane", "notify.credentials-filled": "Dane demo uzupełnione",
        "error.fill-all-fields": "Wypełnij wszystkie pola.", "error.invalid-credentials": "Nieprawidłowe dane dla wybranej wersji.",
        "error.wrong-version": "Ten email jest dla wersji {version}. Wybierz prawidłową wersję.",
        "login.redirecting-student": "🐆 Witaj! Przekierowanie do panelu ucznia...",
        "login.redirecting-teacher": "👨‍🏫 Witaj! Przekierowanie do panelu nauczyciela...",
        "guest.accessing": "🌟 Dostęp jako gość...", "session.active-redirecting": "🐆 Wykryto aktywną sesję. Przekierowanie...",
        "placeholder.email": "twoj@email.com", "placeholder.password": "Twoje hasło",
    },
    "ro": {
        "nav.back": "← Înapoi", "ui.auto-detect": "Automat", "ui.select-language": "Selectează Limba",
        "auth.welcome": "Bine ai venit!", "auth.subtitle": "Continuă aventura cu Yaguará prin ecosistemele colombiene",
        "ui.lang-detected": "🌍 Limba detectată automat", "ui.lang-suggestion": "💡 Preferi să continui în limba ta maternă?",
        "version.title": "🎯 Alege calea de învățare cu Yaguará",
        "version.individual-title": "Călătorie Individuală", "version.individual-desc": "Aventură personală cu Yaguará prin Columbia",
        "version.classroom-title": "Ediția Clasă", "version.classroom-desc": "Învățare structurată pentru educatori",
        "registration.pref-title": "📚 Selectează limba preferată de învățare",
        "demo.title": "🎯 Acces Demo", "form.email": "Email", "form.password": "Parolă",
        "demo.guest-option": "Sau explorează ca oaspete fără înregistrare",
        "form.email-label": "📧 Adresa de Email", "form.password-label": "🔒 Parolă",
        "auth.forgot-password": "Ai uitat parola?", "auth.login-button": "Începe Aventura",
        "ui.or": "sau", "auth.guest-access": "Acces Oaspete",
        "auth.signup-prompt": "Nu ai cont?", "auth.signup-link": "Înregistrează-te",
        "notify.version-selected": "Versiune Selectată", "notify.version-configured": "configurată",
        "notify.credentials-loaded": "Credențiale Încărcate", "notify.credentials-filled": "Date demo completate",
        "error.fill-all-fields": "Completează toate câmpurile.", "error.invalid-credentials": "Credențiale invalide pentru versiunea selectată.",
        "error.wrong-version": "Acest email este pentru versiunea {version}. Selectează versiunea corectă.",
        "login.redirecting-student": "🐆 Bine ai venit! Redirecționare către panoul elevului...",
        "login.redirecting-teacher": "👨‍🏫 Bine ai venit! Redirecționare către panoul profesorului...",
        "guest.accessing": "🌟 Accesare ca oaspete...", "session.active-redirecting": "🐆 Sesiune activă detectată. Redirecționare...",
        "placeholder.email": "email@tau.ro", "placeholder.password": "Parola ta",
    },
    "cs": {
        "nav.back": "← Zpět", "ui.auto-detect": "Automaticky", "ui.select-language": "Vybrat jazyk",
        "auth.welcome": "Vítejte!", "auth.subtitle": "Pokračujte v dobrodružství s Yaguará kolumbijskými ekosystémy",
        "ui.lang-detected": "🌍 Jazyk detekován automaticky", "ui.lang-suggestion": "💡 Chcete pokračovat ve svém jazyce?",
        "version.title": "🎯 Vyberte si cestu učení s Yaguará",
        "version.individual-title": "Individuální cesta", "version.individual-desc": "Osobní dobrodružství s Yaguará po Kolumbii",
        "version.classroom-title": "Třídní edice", "version.classroom-desc": "Strukturované učení pro pedagogy",
        "registration.pref-title": "📚 Vyberte preferovaný jazyk učení",
        "demo.title": "🎯 Demo přístup", "form.email": "Email", "form.password": "Heslo",
        "demo.guest-option": "Nebo prozkoumejte jako host bez registrace",
        "form.email-label": "📧 E-mailová adresa", "form.password-label": "🔒 Heslo",
        "auth.forgot-password": "Zapomněli jste heslo?", "auth.login-button": "Začít dobrodružství",
        "ui.or": "nebo", "auth.guest-access": "Přístup hosta",
        "auth.signup-prompt": "Nemáte účet?", "auth.signup-link": "Zaregistrujte se",
        "notify.version-selected": "Verze vybrána", "notify.version-configured": "nakonfigurováno",
        "notify.credentials-loaded": "Údaje načteny", "notify.credentials-filled": "Demo data vyplněna",
        "error.fill-all-fields": "Vyplňte všechna pole.", "error.invalid-credentials": "Neplatné údaje pro vybranou verzi.",
        "error.wrong-version": "Tento email je pro verzi {version}. Vyberte správnou verzi.",
        "login.redirecting-student": "🐆 Vítejte! Přesměrování na panel studenta...",
        "login.redirecting-teacher": "👨‍🏫 Vítejte! Přesměrování na panel učitele...",
        "guest.accessing": "🌟 Přístup jako host...", "session.active-redirecting": "🐆 Aktivní relace detekována. Přesměrování...",
        "placeholder.email": "vas@email.cz", "placeholder.password": "Vaše heslo",
    },
    "hu": {
        "nav.back": "← Vissza", "ui.auto-detect": "Automatikus", "ui.select-language": "Nyelv kiválasztása",
        "auth.welcome": "Üdvözöljük!", "auth.subtitle": "Folytasd kalandodat Yaguarával a kolumbiai ökoszisztémákon át",
        "ui.lang-detected": "🌍 Nyelv automatikusan felismerve", "ui.lang-suggestion": "💡 Szeretnéd anyanyelveden folytatni?",
        "version.title": "🎯 Válaszd ki tanulási utadat Yaguarával",
        "version.individual-title": "Egyéni utazás", "version.individual-desc": "Személyes kaland Yaguarával Kolumbián át",
        "version.classroom-title": "Tantermi kiadás", "version.classroom-desc": "Strukturált tanulás oktatók számára",
        "registration.pref-title": "📚 Válaszd ki a tanulási nyelvet",
        "demo.title": "🎯 Demo hozzáférés", "form.email": "Email", "form.password": "Jelszó",
        "demo.guest-option": "Vagy fedezd fel vendégként regisztráció nélkül",
        "form.email-label": "📧 E-mail cím", "form.password-label": "🔒 Jelszó",
        "auth.forgot-password": "Elfelejtetted a jelszavad?", "auth.login-button": "Kaland indítása",
        "ui.or": "vagy", "auth.guest-access": "Vendég hozzáférés",
        "auth.signup-prompt": "Nincs fiókod?", "auth.signup-link": "Regisztrálj itt",
        "notify.version-selected": "Verzió kiválasztva", "notify.version-configured": "beállítva",
        "notify.credentials-loaded": "Adatok betöltve", "notify.credentials-filled": "Demo adatok kitöltve",
        "error.fill-all-fields": "Töltsd ki az összes mezőt.", "error.invalid-credentials": "Érvénytelen adatok a kiválasztott verzióhoz.",
        "error.wrong-version": "Ez az email a {version} verzióhoz tartozik. Válaszd ki a megfelelő verziót.",
        "login.redirecting-student": "🐆 Üdvözöljük! Átirányítás a tanulói panelre...",
        "login.redirecting-teacher": "👨‍🏫 Üdvözöljük! Átirányítás a tanári panelre...",
        "guest.accessing": "🌟 Hozzáférés vendégként...", "session.active-redirecting": "🐆 Aktív munkamenet észlelve. Átirányítás...",
        "placeholder.email": "email@cimed.hu", "placeholder.password": "Jelszavad",
    },
    "sv": {
        "nav.back": "← Tillbaka", "ui.auto-detect": "Automatisk", "ui.select-language": "Välj språk",
        "auth.welcome": "Välkommen!", "auth.subtitle": "Fortsätt ditt äventyr med Yaguará genom Colombias ekosystem",
        "ui.lang-detected": "🌍 Språk upptäckt automatiskt", "ui.lang-suggestion": "💡 Vill du fortsätta på ditt modersmål?",
        "version.title": "🎯 Välj din lärstig med Yaguará",
        "version.individual-title": "Individuell resa", "version.individual-desc": "Personligt äventyr med Yaguará genom Colombia",
        "version.classroom-title": "Klassrumsutgåva", "version.classroom-desc": "Strukturerat lärande för pedagoger",
        "registration.pref-title": "📚 Välj ditt föredragna lärandespråk",
        "demo.title": "🎯 Demoåtkomst", "form.email": "E-post", "form.password": "Lösenord",
        "demo.guest-option": "Eller utforska som gäst utan registrering",
        "form.email-label": "📧 E-postadress", "form.password-label": "🔒 Lösenord",
        "auth.forgot-password": "Glömt lösenord?", "auth.login-button": "Starta äventyret",
        "ui.or": "eller", "auth.guest-access": "Gäståtkomst",
        "auth.signup-prompt": "Inget konto?", "auth.signup-link": "Registrera dig här",
        "notify.version-selected": "Version vald", "notify.version-configured": "konfigurerad",
        "notify.credentials-loaded": "Uppgifter laddade", "notify.credentials-filled": "Demodata ifylld",
        "error.fill-all-fields": "Fyll i alla fält.", "error.invalid-credentials": "Ogiltiga uppgifter för den valda versionen.",
        "error.wrong-version": "Denna e-post är för versionen {version}. Välj rätt version.",
        "login.redirecting-student": "🐆 Välkommen! Omdirigerar till studentpanelen...",
        "login.redirecting-teacher": "👨‍🏫 Välkommen! Omdirigerar till lärarpanelen...",
        "guest.accessing": "🌟 Åtkomst som gäst...", "session.active-redirecting": "🐆 Aktiv session upptäckt. Omdirigerar...",
        "placeholder.email": "din@email.se", "placeholder.password": "Ditt lösenord",
    },
    "no": {
        "nav.back": "← Tilbake", "ui.auto-detect": "Automatisk", "ui.select-language": "Velg språk",
        "auth.welcome": "Velkommen!", "auth.subtitle": "Fortsett eventyret med Yaguará gjennom Colombias økosystemer",
        "ui.lang-detected": "🌍 Språk oppdaget automatisk", "ui.lang-suggestion": "💡 Vil du fortsette på morsmålet ditt?",
        "version.title": "🎯 Velg din læringssti med Yaguará",
        "version.individual-title": "Individuell reise", "version.individual-desc": "Personlig eventyr med Yaguará gjennom Colombia",
        "version.classroom-title": "Klasseromsutgave", "version.classroom-desc": "Strukturert læring for pedagoger",
        "registration.pref-title": "📚 Velg ditt foretrukne læringsspråk",
        "demo.title": "🎯 Demotilgang", "form.email": "E-post", "form.password": "Passord",
        "demo.guest-option": "Eller utforsk som gjest uten registrering",
        "form.email-label": "📧 E-postadresse", "form.password-label": "🔒 Passord",
        "auth.forgot-password": "Glemt passordet?", "auth.login-button": "Start eventyret",
        "ui.or": "eller", "auth.guest-access": "Gjestetilgang",
        "auth.signup-prompt": "Ingen konto?", "auth.signup-link": "Registrer deg her",
        "notify.version-selected": "Versjon valgt", "notify.version-configured": "konfigurert",
        "notify.credentials-loaded": "Påloggingsdetaljer lastet", "notify.credentials-filled": "Demodata fylt inn",
        "error.fill-all-fields": "Fyll inn alle feltene.", "error.invalid-credentials": "Ugyldige detaljer for valgt versjon.",
        "error.wrong-version": "Denne e-posten er for versjon {version}. Velg riktig versjon.",
        "login.redirecting-student": "🐆 Velkommen! Omdirigerer til studentpanelet...",
        "login.redirecting-teacher": "👨‍🏫 Velkommen! Omdirigerer til lærerpanelet...",
        "guest.accessing": "🌟 Tilgang som gjest...", "session.active-redirecting": "🐆 Aktiv økt oppdaget. Omdirigerer...",
        "placeholder.email": "din@epost.no", "placeholder.password": "Ditt passord",
    },
    "da": {
        "nav.back": "← Tilbage", "ui.auto-detect": "Automatisk", "ui.select-language": "Vælg sprog",
        "auth.welcome": "Velkommen!", "auth.subtitle": "Fortsæt dit eventyr med Yaguará gennem Colombias økosystemer",
        "ui.lang-detected": "🌍 Sprog registreret automatisk", "ui.lang-suggestion": "💡 Vil du fortsætte på dit modersmål?",
        "version.title": "🎯 Vælg din læringssti med Yaguará",
        "version.individual-title": "Individuel rejse", "version.individual-desc": "Personligt eventyr med Yaguará gennem Colombia",
        "version.classroom-title": "Klasseværelsesudgave", "version.classroom-desc": "Struktureret læring for undervisere",
        "registration.pref-title": "📚 Vælg dit foretrukne læringssprog",
        "demo.title": "🎯 Demoadgang", "form.email": "Email", "form.password": "Adgangskode",
        "demo.guest-option": "Eller udforsk som gæst uden registrering",
        "form.email-label": "📧 E-mailadresse", "form.password-label": "🔒 Adgangskode",
        "auth.forgot-password": "Glemt adgangskode?", "auth.login-button": "Start eventyret",
        "ui.or": "eller", "auth.guest-access": "Gæsteadgang",
        "auth.signup-prompt": "Ingen konto?", "auth.signup-link": "Tilmeld dig her",
        "notify.version-selected": "Version valgt", "notify.version-configured": "konfigureret",
        "notify.credentials-loaded": "Loginoplysninger indlæst", "notify.credentials-filled": "Demodata udfyldt",
        "error.fill-all-fields": "Udfyld alle felter.", "error.invalid-credentials": "Ugyldige oplysninger for den valgte version.",
        "error.wrong-version": "Denne email er til version {version}. Vælg den korrekte version.",
        "login.redirecting-student": "🐆 Velkommen! Omdirigerer til elevpanelet...",
        "login.redirecting-teacher": "👨‍🏫 Velkommen! Omdirigerer til lærerpanelet...",
        "guest.accessing": "🌟 Adgang som gæst...", "session.active-redirecting": "🐆 Aktiv session registreret. Omdirigerer...",
        "placeholder.email": "din@email.dk", "placeholder.password": "Din adgangskode",
    },
    "fi": {
        "nav.back": "← Takaisin", "ui.auto-detect": "Automaattinen", "ui.select-language": "Valitse kieli",
        "auth.welcome": "Tervetuloa!", "auth.subtitle": "Jatka seikkailuasi Yaguarán kanssa Kolumbian ekosysteemeissä",
        "ui.lang-detected": "🌍 Kieli tunnistettu automaattisesti", "ui.lang-suggestion": "💡 Haluaisitko jatkaa äidinkielelläsi?",
        "version.title": "🎯 Valitse oppimispolkusi Yaguarán kanssa",
        "version.individual-title": "Yksilöllinen matka", "version.individual-desc": "Henkilökohtainen seikkailu Yaguarán kanssa Kolumbiassa",
        "version.classroom-title": "Luokkahuone-editio", "version.classroom-desc": "Jäsennelty oppiminen opettajille",
        "registration.pref-title": "📚 Valitse haluamasi oppimiskieli",
        "demo.title": "🎯 Demokäyttö", "form.email": "Sähköposti", "form.password": "Salasana",
        "demo.guest-option": "Tai tutustu vieraana ilman rekisteröintiä",
        "form.email-label": "📧 Sähköpostiosoite", "form.password-label": "🔒 Salasana",
        "auth.forgot-password": "Unohditko salasanasi?", "auth.login-button": "Aloita seikkailu",
        "ui.or": "tai", "auth.guest-access": "Vieraskäyttö",
        "auth.signup-prompt": "Ei tiliä?", "auth.signup-link": "Rekisteröidy tästä",
        "notify.version-selected": "Versio valittu", "notify.version-configured": "määritetty",
        "notify.credentials-loaded": "Tiedot ladattu", "notify.credentials-filled": "Demotiedot täytetty",
        "error.fill-all-fields": "Täytä kaikki kentät.", "error.invalid-credentials": "Virheelliset tiedot valitulle versiolle.",
        "error.wrong-version": "Tämä sähköposti on versiolle {version}. Valitse oikea versio.",
        "login.redirecting-student": "🐆 Tervetuloa! Ohjataan opiskelijapaneeliin...",
        "login.redirecting-teacher": "👨‍🏫 Tervetuloa! Ohjataan opettajapaneeliin...",
        "guest.accessing": "🌟 Käyttö vieraana...", "session.active-redirecting": "🐆 Aktiivinen istunto havaittu. Ohjataan...",
        "placeholder.email": "sinun@email.fi", "placeholder.password": "Salasanasi",
    },
    "el": {
        "nav.back": "← Πίσω", "ui.auto-detect": "Αυτόματα", "ui.select-language": "Επιλογή γλώσσας",
        "auth.welcome": "Καλώς ήρθατε!", "auth.subtitle": "Συνεχίστε την περιπέτειά σας με τον Yaguará στα κολομβιανά οικοσυστήματα",
        "ui.lang-detected": "🌍 Η γλώσσα εντοπίστηκε αυτόματα", "ui.lang-suggestion": "💡 Θα προτιμούσατε να συνεχίσετε στη μητρική σας γλώσσα;",
        "version.title": "🎯 Επιλέξτε τη μαθησιακή σας διαδρομή με τον Yaguará",
        "version.individual-title": "Ατομικό ταξίδι", "version.individual-desc": "Προσωπική περιπέτεια με τον Yaguará στην Κολομβία",
        "version.classroom-title": "Έκδοση τάξης", "version.classroom-desc": "Δομημένη μάθηση για εκπαιδευτικούς",
        "registration.pref-title": "📚 Επιλέξτε τη γλώσσα μάθησης", "demo.title": "🎯 Πρόσβαση Demo",
        "form.email": "Email", "form.password": "Κωδικός",
        "demo.guest-option": "Ή εξερευνήστε ως επισκέπτης χωρίς εγγραφή",
        "form.email-label": "📧 Διεύθυνση Email", "form.password-label": "🔒 Κωδικός",
        "auth.forgot-password": "Ξεχάσατε τον κωδικό;", "auth.login-button": "Ξεκινήστε την περιπέτεια",
        "ui.or": "ή", "auth.guest-access": "Πρόσβαση επισκέπτη",
        "auth.signup-prompt": "Δεν έχετε λογαριασμό;", "auth.signup-link": "Εγγραφείτε εδώ",
        "notify.version-selected": "Έκδοση επιλέχθηκε", "notify.version-configured": "ρυθμισμένη",
        "notify.credentials-loaded": "Στοιχεία φορτώθηκαν", "notify.credentials-filled": "Δεδομένα demo συμπληρώθηκαν",
        "error.fill-all-fields": "Συμπληρώστε όλα τα πεδία.", "error.invalid-credentials": "Μη έγκυρα στοιχεία για την επιλεγμένη έκδοση.",
        "error.wrong-version": "Αυτό το email είναι για την έκδοση {version}. Επιλέξτε τη σωστή έκδοση.",
        "login.redirecting-student": "🐆 Καλώς ήρθατε! Ανακατεύθυνση στον πίνακα μαθητή...",
        "login.redirecting-teacher": "👨‍🏫 Καλώς ήρθατε! Ανακατεύθυνση στον πίνακα εκπαιδευτικού...",
        "guest.accessing": "🌟 Πρόσβαση ως επισκέπτης...", "session.active-redirecting": "🐆 Ανιχνεύτηκε ενεργή συνεδρία. Ανακατεύθυνση...",
        "placeholder.email": "email@sas.gr", "placeholder.password": "Ο κωδικός σας",
    },
    "bg": {
        "nav.back": "← Назад", "ui.auto-detect": "Автоматично", "ui.select-language": "Изберете език",
        "auth.welcome": "Добре дошли!", "auth.subtitle": "Продължете приключението си с Yaguará през колумбийските екосистеми",
        "ui.lang-detected": "🌍 Езикът е открит автоматично", "ui.lang-suggestion": "💡 Предпочитате ли да продължите на родния си език?",
        "version.title": "🎯 Изберете пътя си на обучение с Yaguará",
        "version.individual-title": "Индивидуално пътуване", "version.individual-desc": "Лично приключение с Yaguará из Колумбия",
        "version.classroom-title": "Издание за клас", "version.classroom-desc": "Структурирано обучение за преподаватели",
        "registration.pref-title": "📚 Изберете предпочитан език за учене", "demo.title": "🎯 Демо достъп",
        "form.email": "Имейл", "form.password": "Парола",
        "demo.guest-option": "Или разгледайте като гост без регистрация",
        "form.email-label": "📧 Имейл адрес", "form.password-label": "🔒 Парола",
        "auth.forgot-password": "Забравена парола?", "auth.login-button": "Започнете приключението",
        "ui.or": "или", "auth.guest-access": "Гост достъп",
        "auth.signup-prompt": "Нямате акаунт?", "auth.signup-link": "Регистрирайте се",
        "notify.version-selected": "Версията е избрана", "notify.version-configured": "конфигурирана",
        "notify.credentials-loaded": "Данните са заредени", "notify.credentials-filled": "Демо данни попълнени",
        "error.fill-all-fields": "Попълнете всички полета.", "error.invalid-credentials": "Невалидни данни за избраната версия.",
        "error.wrong-version": "Този имейл е за версията {version}. Изберете правилната версия.",
        "login.redirecting-student": "🐆 Добре дошли! Пренасочване към панела на ученика...",
        "login.redirecting-teacher": "👨‍🏫 Добре дошли! Пренасочване към панела на учителя...",
        "guest.accessing": "🌟 Достъп като гост...", "session.active-redirecting": "🐆 Открита е активна сесия. Пренасочване...",
        "placeholder.email": "vashiat@email.bg", "placeholder.password": "Вашата парола",
    },
    "hr": {
        "nav.back": "← Natrag", "ui.auto-detect": "Automatski", "ui.select-language": "Odaberite jezik",
        "auth.welcome": "Dobrodošli!", "auth.subtitle": "Nastavite avanturu s Yaguarom kroz kolumbijske ekosustave",
        "ui.lang-detected": "🌍 Jezik automatski otkriven", "ui.lang-suggestion": "💡 Želite li nastaviti na materinjem jeziku?",
        "version.title": "🎯 Odaberite put učenja s Yaguarom",
        "version.individual-title": "Individualno putovanje", "version.individual-desc": "Osobna avantura s Yaguarom kroz Kolumbiju",
        "version.classroom-title": "Izdanje za učionicu", "version.classroom-desc": "Strukturirano učenje za nastavnike",
        "registration.pref-title": "📚 Odaberite željeni jezik učenja", "demo.title": "🎯 Demo pristup",
        "form.email": "Email", "form.password": "Lozinka",
        "demo.guest-option": "Ili istražujte kao gost bez registracije",
        "form.email-label": "📧 Email adresa", "form.password-label": "🔒 Lozinka",
        "auth.forgot-password": "Zaboravili ste lozinku?", "auth.login-button": "Započnite avanturu",
        "ui.or": "ili", "auth.guest-access": "Pristup za goste",
        "auth.signup-prompt": "Nemate račun?", "auth.signup-link": "Registrirajte se",
        "notify.version-selected": "Verzija odabrana", "notify.version-configured": "konfigurirana",
        "notify.credentials-loaded": "Podaci učitani", "notify.credentials-filled": "Demo podaci ispunjeni",
        "error.fill-all-fields": "Ispunite sva polja.", "error.invalid-credentials": "Nevažeći podaci za odabranu verziju.",
        "error.wrong-version": "Ovaj email je za verziju {version}. Odaberite ispravnu verziju.",
        "login.redirecting-student": "🐆 Dobrodošli! Preusmjeravanje na panel učenika...",
        "login.redirecting-teacher": "👨‍🏫 Dobrodošli! Preusmjeravanje na panel nastavnika...",
        "guest.accessing": "🌟 Pristup kao gost...", "session.active-redirecting": "🐆 Otkrivena aktivna sesija. Preusmjeravanje...",
        "placeholder.email": "vas@email.hr", "placeholder.password": "Vaša lozinka",
    },
    "sr": {
        "nav.back": "← Назад", "ui.auto-detect": "Аутоматски", "ui.select-language": "Изаберите језик",
        "auth.welcome": "Добродошли!", "auth.subtitle": "Наставите авантуру са Yaguará кроз колумбијске екосистеме",
        "ui.lang-detected": "🌍 Језик аутоматски препознат", "ui.lang-suggestion": "💡 Желите ли да наставите на матерњем језику?",
        "version.title": "🎯 Изаберите пут учења са Yaguará",
        "version.individual-title": "Индивидуално путовање", "version.individual-desc": "Лична авантура са Yaguará кроз Колумбију",
        "version.classroom-title": "Издање за учионицу", "version.classroom-desc": "Структурирано учење за наставнике",
        "registration.pref-title": "📚 Изаберите жељени језик учења", "demo.title": "🎯 Демо приступ",
        "form.email": "Имејл", "form.password": "Лозинка",
        "demo.guest-option": "Или истражујте као гост без регистрације",
        "form.email-label": "📧 Имејл адреса", "form.password-label": "🔒 Лозинка",
        "auth.forgot-password": "Заборавили сте лозинку?", "auth.login-button": "Започните авантуру",
        "ui.or": "или", "auth.guest-access": "Приступ за госте",
        "auth.signup-prompt": "Немате налог?", "auth.signup-link": "Региструјте се",
        "notify.version-selected": "Верзија изабрана", "notify.version-configured": "конфигурисана",
        "notify.credentials-loaded": "Подаци учитани", "notify.credentials-filled": "Демо подаци попуњени",
        "error.fill-all-fields": "Попуните сва поља.", "error.invalid-credentials": "Неважећи подаци за изабрану верзију.",
        "error.wrong-version": "Овај имејл је за верзију {version}. Изаберите исправну верзију.",
        "login.redirecting-student": "🐆 Добродошли! Преусмеравање на панел ученика...",
        "login.redirecting-teacher": "👨‍🏫 Добродошли! Преусмеравање на панел наставника...",
        "guest.accessing": "🌟 Приступ као гост...", "session.active-redirecting": "🐆 Откривена активна сесија. Преусмеравање...",
        "placeholder.email": "vas@email.rs", "placeholder.password": "Ваша лозинка",
    },
    "sk": {
        "nav.back": "← Späť", "ui.auto-detect": "Automaticky", "ui.select-language": "Vyberte jazyk",
        "auth.welcome": "Vitajte!", "auth.subtitle": "Pokračujte v dobrodružstve s Yaguará kolumbijskými ekosystémami",
        "ui.lang-detected": "🌍 Jazyk rozpoznaný automaticky", "ui.lang-suggestion": "💡 Chcete pokračovať vo svojom jazyku?",
        "version.title": "🎯 Vyberte si cestu učenia s Yaguará",
        "version.individual-title": "Individuálna cesta", "version.individual-desc": "Osobné dobrodružstvo s Yaguará cez Kolumbiu",
        "version.classroom-title": "Edícia triedy", "version.classroom-desc": "Štruktúrované učenie pre pedagógov",
        "registration.pref-title": "📚 Vyberte si jazyk učenia", "demo.title": "🎯 Demo prístup",
        "form.email": "Email", "form.password": "Heslo",
        "demo.guest-option": "Alebo preskúmajte ako hosť bez registrácie",
        "form.email-label": "📧 E-mailová adresa", "form.password-label": "🔒 Heslo",
        "auth.forgot-password": "Zabudli ste heslo?", "auth.login-button": "Začať dobrodružstvo",
        "ui.or": "alebo", "auth.guest-access": "Prístup hosťa",
        "auth.signup-prompt": "Nemáte účet?", "auth.signup-link": "Zaregistrujte sa",
        "notify.version-selected": "Verzia vybraná", "notify.version-configured": "nakonfigurovaná",
        "notify.credentials-loaded": "Údaje načítané", "notify.credentials-filled": "Demo dáta vyplnené",
        "error.fill-all-fields": "Vyplňte všetky polia.", "error.invalid-credentials": "Neplatné údaje pre vybranú verziu.",
        "error.wrong-version": "Tento email je pre verziu {version}. Vyberte správnu verziu.",
        "login.redirecting-student": "🐆 Vitajte! Presmerovanie na panel študenta...",
        "login.redirecting-teacher": "👨‍🏫 Vitajte! Presmerovanie na panel učiteľa...",
        "guest.accessing": "🌟 Prístup ako hosť...", "session.active-redirecting": "🐆 Aktívna relácia zistená. Presmerovanie...",
        "placeholder.email": "vas@email.sk", "placeholder.password": "Vaše heslo",
    },
    "sl": {
        "nav.back": "← Nazaj", "ui.auto-detect": "Samodejno", "ui.select-language": "Izberi jezik",
        "auth.welcome": "Dobrodošli!", "auth.subtitle": "Nadaljujte pustolovščino z Yaguará skozi kolumbijske ekosisteme",
        "ui.lang-detected": "🌍 Jezik samodejno zaznan", "ui.lang-suggestion": "💡 Želite nadaljevati v maternem jeziku?",
        "version.title": "🎯 Izberite učno pot z Yaguará",
        "version.individual-title": "Individualno potovanje", "version.individual-desc": "Osebna pustolovščina z Yaguará skozi Kolumbijo",
        "version.classroom-title": "Razredna izdaja", "version.classroom-desc": "Strukturirano učenje za pedagoge",
        "registration.pref-title": "📚 Izberite želeni učni jezik", "demo.title": "🎯 Demo dostop",
        "form.email": "Email", "form.password": "Geslo",
        "demo.guest-option": "Ali raziščite kot gost brez registracije",
        "form.email-label": "📧 E-poštni naslov", "form.password-label": "🔒 Geslo",
        "auth.forgot-password": "Pozabljeno geslo?", "auth.login-button": "Začni pustolovščino",
        "ui.or": "ali", "auth.guest-access": "Dostop za goste",
        "auth.signup-prompt": "Nimate računa?", "auth.signup-link": "Registrirajte se",
        "notify.version-selected": "Različica izbrana", "notify.version-configured": "nastavljena",
        "notify.credentials-loaded": "Podatki naloženi", "notify.credentials-filled": "Demo podatki izpolnjeni",
        "error.fill-all-fields": "Izpolnite vsa polja.", "error.invalid-credentials": "Neveljavni podatki za izbrano različico.",
        "error.wrong-version": "Ta email je za različico {version}. Izberite pravilno različico.",
        "login.redirecting-student": "🐆 Dobrodošli! Preusmeritev na ploščo študenta...",
        "login.redirecting-teacher": "👨‍🏫 Dobrodošli! Preusmeritev na ploščo učitelja...",
        "guest.accessing": "🌟 Dostop kot gost...", "session.active-redirecting": "🐆 Zaznana aktivna seja. Preusmeritev...",
        "placeholder.email": "vas@email.si", "placeholder.password": "Vaše geslo",
    },
    "lt": {
        "nav.back": "← Atgal", "ui.auto-detect": "Automatiškai", "ui.select-language": "Pasirinkite kalbą",
        "auth.welcome": "Sveiki!", "auth.subtitle": "Tęskite nuotykį su Yaguará per Kolumbijos ekosistemas",
        "ui.lang-detected": "🌍 Kalba aptikta automatiškai", "ui.lang-suggestion": "💡 Norėtumėte tęsti gimtąja kalba?",
        "version.title": "🎯 Pasirinkite mokymosi kelią su Yaguará",
        "version.individual-title": "Individuali kelionė", "version.individual-desc": "Asmeninis nuotykis su Yaguará per Kolumbiją",
        "version.classroom-title": "Klasės leidimas", "version.classroom-desc": "Struktūrizuotas mokymasis pedagogams",
        "registration.pref-title": "📚 Pasirinkite mokymosi kalbą", "demo.title": "🎯 Demo prieiga",
        "form.email": "El. paštas", "form.password": "Slaptažodis",
        "demo.guest-option": "Arba tyrinėkite kaip svečias be registracijos",
        "form.email-label": "📧 El. pašto adresas", "form.password-label": "🔒 Slaptažodis",
        "auth.forgot-password": "Pamiršote slaptažodį?", "auth.login-button": "Pradėti nuotykį",
        "ui.or": "arba", "auth.guest-access": "Svečio prieiga",
        "auth.signup-prompt": "Neturite paskyros?", "auth.signup-link": "Registruokitės",
        "notify.version-selected": "Versija pasirinkta", "notify.version-configured": "sukonfigūruota",
        "notify.credentials-loaded": "Duomenys įkelti", "notify.credentials-filled": "Demo duomenys užpildyti",
        "error.fill-all-fields": "Užpildykite visus laukus.", "error.invalid-credentials": "Neteisingi duomenys pasirinktai versijai.",
        "error.wrong-version": "Šis el. paštas yra versijai {version}. Pasirinkite teisingą versiją.",
        "login.redirecting-student": "🐆 Sveiki! Nukreipimas į mokinio skydelį...",
        "login.redirecting-teacher": "👨‍🏫 Sveiki! Nukreipimas į mokytojo skydelį...",
        "guest.accessing": "🌟 Prieiga kaip svečiui...", "session.active-redirecting": "🐆 Aptikta aktyvi sesija. Nukreipimas...",
        "placeholder.email": "jusu@email.lt", "placeholder.password": "Jūsų slaptažodis",
    },
    "lv": {
        "nav.back": "← Atpakaļ", "ui.auto-detect": "Automātiski", "ui.select-language": "Izvēlieties valodu",
        "auth.welcome": "Laipni lūdzam!", "auth.subtitle": "Turpiniet piedzīvojumu ar Yaguará Kolumbijas ekosistēmās",
        "ui.lang-detected": "🌍 Valoda noteikta automātiski", "ui.lang-suggestion": "💡 Vai vēlaties turpināt dzimtajā valodā?",
        "version.title": "🎯 Izvēlieties mācību ceļu ar Yaguará",
        "version.individual-title": "Individuālais ceļojums", "version.individual-desc": "Personīgs piedzīvojums ar Yaguará pa Kolumbiju",
        "version.classroom-title": "Klases izdevums", "version.classroom-desc": "Strukturēta mācīšanās pedagogiem",
        "registration.pref-title": "📚 Izvēlieties mācību valodu", "demo.title": "🎯 Demo piekļuve",
        "form.email": "E-pasts", "form.password": "Parole",
        "demo.guest-option": "Vai izpētiet kā viesis bez reģistrācijas",
        "form.email-label": "📧 E-pasta adrese", "form.password-label": "🔒 Parole",
        "auth.forgot-password": "Aizmirsāt paroli?", "auth.login-button": "Sākt piedzīvojumu",
        "ui.or": "vai", "auth.guest-access": "Viesa piekļuve",
        "auth.signup-prompt": "Nav konta?", "auth.signup-link": "Reģistrējieties",
        "notify.version-selected": "Versija izvēlēta", "notify.version-configured": "konfigurēta",
        "notify.credentials-loaded": "Dati ielādēti", "notify.credentials-filled": "Demo dati aizpildīti",
        "error.fill-all-fields": "Aizpildiet visus laukus.", "error.invalid-credentials": "Nederīgi dati izvēlētajai versijai.",
        "error.wrong-version": "Šis e-pasts ir versijai {version}. Izvēlieties pareizo versiju.",
        "login.redirecting-student": "🐆 Laipni lūdzam! Novirzīšana uz skolēna paneli...",
        "login.redirecting-teacher": "👨‍🏫 Laipni lūdzam! Novirzīšana uz skolotāja paneli...",
        "guest.accessing": "🌟 Piekļuve kā viesim...", "session.active-redirecting": "🐆 Atrasta aktīva sesija. Novirzīšana...",
        "placeholder.email": "jusu@epasts.lv", "placeholder.password": "Jūsu parole",
    },
    "et": {
        "nav.back": "← Tagasi", "ui.auto-detect": "Automaatne", "ui.select-language": "Valige keel",
        "auth.welcome": "Tere tulemast!", "auth.subtitle": "Jätkake seiklust Yaguaráiga Colombia ökosüsteemides",
        "ui.lang-detected": "🌍 Keel tuvastatud automaatselt", "ui.lang-suggestion": "💡 Kas soovite jätkata emakeeles?",
        "version.title": "🎯 Valige õppetee Yaguaráiga",
        "version.individual-title": "Individuaalne teekond", "version.individual-desc": "Isiklik seiklus Yaguaráiga Colombias",
        "version.classroom-title": "Klassiruumi väljaanne", "version.classroom-desc": "Struktureeritud õpe pedagoogidele",
        "registration.pref-title": "📚 Valige eelistatud õppekeel", "demo.title": "🎯 Demo ligipääs",
        "form.email": "E-post", "form.password": "Parool",
        "demo.guest-option": "Või avastage külalisena ilma registreerimata",
        "form.email-label": "📧 E-posti aadress", "form.password-label": "🔒 Parool",
        "auth.forgot-password": "Unustasid parooli?", "auth.login-button": "Alusta seiklust",
        "ui.or": "või", "auth.guest-access": "Külalise ligipääs",
        "auth.signup-prompt": "Pole kontot?", "auth.signup-link": "Registreeru siin",
        "notify.version-selected": "Versioon valitud", "notify.version-configured": "seadistatud",
        "notify.credentials-loaded": "Andmed laaditud", "notify.credentials-filled": "Demo andmed täidetud",
        "error.fill-all-fields": "Täitke kõik väljad.", "error.invalid-credentials": "Kehtetud andmed valitud versiooni jaoks.",
        "error.wrong-version": "See e-post on versiooni {version} jaoks. Valige õige versioon.",
        "login.redirecting-student": "🐆 Tere tulemast! Suunamine õpilase paneelile...",
        "login.redirecting-teacher": "👨‍🏫 Tere tulemast! Suunamine õpetaja paneelile...",
        "guest.accessing": "🌟 Ligipääs külalisena...", "session.active-redirecting": "🐆 Tuvastatud aktiivne seanss. Suunamine...",
        "placeholder.email": "sinu@email.ee", "placeholder.password": "Sinu parool",
    },
    "ru": {
        "nav.back": "← Назад", "ui.auto-detect": "Авто", "ui.select-language": "Выберите язык",
        "auth.welcome": "Добро пожаловать!", "auth.subtitle": "Продолжайте приключение с Yaguará по экосистемам Колумбии",
        "ui.lang-detected": "🌍 Язык определён автоматически", "ui.lang-suggestion": "💡 Предпочитаете продолжить на родном языке?",
        "version.title": "🎯 Выберите путь обучения с Yaguará",
        "version.individual-title": "Индивидуальное путешествие", "version.individual-desc": "Личное приключение с Yaguará по Колумбии",
        "version.classroom-title": "Классная версия", "version.classroom-desc": "Структурированное обучение для преподавателей",
        "registration.pref-title": "📚 Выберите язык обучения", "demo.title": "🎯 Демо доступ",
        "form.email": "Эл. почта", "form.password": "Пароль",
        "demo.guest-option": "Или исследуйте как гость без регистрации",
        "form.email-label": "📧 Адрес эл. почты", "form.password-label": "🔒 Пароль",
        "auth.forgot-password": "Забыли пароль?", "auth.login-button": "Начать приключение",
        "ui.or": "или", "auth.guest-access": "Гостевой доступ",
        "auth.signup-prompt": "Нет аккаунта?", "auth.signup-link": "Зарегистрируйтесь",
        "notify.version-selected": "Версия выбрана", "notify.version-configured": "настроена",
        "notify.credentials-loaded": "Данные загружены", "notify.credentials-filled": "Демо данные заполнены",
        "error.fill-all-fields": "Заполните все поля.", "error.invalid-credentials": "Неверные данные для выбранной версии.",
        "error.wrong-version": "Этот email для версии {version}. Выберите правильную версию.",
        "login.redirecting-student": "🐆 Добро пожаловать! Перенаправление на панель ученика...",
        "login.redirecting-teacher": "👨‍🏫 Добро пожаловать! Перенаправление на панель преподавателя...",
        "guest.accessing": "🌟 Вход как гость...", "session.active-redirecting": "🐆 Обнаружена активная сессия. Перенаправление...",
        "placeholder.email": "vash@email.ru", "placeholder.password": "Ваш пароль",
    },
    "tr": {
        "nav.back": "← Geri", "ui.auto-detect": "Otomatik", "ui.select-language": "Dil Seçin",
        "auth.welcome": "Hoş geldiniz!", "auth.subtitle": "Yaguará ile Kolombiya ekosistemlerindeki maceranıza devam edin",
        "ui.lang-detected": "🌍 Dil otomatik algılandı", "ui.lang-suggestion": "💡 Ana dilinizde devam etmek ister misiniz?",
        "version.title": "🎯 Yaguará ile öğrenme yolunuzu seçin",
        "version.individual-title": "Bireysel Yolculuk", "version.individual-desc": "Yaguará ile Kolombiya'da kişisel macera",
        "version.classroom-title": "Sınıf Sürümü", "version.classroom-desc": "Eğitimciler için yapılandırılmış öğrenme",
        "registration.pref-title": "📚 Tercih ettiğiniz öğrenme dilini seçin", "demo.title": "🎯 Demo Erişim",
        "form.email": "E-posta", "form.password": "Şifre",
        "demo.guest-option": "Veya kayıt olmadan misafir olarak keşfedin",
        "form.email-label": "📧 E-posta Adresi", "form.password-label": "🔒 Şifre",
        "auth.forgot-password": "Şifrenizi unuttunuz mu?", "auth.login-button": "Maceraya Başla",
        "ui.or": "veya", "auth.guest-access": "Misafir Erişimi",
        "auth.signup-prompt": "Hesabınız yok mu?", "auth.signup-link": "Kaydolun",
        "notify.version-selected": "Sürüm Seçildi", "notify.version-configured": "yapılandırıldı",
        "notify.credentials-loaded": "Bilgiler Yüklendi", "notify.credentials-filled": "Demo verileri dolduruldu",
        "error.fill-all-fields": "Tüm alanları doldurun.", "error.invalid-credentials": "Seçilen sürüm için geçersiz bilgiler.",
        "error.wrong-version": "Bu e-posta {version} sürümü içindir. Doğru sürümü seçin.",
        "login.redirecting-student": "🐆 Hoş geldiniz! Öğrenci paneline yönlendiriliyor...",
        "login.redirecting-teacher": "👨‍🏫 Hoş geldiniz! Öğretmen paneline yönlendiriliyor...",
        "guest.accessing": "🌟 Misafir olarak erişim...", "session.active-redirecting": "🐆 Aktif oturum algılandı. Yönlendiriliyor...",
        "placeholder.email": "email@adresiniz.com", "placeholder.password": "Şifreniz",
    },
    "af": {
        "nav.back": "← Terug", "ui.auto-detect": "Outomaties", "ui.select-language": "Kies Taal",
        "auth.welcome": "Welkom!", "auth.subtitle": "Gaan voort met jou avontuur met Yaguará deur die Colombiaanse ekosisteme",
        "ui.lang-detected": "🌍 Taal outomaties opgespoor", "ui.lang-suggestion": "💡 Wil jy in jou moedertaal voortgaan?",
        "version.title": "🎯 Kies jou leerpad met Yaguará",
        "version.individual-title": "Individuele Reis", "version.individual-desc": "Persoonlike avontuur met Yaguará deur Colombië",
        "version.classroom-title": "Klaskamer Uitgawe", "version.classroom-desc": "Gestruktureerde leer vir opvoeders",
        "registration.pref-title": "📚 Kies jou voorkeur leertaal", "demo.title": "🎯 Demo Toegang",
        "form.email": "E-pos", "form.password": "Wagwoord",
        "demo.guest-option": "Of verken as gas sonder registrasie",
        "form.email-label": "📧 E-posadres", "form.password-label": "🔒 Wagwoord",
        "auth.forgot-password": "Wagwoord vergeet?", "auth.login-button": "Begin Avontuur",
        "ui.or": "of", "auth.guest-access": "Gas Toegang",
        "auth.signup-prompt": "Geen rekening nie?", "auth.signup-link": "Registreer hier",
        "notify.version-selected": "Weergawe Gekies", "notify.version-configured": "gekonfigureer",
        "notify.credentials-loaded": "Besonderhede Gelaai", "notify.credentials-filled": "Demo data ingevul",
        "error.fill-all-fields": "Vul alle velde in.", "error.invalid-credentials": "Ongeldige besonderhede vir die gekose weergawe.",
        "error.wrong-version": "Hierdie e-pos is vir weergawe {version}. Kies die korrekte weergawe.",
        "login.redirecting-student": "🐆 Welkom! Herlei na studentepaneel...",
        "login.redirecting-teacher": "👨‍🏫 Welkom! Herlei na onderwyser paneel...",
        "guest.accessing": "🌟 Toegang as gas...", "session.active-redirecting": "🐆 Aktiewe sessie opgespoor. Herlei...",
        "placeholder.email": "jou@epos.co.za", "placeholder.password": "Jou wagwoord",
    },
    "uk": {
        "nav.back": "← Назад", "ui.auto-detect": "Автоматично", "ui.select-language": "Оберіть мову",
        "auth.welcome": "Ласкаво просимо!", "auth.subtitle": "Продовжуйте пригоду з Yaguará екосистемами Колумбії",
        "ui.lang-detected": "🌍 Мову визначено автоматично", "ui.lang-suggestion": "💡 Бажаєте продовжити рідною мовою?",
        "version.title": "🎯 Оберіть шлях навчання з Yaguará",
        "version.individual-title": "Індивідуальна подорож", "version.individual-desc": "Особиста пригода з Yaguará по Колумбії",
        "version.classroom-title": "Видання для класу", "version.classroom-desc": "Структуроване навчання для педагогів",
        "registration.pref-title": "📚 Оберіть мову навчання", "demo.title": "🎯 Демо доступ",
        "form.email": "Ел. пошта", "form.password": "Пароль",
        "demo.guest-option": "Або досліджуйте як гість без реєстрації",
        "form.email-label": "📧 Адреса ел. пошти", "form.password-label": "🔒 Пароль",
        "auth.forgot-password": "Забули пароль?", "auth.login-button": "Розпочати пригоду",
        "ui.or": "або", "auth.guest-access": "Гостьовий доступ",
        "auth.signup-prompt": "Немає облікового запису?", "auth.signup-link": "Зареєструйтесь",
        "notify.version-selected": "Версію обрано", "notify.version-configured": "налаштовано",
        "notify.credentials-loaded": "Дані завантажено", "notify.credentials-filled": "Демо дані заповнено",
        "error.fill-all-fields": "Заповніть усі поля.", "error.invalid-credentials": "Недійсні дані для обраної версії.",
        "error.wrong-version": "Ця ел. пошта для версії {version}. Оберіть правильну версію.",
        "login.redirecting-student": "🐆 Ласкаво просимо! Перенаправлення на панель учня...",
        "login.redirecting-teacher": "👨‍🏫 Ласкаво просимо! Перенаправлення на панель вчителя...",
        "guest.accessing": "🌟 Доступ як гість...", "session.active-redirecting": "🐆 Виявлено активну сесію. Перенаправлення...",
        "placeholder.email": "vasha@poshta.ua", "placeholder.password": "Ваш пароль",
    },
    "be": {
        "nav.back": "← Назад", "ui.auto-detect": "Аўтаматычна", "ui.select-language": "Абярыце мову",
        "auth.welcome": "Вітаем!", "auth.subtitle": "Працягвайце прыгоду з Yaguará праз экасістэмы Калумбіі",
        "ui.lang-detected": "🌍 Мова вызначана аўтаматычна", "ui.lang-suggestion": "💡 Хочаце працягнуць на роднай мове?",
        "version.title": "🎯 Абярыце шлях навучання з Yaguará",
        "version.individual-title": "Індывідуальнае падарожжа", "version.individual-desc": "Асабістая прыгода з Yaguará па Калумбіі",
        "version.classroom-title": "Выданне для класа", "version.classroom-desc": "Структураванае навучанне для педагогаў",
        "registration.pref-title": "📚 Абярыце мову навучання", "demo.title": "🎯 Дэма доступ",
        "form.email": "Эл. пошта", "form.password": "Пароль",
        "demo.guest-option": "Або даследуйце як госць без рэгістрацыі",
        "form.email-label": "📧 Адрас эл. пошты", "form.password-label": "🔒 Пароль",
        "auth.forgot-password": "Забылі пароль?", "auth.login-button": "Пачаць прыгоду",
        "ui.or": "або", "auth.guest-access": "Гасцявы доступ",
        "auth.signup-prompt": "Няма ўліковага запісу?", "auth.signup-link": "Зарэгіструйцеся",
        "notify.version-selected": "Версія абрана", "notify.version-configured": "наладжана",
        "notify.credentials-loaded": "Даныя загружаны", "notify.credentials-filled": "Дэма даныя запоўнены",
        "error.fill-all-fields": "Запоўніце ўсе палі.", "error.invalid-credentials": "Недапушчальныя даныя для абранай версіі.",
        "error.wrong-version": "Гэта эл. пошта для версіі {version}. Абярыце правільную версію.",
        "login.redirecting-student": "🐆 Вітаем! Перанакіраванне на панэль вучня...",
        "login.redirecting-teacher": "👨‍🏫 Вітаем! Перанакіраванне на панэль настаўніка...",
        "guest.accessing": "🌟 Доступ як госць...", "session.active-redirecting": "🐆 Выяўлена актыўная сесія. Перанакіраванне...",
        "placeholder.email": "vasha@poshta.by", "placeholder.password": "Ваш пароль",
    },
    "sq": {
        "nav.back": "← Kthehu", "ui.auto-detect": "Automatik", "ui.select-language": "Zgjidhni gjuhën",
        "auth.welcome": "Mirësevini!", "auth.subtitle": "Vazhdoni aventurën me Yaguará nëpër ekosistemet kolumbiane",
        "ui.lang-detected": "🌍 Gjuha u zbulua automatikisht", "ui.lang-suggestion": "💡 Dëshironi të vazhdoni në gjuhën tuaj amtare?",
        "version.title": "🎯 Zgjidhni rrugën e mësimit me Yaguará",
        "version.individual-title": "Udhëtimi Individual", "version.individual-desc": "Aventurë personale me Yaguará nëpër Kolumbi",
        "version.classroom-title": "Edicioni i Klasës", "version.classroom-desc": "Mësim i strukturuar për edukatorë",
        "registration.pref-title": "📚 Zgjidhni gjuhën e mësimit", "demo.title": "🎯 Qasje Demo",
        "form.email": "Email", "form.password": "Fjalëkalim",
        "demo.guest-option": "Ose eksploroni si mysafir pa regjistrim",
        "form.email-label": "📧 Adresa e Email", "form.password-label": "🔒 Fjalëkalim",
        "auth.forgot-password": "Keni harruar fjalëkalimin?", "auth.login-button": "Filloni aventurën",
        "ui.or": "ose", "auth.guest-access": "Qasje mysafir",
        "auth.signup-prompt": "Nuk keni llogari?", "auth.signup-link": "Regjistrohuni",
        "notify.version-selected": "Versioni u zgjodh", "notify.version-configured": "konfiguruar",
        "notify.credentials-loaded": "Kredencialet u ngarkuan", "notify.credentials-filled": "Të dhënat demo u plotësuan",
        "error.fill-all-fields": "Plotësoni të gjitha fushat.", "error.invalid-credentials": "Kredenciale të pavlefshme për versionin e zgjedhur.",
        "error.wrong-version": "Ky email është për versionin {version}. Zgjidhni versionin e saktë.",
        "login.redirecting-student": "🐆 Mirësevini! Ridrejtim drejt panelit të studentit...",
        "login.redirecting-teacher": "👨‍🏫 Mirësevini! Ridrejtim drejt panelit të mësuesit...",
        "guest.accessing": "🌟 Qasje si mysafir...", "session.active-redirecting": "🐆 U zbulua sesion aktiv. Ridrejtim...",
        "placeholder.email": "email@juaj.al", "placeholder.password": "Fjalëkalimi juaj",
    },
    "mk": {
        "nav.back": "← Назад", "ui.auto-detect": "Автоматски", "ui.select-language": "Изберете јазик",
        "auth.welcome": "Добредојдовте!", "auth.subtitle": "Продолжете ја авантурата со Yaguará низ колумбиските екосистеми",
        "ui.lang-detected": "🌍 Јазикот е откриен автоматски", "ui.lang-suggestion": "💡 Претпочитате да продолжите на мајчин јазик?",
        "version.title": "🎯 Изберете пат на учење со Yaguará",
        "version.individual-title": "Индивидуално патување", "version.individual-desc": "Лична авантура со Yaguará низ Колумбија",
        "version.classroom-title": "Издание за училница", "version.classroom-desc": "Структурирано учење за наставници",
        "registration.pref-title": "📚 Изберете јазик за учење", "demo.title": "🎯 Демо пристап",
        "form.email": "Е-пошта", "form.password": "Лозинка",
        "demo.guest-option": "Или истражувајте како гостин без регистрација",
        "form.email-label": "📧 Е-поштенска адреса", "form.password-label": "🔒 Лозинка",
        "auth.forgot-password": "Ја заборавивте лозинката?", "auth.login-button": "Започнете авантура",
        "ui.or": "или", "auth.guest-access": "Пристап за гости",
        "auth.signup-prompt": "Немате сметка?", "auth.signup-link": "Регистрирајте се",
        "notify.version-selected": "Верзијата е избрана", "notify.version-configured": "конфигурирана",
        "notify.credentials-loaded": "Податоците се вчитани", "notify.credentials-filled": "Демо податоци пополнети",
        "error.fill-all-fields": "Пополнете ги сите полиња.", "error.invalid-credentials": "Невалидни податоци за избраната верзија.",
        "error.wrong-version": "Оваа е-пошта е за верзијата {version}. Изберете ја правилната верзија.",
        "login.redirecting-student": "🐆 Добредојдовте! Пренасочување кон панелот на ученикот...",
        "login.redirecting-teacher": "👨‍🏫 Добредојдовте! Пренасочување кон панелот на наставникот...",
        "guest.accessing": "🌟 Пристап како гостин...", "session.active-redirecting": "🐆 Откриена е активна сесија. Пренасочување...",
        "placeholder.email": "vasa@eposta.mk", "placeholder.password": "Вашата лозинка",
    },
    "bs": {
        "nav.back": "← Nazad", "ui.auto-detect": "Automatski", "ui.select-language": "Odaberite jezik",
        "auth.welcome": "Dobrodošli!", "auth.subtitle": "Nastavite avanturu s Yaguarom kroz kolumbijske ekosisteme",
        "ui.lang-detected": "🌍 Jezik automatski prepoznat", "ui.lang-suggestion": "💡 Želite li nastaviti na maternjem jeziku?",
        "version.title": "🎯 Odaberite put učenja s Yaguarom",
        "version.individual-title": "Individualno putovanje", "version.individual-desc": "Lična avantura s Yaguarom kroz Kolumbiju",
        "version.classroom-title": "Izdanje za učionicu", "version.classroom-desc": "Strukturirano učenje za nastavnike",
        "registration.pref-title": "📚 Odaberite jezik učenja", "demo.title": "🎯 Demo pristup",
        "form.email": "Email", "form.password": "Lozinka",
        "demo.guest-option": "Ili istražujte kao gost bez registracije",
        "form.email-label": "📧 Email adresa", "form.password-label": "🔒 Lozinka",
        "auth.forgot-password": "Zaboravili ste lozinku?", "auth.login-button": "Započnite avanturu",
        "ui.or": "ili", "auth.guest-access": "Pristup za goste",
        "auth.signup-prompt": "Nemate račun?", "auth.signup-link": "Registrujte se",
        "notify.version-selected": "Verzija odabrana", "notify.version-configured": "konfigurirana",
        "notify.credentials-loaded": "Podaci učitani", "notify.credentials-filled": "Demo podaci popunjeni",
        "error.fill-all-fields": "Popunite sva polja.", "error.invalid-credentials": "Nevažeći podaci za odabranu verziju.",
        "error.wrong-version": "Ovaj email je za verziju {version}. Odaberite ispravnu verziju.",
        "login.redirecting-student": "🐆 Dobrodošli! Preusmjeravanje na panel učenika...",
        "login.redirecting-teacher": "👨‍🏫 Dobrodošli! Preusmjeravanje na panel nastavnika...",
        "guest.accessing": "🌟 Pristup kao gost...", "session.active-redirecting": "🐆 Otkrivena aktivna sesija. Preusmjeravanje...",
        "placeholder.email": "vas@email.ba", "placeholder.password": "Vaša lozinka",
    },
    "is": {
        "nav.back": "← Til baka", "ui.auto-detect": "Sjálfvirkt", "ui.select-language": "Veldu tungumál",
        "auth.welcome": "Velkomin!", "auth.subtitle": "Haltu áfram ævintýrinu með Yaguará um vistkerfi Kólumbíu",
        "ui.lang-detected": "🌍 Tungumál greindist sjálfvirkt", "ui.lang-suggestion": "💡 Viltu halda áfram á móðurmáli þínu?",
        "version.title": "🎯 Veldu námsleið þína með Yaguará",
        "version.individual-title": "Einstaklingsleiðangur", "version.individual-desc": "Persónulegt ævintýri með Yaguará um Kólumbíu",
        "version.classroom-title": "Kennslustofu útgáfa", "version.classroom-desc": "Skipulögð nám fyrir kennara",
        "registration.pref-title": "📚 Veldu námstungumál", "demo.title": "🎯 Kynningaraðgangur",
        "form.email": "Netfang", "form.password": "Lykilorð",
        "demo.guest-option": "Eða skoðaðu sem gestur án skráningar",
        "form.email-label": "📧 Netfang", "form.password-label": "🔒 Lykilorð",
        "auth.forgot-password": "Gleymdirðu lykilorðinu?", "auth.login-button": "Byrja ævintýri",
        "ui.or": "eða", "auth.guest-access": "Gestaaðgangur",
        "auth.signup-prompt": "Ekki með reikning?", "auth.signup-link": "Skráðu þig hér",
        "notify.version-selected": "Útgáfa valin", "notify.version-configured": "stillt",
        "notify.credentials-loaded": "Upplýsingar hlaðnar", "notify.credentials-filled": "Kynningargögn fyllt út",
        "error.fill-all-fields": "Fylltu út alla reiti.", "error.invalid-credentials": "Ógild upplýsingar fyrir valda útgáfu.",
        "error.wrong-version": "Þetta netfang er fyrir útgáfuna {version}. Veldu rétta útgáfu.",
        "login.redirecting-student": "🐆 Velkomin! Endurbeint á nemendaspjald...",
        "login.redirecting-teacher": "👨‍🏫 Velkomin! Endurbeint á kennaraspjald...",
        "guest.accessing": "🌟 Aðgangur sem gestur...", "session.active-redirecting": "🐆 Virk lota greindist. Endurbeint...",
        "placeholder.email": "thitt@netfang.is", "placeholder.password": "Lykilorðið þitt",
    },
    "ca": {
        "nav.back": "← Enrere", "ui.auto-detect": "Automàtic", "ui.select-language": "Selecciona idioma",
        "auth.welcome": "Benvingut!", "auth.subtitle": "Continua la teva aventura amb Yaguará pels ecosistemes colombians",
        "ui.lang-detected": "🌍 Idioma detectat automàticament", "ui.lang-suggestion": "💡 Prefereixes continuar en la teva llengua materna?",
        "version.title": "🎯 Tria el teu camí d'aprenentatge amb Yaguará",
        "version.individual-title": "Viatge Individual", "version.individual-desc": "Aventura personal amb Yaguará per Colòmbia",
        "version.classroom-title": "Edició d'Aula", "version.classroom-desc": "Aprenentatge estructurat per a educadors",
        "registration.pref-title": "📚 Selecciona l'idioma d'aprenentatge", "demo.title": "🎯 Accés Demo",
        "form.email": "Email", "form.password": "Contrasenya",
        "demo.guest-option": "O explora com a convidat sense registrar-te",
        "form.email-label": "📧 Adreça de correu", "form.password-label": "🔒 Contrasenya",
        "auth.forgot-password": "Has oblidat la contrasenya?", "auth.login-button": "Comença l'Aventura",
        "ui.or": "o", "auth.guest-access": "Accés Convidat",
        "auth.signup-prompt": "No tens compte?", "auth.signup-link": "Registra't aquí",
        "notify.version-selected": "Versió Seleccionada", "notify.version-configured": "configurada",
        "notify.credentials-loaded": "Credencials Carregades", "notify.credentials-filled": "Dades demo emplenades",
        "error.fill-all-fields": "Omple tots els camps.", "error.invalid-credentials": "Credencials no vàlides per a la versió seleccionada.",
        "error.wrong-version": "Aquest email és per a la versió {version}. Selecciona la versió correcta.",
        "login.redirecting-student": "🐆 Benvingut! Redirigint al panell d'estudiant...",
        "login.redirecting-teacher": "👨‍🏫 Benvingut! Redirigint al panell de professor...",
        "guest.accessing": "🌟 Accedint com a convidat...", "session.active-redirecting": "🐆 Sessió activa detectada. Redirigint...",
        "placeholder.email": "el.teu@email.cat", "placeholder.password": "La teva contrasenya",
    },
    "gl": {
        "nav.back": "← Volver", "ui.auto-detect": "Automático", "ui.select-language": "Seleccionar idioma",
        "auth.welcome": "Benvido!", "auth.subtitle": "Continúa a aventura con Yaguará polos ecosistemas colombianos",
        "ui.lang-detected": "🌍 Idioma detectado automaticamente", "ui.lang-suggestion": "💡 Prefires continuar na túa lingua?",
        "version.title": "🎯 Elixe o camiño de aprendizaxe con Yaguará",
        "version.individual-title": "Viaxe Individual", "version.individual-desc": "Aventura persoal con Yaguará por Colombia",
        "version.classroom-title": "Edición de Aula", "version.classroom-desc": "Aprendizaxe estruturada para educadores",
        "registration.pref-title": "📚 Selecciona o idioma de aprendizaxe", "demo.title": "🎯 Acceso Demo",
        "form.email": "Email", "form.password": "Contrasinal",
        "demo.guest-option": "Ou explora como convidado sen rexistrarte",
        "form.email-label": "📧 Enderezo de Email", "form.password-label": "🔒 Contrasinal",
        "auth.forgot-password": "Esqueciches o contrasinal?", "auth.login-button": "Comezar Aventura",
        "ui.or": "ou", "auth.guest-access": "Acceso Convidado",
        "auth.signup-prompt": "Non tes conta?", "auth.signup-link": "Rexístrate aquí",
        "notify.version-selected": "Versión Seleccionada", "notify.version-configured": "configurada",
        "notify.credentials-loaded": "Credenciais Cargadas", "notify.credentials-filled": "Datos demo enchidos",
        "error.fill-all-fields": "Enche todos os campos.", "error.invalid-credentials": "Credenciais non válidas para a versión seleccionada.",
        "error.wrong-version": "Este email é para a versión {version}. Selecciona a versión correcta.",
        "login.redirecting-student": "🐆 Benvido! Redirixindo ao panel de estudante...",
        "login.redirecting-teacher": "👨‍🏫 Benvido! Redirixindo ao panel de profesor...",
        "guest.accessing": "🌟 Accedendo como convidado...", "session.active-redirecting": "🐆 Sesión activa detectada. Redirixindo...",
        "placeholder.email": "o.teu@email.gal", "placeholder.password": "O teu contrasinal",
    },
    "eu": {
        "nav.back": "← Atzera", "ui.auto-detect": "Automatikoa", "ui.select-language": "Hizkuntza aukeratu",
        "auth.welcome": "Ongi etorri!", "auth.subtitle": "Jarraitu abentura Yaguarárekin Kolonbiako ekosistemen bidez",
        "ui.lang-detected": "🌍 Hizkuntza automatikoki detektatu da", "ui.lang-suggestion": "💡 Nahiago duzu ama-hizkuntzan jarraitzea?",
        "version.title": "🎯 Aukeratu ikaskuntza-bidea Yaguarárekin",
        "version.individual-title": "Banakako bidaia", "version.individual-desc": "Abentura pertsonala Yaguarárekin Kolonbian",
        "version.classroom-title": "Gela-edizioa", "version.classroom-desc": "Ikaskuntza egituratua hezitzaileentzat",
        "registration.pref-title": "📚 Aukeratu ikaskuntza-hizkuntza", "demo.title": "🎯 Demo sarbidea",
        "form.email": "Emaila", "form.password": "Pasahitza",
        "demo.guest-option": "Edo arakatu gonbidatu gisa erregistrorik gabe",
        "form.email-label": "📧 Email helbidea", "form.password-label": "🔒 Pasahitza",
        "auth.forgot-password": "Pasahitza ahaztu duzu?", "auth.login-button": "Hasi abentura",
        "ui.or": "edo", "auth.guest-access": "Gonbidatu sarbidea",
        "auth.signup-prompt": "Ez duzu konturik?", "auth.signup-link": "Erregistratu hemen",
        "notify.version-selected": "Bertsioa hautatua", "notify.version-configured": "konfiguratua",
        "notify.credentials-loaded": "Kredentzialak kargatuta", "notify.credentials-filled": "Demo datuak beteta",
        "error.fill-all-fields": "Bete eremu guztiak.", "error.invalid-credentials": "Kredentzial baliogabeak hautatutako bertsiorako.",
        "error.wrong-version": "Email hau {version} bertsiorako da. Aukeratu bertsio zuzena.",
        "login.redirecting-student": "🐆 Ongi etorri! Ikaslearen panelera birbideratzen...",
        "login.redirecting-teacher": "👨‍🏫 Ongi etorri! Irakaslearen panelera birbideratzen...",
        "guest.accessing": "🌟 Gonbidatu gisa sartzen...", "session.active-redirecting": "🐆 Saio aktiboa detektatu da. Birbideratzen...",
        "placeholder.email": "zure@emaila.eus", "placeholder.password": "Zure pasahitza",
    },
    "mt": {
        "nav.back": "← Lura", "ui.auto-detect": "Awtomatiku", "ui.select-language": "Agħżel Lingwa",
        "auth.welcome": "Merħba!", "auth.subtitle": "Kompli l-avventura ma' Yaguará fl-ekosistemi Kolumbjani",
        "ui.lang-detected": "🌍 Il-lingwa nstabet awtomatikament", "ui.lang-suggestion": "💡 Tippreferi tkompli fil-lingwa nattiva?",
        "version.title": "🎯 Agħżel il-mogħdija tat-tagħlim ma' Yaguará",
        "version.individual-title": "Vjaġġ Individwali", "version.individual-desc": "Avventura personali ma' Yaguará fil-Kolombja",
        "version.classroom-title": "Edizzjoni tal-Klassi", "version.classroom-desc": "Tagħlim strutturat għall-edukaturi",
        "registration.pref-title": "📚 Agħżel il-lingwa tat-tagħlim", "demo.title": "🎯 Aċċess Demo",
        "form.email": "Email", "form.password": "Password",
        "demo.guest-option": "Jew esplora bħala mistieden mingħajr reġistrazzjoni",
        "form.email-label": "📧 Indirizz Email", "form.password-label": "🔒 Password",
        "auth.forgot-password": "Insejt il-password?", "auth.login-button": "Ibda l-Avventura",
        "ui.or": "jew", "auth.guest-access": "Aċċess Mistieden",
        "auth.signup-prompt": "M'għandekx kont?", "auth.signup-link": "Irreġistra hawn",
        "notify.version-selected": "Verżjoni magħżula", "notify.version-configured": "kkonfigurata",
        "notify.credentials-loaded": "Kredenzjali mgħobbija", "notify.credentials-filled": "Data demo mimlija",
        "error.fill-all-fields": "Imla l-oqsma kollha.", "error.invalid-credentials": "Kredenzjali invalidi għall-verżjoni magħżula.",
        "error.wrong-version": "Dan l-email huwa għall-verżjoni {version}. Agħżel il-verżjoni korretta.",
        "login.redirecting-student": "🐆 Merħba! Ridirezzjonat lejn il-panel tal-istudent...",
        "login.redirecting-teacher": "👨‍🏫 Merħba! Ridirezzjonat lejn il-panel tal-għalliem...",
        "guest.accessing": "🌟 Dħul bħala mistieden...", "session.active-redirecting": "🐆 Sessjoni attiva misjuba. Ridirezzjonat...",
        "placeholder.email": "tieghek@email.mt", "placeholder.password": "Il-password tiegħek",
    },
    "cy": {
        "nav.back": "← Yn ôl", "ui.auto-detect": "Awtomatig", "ui.select-language": "Dewis Iaith",
        "auth.welcome": "Croeso!", "auth.subtitle": "Parhewch eich antur gyda Yaguará drwy ecosystemau Colombia",
        "ui.lang-detected": "🌍 Iaith wedi'i chanfod yn awtomatig", "ui.lang-suggestion": "💡 Hoffech chi barhau yn eich mamiaith?",
        "version.title": "🎯 Dewiswch eich llwybr dysgu gyda Yaguará",
        "version.individual-title": "Taith Unigol", "version.individual-desc": "Antur bersonol gyda Yaguará drwy Colombia",
        "version.classroom-title": "Argraffiad Dosbarth", "version.classroom-desc": "Dysgu strwythuredig ar gyfer addysgwyr",
        "registration.pref-title": "📚 Dewiswch eich iaith ddysgu", "demo.title": "🎯 Mynediad Demo",
        "form.email": "E-bost", "form.password": "Cyfrinair",
        "demo.guest-option": "Neu archwiliwch fel gwestai heb gofrestru",
        "form.email-label": "📧 Cyfeiriad E-bost", "form.password-label": "🔒 Cyfrinair",
        "auth.forgot-password": "Wedi anghofio'ch cyfrinair?", "auth.login-button": "Dechrau'r Antur",
        "ui.or": "neu", "auth.guest-access": "Mynediad Gwestai",
        "auth.signup-prompt": "Dim cyfrif?", "auth.signup-link": "Cofrestrwch yma",
        "notify.version-selected": "Fersiwn wedi'i dewis", "notify.version-configured": "wedi'i ffurfweddu",
        "notify.credentials-loaded": "Manylion wedi'u llwytho", "notify.credentials-filled": "Data demo wedi'i lenwi",
        "error.fill-all-fields": "Llenwch bob maes.", "error.invalid-credentials": "Manylion annilys ar gyfer y fersiwn.",
        "error.wrong-version": "Mae'r e-bost hwn ar gyfer fersiwn {version}. Dewiswch y fersiwn gywir.",
        "login.redirecting-student": "🐆 Croeso! Ailgyfeirio i'r panel myfyriwr...",
        "login.redirecting-teacher": "👨‍🏫 Croeso! Ailgyfeirio i'r panel athro...",
        "guest.accessing": "🌟 Mynediad fel gwestai...", "session.active-redirecting": "🐆 Sesiwn actif wedi'i ganfod. Ailgyfeirio...",
        "placeholder.email": "eich@ebost.cymru", "placeholder.password": "Eich cyfrinair",
    },
    "ga": {
        "nav.back": "← Ar ais", "ui.auto-detect": "Uathoibríoch", "ui.select-language": "Roghnaigh Teanga",
        "auth.welcome": "Fáilte!", "auth.subtitle": "Lean ar do eachtra le Yaguará trí éiceachórais na Colóime",
        "ui.lang-detected": "🌍 Teanga braithe go huathoibríoch", "ui.lang-suggestion": "💡 Ar mhaith leat leanúint i do theanga dhúchais?",
        "version.title": "🎯 Roghnaigh do chosán foghlama le Yaguará",
        "version.individual-title": "Turas Aonair", "version.individual-desc": "Eachtra phearsanta le Yaguará tríd an gColóim",
        "version.classroom-title": "Eagrán Seomra Ranga", "version.classroom-desc": "Foghlaim struchtúrtha d'oideachasóirí",
        "registration.pref-title": "📚 Roghnaigh teanga foghlama", "demo.title": "🎯 Rochtain Demo",
        "form.email": "Ríomhphost", "form.password": "Pasfhocal",
        "demo.guest-option": "Nó déan iniúchadh mar aoi gan clárú",
        "form.email-label": "📧 Seoladh Ríomhphoist", "form.password-label": "🔒 Pasfhocal",
        "auth.forgot-password": "Ar dhearmad tú do phasfhocal?", "auth.login-button": "Tosaigh an Eachtra",
        "ui.or": "nó", "auth.guest-access": "Rochtain Aoi",
        "auth.signup-prompt": "Gan cuntas?", "auth.signup-link": "Cláraigh anseo",
        "notify.version-selected": "Leagan roghnaithe", "notify.version-configured": "cumraithe",
        "notify.credentials-loaded": "Dintiúir luchtaithe", "notify.credentials-filled": "Sonraí demo líonta",
        "error.fill-all-fields": "Líon gach réimse.", "error.invalid-credentials": "Dintiúir neamhbhailí don leagan roghnaithe.",
        "error.wrong-version": "Is don leagan {version} an ríomhphost seo. Roghnaigh an leagan ceart.",
        "login.redirecting-student": "🐆 Fáilte! Ag atreorú chuig painéal an mhic léinn...",
        "login.redirecting-teacher": "👨‍🏫 Fáilte! Ag atreorú chuig painéal an mhúinteora...",
        "guest.accessing": "🌟 Ag rochtain mar aoi...", "session.active-redirecting": "🐆 Seisiún gníomhach braithe. Ag atreorú...",
        "placeholder.email": "do@rphost.ie", "placeholder.password": "Do phasfhocal",
    },
    "gd": {
        "nav.back": "← Air ais", "ui.auto-detect": "Fèin-ghluasadach", "ui.select-language": "Tagh Cànan",
        "auth.welcome": "Fàilte!", "auth.subtitle": "Lean air adhart le do thuras le Yaguará tro eco-shiostaman Choloimbia",
        "ui.lang-detected": "🌍 Cànan air a lorg gu fèin-ghluasadach", "ui.lang-suggestion": "💡 Am b' fheàrr leat leantainn ann an cànan do mhàthar?",
        "version.title": "🎯 Tagh do shlighe ionnsachaidh le Yaguará",
        "version.individual-title": "Turas Fa Leth", "version.individual-desc": "Turas pearsanta le Yaguará tro Choloimbia",
        "version.classroom-title": "Deasachadh Clas", "version.classroom-desc": "Ionnsachadh structarach airson tidsearan",
        "registration.pref-title": "📚 Tagh cànan ionnsachaidh", "demo.title": "🎯 Ruigsinneachd Demo",
        "form.email": "Post-d", "form.password": "Facal-faire",
        "demo.guest-option": "No rannsaich mar aoigh gun clàradh",
        "form.email-label": "📧 Seòladh Post-d", "form.password-label": "🔒 Facal-faire",
        "auth.forgot-password": "An do dhìochuimhnich thu d' fhacal-faire?", "auth.login-button": "Tòisich an Turas",
        "ui.or": "no", "auth.guest-access": "Ruigsinneachd Aoigh",
        "auth.signup-prompt": "Gun chunntas?", "auth.signup-link": "Clàraich an seo",
        "notify.version-selected": "Tionndadh air a thaghadh", "notify.version-configured": "air a rèiteachadh",
        "notify.credentials-loaded": "Teisteanasan air an luchdachadh", "notify.credentials-filled": "Dàta demo air a lìonadh",
        "error.fill-all-fields": "Lìon a-steach gach raon.", "error.invalid-credentials": "Teisteanasan mì-dhligheach airson an tionndaidh.",
        "error.wrong-version": "Tha am post-d seo airson tionndadh {version}. Tagh an tionndadh ceart.",
        "login.redirecting-student": "🐆 Fàilte! Ag ath-stiùireadh gu panail an oileanach...",
        "login.redirecting-teacher": "👨‍🏫 Fàilte! Ag ath-stiùireadh gu panail an tidseir...",
        "guest.accessing": "🌟 A' faighinn ruigsinneachd mar aoigh...", "session.active-redirecting": "🐆 Seisean gnìomhach air a lorg. Ag ath-stiùireadh...",
        "placeholder.email": "do@phost-d.co.uk", "placeholder.password": "D' fhacal-faire",
    },
    "lb": {
        "nav.back": "← Zréck", "ui.auto-detect": "Automatesch", "ui.select-language": "Sprooch wielen",
        "auth.welcome": "Wëllkomm!", "auth.subtitle": "Setzt Äert Abenteuer mat Yaguará duerch d'kolumbianesch Ökosystemer fort",
        "ui.lang-detected": "🌍 Sprooch automatesch erkannt", "ui.lang-suggestion": "💡 Wëllt Dir an Ärer Mammesprooch weiderfueren?",
        "version.title": "🎯 Wielt Äre Léierpad mat Yaguará",
        "version.individual-title": "Individuell Rees", "version.individual-desc": "Perséinlecht Abenteuer mat Yaguará duerch Kolumbien",
        "version.classroom-title": "Klassesall Editioun", "version.classroom-desc": "Strukturéiert Léieren fir Enseignanten",
        "registration.pref-title": "📚 Wielt Är Léiersprooch", "demo.title": "🎯 Demo Zougang",
        "form.email": "Email", "form.password": "Passwuert",
        "demo.guest-option": "Oder entdeckt als Gaascht ouni Registréierung",
        "form.email-label": "📧 Email Adress", "form.password-label": "🔒 Passwuert",
        "auth.forgot-password": "Passwuert vergiess?", "auth.login-button": "Abenteuer ufänken",
        "ui.or": "oder", "auth.guest-access": "Gaascht Zougang",
        "auth.signup-prompt": "Keen Kont?", "auth.signup-link": "Registréiert Iech hei",
        "notify.version-selected": "Versioun gewielt", "notify.version-configured": "konfiguréiert",
        "notify.credentials-loaded": "Daten gelueden", "notify.credentials-filled": "Demo Daten ausgefëllt",
        "error.fill-all-fields": "Fëllt all Felder aus.", "error.invalid-credentials": "Ongëlteg Daten fir déi gewielten Versioun.",
        "error.wrong-version": "Dës Email ass fir d'Versioun {version}. Wielt déi richteg Versioun.",
        "login.redirecting-student": "🐆 Wëllkomm! Ëmleitung op de Schüler Panel...",
        "login.redirecting-teacher": "👨‍🏫 Wëllkomm! Ëmleitung op den Enseignant Panel...",
        "guest.accessing": "🌟 Zougang als Gaascht...", "session.active-redirecting": "🐆 Aktiv Sessioun erkannt. Ëmleitung...",
        "placeholder.email": "aer@email.lu", "placeholder.password": "Äert Passwuert",
    },
}
