"""Login page translations — Middle East, Africa, Oceania, and other languages."""

TRANS_OTHER = {
    "ar": {
        "nav.back": "→ رجوع", "ui.auto-detect": "تلقائي", "ui.select-language": "اختر اللغة",
        "auth.welcome": "!مرحباً", "auth.subtitle": "واصل مغامرتك مع Yaguará عبر الأنظمة البيئية الكولومبية",
        "ui.lang-detected": "🌍 تم الكشف عن اللغة تلقائياً", "ui.lang-suggestion": "💡 هل تفضل المتابعة بلغتك الأم؟",
        "version.title": "🎯 اختر مسار تعلمك مع Yaguará", "version.individual-title": "رحلة فردية",
        "version.individual-desc": "مغامرة شخصية مع Yaguará عبر كولومبيا",
        "version.classroom-title": "نسخة الفصل الدراسي", "version.classroom-desc": "تعلم منظم للمعلمين",
        "registration.pref-title": "📚 اختر لغة التعلم المفضلة لديك", "demo.title": "🎯 وصول تجريبي",
        "form.email": "البريد الإلكتروني", "form.password": "كلمة المرور",
        "demo.guest-option": "أو استكشف كضيف بدون تسجيل",
        "form.email-label": "📧 عنوان البريد الإلكتروني", "form.password-label": "🔒 كلمة المرور",
        "auth.forgot-password": "نسيت كلمة المرور؟", "auth.login-button": "ابدأ المغامرة", "ui.or": "أو",
        "auth.guest-access": "دخول كضيف", "auth.signup-prompt": "ليس لديك حساب؟",
        "auth.signup-link": "سجل هنا", "notify.version-selected": "تم اختيار النسخة",
        "notify.version-configured": "تم الإعداد", "notify.credentials-loaded": "تم تحميل بيانات الاعتماد",
        "notify.credentials-filled": "تم ملء البيانات التجريبية", "error.fill-all-fields": "يرجى ملء جميع الحقول.",
        "error.invalid-credentials": "بيانات اعتماد غير صالحة للنسخة المحددة.",
        "error.wrong-version": "هذا البريد الإلكتروني للنسخة {version}. يرجى اختيار النسخة الصحيحة.",
        "login.redirecting-student": "🐆 مرحباً! جارٍ التوجيه إلى لوحة الطالب...",
        "login.redirecting-teacher": "👨‍🏫 مرحباً! جارٍ التوجيه إلى لوحة المعلم...",
        "guest.accessing": "🌟 جارٍ الدخول كضيف...",
        "session.active-redirecting": "🐆 تم اكتشاف جلسة نشطة. جارٍ التوجيه...",
        "placeholder.email": "your@email.com", "placeholder.password": "كلمة المرور",
    },
    "he": {
        "nav.back": "→ חזרה", "ui.auto-detect": "אוטומטי", "ui.select-language": "בחר שפה",
        "auth.welcome": "!ברוכים הבאים", "auth.subtitle": "המשיכו את ההרפתקה שלכם עם Yaguará דרך המערכות האקולוגיות של קולומביה",
        "ui.lang-detected": "🌍 השפה זוהתה אוטומטית", "ui.lang-suggestion": "💡 האם תרצו להמשיך בשפת האם שלכם?",
        "version.title": "🎯 בחרו את מסלול הלמידה שלכם עם Yaguará", "version.individual-title": "מסע אישי",
        "version.individual-desc": "הרפתקה אישית עם Yaguará דרך קולומביה",
        "version.classroom-title": "מהדורת כיתה", "version.classroom-desc": "למידה מובנית למחנכים",
        "registration.pref-title": "📚 בחרו את שפת הלמידה המועדפת", "demo.title": "🎯 גישת הדגמה",
        "form.email": "אימייל", "form.password": "סיסמה",
        "demo.guest-option": "או חקרו כאורח ללא הרשמה",
        "form.email-label": "📧 כתובת אימייל", "form.password-label": "🔒 סיסמה",
        "auth.forgot-password": "שכחת סיסמה?", "auth.login-button": "התחל הרפתקה", "ui.or": "או",
        "auth.guest-access": "כניסת אורח", "auth.signup-prompt": "אין לך חשבון?",
        "auth.signup-link": "הירשם כאן", "notify.version-selected": "הגרסה נבחרה",
        "notify.version-configured": "הוגדר", "notify.credentials-loaded": "פרטי ההתחברות נטענו",
        "notify.credentials-filled": "נתוני ההדגמה מולאו", "error.fill-all-fields": "אנא מלאו את כל השדות.",
        "error.invalid-credentials": "פרטי התחברות לא תקינים לגרסה שנבחרה.",
        "error.wrong-version": "אימייל זה שייך לגרסה {version}. אנא בחרו את הגרסה הנכונה.",
        "login.redirecting-student": "🐆 ברוכים הבאים! מפנה ללוח התלמיד...",
        "login.redirecting-teacher": "👨‍🏫 ברוכים הבאים! מפנה ללוח המורה...",
        "guest.accessing": "🌟 נכנס כאורח...",
        "session.active-redirecting": "🐆 זוהתה הפעלה פעילה. מפנה...",
        "placeholder.email": "your@email.com", "placeholder.password": "הסיסמה שלך",
    },
    "fa": {
        "nav.back": "→ بازگشت", "ui.auto-detect": "خودکار", "ui.select-language": "انتخاب زبان",
        "auth.welcome": "!خوش آمدید", "auth.subtitle": "ماجراجویی خود را با Yaguará در اکوسیستم‌های کلمبیا ادامه دهید",
        "ui.lang-detected": "🌍 زبان به صورت خودکار شناسایی شد", "ui.lang-suggestion": "💡 آیا ترجیح می‌دهید به زبان مادری خود ادامه دهید؟",
        "version.title": "🎯 مسیر یادگیری خود را با Yaguará انتخاب کنید", "version.individual-title": "سفر فردی",
        "version.individual-desc": "ماجراجویی شخصی با Yaguará در کلمبیا",
        "version.classroom-title": "نسخه کلاس درس", "version.classroom-desc": "یادگیری ساختارمند برای مربیان",
        "registration.pref-title": "📚 زبان یادگیری مورد علاقه خود را انتخاب کنید", "demo.title": "🎯 دسترسی آزمایشی",
        "form.email": "ایمیل", "form.password": "رمز عبور",
        "demo.guest-option": "یا بدون ثبت‌نام به عنوان مهمان کاوش کنید",
        "form.email-label": "📧 آدرس ایمیل", "form.password-label": "🔒 رمز عبور",
        "auth.forgot-password": "رمز عبور را فراموش کردید؟", "auth.login-button": "شروع ماجراجویی", "ui.or": "یا",
        "auth.guest-access": "دسترسی مهمان", "auth.signup-prompt": "حساب کاربری ندارید؟",
        "auth.signup-link": "اینجا ثبت‌نام کنید", "notify.version-selected": "نسخه انتخاب شد",
        "notify.version-configured": "پیکربندی شد", "notify.credentials-loaded": "اطلاعات ورود بارگذاری شد",
        "notify.credentials-filled": "داده‌های آزمایشی پر شد", "error.fill-all-fields": "لطفاً همه فیلدها را پر کنید.",
        "error.invalid-credentials": "اطلاعات ورود نامعتبر برای نسخه انتخاب شده.",
        "error.wrong-version": "این ایمیل برای نسخه {version} است. لطفاً نسخه صحیح را انتخاب کنید.",
        "login.redirecting-student": "🐆 خوش آمدید! در حال هدایت به پنل دانش‌آموز...",
        "login.redirecting-teacher": "👨‍🏫 خوش آمدید! در حال هدایت به پنل معلم...",
        "guest.accessing": "🌟 در حال ورود به عنوان مهمان...",
        "session.active-redirecting": "🐆 نشست فعال شناسایی شد. در حال هدایت...",
        "placeholder.email": "your@email.com", "placeholder.password": "رمز عبور شما",
    },
    "ps": {
        "nav.back": "→ شاته", "ui.auto-detect": "اتوماتیک", "ui.select-language": "ژبه وټاکئ",
        "auth.welcome": "!ښه راغلاست", "auth.subtitle": "د Yaguará سره د کولمبیا د چاپیریال سیسټمونو کې خپله ماجراجویي دوام ورکئ",
        "ui.lang-detected": "🌍 ژبه په اتوماتیک ډول وپیژندل شوه", "ui.lang-suggestion": "💡 ایا تاسو غواړئ خپله مورنۍ ژبه وکاروئ؟",
        "version.title": "🎯 د Yaguará سره خپل زده کړې لاره وټاکئ", "version.individual-title": "انفرادي سفر",
        "version.individual-desc": "د Yaguará سره د کولمبیا شخصي ماجراجویي",
        "version.classroom-title": "صنفي نسخه", "version.classroom-desc": "د ښوونکو لپاره جوړښتي زده کړه",
        "registration.pref-title": "📚 خپله غوره زده کړې ژبه وټاکئ", "demo.title": "🎯 ډیمو لاسرسی",
        "form.email": "بریښنالیک", "form.password": "پټنوم",
        "demo.guest-option": "یا د نوم لیکنې پرته د میلمه په توګه وګورئ",
        "form.email-label": "📧 د بریښنالیک پته", "form.password-label": "🔒 پټنوم",
        "auth.forgot-password": "پټنوم مو هیر شوی؟", "auth.login-button": "ماجراجویي پیل کړئ", "ui.or": "یا",
        "auth.guest-access": "د میلمه لاسرسی", "auth.signup-prompt": "حساب نلرئ؟",
        "auth.signup-link": "دلته نوم لیکنه وکړئ", "notify.version-selected": "نسخه وټاکل شوه",
        "notify.version-configured": "تنظیم شو", "notify.credentials-loaded": "اسناد پورته شول",
        "notify.credentials-filled": "ډیمو ډاټا ډکه شوه", "error.fill-all-fields": "مهرباني وکړئ ټول ساحې ډک کړئ.",
        "error.invalid-credentials": "د ټاکل شوې نسخې لپاره ناسم اسناد.",
        "error.wrong-version": "دا بریښنالیک د {version} نسخې لپاره دی. مهرباني وکړئ سمه نسخه وټاکئ.",
        "login.redirecting-student": "🐆 ښه راغلاست! د زده کوونکي پینل ته لیږدول کیږي...",
        "login.redirecting-teacher": "👨‍🏫 ښه راغلاست! د ښوونکي پینل ته لیږدول کیږي...",
        "guest.accessing": "🌟 د میلمه په توګه دننه کیدل...",
        "session.active-redirecting": "🐆 فعاله ناسته وموندل شوه. لیږدول کیږي...",
        "placeholder.email": "your@email.com", "placeholder.password": "ستاسو پټنوم",
    },
    "ku": {
        "nav.back": "← Veger", "ui.auto-detect": "Otomatîk", "ui.select-language": "Zimanê hilbijêre",
        "auth.welcome": "Bi xêr hatî!", "auth.subtitle": "Serpêhatiya xwe bi Yaguará re di ekosîstemên Kolombiyayê de bidomîne",
        "ui.lang-detected": "🌍 Ziman bi otomatîk hat nasîn", "ui.lang-suggestion": "💡 Tu dixwazî bi zimanê xwe yê dayikê bidomînî?",
        "version.title": "🎯 Riya xwe ya fêrbûnê bi Yaguará re hilbijêre", "version.individual-title": "Rêwîtiya takekesî",
        "version.individual-desc": "Serpêhatiya kesane bi Yaguará re li Kolombiyayê",
        "version.classroom-title": "Guhertoya polê", "version.classroom-desc": "Hînkirina birêkûpêk ji bo mamosteyan",
        "registration.pref-title": "📚 Zimanê fêrbûna bijare hilbijêre", "demo.title": "🎯 Gihîştina demo",
        "form.email": "E-peyam", "form.password": "Şîfre",
        "demo.guest-option": "An jî bêyî tomarkirin wekî mêvan bigere",
        "form.email-label": "📧 Navnîşana e-peyamê", "form.password-label": "🔒 Şîfre",
        "auth.forgot-password": "Şîfre ji bîr kir?", "auth.login-button": "Serpêhatiyê dest pê bike", "ui.or": "an",
        "auth.guest-access": "Gihîştina mêvan", "auth.signup-prompt": "Hesab tune?",
        "auth.signup-link": "Li vir tomar bibe", "notify.version-selected": "Guhertoyek hat hilbijartin",
        "notify.version-configured": "hate mîheng kirin", "notify.credentials-loaded": "Danasîn hatin barkirin",
        "notify.credentials-filled": "Daneyên demo hatin dagirtin", "error.fill-all-fields": "Ji kerema xwe hemû qadan dagire.",
        "error.invalid-credentials": "Ji bo guhertoya hilbijartî nasname nederbasdar.",
        "error.wrong-version": "Ev e-peyam ji bo guhertoya {version} e. Ji kerema xwe guhertoya rast hilbijêre.",
        "login.redirecting-student": "🐆 Bi xêr hatî! Berbi panêla xwendekar ve tê rêve kirin...",
        "login.redirecting-teacher": "👨‍🏫 Bi xêr hatî! Berbi panêla mamoste ve tê rêve kirin...",
        "guest.accessing": "🌟 Wekî mêvan tê ketin...",
        "session.active-redirecting": "🐆 Danişîna çalak hat dîtin. Tê rêve kirin...",
        "placeholder.email": "your@email.com", "placeholder.password": "Şîfreya te",
    },
    "sd": {
        "nav.back": "→ واپس", "ui.auto-detect": "خودڪار", "ui.select-language": "ٻولي چونڊيو",
        "auth.welcome": "!ڀلي ڪري آيا", "auth.subtitle": "Yaguará سان گڏ ڪولمبيا جي ماحولياتي نظام ۾ پنهنجو مهم جاري رکو",
        "ui.lang-detected": "🌍 ٻولي خودڪار طور تي سڃاتي وئي", "ui.lang-suggestion": "💡 ڇا توهان پنهنجي مادري ٻولي ۾ جاري رکڻ چاهيندا؟",
        "version.title": "🎯 Yaguará سان پنهنجو سکيا جو رستو چونڊيو", "version.individual-title": "انفرادي سفر",
        "version.individual-desc": "Yaguará سان ڪولمبيا ۾ ذاتي مهم",
        "version.classroom-title": "ڪلاس روم ايڊيشن", "version.classroom-desc": "استادن لاءِ منظم تعليم",
        "registration.pref-title": "📚 پنهنجي پسنديده سکيا جي ٻولي چونڊيو", "demo.title": "🎯 ڊيمو رسائي",
        "form.email": "اي ميل", "form.password": "پاسورڊ",
        "demo.guest-option": "يا بغير رجسٽريشن جي مهمان طور ڏسو",
        "form.email-label": "📧 اي ميل پتو", "form.password-label": "🔒 پاسورڊ",
        "auth.forgot-password": "پاسورڊ وساري ويا؟", "auth.login-button": "مهم شروع ڪريو", "ui.or": "يا",
        "auth.guest-access": "مهمان رسائي", "auth.signup-prompt": "اڪائونٽ ناهي؟",
        "auth.signup-link": "هتي سائن اپ ڪريو", "notify.version-selected": "ورزن چونڊيو ويو",
        "notify.version-configured": "ترتيب ڏنو ويو", "notify.credentials-loaded": "سندون لوڊ ٿيون",
        "notify.credentials-filled": "ڊيمو ڊيٽا ڀريو ويو", "error.fill-all-fields": "مهرباني ڪري سڀ فيلڊ ڀريو.",
        "error.invalid-credentials": "چونڊيل ورزن لاءِ غلط سندون.",
        "error.wrong-version": "هي اي ميل {version} ورزن لاءِ آهي. مهرباني ڪري صحيح ورزن چونڊيو.",
        "login.redirecting-student": "🐆 ڀلي ڪري آيا! شاگرد پينل ڏانهن موڪليو پيو وڃي...",
        "login.redirecting-teacher": "👨‍🏫 ڀلي ڪري آيا! استاد پينل ڏانهن موڪليو پيو وڃي...",
        "guest.accessing": "🌟 مهمان طور داخل ٿيندي...",
        "session.active-redirecting": "🐆 فعال سيشن مليو. موڪليو پيو وڃي...",
        "placeholder.email": "your@email.com", "placeholder.password": "توهان جو پاسورڊ",
    },
    "ug": {
        "nav.back": "→ قايتىش", "ui.auto-detect": "ئاپتوماتىك", "ui.select-language": "تىل تاللاڭ",
        "auth.welcome": "!خۇش كەلدىڭىز", "auth.subtitle": "Yaguará بىلەن كولومبىيە ئېكولوگىيىلىك سىستېمىسىدا ساياھىتىڭىزنى داۋاملاشتۇرۇڭ",
        "ui.lang-detected": "🌍 تىل ئاپتوماتىك بايقالدى", "ui.lang-suggestion": "💡 ئانا تىلىڭىزدا داۋاملاشتۇرماقچىمۇ؟",
        "version.title": "🎯 Yaguará بىلەن ئۆگىنىش يولىڭىزنى تاللاڭ", "version.individual-title": "شەخسىي ساياھەت",
        "version.individual-desc": "Yaguará بىلەن كولومبىيەدە شەخسىي ساياھەت",
        "version.classroom-title": "سىنىپ نەشرى", "version.classroom-desc": "ئوقۇتقۇچىلار ئۈچۈن قۇرۇلمىلىق ئۆگىنىش",
        "registration.pref-title": "📚 ياقتۇرىدىغان ئۆگىنىش تىلىنى تاللاڭ", "demo.title": "🎯 سىناق زىيارىتى",
        "form.email": "ئېلخەت", "form.password": "پارول",
        "demo.guest-option": "ياكى تىزىملاتماي مېھمان سۈپىتىدە كۆرۈڭ",
        "form.email-label": "📧 ئېلخەت ئادرېسى", "form.password-label": "🔒 پارول",
        "auth.forgot-password": "پارولنى ئۇنتۇدىڭىزمۇ؟", "auth.login-button": "ساياھەتنى باشلاش", "ui.or": "ياكى",
        "auth.guest-access": "مېھمان زىيارىتى", "auth.signup-prompt": "ھېسابىڭىز يوقمۇ؟",
        "auth.signup-link": "بۇ يەردە تىزىملىتىڭ", "notify.version-selected": "نەشرى تاللاندى",
        "notify.version-configured": "تەڭشەلدى", "notify.credentials-loaded": "كىرىش ئۇچۇرلىرى يۈكلەندى",
        "notify.credentials-filled": "سىناق سانلىق مەلۇماتلىرى تولدۇرۇلدى", "error.fill-all-fields": "بارلىق بوشلۇقلارنى تولدۇرۇڭ.",
        "error.invalid-credentials": "تاللانغان نەشرى ئۈچۈن ئىناۋەتسىز كىرىش ئۇچۇرلىرى.",
        "error.wrong-version": "بۇ ئېلخەت {version} نەشرى ئۈچۈن. توغرا نەشرىنى تاللاڭ.",
        "login.redirecting-student": "🐆 خۇش كەلدىڭىز! ئوقۇغۇچى تاختىسىغا يۆتكەلمەكتە...",
        "login.redirecting-teacher": "👨‍🏫 خۇش كەلدىڭىز! ئوقۇتقۇچى تاختىسىغا يۆتكەلمەكتە...",
        "guest.accessing": "🌟 مېھمان سۈپىتىدە كىرىۋاتىدۇ...",
        "session.active-redirecting": "🐆 ئاكتىپ ئۇلىنىش بايقالدى. يۆتكەلمەكتە...",
        "placeholder.email": "your@email.com", "placeholder.password": "پارولىڭىز",
    },
    "sw": {
        "nav.back": "← Rudi", "ui.auto-detect": "Otomatiki", "ui.select-language": "Chagua Lugha",
        "auth.welcome": "Karibu!", "auth.subtitle": "Endelea na safari yako na Yaguará kupitia mifumo ya ikolojia ya Kolombia",
        "ui.lang-detected": "🌍 Lugha imetambuliwa kiotomatiki", "ui.lang-suggestion": "💡 Je, ungependa kuendelea kwa lugha yako ya asili?",
        "version.title": "🎯 Chagua njia yako ya kujifunza na Yaguará", "version.individual-title": "Safari ya Kibinafsi",
        "version.individual-desc": "Safari ya kibinafsi na Yaguará kupitia Kolombia",
        "version.classroom-title": "Toleo la Darasa", "version.classroom-desc": "Kujifunza kwa mpangilio kwa waalimu",
        "registration.pref-title": "📚 Chagua lugha unayopendelea kujifunza", "demo.title": "🎯 Ufikiaji wa Demo",
        "form.email": "Barua pepe", "form.password": "Nenosiri",
        "demo.guest-option": "Au chunguza kama mgeni bila usajili",
        "form.email-label": "📧 Anwani ya Barua pepe", "form.password-label": "🔒 Nenosiri",
        "auth.forgot-password": "Umesahau nenosiri?", "auth.login-button": "Anza Safari", "ui.or": "au",
        "auth.guest-access": "Ufikiaji wa Mgeni", "auth.signup-prompt": "Huna akaunti?",
        "auth.signup-link": "Jisajili hapa", "notify.version-selected": "Toleo Limechaguliwa",
        "notify.version-configured": "limesanidiwa", "notify.credentials-loaded": "Vitambulisho Vimepakiwa",
        "notify.credentials-filled": "Data ya demo imejazwa", "error.fill-all-fields": "Tafadhali jaza sehemu zote.",
        "error.invalid-credentials": "Vitambulisho visivyo sahihi kwa toleo lililochaguliwa.",
        "error.wrong-version": "Barua pepe hii ni ya toleo la {version}. Tafadhali chagua toleo sahihi.",
        "login.redirecting-student": "🐆 Karibu! Inaelekeza kwenye paneli ya mwanafunzi...",
        "login.redirecting-teacher": "👨‍🏫 Karibu! Inaelekeza kwenye paneli ya mwalimu...",
        "guest.accessing": "🌟 Inafikiwa kama mgeni...",
        "session.active-redirecting": "🐆 Kipindi kinachotumika kimegunduliwa. Inaelekeza...",
        "placeholder.email": "your@email.com", "placeholder.password": "Nenosiri lako",
    },
    "am": {
        "nav.back": "← ተመለስ", "ui.auto-detect": "ራስ-ሰር", "ui.select-language": "ቋንቋ ይምረጡ",
        "auth.welcome": "እንኳን ደህና መጡ!", "auth.subtitle": "ከYaguará ጋር በኮሎምቢያ ሥነ-ምህዳሮች ውስጥ ጀብዱዎን ይቀጥሉ",
        "ui.lang-detected": "🌍 ቋንቋ በራስ-ሰር ተለይቷል", "ui.lang-suggestion": "💡 በእናት ቋንቋዎ መቀጠል ይፈልጋሉ?",
        "version.title": "🎯 ከYaguará ጋር የመማሪያ መንገድዎን ይምረጡ", "version.individual-title": "የግል ጉዞ",
        "version.individual-desc": "ከYaguará ጋር በኮሎምቢያ ውስጥ የግል ጀብዱ",
        "version.classroom-title": "የክፍል ዕትም", "version.classroom-desc": "ለአስተማሪዎች የተዋቀረ ትምህርት",
        "registration.pref-title": "📚 የሚመርጡትን የመማሪያ ቋንቋ ይምረጡ", "demo.title": "🎯 ማሳያ መዳረሻ",
        "form.email": "ኢሜይል", "form.password": "የይለፍ ቃል",
        "demo.guest-option": "ወይም ያለ ምዝገባ እንደ እንግዳ ያስሱ",
        "form.email-label": "📧 የኢሜይል አድራሻ", "form.password-label": "🔒 የይለፍ ቃል",
        "auth.forgot-password": "የይለፍ ቃል ረሱ?", "auth.login-button": "ጀብዱ ይጀምሩ", "ui.or": "ወይም",
        "auth.guest-access": "የእንግዳ መዳረሻ", "auth.signup-prompt": "መለያ የለዎትም?",
        "auth.signup-link": "እዚህ ይመዝገቡ", "notify.version-selected": "ዕትም ተመርጧል",
        "notify.version-configured": "ተዋቅሯል", "notify.credentials-loaded": "ማረጋገጫዎች ተጭነዋል",
        "notify.credentials-filled": "የማሳያ ውሂብ ተሞልቷል", "error.fill-all-fields": "እባክዎ ሁሉንም መስኮች ይሙሉ።",
        "error.invalid-credentials": "ለተመረጠው ዕትም ልክ ያልሆኑ ማረጋገጫዎች።",
        "error.wrong-version": "ይህ ኢሜይል ለ{version} ዕትም ነው። እባክዎ ትክክለኛውን ዕትም ይምረጡ።",
        "login.redirecting-student": "🐆 እንኳን ደህና መጡ! ወደ ተማሪ ፓነል እየተላከ ነው...",
        "login.redirecting-teacher": "👨‍🏫 እንኳን ደህና መጡ! ወደ አስተማሪ ፓነል እየተላከ ነው...",
        "guest.accessing": "🌟 እንደ እንግዳ እየገባ ነው...",
        "session.active-redirecting": "🐆 ንቁ ክፍለ-ጊዜ ተገኝቷል። እየተላከ ነው...",
        "placeholder.email": "your@email.com", "placeholder.password": "የይለፍ ቃልዎ",
    },
    "ha": {
        "nav.back": "← Komawa", "ui.auto-detect": "Atomatik", "ui.select-language": "Zaɓi Harshe",
        "auth.welcome": "Barka da zuwa!", "auth.subtitle": "Ci gaba da kasadarka tare da Yaguará ta cikin yanayin halittu na Colombia",
        "ui.lang-detected": "🌍 An gano harshe ta atomatik", "ui.lang-suggestion": "💡 Kuna son ci gaba da harshen uwa naku?",
        "version.title": "🎯 Zaɓi hanyar koyo tare da Yaguará", "version.individual-title": "Tafiya ta Kai",
        "version.individual-desc": "Kasadar kai tare da Yaguará ta cikin Colombia",
        "version.classroom-title": "Sigar Aji", "version.classroom-desc": "Koyon da aka tsara don malamai",
        "registration.pref-title": "📚 Zaɓi harshen koyo da kuka fi so", "demo.title": "🎯 Samun Gwaji",
        "form.email": "Imel", "form.password": "Kalmar sirri",
        "demo.guest-option": "Ko bincika a matsayin baƙo ba tare da rajista ba",
        "form.email-label": "📧 Adireshin Imel", "form.password-label": "🔒 Kalmar sirri",
        "auth.forgot-password": "An manta kalmar sirri?", "auth.login-button": "Fara Kasada", "ui.or": "ko",
        "auth.guest-access": "Samun Baƙo", "auth.signup-prompt": "Ba ku da asusu?",
        "auth.signup-link": "Yi rajista a nan", "notify.version-selected": "An Zaɓi Sigar",
        "notify.version-configured": "an saita", "notify.credentials-loaded": "An Ɗora Takardun Shiga",
        "notify.credentials-filled": "An cika bayanan gwaji", "error.fill-all-fields": "Da fatan za a cika duk wuraren.",
        "error.invalid-credentials": "Takardun shiga marasa inganci don sigar da aka zaɓa.",
        "error.wrong-version": "Wannan imel ɗin na sigar {version} ne. Da fatan za a zaɓi sigar da ta dace.",
        "login.redirecting-student": "🐆 Barka da zuwa! Ana tura zuwa ɗakin ɗalibi...",
        "login.redirecting-teacher": "👨‍🏫 Barka da zuwa! Ana tura zuwa ɗakin malami...",
        "guest.accessing": "🌟 Ana shiga a matsayin baƙo...",
        "session.active-redirecting": "🐆 An sami zama mai aiki. Ana tura...",
        "placeholder.email": "your@email.com", "placeholder.password": "Kalmar sirrin ku",
    },
    "yo": {
        "nav.back": "← Padà", "ui.auto-detect": "Aifọwọyi", "ui.select-language": "Yan Èdè",
        "auth.welcome": "Ẹ káàbọ̀!", "auth.subtitle": "Tẹ̀síwájú ìrìn-àjò rẹ pẹ̀lú Yaguará nípasẹ̀ àwọn ètò ẹ̀dá-alààyè Colombia",
        "ui.lang-detected": "🌍 A ti rí èdè láifọwọ́yí", "ui.lang-suggestion": "💡 Ṣé o fẹ́ tẹ̀síwájú ní èdè ìyá rẹ?",
        "version.title": "🎯 Yan ọ̀nà ẹ̀kọ́ rẹ pẹ̀lú Yaguará", "version.individual-title": "Ìrìn-àjò Àdáni",
        "version.individual-desc": "Ìrìn-àjò àdáni pẹ̀lú Yaguará nípasẹ̀ Colombia",
        "version.classroom-title": "Àtẹ̀jáde Kíláàsì", "version.classroom-desc": "Ẹ̀kọ́ tó ní ètò fún àwọn olùkọ́",
        "registration.pref-title": "📚 Yan èdè ẹ̀kọ́ tí o fẹ́ràn", "demo.title": "🎯 Àyẹwò Wọlé",
        "form.email": "Ímeèlì", "form.password": "Ọ̀rọ̀ aṣínà",
        "demo.guest-option": "Tàbí ṣàyẹ̀wò bíi àlejò láìsí ìforúkọsílẹ̀",
        "form.email-label": "📧 Àdírẹ́sì Ímeèlì", "form.password-label": "🔒 Ọ̀rọ̀ aṣínà",
        "auth.forgot-password": "Ọ̀rọ̀ aṣínà ti gbàgbé?", "auth.login-button": "Bẹ̀rẹ̀ Ìrìn-àjò", "ui.or": "tàbí",
        "auth.guest-access": "Àṣà Àlejò", "auth.signup-prompt": "Kò ní àkọọ́lẹ̀?",
        "auth.signup-link": "Forúkọ sílẹ̀ níbí", "notify.version-selected": "A Ti Yan Àtẹ̀jáde",
        "notify.version-configured": "ti ṣètò", "notify.credentials-loaded": "A Ti Kó Ìwé-ẹ̀rí Sínú",
        "notify.credentials-filled": "A ti kún data àyẹwò", "error.fill-all-fields": "Jọ̀wọ́ kún gbogbo àwọn àyè.",
        "error.invalid-credentials": "Ìwé-ẹ̀rí tí kò tọ́ fún àtẹ̀jáde tí a yan.",
        "error.wrong-version": "Ímeèlì yìí jẹ́ fún àtẹ̀jáde {version}. Jọ̀wọ́ yan àtẹ̀jáde tí ó tọ́.",
        "login.redirecting-student": "🐆 Ẹ káàbọ̀! A ń darí lọ sí pánẹ́ẹ̀lì akẹ́kọ̀ọ́...",
        "login.redirecting-teacher": "👨‍🏫 Ẹ káàbọ̀! A ń darí lọ sí pánẹ́ẹ̀lì olùkọ́...",
        "guest.accessing": "🌟 A ń wọlé bíi àlejò...",
        "session.active-redirecting": "🐆 A rí ìgbà tí ó ṣiṣẹ́. A ń darí...",
        "placeholder.email": "your@email.com", "placeholder.password": "Ọ̀rọ̀ aṣínà rẹ",
    },
    "ig": {
        "nav.back": "← Laghachi", "ui.auto-detect": "Akpaaka", "ui.select-language": "Họrọ Asụsụ",
        "auth.welcome": "Nnọọ!", "auth.subtitle": "Gaa n'ihu na njem gị na Yaguará site na usoro ihe ndị dị ndụ nke Colombia",
        "ui.lang-detected": "🌍 Achọpụtara asụsụ na akpaaka", "ui.lang-suggestion": "💡 Ị chọrọ ịga n'ihu n'asụsụ nne gị?",
        "version.title": "🎯 Họrọ ụzọ mmụta gị na Yaguará", "version.individual-title": "Njem Onwe",
        "version.individual-desc": "Njem nkeonwe na Yaguará site na Colombia",
        "version.classroom-title": "Ụdị Klaasị", "version.classroom-desc": "Mmụta e haziri maka ndị nkụzi",
        "registration.pref-title": "📚 Họrọ asụsụ mmụta ị masịrị", "demo.title": "🎯 Nbanye Demo",
        "form.email": "Email", "form.password": "Okwuntughe",
        "demo.guest-option": "Ma ọ bụ nyochaa dịka ọbịa na-enweghị ndebanye aha",
        "form.email-label": "📧 Adreesị Email", "form.password-label": "🔒 Okwuntughe",
        "auth.forgot-password": "Chefuru okwuntughe?", "auth.login-button": "Malite Njem", "ui.or": "ma ọ bụ",
        "auth.guest-access": "Nbanye Ọbịa", "auth.signup-prompt": "Enweghị akaụntụ?",
        "auth.signup-link": "Debanye aha ebe a", "notify.version-selected": "Ahọrọla Ụdị",
        "notify.version-configured": "edoziri", "notify.credentials-loaded": "Ebunyela Nzere",
        "notify.credentials-filled": "Ejupụtara data demo", "error.fill-all-fields": "Biko jupụta oghere niile.",
        "error.invalid-credentials": "Nzere na-ezighị ezi maka ụdị ahọrọla.",
        "error.wrong-version": "Email a bụ maka ụdị {version}. Biko họrọ ụdị ziri ezi.",
        "login.redirecting-student": "🐆 Nnọọ! Na-eduga na panel akwụkwọ...",
        "login.redirecting-teacher": "👨‍🏫 Nnọọ! Na-eduga na panel nkụzi...",
        "guest.accessing": "🌟 Na-abanye dịka ọbịa...",
        "session.active-redirecting": "🐆 Achọpụtara oge na-arụ ọrụ. Na-eduga...",
        "placeholder.email": "your@email.com", "placeholder.password": "Okwuntughe gị",
    },
    "zu": {
        "nav.back": "← Emuva", "ui.auto-detect": "Okuzenzakalelayo", "ui.select-language": "Khetha Ulimi",
        "auth.welcome": "Siyakwamukela!", "auth.subtitle": "Qhubeka nohambo lwakho noYaguará ezindaweni zemvelo zaseColombia",
        "ui.lang-detected": "🌍 Ulimi lutholwe ngokuzenzakalelayo", "ui.lang-suggestion": "💡 Ungathanda ukuqhubeka ngolimi lwakho lwebele?",
        "version.title": "🎯 Khetha indlela yakho yokufunda noYaguará", "version.individual-title": "Uhambo Lomuntu",
        "version.individual-desc": "Uhambo lomuntu noYaguará eColombia",
        "version.classroom-title": "Uhlobo Lweklasi", "version.classroom-desc": "Ukufunda okuhlelekile kothisha",
        "registration.pref-title": "📚 Khetha ulimi lwakho olufunayo lokufunda", "demo.title": "🎯 Ukufinyelela Kwesiboniso",
        "form.email": "I-imeyili", "form.password": "Iphasiwedi",
        "demo.guest-option": "Noma hlola njengesivakashi ngaphandle kokubhalisa",
        "form.email-label": "📧 Ikheli Le-imeyili", "form.password-label": "🔒 Iphasiwedi",
        "auth.forgot-password": "Ukhohlwe iphasiwedi?", "auth.login-button": "Qala Uhambo", "ui.or": "noma",
        "auth.guest-access": "Ukufinyelela Kwesivakashi", "auth.signup-prompt": "Awunayo i-akhawunti?",
        "auth.signup-link": "Bhalisa lapha", "notify.version-selected": "Uhlobo Lukhethiwe",
        "notify.version-configured": "kulungiselelwe", "notify.credentials-loaded": "Imininingwane Ilayishiwe",
        "notify.credentials-filled": "Idatha yesiboniso igcwalisiwe", "error.fill-all-fields": "Sicela ugcwalise zonke izindawo.",
        "error.invalid-credentials": "Imininingwane engavumelekile yohlobo olukhethiwe.",
        "error.wrong-version": "Le imeyili ingeyohlobo lwe-{version}. Sicela ukhethe uhlobo olufanele.",
        "login.redirecting-student": "🐆 Siyakwamukela! Kudluliselwa kuphaneli yomfundi...",
        "login.redirecting-teacher": "👨‍🏫 Siyakwamukela! Kudluliselwa kuphaneli kathisha...",
        "guest.accessing": "🌟 Kungenwa njengesivakashi...",
        "session.active-redirecting": "🐆 Kutholwe iseshini esebenzayo. Kudluliselwa...",
        "placeholder.email": "your@email.com", "placeholder.password": "Iphasiwedi yakho",
    },
    "xh": {
        "nav.back": "← Emva", "ui.auto-detect": "Ngokuzenzekelayo", "ui.select-language": "Khetha Ulwimi",
        "auth.welcome": "Wamkelekile!", "auth.subtitle": "Qhubeka nohambo lwakho noYaguará kwiindawo zemvelo zaseColombia",
        "ui.lang-detected": "🌍 Ulwimi lufunyenwe ngokuzenzekelayo", "ui.lang-suggestion": "💡 Ngaba ungathanda ukuqhubeka ngolwimi lwakho lwenkobe?",
        "version.title": "🎯 Khetha indlela yakho yokufunda noYaguará", "version.individual-title": "Uhambo Lomntu",
        "version.individual-desc": "Uhambo lomntu noYaguará eColombia",
        "version.classroom-title": "Uhlobo Lweklasi", "version.classroom-desc": "Ukufunda okucwangcisiweyo kootitshala",
        "registration.pref-title": "📚 Khetha ulwimi olufunayo lokufunda", "demo.title": "🎯 Ukufikelela Kwedemo",
        "form.email": "I-imeyile", "form.password": "Igama lokugqitha",
        "demo.guest-option": "Okanye phonononga njengondwendwe ngaphandle kokubhalisa",
        "form.email-label": "📧 Idilesi Ye-imeyile", "form.password-label": "🔒 Igama lokugqitha",
        "auth.forgot-password": "Ulibele igama lokugqitha?", "auth.login-button": "Qala Uhambo", "ui.or": "okanye",
        "auth.guest-access": "Ukufikelela Kondwendwe", "auth.signup-prompt": "Akunayo iakhawunti?",
        "auth.signup-link": "Bhalisa apha", "notify.version-selected": "Uhlobo Lukhethiwe",
        "notify.version-configured": "kulungisiwe", "notify.credentials-loaded": "Iziqinisekiso Zilayishiwe",
        "notify.credentials-filled": "Idatha yedemo igcwalisiwe", "error.fill-all-fields": "Nceda ugcwalise zonke iindawo.",
        "error.invalid-credentials": "Iziqinisekiso ezingasebenziyo zohlobo olukhethiweyo.",
        "error.wrong-version": "Le imeyile yeyohlobo lwe-{version}. Nceda ukhethe uhlobo olufanelekileyo.",
        "login.redirecting-student": "🐆 Wamkelekile! Kudluliselwa kwiphaneli yomfundi...",
        "login.redirecting-teacher": "👨‍🏫 Wamkelekile! Kudluliselwa kwiphaneli katitshala...",
        "guest.accessing": "🌟 Kungenwa njengondwendwe...",
        "session.active-redirecting": "🐆 Kufunyenwe iseshoni esebenzayo. Kudluliselwa...",
        "placeholder.email": "your@email.com", "placeholder.password": "Igama lakho lokugqitha",
    },
    "so": {
        "nav.back": "← Dib u noqo", "ui.auto-detect": "Otomaatig", "ui.select-language": "Dooro Luqadda",
        "auth.welcome": "Soo dhawoow!", "auth.subtitle": "Sii wad sheekadaada Yaguará oo ah nidaamyada deegaanka Colombia",
        "ui.lang-detected": "🌍 Luqadda waa la ogaadey si otomaatig ah", "ui.lang-suggestion": "💡 Ma rabtaa inaad ku sii waddo luqaddaada hooyo?",
        "version.title": "🎯 Dooro jidkaaga waxbarashada ee Yaguará", "version.individual-title": "Safar Shakhsi",
        "version.individual-desc": "Sheeko shakhsiyeed Yaguará oo ah Colombia",
        "version.classroom-title": "Nooca Fasalka", "version.classroom-desc": "Waxbarasho la habeeyey oo macallimiinta ah",
        "registration.pref-title": "📚 Dooro luqadda waxbarashada ee aad jeceshahay", "demo.title": "🎯 Gelitaan Demo",
        "form.email": "Email", "form.password": "Furaha sirta",
        "demo.guest-option": "Ama baadh sida marti ahaan la'aantii diiwaangelinta",
        "form.email-label": "📧 Cinwaanka Emailka", "form.password-label": "🔒 Furaha sirta",
        "auth.forgot-password": "Furaha sirta ma illowday?", "auth.login-button": "Bilow Sheekada", "ui.or": "ama",
        "auth.guest-access": "Gelitaan Marti", "auth.signup-prompt": "Akoon ma lihid?",
        "auth.signup-link": "Halkan iska diiwaan geli", "notify.version-selected": "Nooca Waa La Doortay",
        "notify.version-configured": "waa la habeeyey", "notify.credentials-loaded": "Aqoonsiga Waa La Soo Raray",
        "notify.credentials-filled": "Xogta demo waa la buuxiyey", "error.fill-all-fields": "Fadlan buuxi dhammaan meelaha.",
        "error.invalid-credentials": "Aqoonsi aan sax ahayn nooca la doortay.",
        "error.wrong-version": "Emailkan waa nooca {version}. Fadlan dooro nooca saxda ah.",
        "login.redirecting-student": "🐆 Soo dhawoow! Waa la u wareejinayaa bogga ardayga...",
        "login.redirecting-teacher": "👨‍🏫 Soo dhawoow! Waa la u wareejinayaa bogga macallinka...",
        "guest.accessing": "🌟 Waa la gelayaa sida marti...",
        "session.active-redirecting": "🐆 Waxaa la helay fadhiga firfircoon. Waa la u wareejinayaa...",
        "placeholder.email": "your@email.com", "placeholder.password": "Furaha sirtaada",
    },
    "rw": {
        "nav.back": "← Subira inyuma", "ui.auto-detect": "Bwikanyije", "ui.select-language": "Hitamo Ururimi",
        "auth.welcome": "Murakaza neza!", "auth.subtitle": "Komeza urugendo rwawe na Yaguará mu binyabuzima bya Colombia",
        "ui.lang-detected": "🌍 Ururimi rwagaragajwe bwikanyije", "ui.lang-suggestion": "💡 Urashaka gukomeza mu rurimi rwawe kavukire?",
        "version.title": "🎯 Hitamo inzira yawe yo kwiga na Yaguará", "version.individual-title": "Urugendo Bwite",
        "version.individual-desc": "Urugendo bwite na Yaguará muri Colombia",
        "version.classroom-title": "Ubwoko bw'Ishuri", "version.classroom-desc": "Kwiga gushyizweho ku barimu",
        "registration.pref-title": "📚 Hitamo ururimi rwo kwiga ukunda", "demo.title": "🎯 Kwinjira mu Demo",
        "form.email": "Imeli", "form.password": "Ijambo ry'ibanga",
        "demo.guest-option": "Cyangwa reba nk'umushyitsi utiyandikishije",
        "form.email-label": "📧 Aderesi ya Imeli", "form.password-label": "🔒 Ijambo ry'ibanga",
        "auth.forgot-password": "Wibagiwe ijambo ry'ibanga?", "auth.login-button": "Tangira Urugendo", "ui.or": "cyangwa",
        "auth.guest-access": "Kwinjira nk'Umushyitsi", "auth.signup-prompt": "Nta konti ufite?",
        "auth.signup-link": "Iyandikishe hano", "notify.version-selected": "Ubwoko Bwahisemo",
        "notify.version-configured": "byashyizweho", "notify.credentials-loaded": "Ibimenyetso Byashyizwemo",
        "notify.credentials-filled": "Amakuru ya demo yuzuzwa", "error.fill-all-fields": "Nyamuneka uzuze imyanya yose.",
        "error.invalid-credentials": "Ibimenyetso bitagira agaciro ku bwoko bwahisemo.",
        "error.wrong-version": "Iyi imeli ni iy'ubwoko bwa {version}. Nyamuneka hitamo ubwoko bukwiye.",
        "login.redirecting-student": "🐆 Murakaza neza! Birimo kohereza ku kibaho cy'umunyeshuri...",
        "login.redirecting-teacher": "👨‍🏫 Murakaza neza! Birimo kohereza ku kibaho cy'umwarimu...",
        "guest.accessing": "🌟 Birimo kwinjira nk'umushyitsi...",
        "session.active-redirecting": "🐆 Umukoro ukora waragaragaye. Birimo kohereza...",
        "placeholder.email": "your@email.com", "placeholder.password": "Ijambo ry'ibanga ryawe",
    },
    "sn": {
        "nav.back": "← Dzokera", "ui.auto-detect": "Otomatiki", "ui.select-language": "Sarudza Mutauro",
        "auth.welcome": "Titambire!", "auth.subtitle": "Enderera rwendo rwako naYaguará kuburikidza nharaunda dzeColombia",
        "ui.lang-detected": "🌍 Mutauro wawanikwa neotomatiki", "ui.lang-suggestion": "💡 Unoda here kuenderera nemutauro wako wekuberekwa?",
        "version.title": "🎯 Sarudza nzira yako yekudzidza naYaguará", "version.individual-title": "Rwendo Rwemunhu",
        "version.individual-desc": "Rwendo rwemunhu naYaguará kuburikidza neColombia",
        "version.classroom-title": "Rudzi rweKirasi", "version.classroom-desc": "Kudzidza kwakagadzirwa kwevadzidzisi",
        "registration.pref-title": "📚 Sarudza mutauro waunoda wekudzidza", "demo.title": "🎯 Kupinda Demo",
        "form.email": "Email", "form.password": "Shoko rekuvhara",
        "demo.guest-option": "Kana ongorora semuenzi pasina kunyoresa",
        "form.email-label": "📧 Kero yeEmail", "form.password-label": "🔒 Shoko rekuvhara",
        "auth.forgot-password": "Wakanganwa shoko rekuvhara?", "auth.login-button": "Tanga Rwendo", "ui.or": "kana",
        "auth.guest-access": "Kupinda kweMushanyi", "auth.signup-prompt": "Hauna akaundi?",
        "auth.signup-link": "Nyoresa pano", "notify.version-selected": "Rudzi Rwasarudzwa",
        "notify.version-configured": "rwakagadzirwa", "notify.credentials-loaded": "Zvitupa Zvakaiswa",
        "notify.credentials-filled": "Data yedemo yakazadzwa", "error.fill-all-fields": "Ndapota zadza nzvimbo dzose.",
        "error.invalid-credentials": "Zvitupa zvisiri izvo zverudzi rwakasarudzwa.",
        "error.wrong-version": "Iyi email ndeye rudzi rwe{version}. Ndapota sarudza rudzi rwakarurama.",
        "login.redirecting-student": "🐆 Titambire! Kuendesa kupaneli yemudzidzi...",
        "login.redirecting-teacher": "👨‍🏫 Titambire! Kuendesa kupaneli yemudzidzisi...",
        "guest.accessing": "🌟 Kupinda semuenzi...",
        "session.active-redirecting": "🐆 Chikamu chinoshanda chawanikwa. Kuendesa...",
        "placeholder.email": "your@email.com", "placeholder.password": "Shoko rako rekuvhara",
    },
    "st": {
        "nav.back": "← Morao", "ui.auto-detect": "Ka bo eona", "ui.select-language": "Khetha Puo",
        "auth.welcome": "Rea o amohela!", "auth.subtitle": "Tswela pele leeto la hao le Yaguará ka tikolohing tsa tlhaho tsa Colombia",
        "ui.lang-detected": "🌍 Puo e fumanwe ka bo eona", "ui.lang-suggestion": "💡 Na o rata ho tswela pele ka puo ya hao ya lapeng?",
        "version.title": "🎯 Khetha tsela ya hao ya ho ithuta le Yaguará", "version.individual-title": "Leeto la Motho",
        "version.individual-desc": "Leeto la motho le Yaguará ka Colombia",
        "version.classroom-title": "Mofuta oa Phaposi", "version.classroom-desc": "Ho ithuta ho hlophisitsoeng bakeng sa matichere",
        "registration.pref-title": "📚 Khetha puo eo o e ratang ya ho ithuta", "demo.title": "🎯 Phihlello ea Demo",
        "form.email": "Email", "form.password": "Lentsoe la lekunutu",
        "demo.guest-option": "Kapa sheba joaloka moeti ntle le ho ingodisa",
        "form.email-label": "📧 Aterese ea Email", "form.password-label": "🔒 Lentsoe la lekunutu",
        "auth.forgot-password": "O lebetse lentsoe la lekunutu?", "auth.login-button": "Qala Leeto", "ui.or": "kapa",
        "auth.guest-access": "Phihlello ea Moeti", "auth.signup-prompt": "Ha o na ak'haonte?",
        "auth.signup-link": "Ingodisa mona", "notify.version-selected": "Mofuta O Khethiloe",
        "notify.version-configured": "o hlophisitsoe", "notify.credentials-loaded": "Litshupo Li Kentse",
        "notify.credentials-filled": "Lintlha tsa demo li tlatsitsoe", "error.fill-all-fields": "Ka kopo tlatsa libaka tsohle.",
        "error.invalid-credentials": "Litshupo tse sa sebetseng bakeng sa mofuta o khethiloeng.",
        "error.wrong-version": "Email ena ke ea mofuta oa {version}. Ka kopo khetha mofuta o nepahetseng.",
        "login.redirecting-student": "🐆 Rea o amohela! Ho romelloa phaneleng ea moithuti...",
        "login.redirecting-teacher": "👨‍🏫 Rea o amohela! Ho romelloa phaneleng ea mosuoe...",
        "guest.accessing": "🌟 Ho kenngoa joaloka moeti...",
        "session.active-redirecting": "🐆 Ho fumanoe tšebetso e sebetsang. Ho romelloa...",
        "placeholder.email": "your@email.com", "placeholder.password": "Lentsoe la hao la lekunutu",
    },
    "tn": {
        "nav.back": "← Morago", "ui.auto-detect": "Ka bo yone", "ui.select-language": "Tlhopha Puo",
        "auth.welcome": "O amogelesegile!", "auth.subtitle": "Tswelela loeto lwa gago le Yaguará mo ditikologing tsa tlholego tsa Colombia",
        "ui.lang-detected": "🌍 Puo e bonwe ka bo yone", "ui.lang-suggestion": "💡 A o batla go tswelela ka puo ya gago ya ga mme?",
        "version.title": "🎯 Tlhopha tsela ya gago ya go ithuta le Yaguará", "version.individual-title": "Loeto lwa Motho",
        "version.individual-desc": "Loeto lwa motho le Yaguará ka Colombia",
        "version.classroom-title": "Mofuta wa Phaposi", "version.classroom-desc": "Go ithuta go go rulaganeng ga barutabana",
        "registration.pref-title": "📚 Tlhopha puo e o e ratang ya go ithuta", "demo.title": "🎯 Tseno ya Demo",
        "form.email": "Email", "form.password": "Lefoko la sephiri",
        "demo.guest-option": "Kgotsa batla jaaka moeng kwa ntle ga go ikwadisa",
        "form.email-label": "📧 Aterese ya Email", "form.password-label": "🔒 Lefoko la sephiri",
        "auth.forgot-password": "O lebetse lefoko la sephiri?", "auth.login-button": "Simolola Loeto", "ui.or": "kgotsa",
        "auth.guest-access": "Tseno ya Moeng", "auth.signup-prompt": "Ga o na akhaonto?",
        "auth.signup-link": "Ikwadise fano", "notify.version-selected": "Mofuta o Tlhophilwe",
        "notify.version-configured": "o rulaganyeditswe", "notify.credentials-loaded": "Ditlankana di Tsentse",
        "notify.credentials-filled": "Data ya demo e tladitswe", "error.fill-all-fields": "Tswee-tswee tlatsa mafelo otlhe.",
        "error.invalid-credentials": "Ditlankana tse di sa siamang tsa mofuta o o tlhophilweng.",
        "error.wrong-version": "Email e ke ya mofuta wa {version}. Tswee-tswee tlhopha mofuta o o siameng.",
        "login.redirecting-student": "🐆 O amogelesegile! Go romelwa go phanele ya moithuti...",
        "login.redirecting-teacher": "👨‍🏫 O amogelesegile! Go romelwa go phanele ya morutabana...",
        "guest.accessing": "🌟 Go tseniwa jaaka moeng...",
        "session.active-redirecting": "🐆 Go bonwe tiro e e dirang. Go romelwa...",
        "placeholder.email": "your@email.com", "placeholder.password": "Lefoko la gago la sephiri",
    },
    "wo": {
        "nav.back": "← Dellu", "ui.auto-detect": "Boppam", "ui.select-language": "Tann Làkk",
        "auth.welcome": "Dalal jàmm!", "auth.subtitle": "Yëngël sa awo ak Yaguará ci biir àdduna wu set wu Colombia",
        "ui.lang-detected": "🌍 Làkk bi da nees ko gis ci boppam", "ui.lang-suggestion": "💡 Ndax danga bëgg yëngël ci sa làkk yu yaay?",
        "version.title": "🎯 Tann sa yoon wu jàng ak Yaguará", "version.individual-title": "Awo bu Kenn",
        "version.individual-desc": "Awo bu boppam ak Yaguará ci biir Colombia",
        "version.classroom-title": "Mel mu Daara", "version.classroom-desc": "Jàng ju organise ji ñu jàngalekat yi",
        "registration.pref-title": "📚 Tann sa làkk bu bëgg jàng", "demo.title": "🎯 Dugg Demo",
        "form.email": "Email", "form.password": "Baatu sirr",
        "demo.guest-option": "Walla seetal ni njiit te binduwuloo",
        "form.email-label": "📧 Adres Email", "form.password-label": "🔒 Baatu sirr",
        "auth.forgot-password": "Fatte baatu sirr?", "auth.login-button": "Tambali Awo", "ui.or": "walla",
        "auth.guest-access": "Dugg Njiit", "auth.signup-prompt": "Amoo leen kont?",
        "auth.signup-link": "Bindu fii", "notify.version-selected": "Mel mi Tannees Na",
        "notify.version-configured": "defees na ko", "notify.credentials-loaded": "Xarnu yi Duggees Nañu",
        "notify.credentials-filled": "Jëfandikuwaay yi demo fees nañu", "error.fill-all-fields": "Jéggal fees bërëb yépp.",
        "error.invalid-credentials": "Xarnu yi baaxul ci mel mi tannees.",
        "error.wrong-version": "Bii email mooy bu mel mi {version}. Jéggal tann mel mi baax.",
        "login.redirecting-student": "🐆 Dalal jàmm! Yóbbu ci panel jàngkat bi...",
        "login.redirecting-teacher": "👨‍🏫 Dalal jàmm! Yóbbu ci panel jàngalekat bi...",
        "guest.accessing": "🌟 Dugg ni njiit...",
        "session.active-redirecting": "🐆 Gis nees sesiyon bu dox. Yóbbu...",
        "placeholder.email": "your@email.com", "placeholder.password": "Sa baatu sirr",
    },
    "ln": {
        "nav.back": "← Zonga", "ui.auto-detect": "Yango moko", "ui.select-language": "Pona Monoko",
        "auth.welcome": "Boyei malamu!", "auth.subtitle": "Kokoba mobembo na yo na Yaguará na kati ya bisika ya bomoi ya Colombia",
        "ui.lang-detected": "🌍 Monoko emonani yango moko", "ui.lang-suggestion": "💡 Olingi kokoba na monoko na yo ya mbotama?",
        "version.title": "🎯 Pona nzela na yo ya koyekola na Yaguará", "version.individual-title": "Mobembo ya Moto",
        "version.individual-desc": "Mobembo ya moto na Yaguará na kati ya Colombia",
        "version.classroom-title": "Lolenge la Kelasi", "version.classroom-desc": "Koyekola oyo ebongisami mpo na balakisi",
        "registration.pref-title": "📚 Pona monoko oyo olingi ya koyekola", "demo.title": "🎯 Kokota Demo",
        "form.email": "Email", "form.password": "Liloba ya nkuku",
        "demo.guest-option": "To tala lokola mopaya kozanga komikoma",
        "form.email-label": "📧 Adresi ya Email", "form.password-label": "🔒 Liloba ya nkuku",
        "auth.forgot-password": "Obosani liloba ya nkuku?", "auth.login-button": "Banda Mobembo", "ui.or": "to",
        "auth.guest-access": "Kokota ya Mopaya", "auth.signup-prompt": "Ozali na konte te?",
        "auth.signup-link": "Komikoma awa", "notify.version-selected": "Lolenge Eponami",
        "notify.version-configured": "ebongisami", "notify.credentials-loaded": "Bakarte Bakotisami",
        "notify.credentials-filled": "Banzela ya demo etondisami", "error.fill-all-fields": "Svp tondisa bisika nyonso.",
        "error.invalid-credentials": "Bakarte ya mabe mpo na lolenge eponami.",
        "error.wrong-version": "Email oyo ezali ya lolenge ya {version}. Svp pona lolenge ya malamu.",
        "login.redirecting-student": "🐆 Boyei malamu! Kokamba na paneli ya moyekoli...",
        "login.redirecting-teacher": "👨‍🏫 Boyei malamu! Kokamba na paneli ya molakisi...",
        "guest.accessing": "🌟 Kokota lokola mopaya...",
        "session.active-redirecting": "🐆 Sesiyo oyo ezali kosala emonani. Kokamba...",
        "placeholder.email": "your@email.com", "placeholder.password": "Liloba na yo ya nkuku",
    },
    "ti": {
        "nav.back": "← ተመለስ", "ui.auto-detect": "ብቐጥታ", "ui.select-language": "ቋንቋ ምረጽ",
        "auth.welcome": "እንቋዕ ብደሓን መጻእኩም!", "auth.subtitle": "ምስ Yaguará ኣብ ስነ-ህይወታዊ ስርዓታት ኮሎምብያ ጉዕዞኻ ቀጽል",
        "ui.lang-detected": "🌍 ቋንቋ ብቐጥታ ተረኺቡ", "ui.lang-suggestion": "💡 ብቋንቋ ኣዴኻ ክትቅጽል ትደሊ?",
        "version.title": "🎯 ምስ Yaguará መንገዲ ትምህርትኻ ምረጽ", "version.individual-title": "ውልቃዊ ጉዕዞ",
        "version.individual-desc": "ምስ Yaguará ኣብ ኮሎምብያ ውልቃዊ ጉዕዞ",
        "version.classroom-title": "ናይ ክፍሊ ሕታም", "version.classroom-desc": "ንመምህራን ዝተሰርዐ ትምህርቲ",
        "registration.pref-title": "📚 ዝደለኻዮ ቋንቋ ትምህርቲ ምረጽ", "demo.title": "🎯 ናይ ሞክ ኣገልግሎት",
        "form.email": "ኢመይል", "form.password": "ምስጢራዊ ቃል",
        "demo.guest-option": "ወይ ከም ጋሻ ብዘይ ምምዝጋብ ርአ",
        "form.email-label": "📧 ኣድራሻ ኢመይል", "form.password-label": "🔒 ምስጢራዊ ቃል",
        "auth.forgot-password": "ምስጢራዊ ቃል ረሲዕካ?", "auth.login-button": "ጉዕዞ ጀምር", "ui.or": "ወይ",
        "auth.guest-access": "ናይ ጋሻ ኣገልግሎት", "auth.signup-prompt": "ኣካውንቲ የብልካን?",
        "auth.signup-link": "ኣብዚ ተመዝገብ", "notify.version-selected": "ሕታም ተመሪጹ",
        "notify.version-configured": "ተሰሪዑ", "notify.credentials-loaded": "ናይ መእተዊ ሓበሬታ ተሰቒሉ",
        "notify.credentials-filled": "ናይ ሞክ ሓበሬታ ተመሊኡ", "error.fill-all-fields": "በጃኻ ኩሎም ቦታታት ምልኣዮም።",
        "error.invalid-credentials": "ንዝተመርጸ ሕታም ዘይቅኑዕ ናይ መእተዊ ሓበሬታ።",
        "error.wrong-version": "እዚ ኢመይል ንሕታም {version} እዩ። በጃኻ ቅኑዕ ሕታም ምረጽ።",
        "login.redirecting-student": "🐆 እንቋዕ ብደሓን! ናብ ናይ ተማሃራይ ፓነል ይውሰድ ኣሎ...",
        "login.redirecting-teacher": "👨‍🏫 እንቋዕ ብደሓን! ናብ ናይ መምህር ፓነል ይውሰድ ኣሎ...",
        "guest.accessing": "🌟 ከም ጋሻ ይኣቱ ኣሎ...",
        "session.active-redirecting": "🐆 ንጡፍ ክፍለ-ግዜ ተረኺቡ። ይውሰድ ኣሎ...",
        "placeholder.email": "your@email.com", "placeholder.password": "ምስጢራዊ ቃልካ",
    },
    "mg": {
        "nav.back": "← Miverina", "ui.auto-detect": "Otomatika", "ui.select-language": "Misafidiana Fiteny",
        "auth.welcome": "Tongasoa!", "auth.subtitle": "Tohizo ny dia miaraka amin'i Yaguará amin'ny tontolo iainana ao Colombia",
        "ui.lang-detected": "🌍 Ny fiteny dia hita ho azy", "ui.lang-suggestion": "💡 Te hanohy amin'ny fiteninao ve ianao?",
        "version.title": "🎯 Misafidiana ny lalanao fianarana miaraka amin'i Yaguará", "version.individual-title": "Dia Manokana",
        "version.individual-desc": "Dia manokana miaraka amin'i Yaguará any Colombia",
        "version.classroom-title": "Karazana Kilasy", "version.classroom-desc": "Fianarana voalamina ho an'ny mpampianatra",
        "registration.pref-title": "📚 Misafidiana ny fiteny tianao hianarana", "demo.title": "🎯 Fidirana Demo",
        "form.email": "Mailaka", "form.password": "Teny miafina",
        "demo.guest-option": "Na mijery ho vahiny tsy mila fisoratana anarana",
        "form.email-label": "📧 Adiresy Mailaka", "form.password-label": "🔒 Teny miafina",
        "auth.forgot-password": "Hadinoinao ny teny miafina?", "auth.login-button": "Hanomboka ny Dia", "ui.or": "na",
        "auth.guest-access": "Fidirana Vahiny", "auth.signup-prompt": "Tsy manana kaonty?",
        "auth.signup-link": "Misoratra eto", "notify.version-selected": "Karazana Voafidy",
        "notify.version-configured": "voalamina", "notify.credentials-loaded": "Porofo Tafiditra",
        "notify.credentials-filled": "Angona demo voafeno", "error.fill-all-fields": "Azafady fenoy ny saha rehetra.",
        "error.invalid-credentials": "Porofo tsy mety ho an'ny karazana voafidy.",
        "error.wrong-version": "Ity mailaka ity dia ho an'ny karazana {version}. Azafady safidio ny karazana marina.",
        "login.redirecting-student": "🐆 Tongasoa! Alefa any amin'ny panelan'ny mpianatra...",
        "login.redirecting-teacher": "👨‍🏫 Tongasoa! Alefa any amin'ny panelan'ny mpampianatra...",
        "guest.accessing": "🌟 Miditra ho vahiny...",
        "session.active-redirecting": "🐆 Hita ny fizarana mavitrika. Alefa...",
        "placeholder.email": "your@email.com", "placeholder.password": "Ny teny miafina anao",
    },
    "mi": {
        "nav.back": "← Hoki", "ui.auto-detect": "Aunoa", "ui.select-language": "Kōwhiria te Reo",
        "auth.welcome": "Nau mai!", "auth.subtitle": "Haere tonu i tō haerenga me Yaguará mā ngā pūnaha hauropi o Kōrombia",
        "ui.lang-detected": "🌍 Kua kitea aunoa te reo", "ui.lang-suggestion": "💡 Kei te hiahia koe ki te haere tonu i tō reo ake?",
        "version.title": "🎯 Kōwhiria tō ara ako me Yaguará", "version.individual-title": "Haerenga Takitahi",
        "version.individual-desc": "Haerenga takitahi me Yaguará mā Kōrombia",
        "version.classroom-title": "Putanga Akomanga", "version.classroom-desc": "Ako whakaraupapa mā ngā kaiako",
        "registration.pref-title": "📚 Kōwhiria tō reo ako e hiahia ana", "demo.title": "🎯 Urunga Whakaatu",
        "form.email": "Īmēra", "form.password": "Kupuhipa",
        "demo.guest-option": "Tūhura rānei hei manuhiri kāore he rēhita",
        "form.email-label": "📧 Wāhitau Īmēra", "form.password-label": "🔒 Kupuhipa",
        "auth.forgot-password": "Kua wareware te kupuhipa?", "auth.login-button": "Tīmata te Haerenga", "ui.or": "rānei",
        "auth.guest-access": "Urunga Manuhiri", "auth.signup-prompt": "Kāore he pūkete?",
        "auth.signup-link": "Rēhitatia ki konei", "notify.version-selected": "Kua Kōwhiria te Putanga",
        "notify.version-configured": "kua whirihoratia", "notify.credentials-loaded": "Kua Utaina ngā Taipitopito",
        "notify.credentials-filled": "Kua whakakīia ngā raraunga whakaatu", "error.fill-all-fields": "Whakakīia ngā āpure katoa.",
        "error.invalid-credentials": "He taipitopito hē mō te putanga kua kōwhiria.",
        "error.wrong-version": "Ko tēnei īmēra mō te putanga {version}. Kōwhiria te putanga tika.",
        "login.redirecting-student": "🐆 Nau mai! E whakawhiti ana ki te papatohu ākonga...",
        "login.redirecting-teacher": "👨‍🏫 Nau mai! E whakawhiti ana ki te papatohu kaiako...",
        "guest.accessing": "🌟 E uru ana hei manuhiri...",
        "session.active-redirecting": "🐆 Kua kitea he wāhanga kei te mahi. E whakawhiti ana...",
        "placeholder.email": "your@email.com", "placeholder.password": "Tō kupuhipa",
    },
    "sm": {
        "nav.back": "← Toe foi", "ui.auto-detect": "Otometi", "ui.select-language": "Filifili Gagana",
        "auth.welcome": "Afio mai!", "auth.subtitle": "Faaauau lau malaga ma Yaguará e ala i faiga o le siosiomaga o Kolomipia",
        "ui.lang-detected": "🌍 Ua maua le gagana e le otometi", "ui.lang-suggestion": "💡 E te manaʻo e faaauau i lou gagana?",
        "version.title": "🎯 Filifili lou ala aʻoaʻoga ma Yaguará", "version.individual-title": "Malaga Tumaoti",
        "version.individual-desc": "Malaga tumaoti ma Yaguará e ala i Kolomipia",
        "version.classroom-title": "Ituaiga Vasega", "version.classroom-desc": "Aʻoaʻoga faʻatulagaina mo faiaʻoga",
        "registration.pref-title": "📚 Filifili lou gagana aʻoaʻoga e fiafia i ai", "demo.title": "🎯 Avanoa Demo",
        "form.email": "Imeli", "form.password": "Upu faʻalilolilo",
        "demo.guest-option": "Pe suʻesuʻe o se tagata mai fafo e aunoa ma le lesitala",
        "form.email-label": "📧 Tuatusi Imeli", "form.password-label": "🔒 Upu faʻalilolilo",
        "auth.forgot-password": "Ua galo le upu faʻalilolilo?", "auth.login-button": "Amata le Malaga", "ui.or": "pe",
        "auth.guest-access": "Avanoa Tagata Mai Fafo", "auth.signup-prompt": "E leai sau teugatā?",
        "auth.signup-link": "Lesitala iinei", "notify.version-selected": "Ua Filifilia le Ituaiga",
        "notify.version-configured": "ua faʻatulagaina", "notify.credentials-loaded": "Ua Utaina Faʻamaoniga",
        "notify.credentials-filled": "Ua tumu faʻamatalaga demo", "error.fill-all-fields": "Faʻamolemole faʻatumu vaega uma.",
        "error.invalid-credentials": "Faʻamaoniga le aoga mo le ituaiga filifilia.",
        "error.wrong-version": "O lenei imeli e mo le ituaiga {version}. Faʻamolemole filifili le ituaiga saʻo.",
        "login.redirecting-student": "🐆 Afio mai! O loʻo faʻasino atu i le panel tamaiti aʻoga...",
        "login.redirecting-teacher": "👨‍🏫 Afio mai! O loʻo faʻasino atu i le panel faiaʻoga...",
        "guest.accessing": "🌟 O loʻo ulufale mai o se tagata mai fafo...",
        "session.active-redirecting": "🐆 Ua maua se sesiona galue. O loʻo faʻasino atu...",
        "placeholder.email": "your@email.com", "placeholder.password": "Lau upu faʻalilolilo",
    },
    "haw": {
        "nav.back": "← Hoʻi", "ui.auto-detect": "Maʻamau", "ui.select-language": "Koho ʻŌlelo",
        "auth.welcome": "Aloha!", "auth.subtitle": "E hoʻomau i kou huakaʻi me Yaguará ma nā kaiaola o Kolombia",
        "ui.lang-detected": "🌍 Ua ʻike ʻia ka ʻōlelo ma ka maʻamau", "ui.lang-suggestion": "💡 Makemake ʻoe e hoʻomau ma kou ʻōlelo makuahine?",
        "version.title": "🎯 E koho i kou ala aʻo me Yaguará", "version.individual-title": "Huakaʻi Hoʻokahi",
        "version.individual-desc": "Huakaʻi ponoʻī me Yaguará ma Kolombia",
        "version.classroom-title": "ʻAno Papa", "version.classroom-desc": "Aʻo hoʻonohonoho no nā kumu",
        "registration.pref-title": "📚 E koho i kou ʻōlelo aʻo punahele", "demo.title": "🎯 Komo Demo",
        "form.email": "Leka uila", "form.password": "Hua huna",
        "demo.guest-option": "A i ʻole e nānā ma ke ʻano o ka malihini me ka hoʻopaʻa inoa ʻole",
        "form.email-label": "📧 Leka Uila", "form.password-label": "🔒 Hua Huna",
        "auth.forgot-password": "Poina i ka hua huna?", "auth.login-button": "Hoʻomaka i ka Huakaʻi", "ui.or": "a i ʻole",
        "auth.guest-access": "Komo Malihini", "auth.signup-prompt": "ʻAʻohe moʻokāki?",
        "auth.signup-link": "Kāinoa ma aneʻi", "notify.version-selected": "Ua Koho ʻia ka ʻAno",
        "notify.version-configured": "ua hoʻonohonoho ʻia", "notify.credentials-loaded": "Ua Hoʻouka ʻia nā Palapala",
        "notify.credentials-filled": "Ua hoʻopiha ʻia ka ʻikepili demo", "error.fill-all-fields": "E hoʻopiha i nā māhele a pau.",
        "error.invalid-credentials": "Palapala hewa no ka ʻano i koho ʻia.",
        "error.wrong-version": "No ka ʻano {version} kēia leka uila. E koho i ka ʻano pololei.",
        "login.redirecting-student": "🐆 Aloha! Ke alakaʻi nei i ka papa haumāna...",
        "login.redirecting-teacher": "👨‍🏫 Aloha! Ke alakaʻi nei i ka papa kumu...",
        "guest.accessing": "🌟 Ke komo nei ma ke ʻano malihini...",
        "session.active-redirecting": "🐆 Ua ʻike ʻia kahi papa hana. Ke alakaʻi nei...",
        "placeholder.email": "your@email.com", "placeholder.password": "Kou hua huna",
    },
    "fj": {
        "nav.back": "← Lesu", "ui.auto-detect": "Ira ga", "ui.select-language": "Digitaka na Vosa",
        "auth.welcome": "Bula!", "auth.subtitle": "Vakacuruma na nomu lako kei Yaguará ena veika bula ni Colombia",
        "ui.lang-detected": "🌍 Na vosa sa kunea ira ga", "ui.lang-suggestion": "💡 Ko vinakata mo vakacuruma ena nomu vosa?",
        "version.title": "🎯 Digitaka na nomu sala ni vuli kei Yaguará", "version.individual-title": "Na Lako Vata Ga",
        "version.individual-desc": "Na lako vata ga kei Yaguará ena Colombia",
        "version.classroom-title": "Ituvatuva ni Kalasi", "version.classroom-desc": "Na vuli vakatutu me vei ira na qasenivuli",
        "registration.pref-title": "📚 Digitaka na nomu vosa ni vuli", "demo.title": "🎯 Curu Demo",
        "form.email": "Imeli", "form.password": "Vosa ni lako",
        "demo.guest-option": "Se raica me vulagi e sega ni rejisita",
        "form.email-label": "📧 Tikina ni Imeli", "form.password-label": "🔒 Vosa ni lako",
        "auth.forgot-password": "Sa guilecava na vosa ni lako?", "auth.login-button": "Tekivu na Lako", "ui.or": "se",
        "auth.guest-access": "Curu ni Vulagi", "auth.signup-prompt": "Sega ni dua na akaude?",
        "auth.signup-link": "Rejisita eke", "notify.version-selected": "Sa Digitaki na Ituvatuva",
        "notify.version-configured": "sa vakacokotaki", "notify.credentials-loaded": "Sa Loudi na Itukutuku",
        "notify.credentials-filled": "Sa vakacurumi na itukutuku ni demo", "error.fill-all-fields": "Meda vakacuruma na vanua kece.",
        "error.invalid-credentials": "Na itukutuku sega ni dodonu me baleta na ituvatuva sa digitaki.",
        "error.wrong-version": "Na imeli oqo e baleta na ituvatuva ni {version}. Meda digitaka na ituvatuva dodonu.",
        "login.redirecting-student": "🐆 Bula! Sa veivosaki ki na papa ni gone vuli...",
        "login.redirecting-teacher": "👨‍🏫 Bula! Sa veivosaki ki na papa ni qasenivuli...",
        "guest.accessing": "🌟 Sa curumi me vulagi...",
        "session.active-redirecting": "🐆 Sa kunei na cakacaka sa caka tiko. Sa veivosaki...",
        "placeholder.email": "your@email.com", "placeholder.password": "Na nomu vosa ni lako",
    },
    "eo": {
        "nav.back": "← Reen", "ui.auto-detect": "Aŭtomate", "ui.select-language": "Elektu Lingvon",
        "auth.welcome": "Bonvenon!", "auth.subtitle": "Daŭrigu vian aventuron kun Yaguará tra la ekosistemoj de Kolombio",
        "ui.lang-detected": "🌍 Lingvo aŭtomate detektita", "ui.lang-suggestion": "💡 Ĉu vi preferas daŭrigi en via denaska lingvo?",
        "version.title": "🎯 Elektu vian lernovojon kun Yaguará", "version.individual-title": "Individua Vojaĝo",
        "version.individual-desc": "Persona aventuro kun Yaguará tra Kolombio",
        "version.classroom-title": "Klasĉambra Eldono", "version.classroom-desc": "Strukturita lernado por instruistoj",
        "registration.pref-title": "📚 Elektu vian preferatan lernolingvon", "demo.title": "🎯 Demo-Aliro",
        "form.email": "Retpoŝto", "form.password": "Pasvorto",
        "demo.guest-option": "Aŭ esploru kiel gasto sen registriĝo",
        "form.email-label": "📧 Retpoŝtadreso", "form.password-label": "🔒 Pasvorto",
        "auth.forgot-password": "Forgesis pasvorton?", "auth.login-button": "Komencu Aventuron", "ui.or": "aŭ",
        "auth.guest-access": "Gasta Aliro", "auth.signup-prompt": "Ĉu vi ne havas konton?",
        "auth.signup-link": "Registriĝu ĉi tie", "notify.version-selected": "Eldono Elektita",
        "notify.version-configured": "agordita", "notify.credentials-loaded": "Akreditaĵoj Ŝargitaj",
        "notify.credentials-filled": "Demo-datumoj plenigitaj", "error.fill-all-fields": "Bonvolu plenigi ĉiujn kampojn.",
        "error.invalid-credentials": "Nevalidaj akreditaĵoj por la elektita eldono.",
        "error.wrong-version": "Ĉi tiu retpoŝto estas por la eldono {version}. Bonvolu elekti la ĝustan eldonon.",
        "login.redirecting-student": "🐆 Bonvenon! Alidirektado al la lernantpanelo...",
        "login.redirecting-teacher": "👨‍🏫 Bonvenon! Alidirektado al la instruistpanelo...",
        "guest.accessing": "🌟 Alirado kiel gasto...",
        "session.active-redirecting": "🐆 Aktiva seanco detektita. Alidirektado...",
        "placeholder.email": "your@email.com", "placeholder.password": "Via pasvorto",
    },
    "la": {
        "nav.back": "← Retro", "ui.auto-detect": "Auto", "ui.select-language": "Elige Linguam",
        "auth.welcome": "Salve!", "auth.subtitle": "Perge iter tuum cum Yaguará per systemata oecologica Columbiae",
        "ui.lang-detected": "🌍 Lingua automatice detecta est", "ui.lang-suggestion": "💡 Visne pergere lingua tua materna?",
        "version.title": "🎯 Elige viam discendi cum Yaguará", "version.individual-title": "Iter Singulare",
        "version.individual-desc": "Iter personale cum Yaguará per Columbiam",
        "version.classroom-title": "Editio Scholae", "version.classroom-desc": "Discentia structa pro magistris",
        "registration.pref-title": "📚 Elige linguam discendi praedilectam", "demo.title": "🎯 Accessus Demonstrationis",
        "form.email": "Litterae electronicae", "form.password": "Tessera",
        "demo.guest-option": "Vel explora ut hospes sine inscriptione",
        "form.email-label": "📧 Inscriptio Litterarum Electronicarum", "form.password-label": "🔒 Tessera",
        "auth.forgot-password": "Tesseram oblitus es?", "auth.login-button": "Incipe Iter", "ui.or": "vel",
        "auth.guest-access": "Accessus Hospitis", "auth.signup-prompt": "Rationem non habes?",
        "auth.signup-link": "Hic inscribe", "notify.version-selected": "Editio Electa",
        "notify.version-configured": "configurata", "notify.credentials-loaded": "Mandata Onerata",
        "notify.credentials-filled": "Data demonstrationis impleta", "error.fill-all-fields": "Quaeso omnes agros imple.",
        "error.invalid-credentials": "Mandata invalida pro editione electa.",
        "error.wrong-version": "Hae litterae electronicae sunt pro editione {version}. Quaeso elige editionem rectam.",
        "login.redirecting-student": "🐆 Salve! Dirigitur ad tabulam discipuli...",
        "login.redirecting-teacher": "👨‍🏫 Salve! Dirigitur ad tabulam magistri...",
        "guest.accessing": "🌟 Ut hospes accedens...",
        "session.active-redirecting": "🐆 Sessio activa detecta. Dirigitur...",
        "placeholder.email": "your@email.com", "placeholder.password": "Tessera tua",
    },
    "bo": {
        "nav.back": "← ཕྱིར་ལོག", "ui.auto-detect": "རང་འགུལ", "ui.select-language": "སྐད་ཡིག་འདེམ་པ",
        "auth.welcome": "བཀྲ་ཤིས་བདེ་ལེགས!", "auth.subtitle": "Yaguará དང་མཉམ་དུ་ཁོ་ལོམ་བི་ཡའི་སྐྱེ་ཁམས་ཀྱི་ལམ་ནས་ཁྱེད་ཀྱི་སྤྲོ་སྣང་མུ་མཐུད།",
        "ui.lang-detected": "🌍 སྐད་ཡིག་རང་འགུལ་གྱིས་ངོས་ཟིན་བྱུང།", "ui.lang-suggestion": "💡 ཁྱེད་ཀྱི་ཕ་སྐད་ཀྱིས་མུ་མཐུད་འདོད་དམ?",
        "version.title": "🎯 Yaguará དང་མཉམ་དུ་སློབ་སྦྱོང་གི་ལམ་འདེམ་པ", "version.individual-title": "སྒེར་གྱི་འགྲུལ་བཞུད",
        "version.individual-desc": "Yaguará དང་མཉམ་དུ་ཁོ་ལོམ་བི་ཡར་སྒེར་གྱི་སྤྲོ་སྣང།",
        "version.classroom-title": "སློབ་ཁང་པར་གཞི", "version.classroom-desc": "དགེ་རྒན་ཚོའི་ཆེད་སྒྲིག་བཀོད་སློབ་སྦྱོང།",
        "registration.pref-title": "📚 སྐད་ཡིག་གང་ཞིག་སློབ་སྦྱོང་བྱེད་འདོད་པ་འདེམ་པ", "demo.title": "🎯 ཚོད་ལྟའི་འཛུལ་ཞུགས",
        "form.email": "གློག་འཕྲིན", "form.password": "གསང་ཡིག",
        "demo.guest-option": "ཡང་ན་ཐོ་འགོད་མེད་པར་མགྲོན་པོའི་ཐོག་ནས་ལྟ་བ",
        "form.email-label": "📧 གློག་འཕྲིན་ཁ་བྱང།", "form.password-label": "🔒 གསང་ཡིག",
        "auth.forgot-password": "གསང་ཡིག་བརྗེད་སོང་ངམ?", "auth.login-button": "སྤྲོ་སྣང་འགོ་བཙུགས", "ui.or": "ཡང་ན",
        "auth.guest-access": "མགྲོན་པོའི་འཛུལ་ཞུགས", "auth.signup-prompt": "ཐོ་ཁུངས་མེད་དམ?",
        "auth.signup-link": "འདིར་ཐོ་འགོད་བྱོས", "notify.version-selected": "པར་གཞི་འདེམས་ཟིན",
        "notify.version-configured": "སྒྲིག་བཀོད་ཟིན", "notify.credentials-loaded": "ཐོ་འགོད་ཀྱི་གནས་ཚུལ་བླུགས་ཟིན",
        "notify.credentials-filled": "ཚོད་ལྟའི་གཞི་གྲངས་བཀང་ཟིན", "error.fill-all-fields": "ས་ཁོངས་ཚང་མ་བཀང་རོགས།",
        "error.invalid-credentials": "འདེམས་ཟིན་པའི་པར་གཞིའི་ཆེད་ཐོ་འགོད་ཀྱི་གནས་ཚུལ་མི་འཐུས།",
        "error.wrong-version": "གློག་འཕྲིན་འདི་{version} པར་གཞིའི་ཆེད་ཡིན། པར་གཞི་ཡང་དག་འདེམ་རོགས།",
        "login.redirecting-student": "🐆 བཀྲ་ཤིས་བདེ་ལེགས! སློབ་ཕྲུག་གི་ལྡེབ་ངོས་སུ་བསྐྱོད་བཞིན...",
        "login.redirecting-teacher": "👨‍🏫 བཀྲ་ཤིས་བདེ་ལེགས! དགེ་རྒན་གྱི་ལྡེབ་ངོས་སུ་བསྐྱོད་བཞིན...",
        "guest.accessing": "🌟 མགྲོན་པོའི་ཐོག་ནས་འཛུལ་བཞིན...",
        "session.active-redirecting": "🐆 བྱེད་སྒོ་ཡོད་པའི་མཐུན་རྐྱེན་རྗེད་སོང། བསྐྱོད་བཞིན...",
        "placeholder.email": "your@email.com", "placeholder.password": "ཁྱེད་ཀྱི་གསང་ཡིག",
    },
}
