"""Login page translations — Asian languages."""

TRANS_ASIA = {
    "zh": {
        "nav.back": "← 返回",
        "ui.auto-detect": "自动",
        "ui.select-language": "选择语言",
        "auth.welcome": "欢迎！",
        "auth.subtitle": "与Yaguará一起继续探索哥伦比亚生态系统的冒险",
        "ui.lang-detected": "🌍 语言已自动检测",
        "ui.lang-suggestion": "💡 您想用母语继续吗？",
        "version.title": "🎯 与Yaguará一起选择您的学习路径",
        "version.individual-title": "个人旅程",
        "version.individual-desc": "与Yaguará一起穿越哥伦比亚的个人冒险",
        "version.classroom-title": "课堂版",
        "version.classroom-desc": "为教育工作者设计的结构化学习",
        "registration.pref-title": "📚 选择您喜欢的学习语言",
        "demo.title": "🎯 演示访问",
        "form.email": "电子邮件",
        "form.password": "密码",
        "demo.guest-option": "或以访客身份浏览，无需注册",
        "form.email-label": "📧 电子邮件地址",
        "form.password-label": "🔒 密码",
        "auth.forgot-password": "忘记密码？",
        "auth.login-button": "开始冒险",
        "ui.or": "或",
        "auth.guest-access": "访客访问",
        "auth.signup-prompt": "没有账户？",
        "auth.signup-link": "在此注册",
        "notify.version-selected": "版本已选择",
        "notify.version-configured": "已配置",
        "notify.credentials-loaded": "凭据已加载",
        "notify.credentials-filled": "演示数据已填充",
        "error.fill-all-fields": "请填写所有字段。",
        "error.invalid-credentials": "所选版本的凭据无效。",
        "error.wrong-version": "此电子邮件用于{version}版本。请选择正确的版本。",
        "login.redirecting-student": "🐆 欢迎！正在重定向到学生面板...",
        "login.redirecting-teacher": "👨‍🏫 欢迎！正在重定向到教师面板...",
        "guest.accessing": "🌟 正在以访客身份访问...",
        "session.active-redirecting": "🐆 检测到活跃会话。正在重定向...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "您的密码"
    },
    "zh-tw": {
        "nav.back": "← 返回",
        "ui.auto-detect": "自動",
        "ui.select-language": "選擇語言",
        "auth.welcome": "歡迎！",
        "auth.subtitle": "與Yaguará一起繼續探索哥倫比亞生態系統的冒險",
        "ui.lang-detected": "🌍 語言已自動偵測",
        "ui.lang-suggestion": "💡 您想用母語繼續嗎？",
        "version.title": "🎯 與Yaguará一起選擇您的學習路徑",
        "version.individual-title": "個人旅程",
        "version.individual-desc": "與Yaguará一起穿越哥倫比亞的個人冒險",
        "version.classroom-title": "課堂版",
        "version.classroom-desc": "為教育工作者設計的結構化學習",
        "registration.pref-title": "📚 選擇您喜歡的學習語言",
        "demo.title": "🎯 演示存取",
        "form.email": "電子郵件",
        "form.password": "密碼",
        "demo.guest-option": "或以訪客身份瀏覽，無需註冊",
        "form.email-label": "📧 電子郵件地址",
        "form.password-label": "🔒 密碼",
        "auth.forgot-password": "忘記密碼？",
        "auth.login-button": "開始冒險",
        "ui.or": "或",
        "auth.guest-access": "訪客存取",
        "auth.signup-prompt": "沒有帳戶？",
        "auth.signup-link": "在此註冊",
        "notify.version-selected": "版本已選擇",
        "notify.version-configured": "已設定",
        "notify.credentials-loaded": "憑證已載入",
        "notify.credentials-filled": "演示資料已填入",
        "error.fill-all-fields": "請填寫所有欄位。",
        "error.invalid-credentials": "所選版本的憑證無效。",
        "error.wrong-version": "此電子郵件用於{version}版本。請選擇正確的版本。",
        "login.redirecting-student": "🐆 歡迎！正在重新導向至學生面板...",
        "login.redirecting-teacher": "👨‍🏫 歡迎！正在重新導向至教師面板...",
        "guest.accessing": "🌟 正在以訪客身份存取...",
        "session.active-redirecting": "🐆 偵測到使用中的工作階段。正在重新導向...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "您的密碼"
    },
    "ja": {
        "nav.back": "← 戻る",
        "ui.auto-detect": "自動",
        "ui.select-language": "言語を選択",
        "auth.welcome": "ようこそ！",
        "auth.subtitle": "Yaguaráと一緒にコロンビアの生態系を冒険しよう",
        "ui.lang-detected": "🌍 言語が自動検出されました",
        "ui.lang-suggestion": "💡 母国語で続けますか？",
        "version.title": "🎯 Yaguaráと学習パスを選択",
        "version.individual-title": "個人の旅",
        "version.individual-desc": "Yaguaráとコロンビアを巡る個人冒険",
        "version.classroom-title": "教室版",
        "version.classroom-desc": "教育者向けの構造化学習",
        "registration.pref-title": "📚 学習言語を選択してください",
        "demo.title": "🎯 デモアクセス",
        "form.email": "メール",
        "form.password": "パスワード",
        "demo.guest-option": "登録なしでゲストとして探索することもできます",
        "form.email-label": "📧 メールアドレス",
        "form.password-label": "🔒 パスワード",
        "auth.forgot-password": "パスワードを忘れましたか？",
        "auth.login-button": "冒険を始める",
        "ui.or": "または",
        "auth.guest-access": "ゲストアクセス",
        "auth.signup-prompt": "アカウントをお持ちでないですか？",
        "auth.signup-link": "こちらから登録",
        "notify.version-selected": "バージョン選択済み",
        "notify.version-configured": "設定済み",
        "notify.credentials-loaded": "認証情報を読み込みました",
        "notify.credentials-filled": "デモデータが入力されました",
        "error.fill-all-fields": "すべてのフィールドを入力してください。",
        "error.invalid-credentials": "選択したバージョンの認証情報が無効です。",
        "error.wrong-version": "このメールは{version}バージョン用です。正しいバージョンを選択してください。",
        "login.redirecting-student": "🐆 ようこそ！学生パネルにリダイレクト中...",
        "login.redirecting-teacher": "👨‍🏫 ようこそ！教師パネルにリダイレクト中...",
        "guest.accessing": "🌟 ゲストとしてアクセス中...",
        "session.active-redirecting": "🐆 アクティブなセッションを検出。リダイレクト中...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "パスワード"
    },
    "ko": {
        "nav.back": "← 뒤로",
        "ui.auto-detect": "자동",
        "ui.select-language": "언어 선택",
        "auth.welcome": "환영합니다!",
        "auth.subtitle": "Yaguará와 함께 콜롬비아 생태계 모험을 계속하세요",
        "ui.lang-detected": "🌍 언어가 자동으로 감지되었습니다",
        "ui.lang-suggestion": "💡 모국어로 계속하시겠습니까?",
        "version.title": "🎯 Yaguará와 학습 경로를 선택하세요",
        "version.individual-title": "개인 여정",
        "version.individual-desc": "Yaguará와 함께하는 콜롬비아 개인 모험",
        "version.classroom-title": "교실 에디션",
        "version.classroom-desc": "교육자를 위한 구조화된 학습",
        "registration.pref-title": "📚 선호하는 학습 언어를 선택하세요",
        "demo.title": "🎯 데모 접속",
        "form.email": "이메일",
        "form.password": "비밀번호",
        "demo.guest-option": "또는 등록 없이 게스트로 탐색하세요",
        "form.email-label": "📧 이메일 주소",
        "form.password-label": "🔒 비밀번호",
        "auth.forgot-password": "비밀번호를 잊으셨나요?",
        "auth.login-button": "모험 시작",
        "ui.or": "또는",
        "auth.guest-access": "게스트 접속",
        "auth.signup-prompt": "계정이 없으신가요?",
        "auth.signup-link": "여기서 가입",
        "notify.version-selected": "버전 선택됨",
        "notify.version-configured": "구성됨",
        "notify.credentials-loaded": "인증정보 로드됨",
        "notify.credentials-filled": "데모 데이터 입력됨",
        "error.fill-all-fields": "모든 필드를 입력해 주세요.",
        "error.invalid-credentials": "선택한 버전의 인증정보가 유효하지 않습니다.",
        "error.wrong-version": "이 이메일은 {version} 버전용입니다. 올바른 버전을 선택해 주세요.",
        "login.redirecting-student": "🐆 환영합니다! 학생 패널로 이동 중...",
        "login.redirecting-teacher": "👨‍🏫 환영합니다! 교사 패널로 이동 중...",
        "guest.accessing": "🌟 게스트로 접속 중...",
        "session.active-redirecting": "🐆 활성 세션 감지. 이동 중...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "비밀번호"
    },
    "hi": {
        "nav.back": "← वापस",
        "ui.auto-detect": "स्वतः",
        "ui.select-language": "भाषा चुनें",
        "auth.welcome": "स्वागत है!",
        "auth.subtitle": "Yaguará के साथ कोलंबियाई पारिस्थितिकी तंत्र में अपना साहसिक कार्य जारी रखें",
        "ui.lang-detected": "🌍 भाषा स्वतः पहचानी गई",
        "ui.lang-suggestion": "💡 क्या आप अपनी मातृभाषा में जारी रखना चाहेंगे?",
        "version.title": "🎯 Yaguará के साथ अपना सीखने का मार्ग चुनें",
        "version.individual-title": "व्यक्तिगत यात्रा",
        "version.individual-desc": "Yaguará के साथ कोलंबिया में व्यक्तिगत साहसिक कार्य",
        "version.classroom-title": "कक्षा संस्करण",
        "version.classroom-desc": "शिक्षकों के लिए संरचित शिक्षा",
        "registration.pref-title": "📚 अपनी पसंदीदा शिक्षण भाषा चुनें",
        "demo.title": "🎯 डेमो एक्सेस",
        "form.email": "ईमेल",
        "form.password": "पासवर्ड",
        "demo.guest-option": "या बिना पंजीकरण के अतिथि के रूप में देखें",
        "form.email-label": "📧 ईमेल पता",
        "form.password-label": "🔒 पासवर्ड",
        "auth.forgot-password": "पासवर्ड भूल गए?",
        "auth.login-button": "साहसिक कार्य शुरू करें",
        "ui.or": "या",
        "auth.guest-access": "अतिथि प्रवेश",
        "auth.signup-prompt": "खाता नहीं है?",
        "auth.signup-link": "यहाँ साइन अप करें",
        "notify.version-selected": "संस्करण चयनित",
        "notify.version-configured": "कॉन्फ़िगर किया गया",
        "notify.credentials-loaded": "प्रमाण-पत्र लोड हो गए",
        "notify.credentials-filled": "डेमो डेटा भरा गया",
        "error.fill-all-fields": "कृपया सभी फ़ील्ड भरें।",
        "error.invalid-credentials": "चयनित संस्करण के लिए अमान्य प्रमाण-पत्र।",
        "error.wrong-version": "यह ईमेल {version} संस्करण के लिए है। कृपया सही संस्करण चुनें।",
        "login.redirecting-student": "🐆 स्वागत है! छात्र पैनल पर रीडायरेक्ट हो रहा है...",
        "login.redirecting-teacher": "👨‍🏫 स्वागत है! शिक्षक पैनल पर रीडायरेक्ट हो रहा है...",
        "guest.accessing": "🌟 अतिथि के रूप में प्रवेश हो रहा है...",
        "session.active-redirecting": "🐆 सक्रिय सत्र पाया गया। रीडायरेक्ट हो रहा है...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "आपका पासवर्ड"
    },
    "bn": {
        "nav.back": "← পিছনে",
        "ui.auto-detect": "স্বয়ংক্রিয়",
        "ui.select-language": "ভাষা নির্বাচন করুন",
        "auth.welcome": "স্বাগতম!",
        "auth.subtitle": "Yaguará-এর সাথে কলম্বিয়ান বাস্তুতন্ত্রে আপনার অভিযান চালিয়ে যান",
        "ui.lang-detected": "🌍 ভাষা স্বয়ংক্রিয়ভাবে শনাক্ত হয়েছে",
        "ui.lang-suggestion": "💡 আপনি কি আপনার মাতৃভাষায় চালিয়ে যেতে চান?",
        "version.title": "🎯 Yaguará-এর সাথে আপনার শেখার পথ বেছে নিন",
        "version.individual-title": "ব্যক্তিগত যাত্রা",
        "version.individual-desc": "Yaguará-এর সাথে কলম্বিয়ায় ব্যক্তিগত অভিযান",
        "version.classroom-title": "শ্রেণীকক্ষ সংস্করণ",
        "version.classroom-desc": "শিক্ষকদের জন্য কাঠামোগত শিক্ষা",
        "registration.pref-title": "📚 আপনার পছন্দের শিক্ষার ভাষা নির্বাচন করুন",
        "demo.title": "🎯 ডেমো অ্যাক্সেস",
        "form.email": "ইমেইল",
        "form.password": "পাসওয়ার্ড",
        "demo.guest-option": "অথবা নিবন্ধন ছাড়াই অতিথি হিসেবে দেখুন",
        "form.email-label": "📧 ইমেইল ঠিকানা",
        "form.password-label": "🔒 পাসওয়ার্ড",
        "auth.forgot-password": "পাসওয়ার্ড ভুলে গেছেন?",
        "auth.login-button": "অভিযান শুরু করুন",
        "ui.or": "অথবা",
        "auth.guest-access": "অতিথি প্রবেশ",
        "auth.signup-prompt": "অ্যাকাউন্ট নেই?",
        "auth.signup-link": "এখানে সাইন আপ করুন",
        "notify.version-selected": "সংস্করণ নির্বাচিত",
        "notify.version-configured": "কনফিগার করা হয়েছে",
        "notify.credentials-loaded": "শংসাপত্র লোড হয়েছে",
        "notify.credentials-filled": "ডেমো ডেটা পূরণ হয়েছে",
        "error.fill-all-fields": "অনুগ্রহ করে সব ক্ষেত্র পূরণ করুন।",
        "error.invalid-credentials": "নির্বাচিত সংস্করণের জন্য অবৈধ শংসাপত্র।",
        "error.wrong-version": "এই ইমেইল {version} সংস্করণের জন্য। অনুগ্রহ করে সঠিক সংস্করণ নির্বাচন করুন।",
        "login.redirecting-student": "🐆 স্বাগতম! ছাত্র প্যানেলে রিডাইরেক্ট হচ্ছে...",
        "login.redirecting-teacher": "👨‍🏫 স্বাগতম! শিক্ষক প্যানেলে রিডাইরেক্ট হচ্ছে...",
        "guest.accessing": "🌟 অতিথি হিসেবে প্রবেশ করা হচ্ছে...",
        "session.active-redirecting": "🐆 সক্রিয় সেশন পাওয়া গেছে। রিডাইরেক্ট হচ্ছে...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "আপনার পাসওয়ার্ড"
    },
    "ur": {
        "nav.back": "→ واپس",
        "ui.auto-detect": "خودکار",
        "ui.select-language": "زبان منتخب کریں",
        "auth.welcome": "!خوش آمدید",
        "auth.subtitle": "Yaguará کے ساتھ کولمبیائی ماحولیاتی نظام میں اپنا مہم جاری رکھیں",
        "ui.lang-detected": "🌍 زبان خودکار طور پر پہچانی گئی",
        "ui.lang-suggestion": "💡 کیا آپ اپنی مادری زبان میں جاری رکھنا چاہیں گے؟",
        "version.title": "🎯 Yaguará کے ساتھ اپنا سیکھنے کا راستہ منتخب کریں",
        "version.individual-title": "انفرادی سفر",
        "version.individual-desc": "Yaguará کے ساتھ کولمبیا میں ذاتی مہم",
        "version.classroom-title": "کلاس روم ایڈیشن",
        "version.classroom-desc": "اساتذہ کے لیے منظم تعلیم",
        "registration.pref-title": "📚 اپنی پسندیدہ سیکھنے کی زبان منتخب کریں",
        "demo.title": "🎯 ڈیمو رسائی",
        "form.email": "ای میل",
        "form.password": "پاسورڈ",
        "demo.guest-option": "یا بغیر رجسٹریشن کے مہمان کے طور پر دیکھیں",
        "form.email-label": "📧 ای میل ایڈریس",
        "form.password-label": "🔒 پاسورڈ",
        "auth.forgot-password": "پاسورڈ بھول گئے؟",
        "auth.login-button": "مہم شروع کریں",
        "ui.or": "یا",
        "auth.guest-access": "مہمان رسائی",
        "auth.signup-prompt": "اکاؤنٹ نہیں ہے؟",
        "auth.signup-link": "یہاں سائن اپ کریں",
        "notify.version-selected": "ورژن منتخب",
        "notify.version-configured": "ترتیب دیا گیا",
        "notify.credentials-loaded": "اسناد لوڈ ہو گئیں",
        "notify.credentials-filled": "ڈیمو ڈیٹا بھرا گیا",
        "error.fill-all-fields": "براہ کرم تمام فیلڈز بھریں۔",
        "error.invalid-credentials": "منتخب ورژن کے لیے غلط اسناد۔",
        "error.wrong-version": "یہ ای میل {version} ورژن کے لیے ہے۔ براہ کرم صحیح ورژن منتخب کریں۔",
        "login.redirecting-student": "🐆 !خوش آمدید طالب علم پینل پر بھیجا جا رہا ہے...",
        "login.redirecting-teacher": "👨‍🏫 !خوش آمدید استاد پینل پر بھیجا جا رہا ہے...",
        "guest.accessing": "🌟 مہمان کے طور پر رسائی ہو رہی ہے...",
        "session.active-redirecting": "🐆 فعال سیشن ملا۔ بھیجا جا رہا ہے...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "آپ کا پاسورڈ"
    },
    "ta": {
        "nav.back": "← பின்செல்",
        "ui.auto-detect": "தானியங்கி",
        "ui.select-language": "மொழியைத் தேர்ந்தெடுக்கவும்",
        "auth.welcome": "வரவேற்கிறோம்!",
        "auth.subtitle": "Yaguará உடன் கொலம்பிய சுற்றுச்சூழல் அமைப்புகளில் உங்கள் சாகசத்தைத் தொடரவும்",
        "ui.lang-detected": "🌍 மொழி தானாகக் கண்டறியப்பட்டது",
        "ui.lang-suggestion": "💡 உங்கள் தாய்மொழியில் தொடர விரும்புகிறீர்களா?",
        "version.title": "🎯 Yaguará உடன் உங்கள் கற்றல் பாதையைத் தேர்ந்தெடுக்கவும்",
        "version.individual-title": "தனிநபர் பயணம்",
        "version.individual-desc": "Yaguará உடன் கொலம்பியா வழியாக தனிநபர் சாகசம்",
        "version.classroom-title": "வகுப்பறை பதிப்பு",
        "version.classroom-desc": "கல்வியாளர்களுக்கான கட்டமைக்கப்பட்ட கற்றல்",
        "registration.pref-title": "📚 உங்கள் விருப்பமான கற்றல் மொழியைத் தேர்ந்தெடுக்கவும்",
        "demo.title": "🎯 டெமோ அணுகல்",
        "form.email": "மின்னஞ்சல்",
        "form.password": "கடவுச்சொல்",
        "demo.guest-option": "அல்லது பதிவு இல்லாமல் விருந்தினராக ஆராயுங்கள்",
        "form.email-label": "📧 மின்னஞ்சல் முகவரி",
        "form.password-label": "🔒 கடவுச்சொல்",
        "auth.forgot-password": "கடவுச்சொல்லை மறந்துவிட்டீர்களா?",
        "auth.login-button": "சாகசத்தைத் தொடங்கு",
        "ui.or": "அல்லது",
        "auth.guest-access": "விருந்தினர் அணுகல்",
        "auth.signup-prompt": "கணக்கு இல்லையா?",
        "auth.signup-link": "இங்கே பதிவு செய்யுங்கள்",
        "notify.version-selected": "பதிப்பு தேர்ந்தெடுக்கப்பட்டது",
        "notify.version-configured": "கட்டமைக்கப்பட்டது",
        "notify.credentials-loaded": "சான்றுகள் ஏற்றப்பட்டன",
        "notify.credentials-filled": "டெமோ தரவு நிரப்பப்பட்டது",
        "error.fill-all-fields": "அனைத்து புலங்களையும் நிரப்பவும்.",
        "error.invalid-credentials": "தேர்ந்தெடுக்கப்பட்ட பதிப்புக்கு தவறான சான்றுகள்.",
        "error.wrong-version": "இந்த மின்னஞ்சல் {version} பதிப்புக்கானது. சரியான பதிப்பைத் தேர்ந்தெடுக்கவும்.",
        "login.redirecting-student": "🐆 வரவேற்கிறோம்! மாணவர் பலகத்திற்கு திருப்பி அனுப்பப்படுகிறது...",
        "login.redirecting-teacher": "👨‍🏫 வரவேற்கிறோம்! ஆசிரியர் பலகத்திற்கு திருப்பி அனுப்பப்படுகிறது...",
        "guest.accessing": "🌟 விருந்தினராக அணுகப்படுகிறது...",
        "session.active-redirecting": "🐆 செயலில் உள்ள அமர்வு கண்டறியப்பட்டது. திருப்பி அனுப்பப்படுகிறது...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "உங்கள் கடவுச்சொல்"
    },
    "te": {
        "nav.back": "← వెనుకకు",
        "ui.auto-detect": "స్వయంచాలక",
        "ui.select-language": "భాషను ఎంచుకోండి",
        "auth.welcome": "స్వాగతం!",
        "auth.subtitle": "Yaguará తో కొలంబియన్ పర్యావరణ వ్యవస్థలలో మీ సాహసాన్ని కొనసాగించండి",
        "ui.lang-detected": "🌍 భాష స్వయంచాలకంగా గుర్తించబడింది",
        "ui.lang-suggestion": "💡 మీ మాతృభాషలో కొనసాగించాలనుకుంటున్నారా?",
        "version.title": "🎯 Yaguará తో మీ నేర్చుకునే మార్గాన్ని ఎంచుకోండి",
        "version.individual-title": "వ్యక్తిగత ప్రయాణం",
        "version.individual-desc": "Yaguará తో కొలంబియాలో వ్యక్తిగత సాహసం",
        "version.classroom-title": "తరగతి గది ఎడిషన్",
        "version.classroom-desc": "విద్యావేత్తలకు నిర్మాణాత్మక అభ్యసనం",
        "registration.pref-title": "📚 మీ ఇష్టమైన అభ్యసన భాషను ఎంచుకోండి",
        "demo.title": "🎯 డెమో యాక్సెస్",
        "form.email": "ఇమెయిల్",
        "form.password": "పాస్‌వర్డ్",
        "demo.guest-option": "లేదా నమోదు లేకుండా అతిథిగా అన్వేషించండి",
        "form.email-label": "📧 ఇమెయిల్ చిరునామా",
        "form.password-label": "🔒 పాస్‌వర్డ్",
        "auth.forgot-password": "పాస్‌వర్డ్ మర్చిపోయారా?",
        "auth.login-button": "సాహసం ప్రారంభించు",
        "ui.or": "లేదా",
        "auth.guest-access": "అతిథి ప్రవేశం",
        "auth.signup-prompt": "ఖాతా లేదా?",
        "auth.signup-link": "ఇక్కడ సైన్ అప్ చేయండి",
        "notify.version-selected": "వెర్షన్ ఎంచుకోబడింది",
        "notify.version-configured": "కాన్ఫిగర్ చేయబడింది",
        "notify.credentials-loaded": "ఆధారాలు లోడ్ అయ్యాయి",
        "notify.credentials-filled": "డెమో డేటా నింపబడింది",
        "error.fill-all-fields": "దయచేసి అన్ని ఫీల్డ్‌లను నింపండి.",
        "error.invalid-credentials": "ఎంచుకున్న వెర్షన్‌కు చెల్లని ఆధారాలు.",
        "error.wrong-version": "ఈ ఇమెయిల్ {version} వెర్షన్ కోసం. దయచేసి సరైన వెర్షన్‌ను ఎంచుకోండి.",
        "login.redirecting-student": "🐆 స్వాగతం! విద్యార్థి ప్యానెల్‌కు మళ్ళించబడుతోంది...",
        "login.redirecting-teacher": "👨‍🏫 స్వాగతం! ఉపాధ్యాయ ప్యానెల్‌కు మళ్ళించబడుతోంది...",
        "guest.accessing": "🌟 అతిథిగా ప్రవేశిస్తోంది...",
        "session.active-redirecting": "🐆 క్రియాశీల సెషన్ గుర్తించబడింది. మళ్ళించబడుతోంది...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "మీ పాస్‌వర్డ్"
    },
    "mr": {
        "nav.back": "← Back",
        "ui.auto-detect": "Auto",
        "ui.select-language": "Select Language",
        "auth.welcome": "Welcome!",
        "auth.subtitle": "Continue your adventure with Yaguará through Colombian ecosystems",
        "ui.lang-detected": "🌍 Language detected automatically",
        "ui.lang-suggestion": "💡 Would you prefer to continue in your native language?",
        "version.title": "🎯 Choose your learning path with Yaguará",
        "version.individual-title": "Individual Journey",
        "version.individual-desc": "Personal adventure with Yaguará through Colombia",
        "version.classroom-title": "Classroom Edition",
        "version.classroom-desc": "Structured learning for educators",
        "registration.pref-title": "📚 Select your preferred learning language",
        "demo.title": "🎯 Demo Access",
        "form.email": "Email",
        "form.password": "Password",
        "demo.guest-option": "Or explore as a guest without registration",
        "form.email-label": "📧 Email Address",
        "form.password-label": "🔒 Password",
        "auth.forgot-password": "Forgot your password?",
        "auth.login-button": "Start Adventure",
        "ui.or": "or",
        "auth.guest-access": "Guest Access",
        "auth.signup-prompt": "Don't have an account?",
        "auth.signup-link": "Sign up here",
        "notify.version-selected": "Version Selected",
        "notify.version-configured": "configured",
        "notify.credentials-loaded": "Credentials Loaded",
        "notify.credentials-filled": "Demo data filled",
        "error.fill-all-fields": "Please fill in all fields.",
        "error.invalid-credentials": "Invalid credentials for the selected version.",
        "error.wrong-version": "This email is for the {version} version. Please select the correct version.",
        "login.redirecting-student": "🐆 Welcome! Redirecting to student panel...",
        "login.redirecting-teacher": "👨‍🏫 Welcome! Redirecting to teacher panel...",
        "guest.accessing": "🌟 Accessing as guest...",
        "session.active-redirecting": "🐆 Active session detected. Redirecting...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "Your password"
    },
    "gu": {
        "nav.back": "← Back",
        "ui.auto-detect": "Auto",
        "ui.select-language": "Select Language",
        "auth.welcome": "Welcome!",
        "auth.subtitle": "Continue your adventure with Yaguará through Colombian ecosystems",
        "ui.lang-detected": "🌍 Language detected automatically",
        "ui.lang-suggestion": "💡 Would you prefer to continue in your native language?",
        "version.title": "🎯 Choose your learning path with Yaguará",
        "version.individual-title": "Individual Journey",
        "version.individual-desc": "Personal adventure with Yaguará through Colombia",
        "version.classroom-title": "Classroom Edition",
        "version.classroom-desc": "Structured learning for educators",
        "registration.pref-title": "📚 Select your preferred learning language",
        "demo.title": "🎯 Demo Access",
        "form.email": "Email",
        "form.password": "Password",
        "demo.guest-option": "Or explore as a guest without registration",
        "form.email-label": "📧 Email Address",
        "form.password-label": "🔒 Password",
        "auth.forgot-password": "Forgot your password?",
        "auth.login-button": "Start Adventure",
        "ui.or": "or",
        "auth.guest-access": "Guest Access",
        "auth.signup-prompt": "Don't have an account?",
        "auth.signup-link": "Sign up here",
        "notify.version-selected": "Version Selected",
        "notify.version-configured": "configured",
        "notify.credentials-loaded": "Credentials Loaded",
        "notify.credentials-filled": "Demo data filled",
        "error.fill-all-fields": "Please fill in all fields.",
        "error.invalid-credentials": "Invalid credentials for the selected version.",
        "error.wrong-version": "This email is for the {version} version. Please select the correct version.",
        "login.redirecting-student": "🐆 Welcome! Redirecting to student panel...",
        "login.redirecting-teacher": "👨‍🏫 Welcome! Redirecting to teacher panel...",
        "guest.accessing": "🌟 Accessing as guest...",
        "session.active-redirecting": "🐆 Active session detected. Redirecting...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "Your password"
    },
    "kn": {
        "nav.back": "← Back",
        "ui.auto-detect": "Auto",
        "ui.select-language": "Select Language",
        "auth.welcome": "Welcome!",
        "auth.subtitle": "Continue your adventure with Yaguará through Colombian ecosystems",
        "ui.lang-detected": "🌍 Language detected automatically",
        "ui.lang-suggestion": "💡 Would you prefer to continue in your native language?",
        "version.title": "🎯 Choose your learning path with Yaguará",
        "version.individual-title": "Individual Journey",
        "version.individual-desc": "Personal adventure with Yaguará through Colombia",
        "version.classroom-title": "Classroom Edition",
        "version.classroom-desc": "Structured learning for educators",
        "registration.pref-title": "📚 Select your preferred learning language",
        "demo.title": "🎯 Demo Access",
        "form.email": "Email",
        "form.password": "Password",
        "demo.guest-option": "Or explore as a guest without registration",
        "form.email-label": "📧 Email Address",
        "form.password-label": "🔒 Password",
        "auth.forgot-password": "Forgot your password?",
        "auth.login-button": "Start Adventure",
        "ui.or": "or",
        "auth.guest-access": "Guest Access",
        "auth.signup-prompt": "Don't have an account?",
        "auth.signup-link": "Sign up here",
        "notify.version-selected": "Version Selected",
        "notify.version-configured": "configured",
        "notify.credentials-loaded": "Credentials Loaded",
        "notify.credentials-filled": "Demo data filled",
        "error.fill-all-fields": "Please fill in all fields.",
        "error.invalid-credentials": "Invalid credentials for the selected version.",
        "error.wrong-version": "This email is for the {version} version. Please select the correct version.",
        "login.redirecting-student": "🐆 Welcome! Redirecting to student panel...",
        "login.redirecting-teacher": "👨‍🏫 Welcome! Redirecting to teacher panel...",
        "guest.accessing": "🌟 Accessing as guest...",
        "session.active-redirecting": "🐆 Active session detected. Redirecting...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "Your password"
    },
    "ml": {
        "nav.back": "← Back",
        "ui.auto-detect": "Auto",
        "ui.select-language": "Select Language",
        "auth.welcome": "Welcome!",
        "auth.subtitle": "Continue your adventure with Yaguará through Colombian ecosystems",
        "ui.lang-detected": "🌍 Language detected automatically",
        "ui.lang-suggestion": "💡 Would you prefer to continue in your native language?",
        "version.title": "🎯 Choose your learning path with Yaguará",
        "version.individual-title": "Individual Journey",
        "version.individual-desc": "Personal adventure with Yaguará through Colombia",
        "version.classroom-title": "Classroom Edition",
        "version.classroom-desc": "Structured learning for educators",
        "registration.pref-title": "📚 Select your preferred learning language",
        "demo.title": "🎯 Demo Access",
        "form.email": "Email",
        "form.password": "Password",
        "demo.guest-option": "Or explore as a guest without registration",
        "form.email-label": "📧 Email Address",
        "form.password-label": "🔒 Password",
        "auth.forgot-password": "Forgot your password?",
        "auth.login-button": "Start Adventure",
        "ui.or": "or",
        "auth.guest-access": "Guest Access",
        "auth.signup-prompt": "Don't have an account?",
        "auth.signup-link": "Sign up here",
        "notify.version-selected": "Version Selected",
        "notify.version-configured": "configured",
        "notify.credentials-loaded": "Credentials Loaded",
        "notify.credentials-filled": "Demo data filled",
        "error.fill-all-fields": "Please fill in all fields.",
        "error.invalid-credentials": "Invalid credentials for the selected version.",
        "error.wrong-version": "This email is for the {version} version. Please select the correct version.",
        "login.redirecting-student": "🐆 Welcome! Redirecting to student panel...",
        "login.redirecting-teacher": "👨‍🏫 Welcome! Redirecting to teacher panel...",
        "guest.accessing": "🌟 Accessing as guest...",
        "session.active-redirecting": "🐆 Active session detected. Redirecting...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "Your password"
    },
    "pa": {
        "nav.back": "← Back",
        "ui.auto-detect": "Auto",
        "ui.select-language": "Select Language",
        "auth.welcome": "Welcome!",
        "auth.subtitle": "Continue your adventure with Yaguará through Colombian ecosystems",
        "ui.lang-detected": "🌍 Language detected automatically",
        "ui.lang-suggestion": "💡 Would you prefer to continue in your native language?",
        "version.title": "🎯 Choose your learning path with Yaguará",
        "version.individual-title": "Individual Journey",
        "version.individual-desc": "Personal adventure with Yaguará through Colombia",
        "version.classroom-title": "Classroom Edition",
        "version.classroom-desc": "Structured learning for educators",
        "registration.pref-title": "📚 Select your preferred learning language",
        "demo.title": "🎯 Demo Access",
        "form.email": "Email",
        "form.password": "Password",
        "demo.guest-option": "Or explore as a guest without registration",
        "form.email-label": "📧 Email Address",
        "form.password-label": "🔒 Password",
        "auth.forgot-password": "Forgot your password?",
        "auth.login-button": "Start Adventure",
        "ui.or": "or",
        "auth.guest-access": "Guest Access",
        "auth.signup-prompt": "Don't have an account?",
        "auth.signup-link": "Sign up here",
        "notify.version-selected": "Version Selected",
        "notify.version-configured": "configured",
        "notify.credentials-loaded": "Credentials Loaded",
        "notify.credentials-filled": "Demo data filled",
        "error.fill-all-fields": "Please fill in all fields.",
        "error.invalid-credentials": "Invalid credentials for the selected version.",
        "error.wrong-version": "This email is for the {version} version. Please select the correct version.",
        "login.redirecting-student": "🐆 Welcome! Redirecting to student panel...",
        "login.redirecting-teacher": "👨‍🏫 Welcome! Redirecting to teacher panel...",
        "guest.accessing": "🌟 Accessing as guest...",
        "session.active-redirecting": "🐆 Active session detected. Redirecting...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "Your password"
    },
    "or": {
        "nav.back": "← Back",
        "ui.auto-detect": "Auto",
        "ui.select-language": "Select Language",
        "auth.welcome": "Welcome!",
        "auth.subtitle": "Continue your adventure with Yaguará through Colombian ecosystems",
        "ui.lang-detected": "🌍 Language detected automatically",
        "ui.lang-suggestion": "💡 Would you prefer to continue in your native language?",
        "version.title": "🎯 Choose your learning path with Yaguará",
        "version.individual-title": "Individual Journey",
        "version.individual-desc": "Personal adventure with Yaguará through Colombia",
        "version.classroom-title": "Classroom Edition",
        "version.classroom-desc": "Structured learning for educators",
        "registration.pref-title": "📚 Select your preferred learning language",
        "demo.title": "🎯 Demo Access",
        "form.email": "Email",
        "form.password": "Password",
        "demo.guest-option": "Or explore as a guest without registration",
        "form.email-label": "📧 Email Address",
        "form.password-label": "🔒 Password",
        "auth.forgot-password": "Forgot your password?",
        "auth.login-button": "Start Adventure",
        "ui.or": "or",
        "auth.guest-access": "Guest Access",
        "auth.signup-prompt": "Don't have an account?",
        "auth.signup-link": "Sign up here",
        "notify.version-selected": "Version Selected",
        "notify.version-configured": "configured",
        "notify.credentials-loaded": "Credentials Loaded",
        "notify.credentials-filled": "Demo data filled",
        "error.fill-all-fields": "Please fill in all fields.",
        "error.invalid-credentials": "Invalid credentials for the selected version.",
        "error.wrong-version": "This email is for the {version} version. Please select the correct version.",
        "login.redirecting-student": "🐆 Welcome! Redirecting to student panel...",
        "login.redirecting-teacher": "👨‍🏫 Welcome! Redirecting to teacher panel...",
        "guest.accessing": "🌟 Accessing as guest...",
        "session.active-redirecting": "🐆 Active session detected. Redirecting...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "Your password"
    },
    "si": {
        "nav.back": "← Back",
        "ui.auto-detect": "Auto",
        "ui.select-language": "Select Language",
        "auth.welcome": "Welcome!",
        "auth.subtitle": "Continue your adventure with Yaguará through Colombian ecosystems",
        "ui.lang-detected": "🌍 Language detected automatically",
        "ui.lang-suggestion": "💡 Would you prefer to continue in your native language?",
        "version.title": "🎯 Choose your learning path with Yaguará",
        "version.individual-title": "Individual Journey",
        "version.individual-desc": "Personal adventure with Yaguará through Colombia",
        "version.classroom-title": "Classroom Edition",
        "version.classroom-desc": "Structured learning for educators",
        "registration.pref-title": "📚 Select your preferred learning language",
        "demo.title": "🎯 Demo Access",
        "form.email": "Email",
        "form.password": "Password",
        "demo.guest-option": "Or explore as a guest without registration",
        "form.email-label": "📧 Email Address",
        "form.password-label": "🔒 Password",
        "auth.forgot-password": "Forgot your password?",
        "auth.login-button": "Start Adventure",
        "ui.or": "or",
        "auth.guest-access": "Guest Access",
        "auth.signup-prompt": "Don't have an account?",
        "auth.signup-link": "Sign up here",
        "notify.version-selected": "Version Selected",
        "notify.version-configured": "configured",
        "notify.credentials-loaded": "Credentials Loaded",
        "notify.credentials-filled": "Demo data filled",
        "error.fill-all-fields": "Please fill in all fields.",
        "error.invalid-credentials": "Invalid credentials for the selected version.",
        "error.wrong-version": "This email is for the {version} version. Please select the correct version.",
        "login.redirecting-student": "🐆 Welcome! Redirecting to student panel...",
        "login.redirecting-teacher": "👨‍🏫 Welcome! Redirecting to teacher panel...",
        "guest.accessing": "🌟 Accessing as guest...",
        "session.active-redirecting": "🐆 Active session detected. Redirecting...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "Your password"
    },
    "ne": {
        "nav.back": "← Back",
        "ui.auto-detect": "Auto",
        "ui.select-language": "Select Language",
        "auth.welcome": "Welcome!",
        "auth.subtitle": "Continue your adventure with Yaguará through Colombian ecosystems",
        "ui.lang-detected": "🌍 Language detected automatically",
        "ui.lang-suggestion": "💡 Would you prefer to continue in your native language?",
        "version.title": "🎯 Choose your learning path with Yaguará",
        "version.individual-title": "Individual Journey",
        "version.individual-desc": "Personal adventure with Yaguará through Colombia",
        "version.classroom-title": "Classroom Edition",
        "version.classroom-desc": "Structured learning for educators",
        "registration.pref-title": "📚 Select your preferred learning language",
        "demo.title": "🎯 Demo Access",
        "form.email": "Email",
        "form.password": "Password",
        "demo.guest-option": "Or explore as a guest without registration",
        "form.email-label": "📧 Email Address",
        "form.password-label": "🔒 Password",
        "auth.forgot-password": "Forgot your password?",
        "auth.login-button": "Start Adventure",
        "ui.or": "or",
        "auth.guest-access": "Guest Access",
        "auth.signup-prompt": "Don't have an account?",
        "auth.signup-link": "Sign up here",
        "notify.version-selected": "Version Selected",
        "notify.version-configured": "configured",
        "notify.credentials-loaded": "Credentials Loaded",
        "notify.credentials-filled": "Demo data filled",
        "error.fill-all-fields": "Please fill in all fields.",
        "error.invalid-credentials": "Invalid credentials for the selected version.",
        "error.wrong-version": "This email is for the {version} version. Please select the correct version.",
        "login.redirecting-student": "🐆 Welcome! Redirecting to student panel...",
        "login.redirecting-teacher": "👨‍🏫 Welcome! Redirecting to teacher panel...",
        "guest.accessing": "🌟 Accessing as guest...",
        "session.active-redirecting": "🐆 Active session detected. Redirecting...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "Your password"
    },
    "th": {
        "nav.back": "← ย้อนกลับ",
        "ui.auto-detect": "อัตโนมัติ",
        "ui.select-language": "เลือกภาษา",
        "auth.welcome": "ยินดีต้อนรับ!",
        "auth.subtitle": "ดำเนินการผจญภัยกับ Yaguará ผ่านระบบนิเวศของโคลอมเบีย",
        "ui.lang-detected": "🌍 ตรวจพบภาษาโดยอัตโนมัติ",
        "ui.lang-suggestion": "💡 คุณต้องการดำเนินการต่อในภาษาแม่ของคุณหรือไม่?",
        "version.title": "🎯 เลือกเส้นทางการเรียนรู้กับ Yaguará",
        "version.individual-title": "การเดินทางส่วนบุคคล",
        "version.individual-desc": "การผจญภัยส่วนตัวกับ Yaguará ผ่านโคลอมเบีย",
        "version.classroom-title": "รุ่นห้องเรียน",
        "version.classroom-desc": "การเรียนรู้ที่มีโครงสร้างสำหรับนักการศึกษา",
        "registration.pref-title": "📚 เลือกภาษาเรียนรู้ที่คุณต้องการ",
        "demo.title": "🎯 เข้าถึงเดโม",
        "form.email": "อีเมล",
        "form.password": "รหัสผ่าน",
        "demo.guest-option": "หรือสำรวจในฐานะแขกโดยไม่ต้องลงทะเบียน",
        "form.email-label": "📧 ที่อยู่อีเมล",
        "form.password-label": "🔒 รหัสผ่าน",
        "auth.forgot-password": "ลืมรหัสผ่าน?",
        "auth.login-button": "เริ่มการผจญภัย",
        "ui.or": "หรือ",
        "auth.guest-access": "เข้าใช้งานในฐานะแขก",
        "auth.signup-prompt": "ยังไม่มีบัญชี?",
        "auth.signup-link": "สมัครที่นี่",
        "notify.version-selected": "เลือกเวอร์ชันแล้ว",
        "notify.version-configured": "กำหนดค่าแล้ว",
        "notify.credentials-loaded": "โหลดข้อมูลรับรองแล้ว",
        "notify.credentials-filled": "กรอกข้อมูลเดโมแล้ว",
        "error.fill-all-fields": "กรุณากรอกข้อมูลให้ครบทุกช่อง",
        "error.invalid-credentials": "ข้อมูลรับรองไม่ถูกต้องสำหรับเวอร์ชันที่เลือก",
        "error.wrong-version": "อีเมลนี้ใช้สำหรับเวอร์ชัน {version} กรุณาเลือกเวอร์ชันที่ถูกต้อง",
        "login.redirecting-student": "🐆 ยินดีต้อนรับ! กำลังเปลี่ยนเส้นทางไปยังแผงนักเรียน...",
        "login.redirecting-teacher": "👨‍🏫 ยินดีต้อนรับ! กำลังเปลี่ยนเส้นทางไปยังแผงครู...",
        "guest.accessing": "🌟 กำลังเข้าใช้งานในฐานะแขก...",
        "session.active-redirecting": "🐆 ตรวจพบเซสชันที่ใช้งานอยู่ กำลังเปลี่ยนเส้นทาง...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "รหัสผ่านของคุณ"
    },
    "vi": {
        "nav.back": "← Quay lại",
        "ui.auto-detect": "Tự động",
        "ui.select-language": "Chọn ngôn ngữ",
        "auth.welcome": "Chào mừng!",
        "auth.subtitle": "Tiếp tục cuộc phiêu lưu với Yaguará qua các hệ sinh thái Colombia",
        "ui.lang-detected": "🌍 Ngôn ngữ được phát hiện tự động",
        "ui.lang-suggestion": "💡 Bạn có muốn tiếp tục bằng tiếng mẹ đẻ không?",
        "version.title": "🎯 Chọn lộ trình học tập với Yaguará",
        "version.individual-title": "Hành trình cá nhân",
        "version.individual-desc": "Phiêu lưu cá nhân với Yaguará qua Colombia",
        "version.classroom-title": "Phiên bản lớp học",
        "version.classroom-desc": "Học tập có cấu trúc cho giáo viên",
        "registration.pref-title": "📚 Chọn ngôn ngữ học tập ưa thích",
        "demo.title": "🎯 Truy cập Demo",
        "form.email": "Email",
        "form.password": "Mật khẩu",
        "demo.guest-option": "Hoặc khám phá với tư cách khách mà không cần đăng ký",
        "form.email-label": "📧 Địa chỉ Email",
        "form.password-label": "🔒 Mật khẩu",
        "auth.forgot-password": "Quên mật khẩu?",
        "auth.login-button": "Bắt đầu phiêu lưu",
        "ui.or": "hoặc",
        "auth.guest-access": "Truy cập khách",
        "auth.signup-prompt": "Chưa có tài khoản?",
        "auth.signup-link": "Đăng ký tại đây",
        "notify.version-selected": "Đã chọn phiên bản",
        "notify.version-configured": "đã cấu hình",
        "notify.credentials-loaded": "Đã tải thông tin đăng nhập",
        "notify.credentials-filled": "Đã điền dữ liệu demo",
        "error.fill-all-fields": "Vui lòng điền tất cả các trường.",
        "error.invalid-credentials": "Thông tin đăng nhập không hợp lệ cho phiên bản đã chọn.",
        "error.wrong-version": "Email này dành cho phiên bản {version}. Vui lòng chọn phiên bản đúng.",
        "login.redirecting-student": "🐆 Chào mừng! Đang chuyển hướng đến bảng điều khiển học sinh...",
        "login.redirecting-teacher": "👨‍🏫 Chào mừng! Đang chuyển hướng đến bảng điều khiển giáo viên...",
        "guest.accessing": "🌟 Đang truy cập với tư cách khách...",
        "session.active-redirecting": "🐆 Phát hiện phiên đang hoạt động. Đang chuyển hướng...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "Mật khẩu của bạn"
    },
    "id": {
        "nav.back": "← Kembali",
        "ui.auto-detect": "Otomatis",
        "ui.select-language": "Pilih Bahasa",
        "auth.welcome": "Selamat Datang!",
        "auth.subtitle": "Lanjutkan petualangan Anda bersama Yaguará melalui ekosistem Kolombia",
        "ui.lang-detected": "🌍 Bahasa terdeteksi otomatis",
        "ui.lang-suggestion": "💡 Apakah Anda ingin melanjutkan dalam bahasa ibu Anda?",
        "version.title": "🎯 Pilih jalur belajar Anda bersama Yaguará",
        "version.individual-title": "Perjalanan Individual",
        "version.individual-desc": "Petualangan pribadi bersama Yaguará melalui Kolombia",
        "version.classroom-title": "Edisi Kelas",
        "version.classroom-desc": "Pembelajaran terstruktur untuk pendidik",
        "registration.pref-title": "📚 Pilih bahasa belajar yang Anda sukai",
        "demo.title": "🎯 Akses Demo",
        "form.email": "Email",
        "form.password": "Kata Sandi",
        "demo.guest-option": "Atau jelajahi sebagai tamu tanpa registrasi",
        "form.email-label": "📧 Alamat Email",
        "form.password-label": "🔒 Kata Sandi",
        "auth.forgot-password": "Lupa kata sandi?",
        "auth.login-button": "Mulai Petualangan",
        "ui.or": "atau",
        "auth.guest-access": "Akses Tamu",
        "auth.signup-prompt": "Belum punya akun?",
        "auth.signup-link": "Daftar di sini",
        "notify.version-selected": "Versi Dipilih",
        "notify.version-configured": "dikonfigurasi",
        "notify.credentials-loaded": "Kredensial Dimuat",
        "notify.credentials-filled": "Data demo terisi",
        "error.fill-all-fields": "Harap isi semua bidang.",
        "error.invalid-credentials": "Kredensial tidak valid untuk versi yang dipilih.",
        "error.wrong-version": "Email ini untuk versi {version}. Silakan pilih versi yang benar.",
        "login.redirecting-student": "🐆 Selamat Datang! Mengalihkan ke panel siswa...",
        "login.redirecting-teacher": "👨‍🏫 Selamat Datang! Mengalihkan ke panel guru...",
        "guest.accessing": "🌟 Mengakses sebagai tamu...",
        "session.active-redirecting": "🐆 Sesi aktif terdeteksi. Mengalihkan...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "Kata sandi Anda"
    },
    "ms": {
        "nav.back": "← Kembali",
        "ui.auto-detect": "Auto",
        "ui.select-language": "Pilih Bahasa",
        "auth.welcome": "Selamat Datang!",
        "auth.subtitle": "Teruskan pengembaraan anda bersama Yaguará melalui ekosistem Colombia",
        "ui.lang-detected": "🌍 Bahasa dikesan secara automatik",
        "ui.lang-suggestion": "💡 Adakah anda ingin meneruskan dalam bahasa ibunda anda?",
        "version.title": "🎯 Pilih laluan pembelajaran anda bersama Yaguará",
        "version.individual-title": "Perjalanan Individu",
        "version.individual-desc": "Pengembaraan peribadi bersama Yaguará melalui Colombia",
        "version.classroom-title": "Edisi Bilik Darjah",
        "version.classroom-desc": "Pembelajaran berstruktur untuk pendidik",
        "registration.pref-title": "📚 Pilih bahasa pembelajaran pilihan anda",
        "demo.title": "🎯 Akses Demo",
        "form.email": "Emel",
        "form.password": "Kata Laluan",
        "demo.guest-option": "Atau teroka sebagai tetamu tanpa pendaftaran",
        "form.email-label": "📧 Alamat Emel",
        "form.password-label": "🔒 Kata Laluan",
        "auth.forgot-password": "Lupa kata laluan?",
        "auth.login-button": "Mulakan Pengembaraan",
        "ui.or": "atau",
        "auth.guest-access": "Akses Tetamu",
        "auth.signup-prompt": "Tiada akaun?",
        "auth.signup-link": "Daftar di sini",
        "notify.version-selected": "Versi Dipilih",
        "notify.version-configured": "dikonfigurasi",
        "notify.credentials-loaded": "Kelayakan Dimuatkan",
        "notify.credentials-filled": "Data demo diisi",
        "error.fill-all-fields": "Sila isi semua medan.",
        "error.invalid-credentials": "Kelayakan tidak sah untuk versi yang dipilih.",
        "error.wrong-version": "Emel ini untuk versi {version}. Sila pilih versi yang betul.",
        "login.redirecting-student": "🐆 Selamat Datang! Mengalihkan ke panel pelajar...",
        "login.redirecting-teacher": "👨‍🏫 Selamat Datang! Mengalihkan ke panel guru...",
        "guest.accessing": "🌟 Mengakses sebagai tetamu...",
        "session.active-redirecting": "🐆 Sesi aktif dikesan. Mengalihkan...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "Kata laluan anda"
    },
    "tl": {
        "nav.back": "← Bumalik",
        "ui.auto-detect": "Auto",
        "ui.select-language": "Pumili ng Wika",
        "auth.welcome": "Maligayang Pagdating!",
        "auth.subtitle": "Ipagpatuloy ang iyong pakikipagsapalaran kasama si Yaguará sa mga ekosistema ng Colombia",
        "ui.lang-detected": "🌍 Awtomatikong nakita ang wika",
        "ui.lang-suggestion": "💡 Gusto mo bang magpatuloy sa iyong katutubong wika?",
        "version.title": "🎯 Pumili ng landas ng pag-aaral kasama si Yaguará",
        "version.individual-title": "Indibidwal na Paglalakbay",
        "version.individual-desc": "Personal na pakikipagsapalaran kasama si Yaguará sa Colombia",
        "version.classroom-title": "Edisyon ng Silid-aralan",
        "version.classroom-desc": "Estrukturadong pag-aaral para sa mga guro",
        "registration.pref-title": "📚 Pumili ng gusto mong wika ng pag-aaral",
        "demo.title": "🎯 Demo Access",
        "form.email": "Email",
        "form.password": "Password",
        "demo.guest-option": "O mag-explore bilang bisita nang walang rehistrasyon",
        "form.email-label": "📧 Email Address",
        "form.password-label": "🔒 Password",
        "auth.forgot-password": "Nakalimutan ang password?",
        "auth.login-button": "Simulan ang Pakikipagsapalaran",
        "ui.or": "o",
        "auth.guest-access": "Bisita Access",
        "auth.signup-prompt": "Walang account?",
        "auth.signup-link": "Mag-sign up dito",
        "notify.version-selected": "Napili ang Bersyon",
        "notify.version-configured": "naka-configure",
        "notify.credentials-loaded": "Nai-load ang Kredensyal",
        "notify.credentials-filled": "Napunan ang demo data",
        "error.fill-all-fields": "Mangyaring punan ang lahat ng field.",
        "error.invalid-credentials": "Hindi wastong kredensyal para sa napiling bersyon.",
        "error.wrong-version": "Ang email na ito ay para sa bersyong {version}. Mangyaring piliin ang tamang bersyon.",
        "login.redirecting-student": "🐆 Maligayang Pagdating! Nire-redirect sa panel ng mag-aaral...",
        "login.redirecting-teacher": "👨‍🏫 Maligayang Pagdating! Nire-redirect sa panel ng guro...",
        "guest.accessing": "🌟 Ina-access bilang bisita...",
        "session.active-redirecting": "🐆 May aktibong session. Nire-redirect...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "Iyong password"
    },
    "my": {
        "nav.back": "← Back",
        "ui.auto-detect": "Auto",
        "ui.select-language": "Select Language",
        "auth.welcome": "Welcome!",
        "auth.subtitle": "Continue your adventure with Yaguará through Colombian ecosystems",
        "ui.lang-detected": "🌍 Language detected automatically",
        "ui.lang-suggestion": "💡 Would you prefer to continue in your native language?",
        "version.title": "🎯 Choose your learning path with Yaguará",
        "version.individual-title": "Individual Journey",
        "version.individual-desc": "Personal adventure with Yaguará through Colombia",
        "version.classroom-title": "Classroom Edition",
        "version.classroom-desc": "Structured learning for educators",
        "registration.pref-title": "📚 Select your preferred learning language",
        "demo.title": "🎯 Demo Access",
        "form.email": "Email",
        "form.password": "Password",
        "demo.guest-option": "Or explore as a guest without registration",
        "form.email-label": "📧 Email Address",
        "form.password-label": "🔒 Password",
        "auth.forgot-password": "Forgot your password?",
        "auth.login-button": "Start Adventure",
        "ui.or": "or",
        "auth.guest-access": "Guest Access",
        "auth.signup-prompt": "Don't have an account?",
        "auth.signup-link": "Sign up here",
        "notify.version-selected": "Version Selected",
        "notify.version-configured": "configured",
        "notify.credentials-loaded": "Credentials Loaded",
        "notify.credentials-filled": "Demo data filled",
        "error.fill-all-fields": "Please fill in all fields.",
        "error.invalid-credentials": "Invalid credentials for the selected version.",
        "error.wrong-version": "This email is for the {version} version. Please select the correct version.",
        "login.redirecting-student": "🐆 Welcome! Redirecting to student panel...",
        "login.redirecting-teacher": "👨‍🏫 Welcome! Redirecting to teacher panel...",
        "guest.accessing": "🌟 Accessing as guest...",
        "session.active-redirecting": "🐆 Active session detected. Redirecting...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "Your password"
    },
    "km": {
        "nav.back": "← Back",
        "ui.auto-detect": "Auto",
        "ui.select-language": "Select Language",
        "auth.welcome": "Welcome!",
        "auth.subtitle": "Continue your adventure with Yaguará through Colombian ecosystems",
        "ui.lang-detected": "🌍 Language detected automatically",
        "ui.lang-suggestion": "💡 Would you prefer to continue in your native language?",
        "version.title": "🎯 Choose your learning path with Yaguará",
        "version.individual-title": "Individual Journey",
        "version.individual-desc": "Personal adventure with Yaguará through Colombia",
        "version.classroom-title": "Classroom Edition",
        "version.classroom-desc": "Structured learning for educators",
        "registration.pref-title": "📚 Select your preferred learning language",
        "demo.title": "🎯 Demo Access",
        "form.email": "Email",
        "form.password": "Password",
        "demo.guest-option": "Or explore as a guest without registration",
        "form.email-label": "📧 Email Address",
        "form.password-label": "🔒 Password",
        "auth.forgot-password": "Forgot your password?",
        "auth.login-button": "Start Adventure",
        "ui.or": "or",
        "auth.guest-access": "Guest Access",
        "auth.signup-prompt": "Don't have an account?",
        "auth.signup-link": "Sign up here",
        "notify.version-selected": "Version Selected",
        "notify.version-configured": "configured",
        "notify.credentials-loaded": "Credentials Loaded",
        "notify.credentials-filled": "Demo data filled",
        "error.fill-all-fields": "Please fill in all fields.",
        "error.invalid-credentials": "Invalid credentials for the selected version.",
        "error.wrong-version": "This email is for the {version} version. Please select the correct version.",
        "login.redirecting-student": "🐆 Welcome! Redirecting to student panel...",
        "login.redirecting-teacher": "👨‍🏫 Welcome! Redirecting to teacher panel...",
        "guest.accessing": "🌟 Accessing as guest...",
        "session.active-redirecting": "🐆 Active session detected. Redirecting...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "Your password"
    },
    "lo": {
        "nav.back": "← Back",
        "ui.auto-detect": "Auto",
        "ui.select-language": "Select Language",
        "auth.welcome": "Welcome!",
        "auth.subtitle": "Continue your adventure with Yaguará through Colombian ecosystems",
        "ui.lang-detected": "🌍 Language detected automatically",
        "ui.lang-suggestion": "💡 Would you prefer to continue in your native language?",
        "version.title": "🎯 Choose your learning path with Yaguará",
        "version.individual-title": "Individual Journey",
        "version.individual-desc": "Personal adventure with Yaguará through Colombia",
        "version.classroom-title": "Classroom Edition",
        "version.classroom-desc": "Structured learning for educators",
        "registration.pref-title": "📚 Select your preferred learning language",
        "demo.title": "🎯 Demo Access",
        "form.email": "Email",
        "form.password": "Password",
        "demo.guest-option": "Or explore as a guest without registration",
        "form.email-label": "📧 Email Address",
        "form.password-label": "🔒 Password",
        "auth.forgot-password": "Forgot your password?",
        "auth.login-button": "Start Adventure",
        "ui.or": "or",
        "auth.guest-access": "Guest Access",
        "auth.signup-prompt": "Don't have an account?",
        "auth.signup-link": "Sign up here",
        "notify.version-selected": "Version Selected",
        "notify.version-configured": "configured",
        "notify.credentials-loaded": "Credentials Loaded",
        "notify.credentials-filled": "Demo data filled",
        "error.fill-all-fields": "Please fill in all fields.",
        "error.invalid-credentials": "Invalid credentials for the selected version.",
        "error.wrong-version": "This email is for the {version} version. Please select the correct version.",
        "login.redirecting-student": "🐆 Welcome! Redirecting to student panel...",
        "login.redirecting-teacher": "👨‍🏫 Welcome! Redirecting to teacher panel...",
        "guest.accessing": "🌟 Accessing as guest...",
        "session.active-redirecting": "🐆 Active session detected. Redirecting...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "Your password"
    },
    "mn": {
        "nav.back": "← Back",
        "ui.auto-detect": "Auto",
        "ui.select-language": "Select Language",
        "auth.welcome": "Welcome!",
        "auth.subtitle": "Continue your adventure with Yaguará through Colombian ecosystems",
        "ui.lang-detected": "🌍 Language detected automatically",
        "ui.lang-suggestion": "💡 Would you prefer to continue in your native language?",
        "version.title": "🎯 Choose your learning path with Yaguará",
        "version.individual-title": "Individual Journey",
        "version.individual-desc": "Personal adventure with Yaguará through Colombia",
        "version.classroom-title": "Classroom Edition",
        "version.classroom-desc": "Structured learning for educators",
        "registration.pref-title": "📚 Select your preferred learning language",
        "demo.title": "🎯 Demo Access",
        "form.email": "Email",
        "form.password": "Password",
        "demo.guest-option": "Or explore as a guest without registration",
        "form.email-label": "📧 Email Address",
        "form.password-label": "🔒 Password",
        "auth.forgot-password": "Forgot your password?",
        "auth.login-button": "Start Adventure",
        "ui.or": "or",
        "auth.guest-access": "Guest Access",
        "auth.signup-prompt": "Don't have an account?",
        "auth.signup-link": "Sign up here",
        "notify.version-selected": "Version Selected",
        "notify.version-configured": "configured",
        "notify.credentials-loaded": "Credentials Loaded",
        "notify.credentials-filled": "Demo data filled",
        "error.fill-all-fields": "Please fill in all fields.",
        "error.invalid-credentials": "Invalid credentials for the selected version.",
        "error.wrong-version": "This email is for the {version} version. Please select the correct version.",
        "login.redirecting-student": "🐆 Welcome! Redirecting to student panel...",
        "login.redirecting-teacher": "👨‍🏫 Welcome! Redirecting to teacher panel...",
        "guest.accessing": "🌟 Accessing as guest...",
        "session.active-redirecting": "🐆 Active session detected. Redirecting...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "Your password"
    },
    "uz": {
        "nav.back": "← Back",
        "ui.auto-detect": "Auto",
        "ui.select-language": "Select Language",
        "auth.welcome": "Welcome!",
        "auth.subtitle": "Continue your adventure with Yaguará through Colombian ecosystems",
        "ui.lang-detected": "🌍 Language detected automatically",
        "ui.lang-suggestion": "💡 Would you prefer to continue in your native language?",
        "version.title": "🎯 Choose your learning path with Yaguará",
        "version.individual-title": "Individual Journey",
        "version.individual-desc": "Personal adventure with Yaguará through Colombia",
        "version.classroom-title": "Classroom Edition",
        "version.classroom-desc": "Structured learning for educators",
        "registration.pref-title": "📚 Select your preferred learning language",
        "demo.title": "🎯 Demo Access",
        "form.email": "Email",
        "form.password": "Password",
        "demo.guest-option": "Or explore as a guest without registration",
        "form.email-label": "📧 Email Address",
        "form.password-label": "🔒 Password",
        "auth.forgot-password": "Forgot your password?",
        "auth.login-button": "Start Adventure",
        "ui.or": "or",
        "auth.guest-access": "Guest Access",
        "auth.signup-prompt": "Don't have an account?",
        "auth.signup-link": "Sign up here",
        "notify.version-selected": "Version Selected",
        "notify.version-configured": "configured",
        "notify.credentials-loaded": "Credentials Loaded",
        "notify.credentials-filled": "Demo data filled",
        "error.fill-all-fields": "Please fill in all fields.",
        "error.invalid-credentials": "Invalid credentials for the selected version.",
        "error.wrong-version": "This email is for the {version} version. Please select the correct version.",
        "login.redirecting-student": "🐆 Welcome! Redirecting to student panel...",
        "login.redirecting-teacher": "👨‍🏫 Welcome! Redirecting to teacher panel...",
        "guest.accessing": "🌟 Accessing as guest...",
        "session.active-redirecting": "🐆 Active session detected. Redirecting...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "Your password"
    },
    "kk": {
        "nav.back": "← Back",
        "ui.auto-detect": "Auto",
        "ui.select-language": "Select Language",
        "auth.welcome": "Welcome!",
        "auth.subtitle": "Continue your adventure with Yaguará through Colombian ecosystems",
        "ui.lang-detected": "🌍 Language detected automatically",
        "ui.lang-suggestion": "💡 Would you prefer to continue in your native language?",
        "version.title": "🎯 Choose your learning path with Yaguará",
        "version.individual-title": "Individual Journey",
        "version.individual-desc": "Personal adventure with Yaguará through Colombia",
        "version.classroom-title": "Classroom Edition",
        "version.classroom-desc": "Structured learning for educators",
        "registration.pref-title": "📚 Select your preferred learning language",
        "demo.title": "🎯 Demo Access",
        "form.email": "Email",
        "form.password": "Password",
        "demo.guest-option": "Or explore as a guest without registration",
        "form.email-label": "📧 Email Address",
        "form.password-label": "🔒 Password",
        "auth.forgot-password": "Forgot your password?",
        "auth.login-button": "Start Adventure",
        "ui.or": "or",
        "auth.guest-access": "Guest Access",
        "auth.signup-prompt": "Don't have an account?",
        "auth.signup-link": "Sign up here",
        "notify.version-selected": "Version Selected",
        "notify.version-configured": "configured",
        "notify.credentials-loaded": "Credentials Loaded",
        "notify.credentials-filled": "Demo data filled",
        "error.fill-all-fields": "Please fill in all fields.",
        "error.invalid-credentials": "Invalid credentials for the selected version.",
        "error.wrong-version": "This email is for the {version} version. Please select the correct version.",
        "login.redirecting-student": "🐆 Welcome! Redirecting to student panel...",
        "login.redirecting-teacher": "👨‍🏫 Welcome! Redirecting to teacher panel...",
        "guest.accessing": "🌟 Accessing as guest...",
        "session.active-redirecting": "🐆 Active session detected. Redirecting...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "Your password"
    },
    "ky": {
        "nav.back": "← Back",
        "ui.auto-detect": "Auto",
        "ui.select-language": "Select Language",
        "auth.welcome": "Welcome!",
        "auth.subtitle": "Continue your adventure with Yaguará through Colombian ecosystems",
        "ui.lang-detected": "🌍 Language detected automatically",
        "ui.lang-suggestion": "💡 Would you prefer to continue in your native language?",
        "version.title": "🎯 Choose your learning path with Yaguará",
        "version.individual-title": "Individual Journey",
        "version.individual-desc": "Personal adventure with Yaguará through Colombia",
        "version.classroom-title": "Classroom Edition",
        "version.classroom-desc": "Structured learning for educators",
        "registration.pref-title": "📚 Select your preferred learning language",
        "demo.title": "🎯 Demo Access",
        "form.email": "Email",
        "form.password": "Password",
        "demo.guest-option": "Or explore as a guest without registration",
        "form.email-label": "📧 Email Address",
        "form.password-label": "🔒 Password",
        "auth.forgot-password": "Forgot your password?",
        "auth.login-button": "Start Adventure",
        "ui.or": "or",
        "auth.guest-access": "Guest Access",
        "auth.signup-prompt": "Don't have an account?",
        "auth.signup-link": "Sign up here",
        "notify.version-selected": "Version Selected",
        "notify.version-configured": "configured",
        "notify.credentials-loaded": "Credentials Loaded",
        "notify.credentials-filled": "Demo data filled",
        "error.fill-all-fields": "Please fill in all fields.",
        "error.invalid-credentials": "Invalid credentials for the selected version.",
        "error.wrong-version": "This email is for the {version} version. Please select the correct version.",
        "login.redirecting-student": "🐆 Welcome! Redirecting to student panel...",
        "login.redirecting-teacher": "👨‍🏫 Welcome! Redirecting to teacher panel...",
        "guest.accessing": "🌟 Accessing as guest...",
        "session.active-redirecting": "🐆 Active session detected. Redirecting...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "Your password"
    },
    "tg": {
        "nav.back": "← Back",
        "ui.auto-detect": "Auto",
        "ui.select-language": "Select Language",
        "auth.welcome": "Welcome!",
        "auth.subtitle": "Continue your adventure with Yaguará through Colombian ecosystems",
        "ui.lang-detected": "🌍 Language detected automatically",
        "ui.lang-suggestion": "💡 Would you prefer to continue in your native language?",
        "version.title": "🎯 Choose your learning path with Yaguará",
        "version.individual-title": "Individual Journey",
        "version.individual-desc": "Personal adventure with Yaguará through Colombia",
        "version.classroom-title": "Classroom Edition",
        "version.classroom-desc": "Structured learning for educators",
        "registration.pref-title": "📚 Select your preferred learning language",
        "demo.title": "🎯 Demo Access",
        "form.email": "Email",
        "form.password": "Password",
        "demo.guest-option": "Or explore as a guest without registration",
        "form.email-label": "📧 Email Address",
        "form.password-label": "🔒 Password",
        "auth.forgot-password": "Forgot your password?",
        "auth.login-button": "Start Adventure",
        "ui.or": "or",
        "auth.guest-access": "Guest Access",
        "auth.signup-prompt": "Don't have an account?",
        "auth.signup-link": "Sign up here",
        "notify.version-selected": "Version Selected",
        "notify.version-configured": "configured",
        "notify.credentials-loaded": "Credentials Loaded",
        "notify.credentials-filled": "Demo data filled",
        "error.fill-all-fields": "Please fill in all fields.",
        "error.invalid-credentials": "Invalid credentials for the selected version.",
        "error.wrong-version": "This email is for the {version} version. Please select the correct version.",
        "login.redirecting-student": "🐆 Welcome! Redirecting to student panel...",
        "login.redirecting-teacher": "👨‍🏫 Welcome! Redirecting to teacher panel...",
        "guest.accessing": "🌟 Accessing as guest...",
        "session.active-redirecting": "🐆 Active session detected. Redirecting...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "Your password"
    },
    "tk": {
        "nav.back": "← Back",
        "ui.auto-detect": "Auto",
        "ui.select-language": "Select Language",
        "auth.welcome": "Welcome!",
        "auth.subtitle": "Continue your adventure with Yaguará through Colombian ecosystems",
        "ui.lang-detected": "🌍 Language detected automatically",
        "ui.lang-suggestion": "💡 Would you prefer to continue in your native language?",
        "version.title": "🎯 Choose your learning path with Yaguará",
        "version.individual-title": "Individual Journey",
        "version.individual-desc": "Personal adventure with Yaguará through Colombia",
        "version.classroom-title": "Classroom Edition",
        "version.classroom-desc": "Structured learning for educators",
        "registration.pref-title": "📚 Select your preferred learning language",
        "demo.title": "🎯 Demo Access",
        "form.email": "Email",
        "form.password": "Password",
        "demo.guest-option": "Or explore as a guest without registration",
        "form.email-label": "📧 Email Address",
        "form.password-label": "🔒 Password",
        "auth.forgot-password": "Forgot your password?",
        "auth.login-button": "Start Adventure",
        "ui.or": "or",
        "auth.guest-access": "Guest Access",
        "auth.signup-prompt": "Don't have an account?",
        "auth.signup-link": "Sign up here",
        "notify.version-selected": "Version Selected",
        "notify.version-configured": "configured",
        "notify.credentials-loaded": "Credentials Loaded",
        "notify.credentials-filled": "Demo data filled",
        "error.fill-all-fields": "Please fill in all fields.",
        "error.invalid-credentials": "Invalid credentials for the selected version.",
        "error.wrong-version": "This email is for the {version} version. Please select the correct version.",
        "login.redirecting-student": "🐆 Welcome! Redirecting to student panel...",
        "login.redirecting-teacher": "👨‍🏫 Welcome! Redirecting to teacher panel...",
        "guest.accessing": "🌟 Accessing as guest...",
        "session.active-redirecting": "🐆 Active session detected. Redirecting...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "Your password"
    },
    "az": {
        "nav.back": "← Back",
        "ui.auto-detect": "Auto",
        "ui.select-language": "Select Language",
        "auth.welcome": "Welcome!",
        "auth.subtitle": "Continue your adventure with Yaguará through Colombian ecosystems",
        "ui.lang-detected": "🌍 Language detected automatically",
        "ui.lang-suggestion": "💡 Would you prefer to continue in your native language?",
        "version.title": "🎯 Choose your learning path with Yaguará",
        "version.individual-title": "Individual Journey",
        "version.individual-desc": "Personal adventure with Yaguará through Colombia",
        "version.classroom-title": "Classroom Edition",
        "version.classroom-desc": "Structured learning for educators",
        "registration.pref-title": "📚 Select your preferred learning language",
        "demo.title": "🎯 Demo Access",
        "form.email": "Email",
        "form.password": "Password",
        "demo.guest-option": "Or explore as a guest without registration",
        "form.email-label": "📧 Email Address",
        "form.password-label": "🔒 Password",
        "auth.forgot-password": "Forgot your password?",
        "auth.login-button": "Start Adventure",
        "ui.or": "or",
        "auth.guest-access": "Guest Access",
        "auth.signup-prompt": "Don't have an account?",
        "auth.signup-link": "Sign up here",
        "notify.version-selected": "Version Selected",
        "notify.version-configured": "configured",
        "notify.credentials-loaded": "Credentials Loaded",
        "notify.credentials-filled": "Demo data filled",
        "error.fill-all-fields": "Please fill in all fields.",
        "error.invalid-credentials": "Invalid credentials for the selected version.",
        "error.wrong-version": "This email is for the {version} version. Please select the correct version.",
        "login.redirecting-student": "🐆 Welcome! Redirecting to student panel...",
        "login.redirecting-teacher": "👨‍🏫 Welcome! Redirecting to teacher panel...",
        "guest.accessing": "🌟 Accessing as guest...",
        "session.active-redirecting": "🐆 Active session detected. Redirecting...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "Your password"
    },
    "ka": {
        "nav.back": "← Back",
        "ui.auto-detect": "Auto",
        "ui.select-language": "Select Language",
        "auth.welcome": "Welcome!",
        "auth.subtitle": "Continue your adventure with Yaguará through Colombian ecosystems",
        "ui.lang-detected": "🌍 Language detected automatically",
        "ui.lang-suggestion": "💡 Would you prefer to continue in your native language?",
        "version.title": "🎯 Choose your learning path with Yaguará",
        "version.individual-title": "Individual Journey",
        "version.individual-desc": "Personal adventure with Yaguará through Colombia",
        "version.classroom-title": "Classroom Edition",
        "version.classroom-desc": "Structured learning for educators",
        "registration.pref-title": "📚 Select your preferred learning language",
        "demo.title": "🎯 Demo Access",
        "form.email": "Email",
        "form.password": "Password",
        "demo.guest-option": "Or explore as a guest without registration",
        "form.email-label": "📧 Email Address",
        "form.password-label": "🔒 Password",
        "auth.forgot-password": "Forgot your password?",
        "auth.login-button": "Start Adventure",
        "ui.or": "or",
        "auth.guest-access": "Guest Access",
        "auth.signup-prompt": "Don't have an account?",
        "auth.signup-link": "Sign up here",
        "notify.version-selected": "Version Selected",
        "notify.version-configured": "configured",
        "notify.credentials-loaded": "Credentials Loaded",
        "notify.credentials-filled": "Demo data filled",
        "error.fill-all-fields": "Please fill in all fields.",
        "error.invalid-credentials": "Invalid credentials for the selected version.",
        "error.wrong-version": "This email is for the {version} version. Please select the correct version.",
        "login.redirecting-student": "🐆 Welcome! Redirecting to student panel...",
        "login.redirecting-teacher": "👨‍🏫 Welcome! Redirecting to teacher panel...",
        "guest.accessing": "🌟 Accessing as guest...",
        "session.active-redirecting": "🐆 Active session detected. Redirecting...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "Your password"
    },
    "hy": {
        "nav.back": "← Back",
        "ui.auto-detect": "Auto",
        "ui.select-language": "Select Language",
        "auth.welcome": "Welcome!",
        "auth.subtitle": "Continue your adventure with Yaguará through Colombian ecosystems",
        "ui.lang-detected": "🌍 Language detected automatically",
        "ui.lang-suggestion": "💡 Would you prefer to continue in your native language?",
        "version.title": "🎯 Choose your learning path with Yaguará",
        "version.individual-title": "Individual Journey",
        "version.individual-desc": "Personal adventure with Yaguará through Colombia",
        "version.classroom-title": "Classroom Edition",
        "version.classroom-desc": "Structured learning for educators",
        "registration.pref-title": "📚 Select your preferred learning language",
        "demo.title": "🎯 Demo Access",
        "form.email": "Email",
        "form.password": "Password",
        "demo.guest-option": "Or explore as a guest without registration",
        "form.email-label": "📧 Email Address",
        "form.password-label": "🔒 Password",
        "auth.forgot-password": "Forgot your password?",
        "auth.login-button": "Start Adventure",
        "ui.or": "or",
        "auth.guest-access": "Guest Access",
        "auth.signup-prompt": "Don't have an account?",
        "auth.signup-link": "Sign up here",
        "notify.version-selected": "Version Selected",
        "notify.version-configured": "configured",
        "notify.credentials-loaded": "Credentials Loaded",
        "notify.credentials-filled": "Demo data filled",
        "error.fill-all-fields": "Please fill in all fields.",
        "error.invalid-credentials": "Invalid credentials for the selected version.",
        "error.wrong-version": "This email is for the {version} version. Please select the correct version.",
        "login.redirecting-student": "🐆 Welcome! Redirecting to student panel...",
        "login.redirecting-teacher": "👨‍🏫 Welcome! Redirecting to teacher panel...",
        "guest.accessing": "🌟 Accessing as guest...",
        "session.active-redirecting": "🐆 Active session detected. Redirecting...",
        "placeholder.email": "your@email.com",
        "placeholder.password": "Your password"
    },
}
