<?php
/**
 * Core Vocabulary Seeder — Inserts the curated core vocabulary into dict_words.
 * Covers all POS: verbs, nouns, adjectives, adverbs, pronouns, prepositions,
 * conjunctions, and determiners.
 *
 * Run: php seed-vocabulary-core.php
 */

require_once __DIR__ . '/../config/database.php';

$pdo = getDB();

echo "=== Core Vocabulary Seeder ===\n\n";

// ─── Helpers ──────────────────────────────────────────────────────

function normalize(string $word): string {
    $word = mb_strtolower(trim($word), 'UTF-8');
    if (function_exists('transliterator_transliterate')) {
        return transliterator_transliterate('NFD; [:Nonspacing Mark:] Remove; NFC;', $word);
    }
    $word = preg_replace('/[áà]/u', 'a', $word);
    $word = preg_replace('/[éè]/u', 'e', $word);
    $word = preg_replace('/[íì]/u', 'i', $word);
    $word = preg_replace('/[óò]/u', 'o', $word);
    $word = preg_replace('/[úù]/u', 'u', $word);
    return str_replace('ñ', 'n', $word);
}

function guessGender(string $word, string $pos): ?string {
    if ($pos !== 'noun') return null;
    $w = mb_strtolower($word, 'UTF-8');
    if (preg_match('/(ción|sión|dad|tad|tud|umbre|za|ncia|encia|eza)$/u', $w)) return 'f';
    if (preg_match('/[ao]$/u', $w)) {
        return mb_substr($w, -1) === 'a' ? 'f' : 'm';
    }
    return null;
}

// ─── Word definitions ─────────────────────────────────────────────
// Format: [word, part_of_speech, gender, cefr_level]

$words = [

    // ═══ VERBS ═══════════════════════════════════════════════════
    // Batch 1: Original 50
    ['llegar', 'verb', null, 'A1'],
    ['pasar', 'verb', null, 'A1'],
    ['pensar', 'verb', null, 'A2'],
    ['creer', 'verb', null, 'A2'],
    ['hablar', 'verb', null, 'A1'],
    ['llevar', 'verb', null, 'A2'],
    ['dejar', 'verb', null, 'A2'],
    ['seguir', 'verb', null, 'A2'],
    ['encontrar', 'verb', null, 'A2'],
    ['llamar', 'verb', null, 'A1'],
    ['venir', 'verb', null, 'A2'],
    ['sentir', 'verb', null, 'A2'],
    ['tratar', 'verb', null, 'B1'],
    ['mirar', 'verb', null, 'A1'],
    ['contar', 'verb', null, 'A2'],
    ['empezar', 'verb', null, 'A1'],
    ['esperar', 'verb', null, 'A2'],
    ['buscar', 'verb', null, 'A2'],
    ['existir', 'verb', null, 'B1'],
    ['entrar', 'verb', null, 'A1'],
    ['vivir', 'verb', null, 'A1'],
    ['trabajar', 'verb', null, 'A1'],
    ['escribir', 'verb', null, 'A1'],
    ['leer', 'verb', null, 'A1'],
    ['aprender', 'verb', null, 'A1'],
    ['estudiar', 'verb', null, 'A1'],
    ['comprar', 'verb', null, 'A1'],
    ['pagar', 'verb', null, 'A2'],
    ['vender', 'verb', null, 'A2'],
    ['usar', 'verb', null, 'A1'],
    ['abrir', 'verb', null, 'A1'],
    ['cerrar', 'verb', null, 'A1'],
    ['subir', 'verb', null, 'A2'],
    ['bajar', 'verb', null, 'A2'],
    ['caer', 'verb', null, 'A2'],
    ['ganar', 'verb', null, 'A2'],
    ['perder', 'verb', null, 'A2'],
    ['recordar', 'verb', null, 'A2'],
    ['olvidar', 'verb', null, 'A2'],
    ['cambiar', 'verb', null, 'A2'],
    ['mostrar', 'verb', null, 'A2'],
    ['escuchar', 'verb', null, 'A1'],
    ['terminar', 'verb', null, 'A1'],
    ['crear', 'verb', null, 'B1'],
    ['ofrecer', 'verb', null, 'B1'],
    ['aceptar', 'verb', null, 'A2'],
    ['permitir', 'verb', null, 'B1'],
    ['evitar', 'verb', null, 'B1'],
    ['explicar', 'verb', null, 'A2'],
    ['decidir', 'verb', null, 'A2'],

    // Core irregular verbs
    ['ser', 'verb', null, 'A1'],
    ['estar', 'verb', null, 'A1'],
    ['tener', 'verb', null, 'A1'],
    ['hacer', 'verb', null, 'A1'],
    ['decir', 'verb', null, 'A1'],
    ['ir', 'verb', null, 'A1'],
    ['ver', 'verb', null, 'A1'],
    ['dar', 'verb', null, 'A1'],
    ['saber', 'verb', null, 'A2'],
    ['querer', 'verb', null, 'A1'],

    // Modals/auxiliaries
    ['haber', 'verb', null, 'A2'],
    ['poder', 'verb', null, 'A1'],
    ['deber', 'verb', null, 'A2'],
    ['poner', 'verb', null, 'A2'],
    ['parecer', 'verb', null, 'A2'],

    // Batch 2 verbs
    ['entender', 'verb', null, 'A2'],
    ['imaginar', 'verb', null, 'B1'],
    ['considerar', 'verb', null, 'B1'],
    ['suponer', 'verb', null, 'B1'],
    ['temer', 'verb', null, 'B1'],
    ['desear', 'verb', null, 'B1'],
    ['preferir', 'verb', null, 'A2'],
    ['necesitar', 'verb', null, 'A1'],
    ['ayudar', 'verb', null, 'A1'],
    ['apoyar', 'verb', null, 'B1'],
    ['cuidar', 'verb', null, 'A2'],
    ['respetar', 'verb', null, 'B1'],
    ['proteger', 'verb', null, 'B1'],
    ['controlar', 'verb', null, 'B1'],
    ['organizar', 'verb', null, 'A2'],
    ['preparar', 'verb', null, 'A2'],
    ['participar', 'verb', null, 'B1'],
    ['colaborar', 'verb', null, 'B1'],
    ['intentar', 'verb', null, 'A2'],
    ['lograr', 'verb', null, 'B1'],
    ['fallar', 'verb', null, 'B1'],
    ['mejorar', 'verb', null, 'A2'],
    ['empeorar', 'verb', null, 'B1'],
    ['aumentar', 'verb', null, 'B1'],
    ['reducir', 'verb', null, 'B1'],
    ['mantener', 'verb', null, 'B1'],
    ['resolver', 'verb', null, 'B1'],
    ['elegir', 'verb', null, 'B1'],

    // Movement/body verbs
    ['mover', 'verb', null, 'A2'],
    ['parar', 'verb', null, 'A2'],
    ['quedar', 'verb', null, 'A2'],
    ['salir', 'verb', null, 'A1'],
    ['volver', 'verb', null, 'A2'],
    ['regresar', 'verb', null, 'A2'],
    ['viajar', 'verb', null, 'A2'],
    ['conducir', 'verb', null, 'B1'],
    ['caminar', 'verb', null, 'A1'],
    ['correr', 'verb', null, 'A1'],
    ['sentarse', 'verb', null, 'A2'],
    ['levantarse', 'verb', null, 'A2'],
    ['acostarse', 'verb', null, 'A2'],
    ['despertar', 'verb', null, 'A2'],
    ['dormir', 'verb', null, 'A1'],
    ['descansar', 'verb', null, 'A2'],
    ['reír', 'verb', null, 'A2'],
    ['llorar', 'verb', null, 'A2'],
    ['sonreír', 'verb', null, 'A2'],
    ['gritar', 'verb', null, 'A2'],
    ['romper', 'verb', null, 'A2'],
    ['arreglar', 'verb', null, 'A2'],
    ['construir', 'verb', null, 'B1'],
    ['destruir', 'verb', null, 'B1'],
    ['llenar', 'verb', null, 'A2'],
    ['vaciar', 'verb', null, 'B1'],
    ['guardar', 'verb', null, 'A2'],
    ['tirar', 'verb', null, 'A2'],
    ['empujar', 'verb', null, 'A2'],
    ['jalar', 'verb', null, 'A2'],
    ['comer', 'verb', null, 'A1'],

    // ═══ NOUNS ═══════════════════════════════════════════════════
    // Basic nouns
    ['persona', 'noun', 'f', 'A1'],
    ['cosa', 'noun', 'f', 'A1'],
    ['tiempo', 'noun', 'm', 'A1'],
    ['día', 'noun', 'm', 'A1'],
    ['año', 'noun', 'm', 'A1'],
    ['vida', 'noun', 'f', 'A1'],
    ['mundo', 'noun', 'm', 'A1'],
    ['trabajo', 'noun', 'm', 'A1'],
    ['mano', 'noun', 'f', 'A1'],  // irregular gender: feminine despite -o
    ['parte', 'noun', 'f', 'A1'],

    // People
    ['gente', 'noun', 'f', 'A1'],
    ['niño', 'noun', 'm', 'A1'],
    ['joven', 'noun', 'm', 'A1'],
    ['adulto', 'noun', 'm', 'A2'],
    ['padre', 'noun', 'm', 'A1'],
    ['madre', 'noun', 'f', 'A1'],
    ['hijo', 'noun', 'm', 'A1'],
    ['amigo', 'noun', 'm', 'A1'],
    ['vecino', 'noun', 'm', 'A2'],

    // Time
    ['momento', 'noun', 'm', 'A2'],
    ['noche', 'noun', 'f', 'A1'],
    ['mañana', 'noun', 'f', 'A1'],
    ['tarde', 'noun', 'f', 'A1'],
    ['semana', 'noun', 'f', 'A1'],
    ['mes', 'noun', 'm', 'A1'],
    ['hora', 'noun', 'f', 'A1'],

    // Places/things
    ['historia', 'noun', 'f', 'A2'],
    ['país', 'noun', 'm', 'A2'],
    ['ciudad', 'noun', 'f', 'A1'],
    ['lugar', 'noun', 'm', 'A1'],
    ['casa', 'noun', 'f', 'A1'],
    ['calle', 'noun', 'f', 'A1'],
    ['escuela', 'noun', 'f', 'A1'],

    // Abstract
    ['problema', 'noun', 'm', 'A1'],  // irregular gender: masculine despite -a
    ['pregunta', 'noun', 'f', 'A1'],
    ['respuesta', 'noun', 'f', 'A1'],
    ['idea', 'noun', 'f', 'A2'],
    ['forma', 'noun', 'f', 'A2'],
    ['caso', 'noun', 'm', 'A2'],
    ['ejemplo', 'noun', 'm', 'A2'],
    ['razón', 'noun', 'f', 'A2'],
    ['resultado', 'noun', 'm', 'A2'],

    // Family/groups
    ['familia', 'noun', 'f', 'A1'],
    ['grupo', 'noun', 'm', 'A2'],
    ['equipo', 'noun', 'm', 'A2'],
    ['empresa', 'noun', 'f', 'B1'],
    ['cliente', 'noun', 'm', 'B1'],
    ['usuario', 'noun', 'm', 'B1'],
    ['sistema', 'noun', 'm', 'B1'],
    ['proceso', 'noun', 'm', 'B1'],
    ['nivel', 'noun', 'm', 'A2'],
    ['modelo', 'noun', 'm', 'B1'],

    // Gender/people
    ['mujer', 'noun', 'f', 'A1'],
    ['hombre', 'noun', 'm', 'A1'],

    // Objects/commerce
    ['objeto', 'noun', 'm', 'A2'],
    ['dinero', 'noun', 'm', 'A1'],
    ['precio', 'noun', 'm', 'A2'],
    ['valor', 'noun', 'm', 'B1'],
    ['producto', 'noun', 'm', 'A2'],
    ['servicio', 'noun', 'm', 'A2'],
    ['comida', 'noun', 'f', 'A1'],
    ['bebida', 'noun', 'f', 'A1'],
    ['ropa', 'noun', 'f', 'A1'],

    // Body
    ['cuerpo', 'noun', 'm', 'A2'],
    ['cabeza', 'noun', 'f', 'A2'],
    ['ojo', 'noun', 'm', 'A1'],
    ['cara', 'noun', 'f', 'A2'],
    ['voz', 'noun', 'f', 'A2'],

    // Language
    ['nombre', 'noun', 'm', 'A1'],
    ['palabra', 'noun', 'f', 'A1'],
    ['frase', 'noun', 'f', 'A2'],
    ['lengua', 'noun', 'f', 'A2'],

    // Emotions (Batch 4)
    ['amor', 'noun', 'm', 'A2'],
    ['odio', 'noun', 'm', 'B1'],
    ['miedo', 'noun', 'm', 'A2'],
    ['esperanza', 'noun', 'f', 'B1'],
    ['felicidad', 'noun', 'f', 'A2'],
    ['tristeza', 'noun', 'f', 'A2'],
    ['alegría', 'noun', 'f', 'A2'],
    ['dolor', 'noun', 'm', 'A2'],
    ['placer', 'noun', 'm', 'B1'],
    ['paz', 'noun', 'f', 'A2'],

    // Conflict/society
    ['guerra', 'noun', 'f', 'B1'],
    ['conflicto', 'noun', 'm', 'B1'],
    ['acuerdo', 'noun', 'm', 'B1'],
    ['decisión', 'noun', 'f', 'A2'],
    ['elección', 'noun', 'f', 'B1'],
    ['cambio', 'noun', 'm', 'A2'],
    ['progreso', 'noun', 'm', 'B1'],
    ['desarrollo', 'noun', 'm', 'B1'],
    ['crecimiento', 'noun', 'm', 'B1'],
    ['crisis', 'noun', 'f', 'B1'],

    // Abstract concepts
    ['verdad', 'noun', 'f', 'A2'],
    ['mentira', 'noun', 'f', 'A2'],
    ['error', 'noun', 'm', 'A2'],
    ['éxito', 'noun', 'm', 'B1'],
    ['fracaso', 'noun', 'm', 'B1'],
    ['objetivo', 'noun', 'm', 'B1'],
    ['meta', 'noun', 'f', 'B1'],
    ['plan', 'noun', 'm', 'A2'],
    ['proyecto', 'noun', 'm', 'B1'],

    // ═══ ADJECTIVES ══════════════════════════════════════════════
    ['bueno', 'adjective', null, 'A1'],
    ['malo', 'adjective', null, 'A1'],
    ['grande', 'adjective', null, 'A1'],
    ['pequeño', 'adjective', null, 'A1'],
    ['nuevo', 'adjective', null, 'A1'],
    ['viejo', 'adjective', null, 'A1'],
    ['mismo', 'adjective', null, 'A2'],
    ['otro', 'adjective', null, 'A1'],
    ['mucho', 'adjective', null, 'A1'],
    ['poco', 'adjective', null, 'A1'],
    ['mejor', 'adjective', null, 'A1'],
    ['peor', 'adjective', null, 'A2'],
    ['joven', 'adjective', null, 'A1'],
    ['largo', 'adjective', null, 'A2'],
    ['corto', 'adjective', null, 'A2'],
    ['alto', 'adjective', null, 'A1'],
    ['bajo', 'adjective', null, 'A2'],
    ['fácil', 'adjective', null, 'A1'],
    ['difícil', 'adjective', null, 'A1'],
    ['rápido', 'adjective', null, 'A2'],
    ['lento', 'adjective', null, 'A2'],
    ['claro', 'adjective', null, 'A2'],
    ['oscuro', 'adjective', null, 'A2'],
    ['simple', 'adjective', null, 'A2'],
    ['importante', 'adjective', null, 'A2'],
    ['posible', 'adjective', null, 'A2'],
    ['necesario', 'adjective', null, 'A2'],
    ['seguro', 'adjective', null, 'A2'],
    ['libre', 'adjective', null, 'A2'],
    ['igual', 'adjective', null, 'A2'],
    ['diferente', 'adjective', null, 'A2'],
    ['normal', 'adjective', null, 'A2'],
    ['especial', 'adjective', null, 'A2'],
    ['común', 'adjective', null, 'B1'],

    // ═══ ADVERBS ═════════════════════════════════════════════════
    ['bien', 'adverb', null, 'A1'],
    ['mal', 'adverb', null, 'A1'],
    ['siempre', 'adverb', null, 'A1'],
    ['nunca', 'adverb', null, 'A1'],
    ['a veces', 'adverb', null, 'A1'],
    ['ya', 'adverb', null, 'A2'],
    ['todavía', 'adverb', null, 'A2'],
    ['aquí', 'adverb', null, 'A1'],
    ['ahí', 'adverb', null, 'A1'],
    ['allí', 'adverb', null, 'A1'],
    ['ahora', 'adverb', null, 'A1'],
    ['antes', 'adverb', null, 'A2'],
    ['después', 'adverb', null, 'A1'],
    ['pronto', 'adverb', null, 'A2'],
    ['hoy', 'adverb', null, 'A1'],
    ['ayer', 'adverb', null, 'A1'],
    ['bastante', 'adverb', null, 'A2'],
    ['demasiado', 'adverb', null, 'A2'],
    ['casi', 'adverb', null, 'A2'],
    ['solo', 'adverb', null, 'A2'],
    ['juntos', 'adverb', null, 'A2'],
    ['lejos', 'adverb', null, 'A1'],
    ['cerca', 'adverb', null, 'A1'],
    ['dentro', 'adverb', null, 'A2'],

    // ═══ PRONOUNS ════════════════════════════════════════════════
    ['yo', 'pronoun', null, 'A1'],
    ['tú', 'pronoun', null, 'A1'],
    ['él', 'pronoun', null, 'A1'],
    ['ella', 'pronoun', null, 'A1'],
    ['nosotros', 'pronoun', null, 'A1'],
    ['ellos', 'pronoun', null, 'A1'],
    ['vosotros', 'pronoun', null, 'B1'],

    // ═══ DETERMINERS ═════════════════════════════════════════════
    ['mi', 'determiner', null, 'A1'],
    ['tu', 'determiner', null, 'A1'],
    ['su', 'determiner', null, 'A1'],
    ['nuestro', 'determiner', null, 'A1'],
    ['este', 'determiner', null, 'A1'],
    ['ese', 'determiner', null, 'A1'],
    ['aquel', 'determiner', null, 'A2'],

    // ═══ PREPOSITIONS ════════════════════════════════════════════
    ['de', 'preposition', null, 'A1'],
    ['a', 'preposition', null, 'A1'],
    ['en', 'preposition', null, 'A1'],
    ['con', 'preposition', null, 'A1'],
    ['por', 'preposition', null, 'A1'],
    ['para', 'preposition', null, 'A1'],
    ['sin', 'preposition', null, 'A1'],
    ['sobre', 'preposition', null, 'A1'],
    ['entre', 'preposition', null, 'A1'],
    ['hasta', 'preposition', null, 'A1'],

    // ═══ CONJUNCTIONS ════════════════════════════════════════════
    ['y', 'conjunction', null, 'A1'],
    ['o', 'conjunction', null, 'A1'],
    ['pero', 'conjunction', null, 'A1'],
    ['porque', 'conjunction', null, 'A1'],
    ['aunque', 'conjunction', null, 'A2'],
    ['si', 'conjunction', null, 'A1'],
    ['no', 'adverb', null, 'A1'],

    // ═══ BATCH 3: More verbs ═════════════════════════════════════
    // Kitchen/household verbs
    ['beber', 'verb', null, 'A1'],
    ['cocinar', 'verb', null, 'A1'],
    ['lavar', 'verb', null, 'A2'],
    ['limpiar', 'verb', null, 'A2'],
    ['ordenar', 'verb', null, 'A2'],
    ['encender', 'verb', null, 'A2'],
    ['apagar', 'verb', null, 'A2'],
    ['conectar', 'verb', null, 'A2'],
    ['desconectar', 'verb', null, 'B1'],
    ['revisar', 'verb', null, 'A2'],
    ['probar', 'verb', null, 'A2'],
    ['repetir', 'verb', null, 'A2'],
    ['practicar', 'verb', null, 'A1'],
    ['memorizar', 'verb', null, 'A2'],
    ['quedarse', 'verb', null, 'A2'],
    ['moverse', 'verb', null, 'A2'],
    ['acercarse', 'verb', null, 'A2'],
    ['alejarse', 'verb', null, 'A2'],
    ['cruzar', 'verb', null, 'A2'],
    ['alcanzar', 'verb', null, 'B1'],
    ['perseguir', 'verb', null, 'B1'],
    ['pintar', 'verb', null, 'A2'],
    ['dibujar', 'verb', null, 'A2'],
    ['cortar', 'verb', null, 'A2'],
    ['pegar', 'verb', null, 'A2'],
    ['coser', 'verb', null, 'B1'],
    ['medir', 'verb', null, 'B1'],
    ['pesar', 'verb', null, 'B1'],
    ['mezclar', 'verb', null, 'A2'],
    ['servir', 'verb', null, 'A2'],
    ['calentar', 'verb', null, 'A2'],

    // Communication verbs
    ['preguntar', 'verb', null, 'A1'],
    ['responder', 'verb', null, 'A1'],
    ['contestar', 'verb', null, 'A2'],
    ['describir', 'verb', null, 'A2'],
    ['narrar', 'verb', null, 'B1'],
    ['discutir', 'verb', null, 'B1'],
    ['aclarar', 'verb', null, 'B1'],
    ['saludar', 'verb', null, 'A1'],
    ['despedirse', 'verb', null, 'A1'],
    ['invitar', 'verb', null, 'A2'],
    ['rechazar', 'verb', null, 'B1'],
    ['prometer', 'verb', null, 'B1'],
    ['avisar', 'verb', null, 'A2'],
    ['advertir', 'verb', null, 'B1'],
    ['confirmar', 'verb', null, 'A2'],
    ['cancelar', 'verb', null, 'A2'],

    // Education verbs
    ['enseñar', 'verb', null, 'A2'],
    ['corregir', 'verb', null, 'B1'],
    ['evaluar', 'verb', null, 'B1'],
    ['aprobar', 'verb', null, 'B1'],
    ['reprobar', 'verb', null, 'B1'],
    ['presentar', 'verb', null, 'A2'],
    ['exponer', 'verb', null, 'B1'],

    // ═══ BATCH 3: Household nouns ════════════════════════════════
    ['mesa', 'noun', 'f', 'A1'],
    ['silla', 'noun', 'f', 'A1'],
    ['cama', 'noun', 'f', 'A1'],
    ['sofá', 'noun', 'm', 'A2'],
    ['puerta', 'noun', 'f', 'A1'],
    ['ventana', 'noun', 'f', 'A1'],
    ['pared', 'noun', 'f', 'A2'],
    ['techo', 'noun', 'm', 'A2'],
    ['suelo', 'noun', 'm', 'A2'],
    ['cocina', 'noun', 'f', 'A1'],
    ['baño', 'noun', 'm', 'A1'],
    ['cuarto', 'noun', 'm', 'A1'],
    ['habitación', 'noun', 'f', 'A1'],
    ['oficina', 'noun', 'f', 'A2'],
    ['edificio', 'noun', 'm', 'A2'],
    ['tienda', 'noun', 'f', 'A1'],
    ['mercado', 'noun', 'm', 'A2'],
    ['supermercado', 'noun', 'm', 'A1'],
    ['restaurante', 'noun', 'm', 'A1'],
    ['cafetería', 'noun', 'f', 'A2'],

    // Kitchen items
    ['plato', 'noun', 'm', 'A1'],
    ['vaso', 'noun', 'm', 'A1'],
    ['taza', 'noun', 'f', 'A1'],
    ['cuchara', 'noun', 'f', 'A1'],
    ['tenedor', 'noun', 'm', 'A1'],
    ['cuchillo', 'noun', 'm', 'A1'],
    ['olla', 'noun', 'f', 'A2'],
    ['sartén', 'noun', 'f', 'A2'],
    ['horno', 'noun', 'm', 'A2'],
    ['nevera', 'noun', 'f', 'A2'],

    // Objects
    ['bolsa', 'noun', 'f', 'A1'],
    ['caja', 'noun', 'f', 'A2'],
    ['botella', 'noun', 'f', 'A1'],
    ['llave', 'noun', 'f', 'A1'],
    ['candado', 'noun', 'm', 'B1'],
    ['papel', 'noun', 'm', 'A1'],
    ['libro', 'noun', 'm', 'A1'],
    ['cuaderno', 'noun', 'm', 'A1'],
    ['bolígrafo', 'noun', 'm', 'A1'],
    ['lápiz', 'noun', 'm', 'A1'],

    // ═══ BATCH 3: More adjectives ════════════════════════════════
    ['bonito', 'adjective', null, 'A1'],
    ['feo', 'adjective', null, 'A1'],
    ['limpio', 'adjective', null, 'A1'],
    ['sucio', 'adjective', null, 'A1'],
    ['usado', 'adjective', null, 'A2'],
    ['abierto', 'adjective', null, 'A1'],
    ['cerrado', 'adjective', null, 'A1'],
    ['lleno', 'adjective', null, 'A1'],
    ['vacío', 'adjective', null, 'A2'],
    ['fuerte', 'adjective', null, 'A1'],
    ['débil', 'adjective', null, 'A2'],
    ['duro', 'adjective', null, 'A2'],
    ['blando', 'adjective', null, 'A2'],
    ['ligero', 'adjective', null, 'A2'],
    ['pesado', 'adjective', null, 'A2'],
    ['caliente', 'adjective', null, 'A1'],
    ['frío', 'adjective', null, 'A1'],
    ['húmedo', 'adjective', null, 'B1'],
    ['seco', 'adjective', null, 'A2'],
    ['caro', 'adjective', null, 'A1'],
    ['barato', 'adjective', null, 'A1'],
    ['gratis', 'adjective', null, 'A1'],
    ['útil', 'adjective', null, 'A2'],
    ['inútil', 'adjective', null, 'B1'],
    ['cómodo', 'adjective', null, 'A2'],
    ['incómodo', 'adjective', null, 'B1'],
    ['peligroso', 'adjective', null, 'A2'],

    // ═══ BATCH 3: Professions/People ═════════════════════════════
    ['estudiante', 'noun', 'm', 'A1'],
    ['profesor', 'noun', 'm', 'A1'],
    ['maestro', 'noun', 'm', 'A1'],
    ['doctor', 'noun', 'm', 'A1'],
    ['enfermero', 'noun', 'm', 'A2'],
    ['paciente', 'noun', 'm', 'A2'],
    ['empleado', 'noun', 'm', 'A2'],
    ['jefe', 'noun', 'm', 'A2'],
    ['compañero', 'noun', 'm', 'A2'],
    ['colega', 'noun', 'm', 'A2'],
    ['enemigo', 'noun', 'm', 'A2'],
    ['pareja', 'noun', 'f', 'A2'],
    ['esposo', 'noun', 'm', 'A2'],
    ['esposa', 'noun', 'f', 'A2'],
    ['novio', 'noun', 'm', 'A2'],
    ['novia', 'noun', 'f', 'A2'],
    ['líder', 'noun', 'm', 'B1'],
    ['miembro', 'noun', 'm', 'A2'],
    ['autor', 'noun', 'm', 'B1'],
    ['lector', 'noun', 'm', 'B1'],
    ['oyente', 'noun', 'm', 'B1'],
    ['hablante', 'noun', 'm', 'B1'],
    ['traductor', 'noun', 'm', 'B1'],
    ['intérprete', 'noun', 'm', 'B1'],
    ['experto', 'noun', 'm', 'B1'],
    ['principiante', 'noun', 'm', 'A2'],

    // ═══ BATCH 4: Mental/emotional verbs ═════════════════════════
    ['dudar', 'verb', null, 'A2'],
    ['notar', 'verb', null, 'A2'],
    ['emocionarse', 'verb', null, 'A2'],
    ['preocuparse', 'verb', null, 'A2'],
    ['amar', 'verb', null, 'A2'],
    ['odiar', 'verb', null, 'B1'],
    ['gustar', 'verb', null, 'A1'],
    ['encantar', 'verb', null, 'A1'],
    ['molestar', 'verb', null, 'A2'],
    ['importar', 'verb', null, 'A2'],
    ['afectar', 'verb', null, 'B1'],
    ['confiar', 'verb', null, 'B1'],
    ['sospechar', 'verb', null, 'B1'],
    ['arriesgar', 'verb', null, 'B1'],
    ['rendirse', 'verb', null, 'B1'],

    // Life/movement verbs
    ['nacer', 'verb', null, 'A2'],
    ['crecer', 'verb', null, 'A2'],
    ['morir', 'verb', null, 'A2'],
    ['continuar', 'verb', null, 'A2'],
    ['detener', 'verb', null, 'B1'],
    ['partir', 'verb', null, 'A2'],
    ['mudarse', 'verb', null, 'A2'],
    ['explorar', 'verb', null, 'A2'],
    ['descubrir', 'verb', null, 'A2'],
    ['conocer', 'verb', null, 'A1'],
    ['reconocer', 'verb', null, 'A2'],
    ['hallar', 'verb', null, 'B1'],
    ['conservar', 'verb', null, 'B1'],
    ['abandonar', 'verb', null, 'B1'],
    ['recuperar', 'verb', null, 'B1'],

    // ═══ BATCH 4: Abstract/mental nouns ══════════════════════════
    ['opinión', 'noun', 'f', 'A2'],
    ['pensamiento', 'noun', 'm', 'B1'],
    ['recuerdo', 'noun', 'm', 'A2'],
    ['memoria', 'noun', 'f', 'A2'],
    ['sueño', 'noun', 'm', 'A2'],
    ['solución', 'noun', 'f', 'A2'],
    ['mejora', 'noun', 'f', 'B1'],
    ['avance', 'noun', 'm', 'B1'],
    ['retroceso', 'noun', 'm', 'B1'],
    ['control', 'noun', 'm', 'B1'],
    ['regla', 'noun', 'f', 'A2'],
    ['norma', 'noun', 'f', 'B1'],
    ['ley', 'noun', 'f', 'B1'],
    ['derecho', 'noun', 'm', 'B1'],
    ['obligación', 'noun', 'f', 'B1'],
    ['permiso', 'noun', 'm', 'A2'],
    ['contrato', 'noun', 'm', 'B1'],
    ['confianza', 'noun', 'f', 'B1'],
    ['responsabilidad', 'noun', 'f', 'B1'],

    // ═══ BATCH 4: Emotional/state adjectives ═════════════════════
    ['feliz', 'adjective', null, 'A1'],
    ['triste', 'adjective', null, 'A1'],
    ['contento', 'adjective', null, 'A1'],
    ['enojado', 'adjective', null, 'A2'],
    ['nervioso', 'adjective', null, 'A2'],
    ['tranquilo', 'adjective', null, 'A2'],
    ['cansado', 'adjective', null, 'A1'],
    ['activo', 'adjective', null, 'A2'],
    ['aburrido', 'adjective', null, 'A2'],
    ['emocionado', 'adjective', null, 'A2'],
    ['imposible', 'adjective', null, 'A2'],
    ['probable', 'adjective', null, 'B1'],
    ['incierto', 'adjective', null, 'B1'],
    ['confuso', 'adjective', null, 'B1'],
    ['evidente', 'adjective', null, 'B1'],
    ['oculto', 'adjective', null, 'B1'],
    ['visible', 'adjective', null, 'A2'],
    ['correcto', 'adjective', null, 'A2'],
    ['incorrecto', 'adjective', null, 'A2'],
    ['adecuado', 'adjective', null, 'B1'],
    ['inadecuado', 'adjective', null, 'B1'],
    ['justo', 'adjective', null, 'B1'],
    ['injusto', 'adjective', null, 'B1'],
    ['distinto', 'adjective', null, 'A2'],
    ['similar', 'adjective', null, 'A2'],
    ['opuesto', 'adjective', null, 'B1'],

    // ═══ BATCH 5: Professional/work verbs ════════════════════════
    ['producir', 'verb', null, 'B1'],
    ['fabricar', 'verb', null, 'B1'],
    ['desarrollar', 'verb', null, 'B1'],
    ['diseñar', 'verb', null, 'B1'],
    ['planificar', 'verb', null, 'B1'],
    ['coordinar', 'verb', null, 'B1'],
    ['dirigir', 'verb', null, 'B1'],
    ['administrar', 'verb', null, 'B1'],
    ['gestionar', 'verb', null, 'B1'],
    ['supervisar', 'verb', null, 'B1'],
    ['analizar', 'verb', null, 'B1'],
    ['comparar', 'verb', null, 'A2'],
    ['calcular', 'verb', null, 'B1'],
    ['estimar', 'verb', null, 'B1'],
    ['invertir', 'verb', null, 'B1'],
    ['ahorrar', 'verb', null, 'A2'],
    ['gastar', 'verb', null, 'A2'],
    ['cobrar', 'verb', null, 'B1'],
    ['negociar', 'verb', null, 'B1'],
    ['contratar', 'verb', null, 'B1'],
    ['despedir', 'verb', null, 'B1'],
    ['publicar', 'verb', null, 'B1'],
    ['editar', 'verb', null, 'B1'],
    ['actualizar', 'verb', null, 'B1'],
    ['archivar', 'verb', null, 'B1'],
    ['registrar', 'verb', null, 'B1'],
    ['documentar', 'verb', null, 'B1'],
    ['informar', 'verb', null, 'A2'],
    ['reportar', 'verb', null, 'B1'],

    // Perception verbs
    ['observar', 'verb', null, 'A2'],
    ['oír', 'verb', null, 'A1'],
    ['percibir', 'verb', null, 'B1'],
    ['detectar', 'verb', null, 'B1'],
    ['tocar', 'verb', null, 'A1'],
    ['agarrar', 'verb', null, 'A2'],
    ['sujetar', 'verb', null, 'B1'],
    ['soltar', 'verb', null, 'A2'],
    ['golpear', 'verb', null, 'A2'],
    ['rozar', 'verb', null, 'B1'],
    ['presionar', 'verb', null, 'B1'],
    ['apretar', 'verb', null, 'B1'],
    ['unir', 'verb', null, 'A2'],
    ['separar', 'verb', null, 'A2'],
    ['dividir', 'verb', null, 'B1'],
    ['relacionar', 'verb', null, 'B1'],

    // Legal/social verbs
    ['obedecer', 'verb', null, 'B1'],
    ['cumplir', 'verb', null, 'B1'],
    ['violar', 'verb', null, 'B2'],
    ['exigir', 'verb', null, 'B1'],
    ['prohibir', 'verb', null, 'B1'],
    ['autorizar', 'verb', null, 'B1'],
    ['solicitar', 'verb', null, 'B1'],
    ['reclamar', 'verb', null, 'B1'],
    ['denunciar', 'verb', null, 'B1'],
    ['acusar', 'verb', null, 'B1'],
    ['defender', 'verb', null, 'B1'],
    ['justificar', 'verb', null, 'B1'],
    ['argumentar', 'verb', null, 'B1'],
    ['convencer', 'verb', null, 'B1'],
    ['persuadir', 'verb', null, 'B2'],
    ['influir', 'verb', null, 'B1'],
    ['manipular', 'verb', null, 'B2'],
    ['cooperar', 'verb', null, 'B1'],
    ['competir', 'verb', null, 'B1'],
    ['involucrar', 'verb', null, 'B1'],
    ['oponerse', 'verb', null, 'B1'],
    ['resistir', 'verb', null, 'B1'],
    ['ceder', 'verb', null, 'B1'],

    // Change/cause verbs
    ['transformar', 'verb', null, 'B1'],
    ['modificar', 'verb', null, 'B1'],
    ['alterar', 'verb', null, 'B1'],
    ['adaptar', 'verb', null, 'B1'],
    ['ajustar', 'verb', null, 'B1'],
    ['optimizar', 'verb', null, 'B1'],
    ['deteriorar', 'verb', null, 'B2'],
    ['causar', 'verb', null, 'B1'],
    ['provocar', 'verb', null, 'B1'],
    ['generar', 'verb', null, 'B1'],
    ['impactar', 'verb', null, 'B1'],
    ['conseguir', 'verb', null, 'A2'],
    ['dominar', 'verb', null, 'B1'],
    ['manejar', 'verb', null, 'B1'],
    ['regular', 'verb', null, 'B1'],
    ['limitar', 'verb', null, 'B1'],
    ['expandir', 'verb', null, 'B1'],
    ['restringir', 'verb', null, 'B2'],

    // ═══ BATCH 5: Body/health nouns ══════════════════════════════
    ['cuerpo', 'noun', 'm', 'A2'],
    ['mente', 'noun', 'f', 'B1'],
    ['salud', 'noun', 'f', 'A2'],
    ['enfermedad', 'noun', 'f', 'A2'],
    ['síntoma', 'noun', 'm', 'B1'],
    ['tratamiento', 'noun', 'm', 'B1'],
    ['medicina', 'noun', 'f', 'A2'],
    ['terapia', 'noun', 'f', 'B1'],
    ['cura', 'noun', 'f', 'B1'],
    ['oído', 'noun', 'm', 'A2'],
    ['nariz', 'noun', 'f', 'A2'],
    ['boca', 'noun', 'f', 'A1'],
    ['piel', 'noun', 'f', 'A2'],
    ['sangre', 'noun', 'f', 'B1'],
    ['hueso', 'noun', 'm', 'B1'],
    ['músculo', 'noun', 'm', 'B1'],
    ['corazón', 'noun', 'm', 'A2'],
    ['cerebro', 'noun', 'm', 'B1'],
    ['energía', 'noun', 'f', 'A2'],
    ['fuerza', 'noun', 'f', 'A2'],
    ['equilibrio', 'noun', 'm', 'B1'],
    ['movimiento', 'noun', 'm', 'B1'],
    ['reposo', 'noun', 'm', 'B1'],
    ['fatiga', 'noun', 'f', 'B1'],
    ['estrés', 'noun', 'm', 'B1'],
    ['ánimo', 'noun', 'm', 'B1'],
    ['humor', 'noun', 'm', 'A2'],
    ['estado', 'noun', 'm', 'A2'],

    // Society/culture nouns
    ['sociedad', 'noun', 'f', 'B1'],
    ['comunidad', 'noun', 'f', 'B1'],
    ['cultura', 'noun', 'f', 'A2'],
    ['tradición', 'noun', 'f', 'A2'],
    ['costumbre', 'noun', 'f', 'A2'],
    ['creencia', 'noun', 'f', 'B1'],
    ['religión', 'noun', 'f', 'B1'],
    ['identidad', 'noun', 'f', 'B1'],
    ['origen', 'noun', 'm', 'A2'],
    ['idioma', 'noun', 'm', 'A1'],
    ['dialecto', 'noun', 'm', 'B2'],
    ['acento', 'noun', 'm', 'A2'],
    ['expresión', 'noun', 'f', 'A2'],
    ['significado', 'noun', 'm', 'A2'],
    ['sentido', 'noun', 'm', 'B1'],
    ['mensaje', 'noun', 'm', 'A2'],
    ['discurso', 'noun', 'm', 'B1'],
    ['texto', 'noun', 'm', 'A2'],

    // Arts nouns
    ['arte', 'noun', 'm', 'A2'],
    ['música', 'noun', 'f', 'A1'],
    ['cine', 'noun', 'm', 'A2'],
    ['teatro', 'noun', 'm', 'A2'],
    ['literatura', 'noun', 'f', 'B1'],
    ['pintura', 'noun', 'f', 'A2'],
    ['escultura', 'noun', 'f', 'B1'],
    ['diseño', 'noun', 'm', 'B1'],
    ['moda', 'noun', 'f', 'A2'],
    ['estilo', 'noun', 'm', 'A2'],

    // ═══ BATCH 5: Professional adjectives ════════════════════════
    ['eficiente', 'adjective', null, 'B1'],
    ['ineficiente', 'adjective', null, 'B1'],
    ['productivo', 'adjective', null, 'B1'],
    ['improductivo', 'adjective', null, 'B2'],
    ['creativo', 'adjective', null, 'A2'],
    ['innovador', 'adjective', null, 'B1'],
    ['tradicional', 'adjective', null, 'A2'],
    ['moderno', 'adjective', null, 'A2'],
    ['actual', 'adjective', null, 'A2'],
    ['antiguo', 'adjective', null, 'A2'],
    ['formal', 'adjective', null, 'A2'],
    ['informal', 'adjective', null, 'A2'],
    ['profesional', 'adjective', null, 'B1'],
    ['personal', 'adjective', null, 'A2'],
    ['técnico', 'adjective', null, 'B1'],
    ['práctico', 'adjective', null, 'B1'],
    ['teórico', 'adjective', null, 'B1'],
    ['funcional', 'adjective', null, 'B1'],
    ['operativo', 'adjective', null, 'B1'],
    ['estratégico', 'adjective', null, 'B2'],
    ['global', 'adjective', null, 'B1'],
    ['local', 'adjective', null, 'A2'],
    ['nacional', 'adjective', null, 'B1'],
    ['internacional', 'adjective', null, 'B1'],
    ['público', 'adjective', null, 'A2'],
    ['privado', 'adjective', null, 'A2'],
    ['individual', 'adjective', null, 'B1'],
    ['colectivo', 'adjective', null, 'B1'],
    ['comercial', 'adjective', null, 'B1'],
    ['social', 'adjective', null, 'B1'],

    // Aesthetic adjectives
    ['hermoso', 'adjective', null, 'A2'],
    ['atractivo', 'adjective', null, 'B1'],
    ['agradable', 'adjective', null, 'A2'],
    ['desagradable', 'adjective', null, 'B1'],
    ['interesante', 'adjective', null, 'A2'],
    ['emocionante', 'adjective', null, 'A2'],
    ['impactante', 'adjective', null, 'B1'],
    ['auténtico', 'adjective', null, 'B1'],
    ['falso', 'adjective', null, 'A2'],
    ['real', 'adjective', null, 'A2'],
    ['imaginario', 'adjective', null, 'B1'],
    ['natural', 'adjective', null, 'A2'],
    ['artificial', 'adjective', null, 'B1'],
    ['sencillo', 'adjective', null, 'A2'],
    ['complejo', 'adjective', null, 'B1'],
    ['elegante', 'adjective', null, 'A2'],
    ['popular', 'adjective', null, 'A2'],
    ['famoso', 'adjective', null, 'A2'],
    ['anónimo', 'adjective', null, 'B1'],
    ['clásico', 'adjective', null, 'A2'],
    ['vanguardista', 'adjective', null, 'B2'],
    ['original', 'adjective', null, 'A2'],
    ['raro', 'adjective', null, 'A2'],

    // ═══ BATCH 5: Compound prepositions & function words ═════════
    ['sin embargo', 'conjunction', null, 'A2'],
    ['por eso', 'conjunction', null, 'A2'],
    ['por tanto', 'conjunction', null, 'B1'],
    ['además', 'adverb', null, 'A2'],
    ['incluso', 'adverb', null, 'B1'],
    ['según', 'preposition', null, 'A2'],
    ['contra', 'preposition', null, 'A2'],
    ['salvo', 'preposition', null, 'B1'],
    ['antes de', 'preposition', null, 'A2'],
    ['después de', 'preposition', null, 'A2'],
    ['alrededor de', 'preposition', null, 'B1'],
    ['dentro de', 'preposition', null, 'A2'],
    ['fuera de', 'preposition', null, 'A2'],
    ['a través de', 'preposition', null, 'B1'],
    ['junto a', 'preposition', null, 'A2'],
    ['lejos de', 'preposition', null, 'A2'],
    ['cerca de', 'preposition', null, 'A2'],
    ['debajo de', 'preposition', null, 'A2'],

    // Indefinite pronouns/determiners
    ['algo', 'pronoun', null, 'A1'],
    ['nada', 'pronoun', null, 'A1'],
    ['alguien', 'pronoun', null, 'A1'],
    ['nadie', 'pronoun', null, 'A1'],
    ['todo', 'pronoun', null, 'A1'],
    ['cada', 'pronoun', null, 'A2'],
    ['varios', 'pronoun', null, 'A2'],
    ['muchos', 'pronoun', null, 'A1'],
    ['pocos', 'pronoun', null, 'A1'],

    // ═══ BATCH 6: Analysis/thinking verbs ════════════════════════
    ['reflexionar', 'verb', null, 'B1'],
    ['razonar', 'verb', null, 'B1'],
    ['deducir', 'verb', null, 'B1'],
    ['inferir', 'verb', null, 'B2'],
    ['concluir', 'verb', null, 'B1'],
    ['valorar', 'verb', null, 'B1'],
    ['interpretar', 'verb', null, 'B1'],
    ['comprender', 'verb', null, 'A2'],
    ['asumir', 'verb', null, 'B1'],
    ['plantear', 'verb', null, 'B1'],
    ['formular', 'verb', null, 'B1'],
    ['proponer', 'verb', null, 'B1'],
    ['sugerir', 'verb', null, 'B1'],
    ['cuestionar', 'verb', null, 'B1'],
    ['criticar', 'verb', null, 'B1'],
    ['verificar', 'verb', null, 'B1'],
    ['comprobar', 'verb', null, 'B1'],
    ['descartar', 'verb', null, 'B1'],
    ['negar', 'verb', null, 'B1'],
    ['afirmar', 'verb', null, 'B1'],

    // Tech verbs
    ['programar', 'verb', null, 'B1'],
    ['codificar', 'verb', null, 'B1'],
    ['configurar', 'verb', null, 'B1'],
    ['instalar', 'verb', null, 'A2'],
    ['descargar', 'verb', null, 'A2'],
    ['eliminar', 'verb', null, 'A2'],
    ['borrar', 'verb', null, 'A2'],
    ['enviar', 'verb', null, 'A1'],
    ['recibir', 'verb', null, 'A1'],
    ['compartir', 'verb', null, 'A2'],
    ['difundir', 'verb', null, 'B1'],
    ['transmitir', 'verb', null, 'B1'],
    ['navegar', 'verb', null, 'A2'],
    ['registrarse', 'verb', null, 'A2'],
    ['iniciar', 'verb', null, 'A2'],
    ['acceder', 'verb', null, 'B1'],
    ['bloquear', 'verb', null, 'B1'],
    ['desbloquear', 'verb', null, 'B1'],
    ['copiar', 'verb', null, 'A2'],
    ['imprimir', 'verb', null, 'A2'],

    // Negotiation/power verbs
    ['acordar', 'verb', null, 'B1'],
    ['pactar', 'verb', null, 'B2'],
    ['debatir', 'verb', null, 'B1'],
    ['dialogar', 'verb', null, 'B1'],
    ['mediar', 'verb', null, 'B2'],
    ['arbitrar', 'verb', null, 'B2'],
    ['conciliar', 'verb', null, 'B2'],
    ['someter', 'verb', null, 'B2'],
    ['imponer', 'verb', null, 'B1'],
    ['atacar', 'verb', null, 'B1'],
    ['amenazar', 'verb', null, 'B1'],
    ['castigar', 'verb', null, 'B1'],
    ['sancionar', 'verb', null, 'B2'],
    ['premiar', 'verb', null, 'B1'],
    ['recompensar', 'verb', null, 'B2'],
    ['compensar', 'verb', null, 'B1'],
    ['indemnizar', 'verb', null, 'B2'],
    ['multar', 'verb', null, 'B2'],

    // Existence/legacy verbs
    ['persistir', 'verb', null, 'B1'],
    ['desaparecer', 'verb', null, 'A2'],
    ['surgir', 'verb', null, 'B1'],
    ['emerger', 'verb', null, 'B2'],
    ['evolucionar', 'verb', null, 'B1'],
    ['desarrollarse', 'verb', null, 'B1'],
    ['transformarse', 'verb', null, 'B1'],
    ['adaptarse', 'verb', null, 'B1'],
    ['marcar', 'verb', null, 'A2'],
    ['definir', 'verb', null, 'B1'],
    ['determinar', 'verb', null, 'B1'],
    ['condicionar', 'verb', null, 'B2'],
    ['orientar', 'verb', null, 'B1'],
    ['guiar', 'verb', null, 'A2'],
    ['inspirar', 'verb', null, 'B1'],
    ['motivar', 'verb', null, 'B1'],
    ['contribuir', 'verb', null, 'B1'],
    ['aportar', 'verb', null, 'B1'],
    ['heredar', 'verb', null, 'B1'],
    ['preservar', 'verb', null, 'B1'],
    ['trascender', 'verb', null, 'B2'],

    // ═══ BATCH 6: Tech nouns ═════════════════════════════════════
    ['tecnología', 'noun', 'f', 'A2'],
    ['dispositivo', 'noun', 'm', 'A2'],
    ['máquina', 'noun', 'f', 'A2'],
    ['herramienta', 'noun', 'f', 'A2'],
    ['software', 'noun', 'm', 'B1'],
    ['hardware', 'noun', 'm', 'B1'],
    ['aplicación', 'noun', 'f', 'A2'],
    ['programa', 'noun', 'm', 'A2'],
    ['plataforma', 'noun', 'f', 'B1'],
    ['red', 'noun', 'f', 'A2'],
    ['internet', 'noun', 'm', 'A2'],
    ['sitio', 'noun', 'm', 'A2'],
    ['página', 'noun', 'f', 'A2'],
    ['archivo', 'noun', 'm', 'A2'],
    ['documento', 'noun', 'm', 'A2'],
    ['base', 'noun', 'f', 'B1'],
    ['datos', 'noun', 'm', 'B1'],
    ['servidor', 'noun', 'm', 'B1'],
    ['correo', 'noun', 'm', 'A2'],
    ['publicación', 'noun', 'f', 'B1'],
    ['comentario', 'noun', 'm', 'A2'],
    ['perfil', 'noun', 'm', 'A2'],
    ['cuenta', 'noun', 'f', 'A2'],
    ['contraseña', 'noun', 'f', 'A2'],
    ['privacidad', 'noun', 'f', 'B1'],

    // Government/politics nouns
    ['gobierno', 'noun', 'm', 'B1'],
    ['nación', 'noun', 'f', 'B1'],
    ['poder', 'noun', 'm', 'B1'],
    ['autoridad', 'noun', 'f', 'B1'],
    ['liderazgo', 'noun', 'm', 'B1'],
    ['oposición', 'noun', 'f', 'B1'],
    ['justicia', 'noun', 'f', 'B1'],
    ['deber', 'noun', 'm', 'A2'],
    ['libertad', 'noun', 'f', 'B1'],
    ['igualdad', 'noun', 'f', 'B1'],
    ['política', 'noun', 'f', 'B1'],
    ['ideología', 'noun', 'f', 'B2'],
    ['régimen', 'noun', 'm', 'B2'],
    ['democracia', 'noun', 'f', 'B1'],
    ['dictadura', 'noun', 'f', 'B2'],
    ['institución', 'noun', 'f', 'B1'],
    ['organismo', 'noun', 'm', 'B1'],
    ['administración', 'noun', 'f', 'B1'],
    ['gestión', 'noun', 'f', 'B1'],

    // ═══ BATCH 6: Legal/moral adjectives ═════════════════════════
    ['legal', 'adjective', null, 'B1'],
    ['ilegal', 'adjective', null, 'B1'],
    ['ético', 'adjective', null, 'B1'],
    ['inmoral', 'adjective', null, 'B2'],
    ['legítimo', 'adjective', null, 'B2'],
    ['ilegítimo', 'adjective', null, 'B2'],
    ['responsable', 'adjective', null, 'B1'],
    ['irresponsable', 'adjective', null, 'B1'],
    ['poderoso', 'adjective', null, 'B1'],
    ['dominante', 'adjective', null, 'B1'],
    ['subordinado', 'adjective', null, 'B2'],
    ['autónomo', 'adjective', null, 'B1'],
    ['dependiente', 'adjective', null, 'B1'],
    ['oprimido', 'adjective', null, 'B2'],
    ['vulnerable', 'adjective', null, 'B1'],
    ['estable', 'adjective', null, 'B1'],
    ['inestable', 'adjective', null, 'B1'],
    ['pacífico', 'adjective', null, 'B1'],
    ['violento', 'adjective', null, 'B1'],
    ['neutral', 'adjective', null, 'B1'],
    ['parcial', 'adjective', null, 'B1'],
    ['extremo', 'adjective', null, 'B1'],
    ['moderado', 'adjective', null, 'B1'],

    // ═══ BATCH 6: Discourse markers & adverbs ════════════════════
    ['por ejemplo', 'phrase', null, 'A2'],
    ['es decir', 'phrase', null, 'A2'],
    ['en cambio', 'phrase', null, 'A2'],
    ['en lugar de', 'phrase', null, 'A2'],
    ['a pesar de', 'phrase', null, 'B1'],
    ['debido a', 'phrase', null, 'B1'],
    ['gracias a', 'phrase', null, 'A2'],
    ['en caso de', 'phrase', null, 'B1'],
    ['con respecto a', 'phrase', null, 'B1'],
    ['en cuanto a', 'phrase', null, 'B1'],
    ['principalmente', 'adverb', null, 'B1'],
    ['especialmente', 'adverb', null, 'A2'],
    ['generalmente', 'adverb', null, 'A2'],
    ['normalmente', 'adverb', null, 'A2'],
    ['frecuentemente', 'adverb', null, 'B1'],
    ['raramente', 'adverb', null, 'B1'],
    ['ocasionalmente', 'adverb', null, 'B1'],
    ['gradualmente', 'adverb', null, 'B1'],
    ['eventualmente', 'adverb', null, 'B1'],
    ['finalmente', 'adverb', null, 'A2'],

    // Indefinite pronouns batch 6
    ['ambos', 'pronoun', null, 'A2'],
    ['ninguno', 'pronoun', null, 'A1'],
    ['cualquiera', 'pronoun', null, 'A2'],
    ['cada uno', 'pronoun', null, 'A2'],
    ['el mismo', 'pronoun', null, 'A2'],
    ['tal', 'pronoun', null, 'B1'],
    ['cierto', 'pronoun', null, 'A2'],
    ['diferentes', 'pronoun', null, 'A2'],

    // ═══ BATCH 7: Nature/ecology verbs ═══════════════════════════
    ['florecer', 'verb', null, 'B1'],
    ['marchitarse', 'verb', null, 'B2'],
    ['germinar', 'verb', null, 'B2'],
    ['cultivar', 'verb', null, 'B1'],
    ['sembrar', 'verb', null, 'B1'],
    ['cosechar', 'verb', null, 'B1'],
    ['regar', 'verb', null, 'B1'],
    ['podar', 'verb', null, 'B2'],
    ['fertilizar', 'verb', null, 'B2'],
    ['sobrevivir', 'verb', null, 'B1'],
    ['migrar', 'verb', null, 'B1'],
    ['habitar', 'verb', null, 'B1'],
    ['ocupar', 'verb', null, 'B1'],
    ['desplazarse', 'verb', null, 'B1'],
    ['asentarse', 'verb', null, 'B2'],
    ['contaminar', 'verb', null, 'B1'],
    ['reciclar', 'verb', null, 'A2'],
    ['reutilizar', 'verb', null, 'B1'],

    // Time verbs
    ['pausar', 'verb', null, 'A2'],
    ['alternar', 'verb', null, 'B1'],
    ['variar', 'verb', null, 'B1'],
    ['acelerar', 'verb', null, 'B1'],
    ['frenar', 'verb', null, 'B1'],
    ['anticipar', 'verb', null, 'B1'],
    ['prever', 'verb', null, 'B2'],
    ['posponer', 'verb', null, 'B1'],
    ['aplazar', 'verb', null, 'B1'],
    ['retrasar', 'verb', null, 'B1'],
    ['adelantar', 'verb', null, 'A2'],
    ['durar', 'verb', null, 'A2'],
    ['ocurrir', 'verb', null, 'A2'],
    ['suceder', 'verb', null, 'B1'],
    ['transcurrir', 'verb', null, 'B2'],
    ['progresar', 'verb', null, 'B1'],
    ['estancarse', 'verb', null, 'B2'],
    ['planear', 'verb', null, 'A2'],

    // Arts/creative verbs
    ['actuar', 'verb', null, 'A2'],
    ['cantar', 'verb', null, 'A1'],
    ['bailar', 'verb', null, 'A1'],
    ['esculpir', 'verb', null, 'B2'],
    ['componer', 'verb', null, 'B1'],
    ['emocionar', 'verb', null, 'A2'],
    ['sorprender', 'verb', null, 'A2'],
    ['entretener', 'verb', null, 'B1'],
    ['aburrir', 'verb', null, 'A2'],
    ['distraer', 'verb', null, 'B1'],
    ['conmover', 'verb', null, 'B2'],
    ['estimular', 'verb', null, 'B1'],

    // Meaning verbs
    ['significar', 'verb', null, 'A2'],
    ['representar', 'verb', null, 'B1'],
    ['simbolizar', 'verb', null, 'B1'],
    ['referir', 'verb', null, 'B1'],
    ['meditar', 'verb', null, 'B1'],
    ['contemplar', 'verb', null, 'B1'],
    ['juzgar', 'verb', null, 'B1'],
    ['revelar', 'verb', null, 'B1'],
    ['ocultar', 'verb', null, 'B1'],
    ['comunicar', 'verb', null, 'A2'],
    ['inventar', 'verb', null, 'A2'],
    ['expresar', 'verb', null, 'A2'],

    // ═══ BATCH 7: Nature adjectives ══════════════════════════════
    ['orgánico', 'adjective', null, 'B1'],
    ['sintético', 'adjective', null, 'B1'],
    ['puro', 'adjective', null, 'A2'],
    ['contaminado', 'adjective', null, 'B1'],
    ['templado', 'adjective', null, 'B1'],
    ['frágil', 'adjective', null, 'B1'],
    ['resistente', 'adjective', null, 'B1'],
    ['abundante', 'adjective', null, 'B1'],
    ['escaso', 'adjective', null, 'B1'],
    ['infinito', 'adjective', null, 'B1'],
    ['invisible', 'adjective', null, 'A2'],
    ['diverso', 'adjective', null, 'B1'],
    ['único', 'adjective', null, 'A2'],
    ['limitado', 'adjective', null, 'B1'],

    // Arts adjectives
    ['artístico', 'adjective', null, 'A2'],
    ['expresivo', 'adjective', null, 'B1'],
    ['repetitivo', 'adjective', null, 'B1'],
    ['predecible', 'adjective', null, 'B1'],
    ['sorprendente', 'adjective', null, 'A2'],
    ['bello', 'adjective', null, 'A2'],
    ['sobrecargado', 'adjective', null, 'B2'],
    ['armonioso', 'adjective', null, 'B1'],
    ['caótico', 'adjective', null, 'B1'],
    ['equilibrado', 'adjective', null, 'B1'],
    ['exagerado', 'adjective', null, 'B1'],
    ['sincero', 'adjective', null, 'A2'],
    ['intenso', 'adjective', null, 'B1'],
    ['dramático', 'adjective', null, 'B1'],
    ['sutil', 'adjective', null, 'B1'],
    ['llamativo', 'adjective', null, 'B1'],
    ['discreto', 'adjective', null, 'B1'],
    ['emocional', 'adjective', null, 'A2'],

    // ═══ BATCH 7: Time nouns ═════════════════════════════════════
    ['inicio', 'noun', 'm', 'A2'],
    ['final', 'noun', 'm', 'A2'],
    ['etapa', 'noun', 'f', 'B1'],
    ['fase', 'noun', 'f', 'B1'],
    ['ciclo', 'noun', 'm', 'B1'],
    ['ritmo', 'noun', 'm', 'A2'],
    ['pausa', 'noun', 'f', 'A2'],
    ['intervalo', 'noun', 'm', 'B1'],
    ['duración', 'noun', 'f', 'B1'],
    ['pasado', 'noun', 'm', 'A2'],
    ['presente', 'noun', 'm', 'A2'],
    ['futuro', 'noun', 'm', 'A2'],
    ['evento', 'noun', 'm', 'A2'],
    ['hecho', 'noun', 'm', 'A2'],
    ['suceso', 'noun', 'm', 'B1'],
    ['ocasión', 'noun', 'f', 'A2'],
    ['instante', 'noun', 'm', 'B1'],
    ['periodo', 'noun', 'm', 'B1'],
    ['época', 'noun', 'f', 'B1'],
    ['era', 'noun', 'f', 'B1'],
    ['plazo', 'noun', 'm', 'B1'],
    ['fecha', 'noun', 'f', 'A1'],
    ['calendario', 'noun', 'm', 'A2'],
    ['agenda', 'noun', 'f', 'A2'],
    ['cronograma', 'noun', 'm', 'B1'],

    // Arts nouns
    ['obra', 'noun', 'f', 'A2'],
    ['creación', 'noun', 'f', 'B1'],
    ['imaginación', 'noun', 'f', 'A2'],
    ['inspiración', 'noun', 'f', 'B1'],
    ['contenido', 'noun', 'm', 'A2'],
    ['canción', 'noun', 'f', 'A1'],
    ['melodía', 'noun', 'f', 'B1'],
    ['sonido', 'noun', 'm', 'A2'],
    ['silencio', 'noun', 'm', 'A2'],
    ['imagen', 'noun', 'f', 'A2'],
    ['fotografía', 'noun', 'f', 'A2'],
    ['video', 'noun', 'm', 'A2'],
    ['película', 'noun', 'f', 'A1'],
    ['relato', 'noun', 'm', 'B1'],
    ['cuento', 'noun', 'm', 'A2'],
    ['novela', 'noun', 'f', 'B1'],
    ['poesía', 'noun', 'f', 'B1'],
    ['artista', 'noun', 'm', 'A2'],
    ['creador', 'noun', 'm', 'B1'],
    ['público', 'noun', 'm', 'A2'],
    ['audiencia', 'noun', 'f', 'B1'],

    // ═══ BATCH 7: Adverbs ════════════════════════════════════════
    ['aproximadamente', 'adverb', null, 'B1'],
    ['exactamente', 'adverb', null, 'A2'],
    ['apenas', 'adverb', null, 'A2'],
    ['totalmente', 'adverb', null, 'A2'],
    ['parcialmente', 'adverb', null, 'B1'],
    ['completamente', 'adverb', null, 'A2'],
    ['exclusivamente', 'adverb', null, 'B1'],
    ['simplemente', 'adverb', null, 'A2'],
    ['quizás', 'adverb', null, 'A2'],
    ['tal vez', 'adverb', null, 'A2'],
    ['posiblemente', 'adverb', null, 'B1'],
    ['probablemente', 'adverb', null, 'A2'],
    ['seguramente', 'adverb', null, 'A2'],
    ['definitivamente', 'adverb', null, 'B1'],
    ['claramente', 'adverb', null, 'B1'],
    ['evidentemente', 'adverb', null, 'B1'],
    ['obviamente', 'adverb', null, 'B1'],
    ['supuestamente', 'adverb', null, 'B1'],
    ['únicamente', 'adverb', null, 'B1'],
    ['tampoco', 'adverb', null, 'A1'],
    ['mientras', 'conjunction', null, 'A2'],
    ['entonces', 'adverb', null, 'A2'],
    ['así que', 'conjunction', null, 'A2'],
    ['así', 'adverb', null, 'A2'],

    // ═══ BATCH 8: Physics nouns ══════════════════════════════════
    ['átomo', 'noun', 'm', 'B1'],
    ['molécula', 'noun', 'f', 'B1'],
    ['partícula', 'noun', 'f', 'B1'],
    ['materia', 'noun', 'f', 'B1'],
    ['masa', 'noun', 'f', 'B1'],
    ['volumen', 'noun', 'm', 'B1'],
    ['densidad', 'noun', 'f', 'B2'],
    ['presión', 'noun', 'f', 'B1'],
    ['temperatura', 'noun', 'f', 'A2'],
    ['calor', 'noun', 'm', 'A2'],
    ['fricción', 'noun', 'f', 'B2'],
    ['gravedad', 'noun', 'f', 'B1'],
    ['inercia', 'noun', 'f', 'B2'],
    ['velocidad', 'noun', 'f', 'B1'],
    ['aceleración', 'noun', 'f', 'B2'],
    ['distancia', 'noun', 'f', 'A2'],
    ['dirección', 'noun', 'f', 'A2'],
    ['dimensión', 'noun', 'f', 'B1'],
    ['superficie', 'noun', 'f', 'B1'],
    ['profundidad', 'noun', 'f', 'B1'],
    ['altura', 'noun', 'f', 'A2'],
    ['ancho', 'noun', 'm', 'B1'],

    // Chemistry/materials
    ['elemento', 'noun', 'm', 'B1'],
    ['compuesto', 'noun', 'm', 'B2'],
    ['mezcla', 'noun', 'f', 'B1'],
    ['reacción', 'noun', 'f', 'B1'],
    ['sólido', 'noun', 'm', 'B1'],
    ['líquido', 'noun', 'm', 'B1'],
    ['gas', 'noun', 'm', 'B1'],
    ['plasma', 'noun', 'm', 'B2'],
    ['metal', 'noun', 'm', 'A2'],
    ['madera', 'noun', 'f', 'A2'],
    ['plástico', 'noun', 'm', 'A2'],
    ['vidrio', 'noun', 'm', 'A2'],
    ['tela', 'noun', 'f', 'A2'],
    ['cuero', 'noun', 'm', 'B1'],
    ['piedra', 'noun', 'f', 'A2'],
    ['arena', 'noun', 'f', 'A2'],
    ['polvo', 'noun', 'm', 'B1'],

    // Biology
    ['célula', 'noun', 'f', 'B1'],
    ['tejido', 'noun', 'm', 'B1'],
    ['órgano', 'noun', 'm', 'B1'],
    ['organismo', 'noun', 'm', 'B1'],
    ['especie', 'noun', 'f', 'B1'],
    ['individuo', 'noun', 'm', 'B1'],
    ['hábitat', 'noun', 'm', 'B1'],
    ['entorno', 'noun', 'm', 'B1'],
    ['adaptación', 'noun', 'f', 'B1'],
    ['mutación', 'noun', 'f', 'B2'],
    ['selección', 'noun', 'f', 'B1'],
    ['herencia', 'noun', 'f', 'B1'],
    ['gen', 'noun', 'm', 'B2'],
    ['cromosoma', 'noun', 'm', 'B2'],
    ['ADN', 'noun', 'm', 'B2'],
    ['proteína', 'noun', 'f', 'B2'],
    ['enzima', 'noun', 'f', 'B2'],

    // Body parts
    ['cuello', 'noun', 'm', 'A2'],
    ['hombro', 'noun', 'm', 'A2'],
    ['brazo', 'noun', 'm', 'A1'],
    ['codo', 'noun', 'm', 'B1'],
    ['muñeca', 'noun', 'f', 'B1'],
    ['dedo', 'noun', 'm', 'A1'],
    ['pecho', 'noun', 'm', 'A2'],
    ['espalda', 'noun', 'f', 'A2'],
    ['cintura', 'noun', 'f', 'B1'],
    ['cadera', 'noun', 'f', 'B1'],
    ['pierna', 'noun', 'f', 'A1'],
    ['rodilla', 'noun', 'f', 'A2'],
    ['tobillo', 'noun', 'm', 'B1'],
    ['pie', 'noun', 'm', 'A1'],
    ['uña', 'noun', 'f', 'B1'],
    ['pelo', 'noun', 'm', 'A2'],
    ['barba', 'noun', 'f', 'B1'],

    // Space/astronomy
    ['planeta', 'noun', 'm', 'A2'],
    ['estrella', 'noun', 'f', 'A2'],
    ['sol', 'noun', 'm', 'A1'],
    ['luna', 'noun', 'f', 'A1'],
    ['órbita', 'noun', 'f', 'B1'],
    ['espacio', 'noun', 'm', 'A2'],
    ['universo', 'noun', 'm', 'B1'],
    ['galaxia', 'noun', 'f', 'B1'],
    ['constelación', 'noun', 'f', 'B2'],
    ['cometa', 'noun', 'm', 'B2'],
    ['asteroide', 'noun', 'm', 'B2'],
    ['satélite', 'noun', 'm', 'B1'],
    ['vacío', 'noun', 'm', 'B1'],

    // Society/organizations
    ['estructura', 'noun', 'f', 'B1'],
    ['jerarquía', 'noun', 'f', 'B2'],
    ['estatus', 'noun', 'm', 'B1'],
    ['clase', 'noun', 'f', 'A2'],
    ['élite', 'noun', 'f', 'B2'],
    ['mayoría', 'noun', 'f', 'B1'],
    ['minoría', 'noun', 'f', 'B1'],
    ['ciudadanía', 'noun', 'f', 'B1'],
    ['asociación', 'noun', 'f', 'B1'],
    ['organización', 'noun', 'f', 'B1'],
    ['corporación', 'noun', 'f', 'B2'],
    ['sindicato', 'noun', 'm', 'B2'],
    ['cooperativa', 'noun', 'f', 'B2'],
    ['fundación', 'noun', 'f', 'B1'],

    // Economics
    ['economía', 'noun', 'f', 'B1'],
    ['capital', 'noun', 'm', 'B1'],
    ['inversión', 'noun', 'f', 'B1'],
    ['beneficio', 'noun', 'm', 'B1'],
    ['pérdida', 'noun', 'f', 'B1'],
    ['crédito', 'noun', 'm', 'B1'],
    ['deuda', 'noun', 'f', 'B1'],
    ['interés', 'noun', 'm', 'B1'],
    ['impuesto', 'noun', 'm', 'B1'],
    ['tarifa', 'noun', 'f', 'B1'],
    ['costo', 'noun', 'm', 'A2'],
    ['demanda', 'noun', 'f', 'B1'],
    ['oferta', 'noun', 'f', 'B1'],
    ['consumo', 'noun', 'm', 'B1'],
    ['distribución', 'noun', 'f', 'B1'],
    ['riesgo', 'noun', 'm', 'B1'],

    // Law/justice
    ['legislación', 'noun', 'f', 'B2'],
    ['normativa', 'noun', 'f', 'B2'],
    ['regulación', 'noun', 'f', 'B1'],
    ['jurisdicción', 'noun', 'f', 'B2'],
    ['tribunal', 'noun', 'm', 'B1'],
    ['juez', 'noun', 'm', 'B1'],
    ['abogado', 'noun', 'm', 'B1'],
    ['fiscal', 'noun', 'm', 'B2'],
    ['acusado', 'noun', 'm', 'B2'],
    ['sentencia', 'noun', 'f', 'B1'],
    ['juicio', 'noun', 'm', 'B1'],
    ['apelación', 'noun', 'f', 'B2'],
    ['delito', 'noun', 'm', 'B1'],
    ['crimen', 'noun', 'm', 'B1'],
    ['falta', 'noun', 'f', 'A2'],
    ['pena', 'noun', 'f', 'B1'],

    // Power/conflict
    ['dominio', 'noun', 'm', 'B1'],
    ['alianza', 'noun', 'f', 'B1'],
    ['estabilidad', 'noun', 'f', 'B1'],
    ['orden', 'noun', 'm', 'A2'],
    ['caos', 'noun', 'm', 'B1'],
    ['violencia', 'noun', 'f', 'B1'],
    ['ataque', 'noun', 'm', 'B1'],

    // Philosophy/mind
    ['existencia', 'noun', 'f', 'B1'],
    ['realidad', 'noun', 'f', 'B1'],
    ['apariencia', 'noun', 'f', 'B1'],
    ['esencia', 'noun', 'f', 'B2'],
    ['conciencia', 'noun', 'f', 'B1'],
    ['percepción', 'noun', 'f', 'B1'],
    ['sensación', 'noun', 'f', 'B1'],
    ['intuición', 'noun', 'f', 'B1'],
    ['lógica', 'noun', 'f', 'B1'],
    ['reflexión', 'noun', 'f', 'B1'],
    ['símbolo', 'noun', 'm', 'B1'],
    ['metáfora', 'noun', 'f', 'B2'],
    ['referencia', 'noun', 'f', 'B1'],

    // Epistemology
    ['certeza', 'noun', 'f', 'B1'],
    ['convicción', 'noun', 'f', 'B2'],
    ['fe', 'noun', 'f', 'B1'],
    ['escepticismo', 'noun', 'm', 'B2'],
    ['ignorancia', 'noun', 'f', 'B1'],
    ['sabiduría', 'noun', 'f', 'B1'],
    ['aprendizaje', 'noun', 'm', 'A2'],
    ['comprensión', 'noun', 'f', 'B1'],
    ['entendimiento', 'noun', 'm', 'B1'],
    ['fantasía', 'noun', 'f', 'B1'],
    ['olvido', 'noun', 'm', 'B1'],
    ['conocimiento', 'noun', 'm', 'B1'],

    // Emotions (extended)
    ['afecto', 'noun', 'm', 'B1'],
    ['pasión', 'noun', 'f', 'B1'],
    ['voluntad', 'noun', 'f', 'B1'],
    ['intención', 'noun', 'f', 'B1'],
    ['impulso', 'noun', 'm', 'B1'],
    ['ansiedad', 'noun', 'f', 'B1'],
    ['angustia', 'noun', 'f', 'B1'],
    ['ilusión', 'noun', 'f', 'B1'],
    ['decepción', 'noun', 'f', 'B1'],
    ['frustración', 'noun', 'f', 'B1'],
    ['satisfacción', 'noun', 'f', 'B1'],
    ['culpa', 'noun', 'f', 'B1'],
    ['orgullo', 'noun', 'm', 'B1'],
    ['emoción', 'noun', 'f', 'A2'],
    ['sentimiento', 'noun', 'm', 'A2'],
    ['deseo', 'noun', 'm', 'B1'],

    // Culture/ethics
    ['rito', 'noun', 'm', 'B2'],
    ['mito', 'noun', 'm', 'B1'],
    ['espiritualidad', 'noun', 'f', 'B2'],
    ['ética', 'noun', 'f', 'B1'],
    ['principio', 'noun', 'm', 'B1'],
    ['ideal', 'noun', 'm', 'B1'],
    ['canon', 'noun', 'm', 'B2'],
    ['estética', 'noun', 'f', 'B2'],
    ['belleza', 'noun', 'f', 'A2'],

    // ═══ BATCH 8: Science/legal verbs ════════════════════════════
    ['experimentar', 'verb', null, 'B1'],
    ['demostrar', 'verb', null, 'B1'],
    ['clasificar', 'verb', null, 'B1'],
    ['modelar', 'verb', null, 'B1'],
    ['simular', 'verb', null, 'B1'],
    ['predecir', 'verb', null, 'B1'],
    ['gobernar', 'verb', null, 'B1'],
    ['legislar', 'verb', null, 'B2'],
    ['vigilar', 'verb', null, 'B1'],
    ['auditar', 'verb', null, 'B2'],
    ['investigar', 'verb', null, 'B1'],
    ['sentenciar', 'verb', null, 'B2'],
    ['absolver', 'verb', null, 'B2'],
    ['concebir', 'verb', null, 'B2'],
];

// ─── POS mapping (live DB enum) ───────────────────────────────────
// Live enum: noun, verb, adjective, adverb, pronoun, preposition, conjunction, interjection, article, phrase
$posMap = [
    'noun' => 'noun', 'verb' => 'verb', 'adjective' => 'adjective',
    'adverb' => 'adverb', 'pronoun' => 'pronoun', 'preposition' => 'preposition',
    'conjunction' => 'conjunction', 'interjection' => 'interjection',
    'article' => 'article', 'phrase' => 'phrase',
    'determiner' => 'pronoun',  // map determiner → pronoun (closest enum)
];

// ─── Insert/update ────────────────────────────────────────────────

$checkStmt = $pdo->prepare(
    "SELECT id, part_of_speech FROM dict_words WHERE lang_code = 'es' AND word_normalized = ? LIMIT 1"
);

$insertStmt = $pdo->prepare(
    'INSERT INTO dict_words (lang_code, word, word_normalized, part_of_speech, gender, cefr_level)
     VALUES ("es", ?, ?, ?, ?, ?)'
);

$updateStmt = $pdo->prepare(
    'UPDATE dict_words SET part_of_speech = COALESCE(?, part_of_speech),
     gender = COALESCE(?, gender), cefr_level = ? WHERE id = ?'
);

$inserted = 0;
$updated = 0;
$skipped = 0;

$pdo->beginTransaction();

try {
    foreach ($words as $entry) {
        [$word, $pos, $gender, $cefr] = $entry;
        $norm = normalize($word);

        // Map POS to valid enum
        $dbPos = $posMap[$pos] ?? 'noun';

        // Auto-guess gender for nouns if not provided
        if ($pos === 'noun' && !$gender) {
            $gender = guessGender($word, $pos);
        }

        $checkStmt->execute([$norm]);
        $exists = $checkStmt->fetch();

        if ($exists) {
            $updateStmt->execute([$dbPos, $gender, $cefr, $exists['id']]);
            $updated++;
        } else {
            $insertStmt->execute([$word, $norm, $dbPos, $gender, $cefr]);
            $inserted++;
        }
    }

    $pdo->commit();

    echo "=== Seeding Complete ===\n";
    echo "  New words inserted: $inserted\n";
    echo "  Existing words updated: $updated\n";
    echo "  Total entries processed: " . count($words) . "\n";

} catch (Exception $e) {
    $pdo->rollBack();
    echo "ERROR: " . $e->getMessage() . "\n";
    exit(1);
}

// ─── Summary ──────────────────────────────────────────────────────

echo "\n--- Database totals ---\n";
$stmt = $pdo->query("SELECT COUNT(*) c FROM dict_words WHERE lang_code = 'es'");
echo "Total Spanish words: " . $stmt->fetch()['c'] . "\n";

$stmt = $pdo->query(
    "SELECT part_of_speech, COUNT(*) c FROM dict_words WHERE lang_code = 'es'
     GROUP BY part_of_speech ORDER BY c DESC"
);
echo "\nAll by POS:\n";
while ($row = $stmt->fetch()) {
    echo "  " . ($row['part_of_speech'] ?: 'unknown') . ": " . $row['c'] . "\n";
}

$stmt = $pdo->query(
    "SELECT cefr_level, COUNT(*) c FROM dict_words WHERE lang_code = 'es'
     GROUP BY cefr_level ORDER BY cefr_level"
);
echo "\nAll words by CEFR:\n";
while ($row = $stmt->fetch()) {
    echo "  " . $row['cefr_level'] . ": " . $row['c'] . "\n";
}
